keptn/keptn

install/scripts/deployDynatrace.sh
install/scripts/setupInfrastructure.sh
install/scripts/setupKnative.sh

This prevents those kinds of errors:
Error from server (AlreadyExists): error when creating “../manifests/container-registry/k8s-docker-registry-service.yml”: services “docker-registry” already exists

use kubectl apply instead of create

---

core/control/config/control.yaml

Temporary it was necessary to use the branch cloudevents-sdk

Reuse master branch to deploy control

---

install/scripts/applyAutoTaggingRules.sh

The return value of two curls for creating tagging rules in Dynatrace are not verified correctly. Instead of verifying $?, $1 was checked.

Patch for testing return value of curl

---

install/manifests/dynatrace/cr.yml
install/scripts/applyAutoTaggingRules.sh
install/scripts/createServiceEntry.sh
install/scripts/defineDynatraceCredentials.sh
install/scripts/deployDynatrace.sh
install/scripts/uninstallKeptn.sh
install/scripts/wearUniform.sh

Removed hard-coded URLs (live.dynatrace.com), which were used for Dynatrace SaaS tenants, to support the use of Dynatrace-managed tenants.

#255 Dynatrace-managed support

---

.travis.yml

Since we have a cron job that creates a keptn installation every day based on the develop branch, it is required to exclude this cron job for building artifacts.

Build the develop branch when not a cron job

---

.travis.yml

In order to avoid duplicate travis builds for the same code base of the develop branch, it is required to specify 'AND type = push' instead of 'AND NOT type = cron'.

Changed travis condition for develop branch

---

core/auth/config/authenticator.yaml
core/control/config/control.yaml
core/eventbroker-ext/config/event-broker-ext.yaml
core/eventbroker/config/event-broker.yaml

To use the latest image version of each core component when using the develop branch, it is necessary to set the tag in the manifest to 'latest'.

Set tag of core components to latest for develop branch

---

cli/cmd/send_event_newArtifact.go
cli/cmd/send_event_test.go
releasenotes/releasenotes_develop.md

This PR ensures a consistent use of the word artifact instead of artefact across all keptn repositories.

#387 Fixed typo: Changed artefact to artifact

---

cli/cmd/install.go
releasenotes/releasenotes_develop.md

This PR removes the unused --wait option of one kubectl command. Besides, it changes the execution of commands to use the lib keptutils instead of exec.

#512 Removed --wait option at kubectl command

---

installer/scripts/openshift/setupKeptn.sh

We previously used edge-termination which resulted in requests being redirected to port 80 of the ingress gateway, which is not exposed anymore.
additionally, insecure traffic is now disallowed for this route.

#627 use passthrough termination for keptn route in openshift

---

configuration-service/common/git.go

This allows resource files to be edited in upstream (e.g. in GitLab UI)

#731 pull before checking put/committing changes

---

pitometer-service/examples/remediation.yaml
pitometer-service/examples/service-indicators.yaml
pitometer-service/examples/service-objectives.yaml
pitometer-service/package-lock.json
pitometer-service/package.json
pitometer-service/src/svc/Service.ts
pitometer-service/src/svc/ServiceIndicators.ts
pitometer-service/src/svc/ServiceObjectives.ts

The service now checks if both a `service-indicators.yaml` and `service-objectives.yaml` file are located in the service's directory in the config repo. If they are present and both valid, the service will internally recreate a perfspec.json file that will be passed to pitometer. If those files are not present, the service checks if there is a `perfspec.json` file in the service directory and try to use that for the evaluation

#723 Pitometer enhancement for service-indicators/objectives files

---

configuration-service/common/git.go
configuration-service/handlers/project.go

This fixes the issues that occured in #929 with `keptn create project`
Work in progress - don't merge yet
* When git clone fails, a secret for git credentials was created -> secret is now cleaned up
* The order of cloning a repo and creating a secret was wrong
* Git usernames that contain an `@` (e.g., e-mail address) lead to problems when using `git clone`

Fixing #929 - git clone and secret fixes

---

.gitignore
README.md

Re-opened* and combined PRs
* Added github release + travis build status badges (from #937)
* ignore jetbrains .idea files (from #935)
\* as travis-ci build pipeline requires us to have proper branch naming.

Feature/943 Github Release + Travis Status Badge, ignore .idea files

---

.travis.yml

* Do not use `TRAVIS_COMMIT_RANGE` to determine the files that have changed, as it causes issues with force pushes (e.g., because of `git rebase` or `git commit --amend`)
e.g.: ``fatal: ambiguous argument '678fd63a0ce5...d88351f01ddf': unknown revision or path not in the working tree.`` (see https://github.com/travis-ci/travis-ci/issues/2668 for details)
* Distinguish the downloads for gcloud and go-dep based on the operating system used (linux or osx)
* Added some basic tests that should always run regardless of the origin (external contributor, branch name, ...)
* Allow Pull Requests to the `master` branch only if they are made within this repository from the `develop` branch
This is just the first PR for #957, I will add others for refactoring purpose too.

#957 Travis CI Updates for Contributors and PRs

---

travis-scripts/cronjob_main.sh
travis-scripts/setup_functions.sh

Nightly cron jobs currently fail on travis as the provided GKE version is no longer available.
I've introduced a new variable in travis-ci called `GKE_VERSION`, and I've set it to `1.12.8` at the moment (which should allow `gcloud` to automatically pick the latest 1.12.8-* version).
Also, `print_error` should not be called within the cronjob, as it is not available in there. Using `echo` instead.

#946 fix nightly crons

---

.travis.yml

The following tests seem to fail with os: linux on travis-ci:
```bash
if [[ $CHANGED_FILES == *"${CLI_FOLDER}"*  ]]; then
echo "Testing keptn CLI on osx"
cd ./cli
dep ensure
go test ./...
fi
```
The tests run fine with `os: osx` though, see this build as an example:
https://travis-ci.org/keptn/keptn/builds/598183032
While we need to investigate this for sure, this PR sets the stage for CLI test to osx for now.

#957 basic tests fail on linux, revert back to osx

---

cli/Gopkg.lock
cli/cmd/auth.go
cli/cmd/install.go
cli/utils/websockethelper/websocketHelper.go
installer/manifests/installer/installer.yaml
installer/manifests/keptn/keptn-api-virtualservice.yaml
installer/scripts/common/setupIstio.sh
installer/scripts/common/setupKeptn.sh
releasenotes/releasenotes_develop.md

- Add `gateway` flag in `keptn install` in order to allow to select if a LoadBalancer or a NodePort is used for the istio-ingressgateway
- Set Host in API requests and WS communication

#462 Allow NodePort for istio-ingressgateway

---

cli/cmd/auth.go
cli/cmd/install.go

I just came across a problem with authentication, which I can not properly debug as the error message does not contain the actual error.
This PR adds a proper error message (and a typo)

Enhance error message for authentication failures

---

mongodb-datastore/Gopkg.lock
mongodb-datastore/Gopkg.toml
mongodb-datastore/handlers/config.go
mongodb-datastore/handlers/events.go
mongodb-datastore/handlers/logs.go
mongodb-datastore/restapi/configure_mongodb_datastore.go

This PR adapts the mongodb-datastore service to support the latest go-utils version. 
Mainly, the logging mechanism has changed. 
When creating a logger (`logger := keptnutils.NewLogger("", "", serviceName)`), the first two parameters are empty, because the mongodb-datastore does not receive a keptn context or event ID; this is as designed.

#1011 Use latest version of go-utils for mongodb-datastore

---

.github/ISSUE_TEMPLATE/bug_report.md

Our current template does not provide all the information we need to look into issues.
The new template asks the user to specify the environment and which component they believe is affected right away.
**This PR is set to master on purpose. If you believe that we should go the full cycle with the development branch, let me know.**
FYI: I created a new issue to display how this would look like: https://github.com/keptn/keptn/issues/1003

Update issue/bug report template

---

api/handlers/event_test.go
api/handlers/service.go
api/models/service.go
api/restapi/embedded_spec.go
api/restapi/operations/event/get_event.go
api/service_model.yaml
cli/Gopkg.lock
cli/cmd/create_project.go
cli/cmd/create_service.go
cli/cmd/create_service_test.go
cli/cmd/onboard_service.go
helm-service/controller/helm/umbrella_chart_handler.go
helm-service/controller/onboarder.go
helm-service/controller/onboarder_test.go

This PR contains: 
- Fix of broken test in API
- Helm chart parameter is not mandatory when creating a service
- CLI support of: `keptn create service SERVICENAME --project=PROJECTNAME`
- Now, the helm-service creates an umbrella chart when no umbrella chart is available Before, it created an umbrella chart when the first service was onboarded.

#216 Support creating service without Helm chart 

---

configuration-service/Dockerfile

Dockerfile for configuration service had a copy-paste error (was building jmeter instead of configuration service)

#1026 fixed dockerfile for configuration service

---

installer/Dockerfile

Based on issue #1034, this PR reduces the total size of the installer image from roughly 750 MB down to around 380 MB.
In addition, this can be seen on dockerhub:
https://hub.docker.com/r/keptn/installer/tags
* latest (develop): 287.69 Mb
* feature.1034.*: 135.19 MB
This will not only improve the actual installation time (as fetching the image will be faster), but it will also lower the resource footprint within the internal container registry and also on dockerhub.

#1034 Improve Installer Dockerfile

---

.travis.yml

At the moment we upload every change of the CLI within the develop branch into a new sub-folder.
To be in sync with our docker images, I propose that we upload the latest build of the CLI (within the develop branch) into a folder called "develop".
To understand this change, here is the relevant code of `build_CLI`:
```sh
#!/bin/bash
VERSION=$1
echo "$VERSION" > version
...
env GOOS=darwin GOARCH=amd64 go build -ldflags="-X 'main.Version=$VERSION'" -o keptn
gsutil cp keptn-macOS.zip gs://keptn-cli/${TAG}/keptn-macOS.zip
gsutil cp keptn-macOS.tar.gz gs://keptn-cli/${TAG}/keptn-macOS.tar.gz
...
env GOOS=linux GOARCH=amd64 go build -ldflags="-X 'main.Version=$VERSION'" -o keptn
gsutil cp keptn-linux.zip gs://keptn-cli/${TAG}/keptn-linux.zip
gsutil cp keptn-linux.tar.gz …
```

#946 provide latest version of the CLI

---

bridge/server/lib/services/DatastoreService.js

This adds start-evaluation events as root-elements within the bridge, e.g.::
We will most likely need some more changes after that to completely show all steps of the quality-gates standalone use case.

#1046 Show evaluation start events as root elements in Bridge

---

.travis.yml
travis-scripts/build_develop.sh
travis-scripts/build_feature.sh
travis-scripts/build_release.sh

**Note**: While making this PR I managed to hit the 50-minute limit of travis-ci (when building all images at once).
- Added Lighthouse Service to the "nightly" build script
- Improved docker build/tag/push workflow (slightly speeds up the pipeline)
- Added an output in the `after_script` section of travis that lists all images that have been build for this PR/push
- Raise gcloud version number to 270 to slightly speed up setup time of travis-ci

Lighthouse Service is added to the nightly script, pipeline improvements

---

lighthouse-service/event_handler/evaluate_sli_handler.go
lighthouse-service/event_handler/handler.go
lighthouse-service/event_handler/start_evaluation_handler.go
lighthouse-service/go.mod
lighthouse-service/go.sum

1. Pre-Filter evaluation results by status before evaluating them based on `IncludeResultWithScore`
2. Refactored `getPreviousEvaluations` and added some checks for errors
3. Added a `convertTestsFinishedToStartEvaluationEvent` which we need to convert the current tests-finished event to a start-evaluation event
4. Handle `TestFinishedEventType_0_5_0_Compatible` events
5. Return "pass" for `testStrategy == "functional"` (same as with pitometer service)
6. Added `TestStrategy` to several events

#950 Reworked lighthouse service

---

.idea/runConfigurations/keptn_gatekeeper__Kube_ContDeploy_.xml
gatekeeper-service/README.md
gatekeeper-service/go.mod
gatekeeper-service/go.sum
gatekeeper-service/main.go
gatekeeper-service/skaffold.yaml

The new evaluation results do not contain `evaluationPassed: true/false`, but `result = pass | warning | fail`.
In addition, I removed the struct containing the definition of the `EvaluationDoneEventData` payload from gatekeeper, and use the current version of go-utils (develop branch) which contains the correct version of `EvaluationDoneEventData` (see PR https://github.com/keptn/go-utils/pull/109 ).

#950 Gatekeeper needs to use new evaluation done result

---

jmeter-service/Dockerfile
jmeter-service/README.md
jmeter-service/deploy/service.yaml
jmeter-service/go.mod
jmeter-service/go.sum
jmeter-service/main.go
jmeter-service/skaffold.yaml
lighthouse-service/deploy/distributor.yaml
lighthouse-service/event_handler/handler.go
lighthouse-service/event_handler/start_evaluation_handler.go
lighthouse-service/go.mod
lighthouse-service/go.sum

Jmeter service was constructing events on its own, rather than using the events from go-utils.
I've fixed that, and also removed the "fallback code" I had to introduce in lighthouse-service because of the original behaviour of jmeter service.
Also, I've added skaffold.yaml and Dockerfile stuff to jmeter service for easier debugging.

#1078 adapt jmeter service to use test-finished and evaluation-done events

---

lighthouse-service/event_handler/start_evaluation_handler.go

The default onboarding use case does not use a slo.yaml (similar to 0.5.0 where we did not provide resource indicators and object yaml files). Therefore lighthouse has no purpose other than to say that evaluation is done and has passed.

#1081 send evaluation done event if no slo.yaml is available

---

cli/cmd/status.go

This command implements `keptn status` in the CLI, which 
- shows whether the CLI is authenticated against a cluster and
- the endpoint of the keptn API.

#1006 Add status command in CLI

---

installer/manifests/installer/installer.yaml
installer/manifests/nginx/nginx-configmap-eks.yaml
installer/manifests/nginx/nginx-svc-eks.yaml
installer/manifests/nginx/nginx-svc-nodeport.yaml
installer/manifests/nginx/nginx-svc.yaml
installer/scripts/common/utils.sh
installer/scripts/installIngress.sh
installer/scripts/installIngressForApi.sh

- Removed references to GitHub. Instead, provide manifest files with installer.
- Improved logging of install steps
- Increased wait time for ingress IP

#1128 Deploy NGINX when installing keptn on plain Kubernetes

---

installer/scripts/common/setupIstio.sh
installer/scripts/installIngressForApi.sh

The variable $INGRESS_HOST was not set in case a hostname was found in the ingressgateway.
This was the case for Istio as well as nginx.

#1124 Set ingress host if hostname was found

---

installer/scripts/common/install.sh
installer/scripts/common/utils.sh
test/test_onboard_service.sh

As I was having some issues with debugging, I've added more helpful debug output for the `wait_for_pods_in_namespace` function.
Also, installing tiller caused some problems for me, therefore I added some additional checks for that (still needs to be verified if that works).
Also, the integration test for onboarding a service did not work anymore as we removed the "develop" branch in keptn/examples (and we are now using the master branch).

#1188 Add more debug output to installer and fix onboarding integration test

---

jmeter-service/go.mod
jmeter-service/go.sum
jmeter-service/main.go
lighthouse-service/event_handler/start_evaluation_handler.go
lighthouse-service/event_handler/start_evaluation_handler_test.go
lighthouse-service/go.mod
lighthouse-service/go.sum
lighthouse-service/main.go

The behavior of the jmeter-service has been changed. Thus, it does not send an evaluation-done event when the test execution failed. Instead, it sends a tests-finished event with `result: fail`.
The lighthouse-service has been adapted to react to this new behavior.

#542 Changed jmeter-service to not send evaluationDone events

---

api/handlers/event.go
api/restapi/embedded_spec.go
api/restapi/operations/event/get_event_parameters.go
api/restapi/operations/event/get_event_urlbuilder.go
api/swagger.yaml

Set the query parameters `keptnContext` and `type` for api endpoint GET `v1/event` since this endpoint is designed to get an event of a particular type from a certain keptnContext.

#1210 Set query parameters for /event endpoint as required

---

configuration-service/handlers/project.go
configuration-service/handlers/stage.go

- GET projects endpoint does not include entries that are not keptn projects anymore
- GET stages endpoint returns stages in the correct order (based on the shipyard.yaml)

#1275 Configuration service API improvements

---

mongodb-datastore/deploy/mongodb-datastore.yaml
mongodb-datastore/handlers/events.go

I've implemented this change in the `flattenRecursively` function as every event that is returned goes through this function.

#1300 Remove eventContext from events when delivered from mongodb datastore

---

.travis.yml
travis-scripts/install_gcloud.sh

With this I've refactored our pipeline to move gcloud installation into a seperate script.
Also, we only call the installer where we actually need gcloud.
This should speed up our travis ci pipeline even further.

#1347 Moved gcloud installation into a separate script

---

.travis.yml
api/Dockerfile
configuration-service/Dockerfile
distributor/Dockerfile
eventbroker/Dockerfile
gatekeeper-service/Dockerfile
helm-service/Dockerfile
jmeter-service/Dockerfile
lighthouse-service/Dockerfile
mongodb-datastore/Dockerfile
platform-support/openshift-route-service/Dockerfile

we often run into the issue of external go dependencies not being available (using  `go mod download`). By using the `GOPROXY` setting with an official proxy offered by Google we should be able to bypass this problem and most likely also improve our build speeds.
For more details see #1123

#1123 Added GOPROXY to several builds

---

cli/cmd/installKubernetes.go

As of right now the following command does not work:
```console
$ keptn install --platform=kubernetes
Error: json: Unmarshal(nil)
```
This PR fixes that.

#1357 Fix Kubernetes Installer getCreds.json

---

cli/cmd/send_event_evaluationStart.go
cli/cmd/send_event_newArtifact.go

Fix two typos with missing whitespace.

fix CLI typos

---

helm-service/controller/helm/generated_chart_handler.go
helm-service/controller/helm/generated_chart_handler_test.go
installer/manifests/keptn/keptn-api-virtualservice.yaml

Changes made:
- added DestinationRule for Keptn API VirtualService configuration
- Let helm-service generate DestinationRule for onboarded services that use `deployment_strategy: 'direct'`

#1408 create DestinationRules

---

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html
bridge/client/app/_models/trace.ts

If available the `deploymentURIPublic` is shown as `externallink` next to the event title.

#1404 Link deploymentURIPublic in Bridge

---

cli/cmd/install.go

we limited the compatibility to Kubernetes Server Version >= 1.13, <= 1.15 because we ran into troubles with Istio in other versions. Since we only use Istio in the full installation, there is currently no need to check the version if the  quality-gates standalone version is installed

#1398 check KubeServer version only for full installation

---

test/test_new_artifact.sh
test/utils.sh
test/utils/send_new_artifact_sockshop.sh

This PR refactors and improves the integration test which is executed on travis-ci.
We now also send a secondary new-artifact event with version 0.10.3.
The test is certainly not perfect yet, and is still lacking a lot of assert statements, though it is an improvement compared to the previous version.
The log output of the test when running it locally looks as follows:
```
---------------------------------------------
- Sending new artifact for mongo             -
---------------------------------------------
Availability of provided image cannot be checked.
Starting to send a new-artifact-event to deploy the service carts-db in project sockshop in version mongo:latest
Start updating chart carts-db of stage dev
Finished updating chart carts-db of stage dev
Start upgrading chart …
```

Refactor and improve integration test

---

api/Dockerfile
api/deploy/service.yaml
configuration-service/Dockerfile
distributor/Dockerfile
docs/debugging.md
eventbroker/Dockerfile
gatekeeper-service/Dockerfile
helm-service/Dockerfile
jmeter-service/Dockerfile
lighthouse-service/Dockerfile
mongodb-datastore/Dockerfile
remediation-service/Dockerfile
shipyard-service/Dockerfile
wait-service/Dockerfile

This fixes #1450 .
By switching to a dynamically linked library, Dynatrace is able to detect the Keptn core services written in Go and provide some more insights ;)

#1450 Better Support of Dynatrace Monitoring for Keptn core services

---

bridge/.dockerignore
bridge/Dockerfile

The version of Keptn's Bridge needs to be available as an environment variable in the second stage.

Fix bridge version not being applied in dockerfile

---

.travis.yml
test/test_quality_gates_standalone.sh
test/utils/microk8s_create_cluster.sh

This improves the integration test for the quality-gates variant.
We now can also check that configure monitoring is creating a new configmap for lighthouse!

Update integration test for quality gates standalone

---

cli/cmd/install.go

Openshift 3.11 always uses K8s 1.11 so there is no need to check

disable K8s version check for openshift

---

.travis.yml

This error prevented unit tests for the following services to be executed:
* remediation service
* wait service
* lighthouse service
* mongodb datastore service

Fix error in travis.yaml regarding unit tests / code coverage

---

.travis.yml
test/test_install_gke.sh
test/utils/gke_create_cluster.sh
travis-scripts/install_gcloud.sh

I've split the integration test for GKE into one that has istio pre-installed.
Unfortunately we can not define a test-matrix for jobs in travis-ci (this is only possible for the full travis file), hence I'm using YAML templating syntax ``    <<: *gke_full # use template``

Added integration for existing istio installation

---

cli/cmd/auth.go

We often run into problems with nameserver lookup (nip.io, xip.io) or that the API is currently not available, especially shortly after `keptn install`. This PR improves the error handling and retries connecting to the server before exiting.

Improve troubleshooting logs for keptn auth command

---

README.md

Fixes the wrong display of services in readme:

Fix readme for 0.5.1, 0.5.2 and 0.6.0

---

.idea/runConfigurations/keptn_bridge__Kube_ContDeploy_.xml
bridge/README.md
bridge/deploy/bridge.yaml
bridge/server/app.js
installer/manifests/keptn/core.yaml

This provides an implementation and an example on how to enable Basic Authentication within Keptn's Bridge in the Readme file of Keptn's Bridge.
Using Kubernetes secrets and `optional: true`, I was able to add it to the Installer Manifest as well.

Added basic authentication to Keptn's Bridge

---

helm-service/controller/configuration_changer.go
helm-service/main.go

Fixes #1532.
This avoids connecting to external services.
I also added a log statement for better troubleshooting.

#1532 Avoid connecting to external services when calling helm init

---

.github/workflows/reviewdog.yml
.reviewdog.yml
.travis.yml

This PR introduces reviewdog for automated PR review (using gofmt, govet and golint), and removes the linting task from travis-ci.
This is also a going to be introduced in our keptn-contrib repos as well as our go template.
As a working example, please see PR #1571

Introduce reviewdog

---

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html
bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
bridge/client/app/_components/ktb-events-list/ktb-events-list.component.html
bridge/client/app/_models/trace.ts
bridge/client/app/_services/data.service.ts
bridge/client/styles.scss

With this fix, the heatmap is also display immediately without having to toggle the view and the evaluation result of the current root event is preselected.

Preselect evaluation result of current root event

---

CONTRIBUTING.md
README.md

- Updated contribution guide with coding style information
- Updated contribution guide with info about tests
- Updated README with info about adopters
- Moved info about our roadmap to the top of the README file
- Added a direct link to the Keptn community in the top section of the README
- Removed version information from README as the Keptn core services are compatible with each other anyway, and external/contributed services/integrations are now listed on the website
PREVIEW: 
* [README.md](https://github.com/keptn/keptn/tree/readme#keptn)
* [CONTRIBUTING.md](https://github.com/keptn/keptn/blob/readme/CONTRIBUTING.md)

Updated readme and contribution guide

---

cli/cmd/auth.go

With #1579 I introduced faulty behaviour, which caused issues when using NodePort, e.g.:
```console
Received Keptn Domain: 10.20.0.35.xip.io:30543
Starting to authenticate
Failed to resolve hostname api.keptn.10.20.0.35.xip.io:30543
Retrying...
Failed to resolve hostname api.keptn.10.20.0.35.xip.io:30543
Retrying...
Failed to resolve hostname api.keptn.10.20.0.35.xip.io:30543
Retrying...
[keptn|ERROR] [2020-04-02 08:59:48] keptn install failed
[keptn|ERROR] [2020-04-02 08:59:48] Keptn Test failed.
```
I've changed the call from `.Host` to `.Hostname()` which strips the port of the domain :)

Fix: url.Host contains the port as well, use url.Hostname() strips the port

---

.travis.yml
travis-scripts/build_develop.sh
travis-scripts/build_feature.sh
travis-scripts/build_release.sh

- Execute unit tests always and every time in the beginning of every pipeline
- Simplified travis ci to execute the same jobs for master branch for type push and cron
- Simplified `build_develop`, `build_release` and `build_feature` scripts to include a `cd -` (change back to the previous directory)

Restructure and simplify Travis CI tests

---

.travis.yml

- Removed `travis_terminate` at several points. Calling `travis_terminate` directly exits the whole deployment chain, while we actually want the `after_failure` to be triggered in this case.

Improve troubleshooting for tests

---

configuration-service/common/git.go

**apiVersion** for the Secret. 
Since we are using the k8s core library v1 (v1 "k8s.io/api/core/v1"), the `apiVersion` is actually set to: `apps/v1`. 
Nevertheless, I fixed the wrong `apiVersion` when creating a Git Secret in `\keptn\configuration-service\common\git.go`.

#1529 Change APIVersion from apps/v1beta1 to apps/v1

---

test/test_new_artifact.sh
test/utils/send_new_artifact_sockshop.sh

Right now our integration test does not fail if one of the "wait for deployments" steps fails. This PR fixes that.

Fix integration tests

---

test/utils/gke_create_cluster.sh

There seems to be a problem when creating a cluster via the CLI with `--no-enable-ip-alias`:
```
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=Request contains an invalid argument.
```
To fix this issue, we are now using `--enable-ip-alias`, which corresponds to the following option in the UI:

Fix gke cluster create for integration tests

---

travis-scripts/install_gcloud.sh

This PR updates the gcloud cli installation within travis-ci to version 289.

Update glcoud cli to 289

---

cli/cmd/install.go
installer/scripts/common/install.sh
installer/scripts/common/utils.sh

This partially provides an implementation for #1482 as follows:
* Added `--domain` flag for `keptn install`
* Installer checks for the `--domain` flag. If it exists, it uses the domain provided there, instead of determining the domain by themselves
* Also added a fallback if the installer can not reliably determine `NODE_IP` using `curl ifconfig.me`
* Fixed an issue with the istio virtualservice for the api (api.keptn.KEPTN_DOMAIN:PORT was not reachable without specifying the host header `Host: api.keptn` - so basically it did not work in the browser).
I have performed the following steps to verify that my extension works (and that I didn't break anything):
* Download and install cli for feature 1482 for [linux](https://storage.googleapis.com/keptn-cli/feature-1482%2B20200422.1412/keptn-li …

#1482 allow specifying domain for installer

---

.travis.yml

We upgraded to go 1.13 for all our microservices during go-utils refactoring, but travis was still running on 1.12

Set travis to use golang 1.13

---

.travis.yml

Right now unit tests don't fail in travis. Using `set -e` should help.

Travis: fail unit tests

---

cli/README.md
cli/cmd/install_test.go
cli/pkg/credentialmanager/handler_linux.go

builds on PR #1687 
* PR #1674 broke unit tests for `keptn install`. This PR fixes it.
* Also fixes mocking authentication for Linux auth handler

#1482 Fix unit tests for keptn install

---

api/ws/client_test.go

It is not possible to bind port 80 on newer linux based systems, including travis-ci.
Therefore I've selected a high port that is definately not in use.

Unit tests: Use a high port number to prevent bind errors (port 80 is already taken)

---

test/utils.sh
test/utils/send_new_artifact_sockshop.sh

Our integration tests only worked with `http://`, which fails for installations with `--gateway=NodePort`.
In addition, as we are using a self-signed certificate (= invalid certificate), I had to add the `-k` option to `curl`.

Added HTTPs support for integration tests

---

cli/cmd/add_resource.go
cli/cmd/auth.go
cli/cmd/configure.go
cli/cmd/configure_bridge.go
cli/cmd/configure_domain.go
cli/cmd/configure_monitoring.go
cli/cmd/create.go
cli/cmd/create_project.go
cli/cmd/create_service.go
cli/cmd/delete_project.go
cli/cmd/generate.go
cli/cmd/generate_docs.go
cli/cmd/generate_docs_test.go
cli/cmd/get_event_evaluationDone.go
cli/cmd/install.go
cli/cmd/onboard_service.go
cli/cmd/root.go
cli/cmd/send_event.go
cli/cmd/send_event_evaluationStart.go
cli/cmd/send_event_newArtifact.go
cli/cmd/status.go
cli/cmd/uninstall.go
cli/cmd/version.go
cli/go.sum

This implements #1611.
I also removed the Keptn Logo from the root command, as it uses a lot of space and does not render correctly in Markdown.
A preview of the auto-generated markdown is available in https://github.com/keptn/keptn.github.io/pull/501

#1611 Added command to auto-generate docs

---

cli/cmd/configure_bridge.go

Propper formatting for the output of `keptn configure bridge`.

#435 Format output

---

api/ws/client_test.go

Our unit tests for API failed sometimes on travis while they always work locally.
There seems to be a timing related issue with `ListenAndServe`, which can easily be fixed with a sleep (for now). In the future we should think about using a different testing approach or go channels.

Fix unit tests for API failing on travis (timing issue)

---

cli/cmd/configure_bridge.go
cli/cmd/configure_bridge_test.go

This PR adds a warning message to the command: `keptn configure bridge`. 
- The message shows: `Warning: Make sure to enable basic authentication as described here: https://keptn.sh/docs/0.6.0/reference/keptnsbridge/#enable-authentication`
- A unit test verifies the availability of the documentation. 
Output:
```
PS C:\...\cli> .\keptn.exe configure bridge -a=expose
Bridge successfully exposed and can be reached here: https://bridge.keptn.xxx.xxx.xip.io
Warning: Make sure to enable basic authentication as described here: https://keptn.sh/docs/0.6.0/reference/keptnsbridge/#enable-authentication
PS C:\...\cli>
```

Add a warning note to keptn configure bridge

---

installer/scripts/common/install.sh

Potentially fixes issue #1706, where the nginx ingress host is set using domain:port which does not work.
This is applied to the **master** branch.

#1706 fix installer nginx ingress host

---

installer/scripts/common/install.sh

Potentially fixes issue #1706, where the nginx ingress host is set using domain:port which does not work.
This is a backport of #1710 for the release-0.6.2 branch.

fix nginx ingress host

---

cli/go.mod
cli/go.sum

This PR fixes problems with the build of CLI in release 0.6.2 branch.

Fix cli/go.mod for k8s/helm support

---

api/go.mod
api/go.sum
cli/go.mod
cli/go.sum
configuration-service/go.mod
configuration-service/go.sum
eventbroker/go.mod
eventbroker/go.sum
gatekeeper-service/go.mod
gatekeeper-service/go.sum
helm-service/go.mod
helm-service/go.sum
jmeter-service/go.mod
jmeter-service/go.sum
lighthouse-service/go.mod
lighthouse-service/go.sum
mongodb-datastore/go.mod
mongodb-datastore/go.sum
remediation-service/go.mod
remediation-service/go.sum
shipyard-service/go.mod
shipyard-service/go.sum
wait-service/go.mod
wait-service/go.sum

Update go-utils to the latest version (v0.6.2-alpha).
https://github.com/keptn/go-utils/releases/tag/v0.6.2-alpha

Update go-utils to latest version

---

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html
bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html
bridge/client/app/_components/ktb-event-item/ktb-event-item.component.ts
bridge/client/app/_utils/date.utils.ts

The time is now visualized in the format `x hours y minutes z seconds`. If hours or minutes is 0 they are omitted.

Improved time duration visualization

---

installer/manifests/keptn/core.yaml

we need the distributor to subscribe the configuration service to all events in order to update service-relevant information defined in #1673

added distributor for configuration service

---

.travis.yml
test/utils/expose_keptn_bridge.sh
test/utils/gke_create_cluster.sh
test/utils/minikube_create_cluster.sh

This PR will close issue #1766.
* Reworked the GKE tests for travis ci to allow more than one nightly cluster to be created. The name is now used based on the branch name and GKE version to be tested
* Added `GKE_VERSION` as an environment variable that allows matrix tests
* Also reworked the Minikube tests to use different Minikube versions as a matrix test
* Added a simple script for exposing the Keptn Bridge (for easier debugging/troubleshooting of failed integration tests). The username and password are stored as secret variables in travis-ci, and I have a copy of those values which I can hand out to anyone that needs them.
Please note: Matrix tests in travis are executed in parallel, so this change does not increase the overall test-time in travis-ci:

#1766 Enable GKE tests for 1.15, prepare of 1.16 and 1.17; enable tests for various minikube versions

---

.github/workflows/reviewdog.yml

Starting with the latest reviewdog release it seems to be necessary to manually install `golint`.

Fix reviewdog golint

---

configuration-service/handlers/service_approval.go

this is a fix for PR #1776 , where the filtering of approval events by the stage name has been implemented wrongly. Closes #1756

#1756 fixed approval retrieval

---

.travis.yml

This provides some insight for #1777, as we are trying out multiple versions of Minikube, including the latest version using K8s 1.18.2.
Within this PR, we test the compatibility of Keptn control-plane with Minikube versions 1.3.1, 1.6.2, 1.7.3, 1.9.2 and 1.10.1, which results in the following K8s versions: 1.15, 1.16, 1.17, 1.17.3, 1.18, 1.18.2 (I've added this as comments next to the travis-ci jobs as well).
I believe this is more than enough for the quality-gates use-case for now.

#1777 Added a bigger minikube test matrix

---

installer/manifests/keptn/continuous-deployment.yaml
installer/manifests/logging/mongodb-datastore/k8s/mongodb-datastore.yaml
installer/manifests/logging/mongodb-datastore/mongodb-datastore-distributor.yaml
installer/manifests/logging/mongodb-datastore/openshift/mongodb-datastore.yaml

After the 0.6.1 release we forgot to set some manifests to `:latest` again.

Set manifests to :latest

---

installer/scripts/common/setupIstio.sh
installer/scripts/openshift/setupIstio.sh

Closes #1802 
Due to the upgrade to Helm v3, the `--name` flag we previously used in the `helm template` commands, is not supported anymore. Instead, the name of the template is not a mandatory parameter, as described in the [Helm v3 docs](https://helm.sh/docs/helm/helm_template/)

#1802 adapt helm template commands to helm v3

---

api/swagger-ui/index.html
api/swagger.yaml
gatekeeper-service/deploy/service.yaml
installer/manifests/keptn/api-gateway-nginx.yaml

This PR will make the mongodb-datastore available via the Keptn API.
This will allow for more flexibility in terms of retrieving events via the API, as needed in Issue #1749.
Deprecates the `GET v1/event` endpoint of the `api-service`, which only provided the possibility to retrieve a single event by its type and keptn context ID.
Closes #1791.

#1791 expose mongodb datastore via API gateway

---

.travis.yml
cli/main.go

This PR updates the supported K8s version of the CLI to check for `>= 1.14` and `<= 1.18`.

#1777 Update supported K8s version to 1.14-1.18

---

.travis.yml
docs/README.md
docs/integration_tests.md
test/assets/quality_gates_standalone_sli_dynatrace_step1.yaml
test/assets/quality_gates_standalone_sli_dynatrace_step2.yaml
test/assets/quality_gates_standalone_slo_step1.yaml
test/assets/quality_gates_standalone_slo_step2.yaml
test/assets/quality_gates_standalone_slo_step3.yaml
test/test_install_minishift_quality_gates.sh
test/test_quality_gates_standalone.sh
test/utils.sh

This implements #1591
* Added several utility functions for easier verification of test steps
* So far, I was able to add the following steps from #1591: 
* no configmap for sli provider defined
* install sli provider (dynatrace and retrieve some data of a monitored service, e.g., *demo-
The following cases I can not implement right now:
* use different SLO configurations per stage
**Reason**: We do not support multi-stage quality-gates only use-case
* mix default an  non-default SLIs
**Reason**: Default SLIs do not work in the quality-gates standalone use-case with dynatrace, as we are expecting tags etc... to be set correct
However, I've added several SLIs and SLOs that are not used by default, to verify that things still work as expected.
In addition, I added documentation about …

#1591 Improve integration test for quality-gates

---

cli/cmd/get_event_evaluationDone.go
cli/go.mod
cli/go.sum

Closes #1792 
The CLI now uses the exposed mongodb-datastore (see PR #1791) to retrieve events for the ` keptn get event evaluation-done --keptn-context=1234` command.
Additionally, the output of the `get event` command is now formatted in a more readable way. Example output:
```
$keptn get event evaluation-done --keptn-context=1234
Starting to get evaluation-done event
{
"contenttype": "application/json",
"data": {
"deploymentstrategy": "direct",
"evaluationdetails": {
"indicatorResults": null,
"result": "no evaluation performed by lighthouse because no test has been executed",
"score": 0,
"sloFileContent": "",
"timeEnd": "2020-05-18T10:13:21Z",
"timeStart": "2020-05-18T10:13:21Z"
},
"labels": null,
"project": "sockshop",
"result": "pass",
"service": "carts-db",
"stage": "production", …
```

#1792 retrieve evaluation-done events from mongodb-datastore

---

cli/cmd/install.go
cli/cmd/send_event_newArtifact.go
cli/pkg/docker/docker_utils.go
cli/pkg/docker/docker_utils_test.go

previously, we called external services such as docker.io or quay.io in the `TestCheckImageAvailablity` unit test. These endpoints have now been mocked to ensure our unit tests are not impacted by potential downtimes of those services

mock image availability check responses

---

.travis.yml
test/test_install_gke.sh

This PR adapts travis ci yaml to use GKE 1.16, as it is now available as a regular version. As we know that 1.15 is similar to 1.14, but 1.16 is not, I've disabled the tests for 1.15 to avoid creating too many clusters on GKE.
In addition, as xip.io is failing a lot of times now, I've switched it over to nip.io using a `keptn configure domain` command. This way, we do not only test `keptn configure bridge` but also `keptn configure domain`

#1777 enable GKE 1.16; configure domain to nip.io

---

helm-service/controller/onboarder.go
helm-service/main.go

This PR implements #1801 
* Introduced environment variable "KEPTN_DOMAIN" in helm-service
* Use the environment variable if set
* Use configmap if environment variable is not set

Add environment variable for keptnDomain to helm-service

---

mongodb-datastore/Dockerfile

This PR adds instructions in the Dockerfile for editing the swagger.yaml.
More precisely, the swagger.yaml is edited so that it uses https and all requests require an x-token.

#1791 Patch swagger.yaml for exposing it via api

---

cli/cmd/install.go

This PR changes the behaviour of the `keptn install` command to always verify the Kubernetes server version, except when using openshift.

#1777 Installer Version check changed for all use-cases

---

test/test_quality_gates_standalone.sh

With the recent changes of Keptn API and CLI, we get a different error message when using `keptn get event evaluation-done` and the event does not exist.
This PR fixes the integration test.

#1591 Fix integration test as the CLI no longer returns an error

---

.travis.yml
test/test_keptn_uninstall.sh
test/utils/gke_create_cluster.sh

Fixes #1836 (orphaned resources on GKE for integration tests)
This PR executes and adds a test for `keptn uninstall`.
It also cleans up our default examples namespaces (sockshop-dev, sockshop-staging and sockshop-production). 
I verified that these two actions will lead to no GCE disks left orphaned after a cluster deletion.
Still open: Verify no IP addresses / load balancers / ... are still in use.
In addition, I've modified the create cluster command for GKE to only use 25 GB of persistant storage (instead of 100), and to use [pre-emptible nodes](https://cloud.google.com/compute/docs/instances/preemptible) (those nodes can be removed by google any time) which [cost only 1/5 of a normal node](https://cloud.google.com/compute/all-pricing#n1_machine_types).

#1836 Cleanup Keptn on GKE

---

test/assets/quality_gates_standalone_slo_step1.yaml
test/assets/quality_gates_standalone_slo_step2.yaml
test/assets/quality_gates_standalone_slo_step3.yaml

This fixes #1841.
Sometimes the integration test for quality gates has failed as the criteria for the response_time_p95 SLOs with `<=+10%` was violated.
I increased the SLO and also added another SLO of type warning, just in case.

#1841 Increase SLO criteria for response_time_p95 for integration tests

---

bridge/client/app/app-header/app-header.component.html
bridge/client/app/project-board/project-board.component.html
bridge/client/app/project-board/project-board.component.scss
bridge/client/app/project-board/project-board.component.ts

When clicking on a stage, you now see the deployed services with details like the public deployment URI and the deployment time.
Unfortunately at the moment we can't display more details about the stage in general, like the deployment strategy or the test strategy. This needs to be considered in a separate issue, once we can read those information via the api.

Show stage details in environments screen

---

bridge/client/app/_models/trace.ts
bridge/client/app/app.module.ts
bridge/client/app/project-board/project-board.component.html
bridge/client/app/project-board/project-board.component.scss
bridge/client/app/project-board/project-board.component.ts

We added a filter button to the list of root events, which allows to filter (show/hide) the root events by type.

Allow filtering of roots events by type

---

api/go.mod
api/go.sum
cli/go.mod
cli/go.sum
configuration-service/go.mod
configuration-service/go.sum
eventbroker/go.mod
eventbroker/go.sum
gatekeeper-service/go.mod
gatekeeper-service/go.sum
helm-service/go.mod
helm-service/go.sum
jmeter-service/go.mod
jmeter-service/go.sum
lighthouse-service/go.mod
lighthouse-service/go.sum
mongodb-datastore/go.mod
mongodb-datastore/go.sum
remediation-service/go.mod
remediation-service/go.sum
shipyard-service/go.mod
shipyard-service/go.sum
shipyard-service/main_test.go
wait-service/go.mod
wait-service/go.sum

This PR updates to the lateset version of go-utils.
In addition, a unit test for ~lighthouse~ shipyard service was fixed.

Update all services to latest go-utils

---

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html
bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html

The result message is shown as a tooltip of the warning icon also for info SLIs. In this case the warning icon is black instead of red.

Show result message also for info SLIs

---

cli/pkg/websockethelper/websocket_helper.go
installer/manifests/keptn/keptn-ingress.yaml
installer/scripts/openshift/installOnOpenshift.sh

Fixes #1797.
This PR removes the reference to the api.keptn host header and updates to the latest version of go-utils.

Remove reference to api.keptn hostheader

---

gatekeeper-service/pkg/handler/evaluation_done_event_handler.go
gatekeeper-service/pkg/handler/evaluation_done_event_handler_test.go
gatekeeper-service/pkg/handler/handler_test.go

Closes #1695 
With this PR, the gatekeeper-service checks wether the `deployment_strategy` for next stage is defined. If not, no further event is sent out.

#1695 Don't send out an event if no deployment_strategy is defined

---

cli/cmd/configure_domain.go

Closes #1752 
After configuring the domain, the following output is appended:
```
NOTE: If you have exposed the Keptn's bridge via 'keptn configure bridge --action=expose', please execute the following commands to re-enable access:
keptn configure bridge --action=lockdown
keptn configure bridge --action=expose
NOTE: VirtualServices for services that have been onboarded previously have not been updated.
```
Note that updating the VirtualServices for onboarded services also requires updating the corresponding resources within the configuration service (GitOps repo for the service). If we would like to tackle this, I propose to create a follow up-issue for moving the execution of the `configure domain` command to the `api-service` (as we did with the `configure bridge` command). This would …

#1752 added instructions to re-enable bridge access 

---

cli/cmd/configure_domain.go

Closes #1796 
This PR checks the currently configured domain to see if a Port is included in the URL before replacing its value in the `keptn-domain` ConfigMap.
If a port has been found, it will be appended to the domain provided to the `configure domain` command

#1796 keep NodePort in ConfigMap when configure domain is used

---

installer/scripts/common/setupKeptn.sh
installer/scripts/openshift/setupKeptn.sh

This partially fixes #1872.
In PR #1867 the distributor was renamed, but the installer was not adapted. Within this PR I am also fixing this in the installer.

#1872 fix installer checks for helm-service distributor

---

gatekeeper-service/pkg/handler/approval_finished_event_handler.go
gatekeeper-service/pkg/handler/approval_finished_event_handler_test.go
gatekeeper-service/pkg/handler/evaluation_done_event_handler.go
gatekeeper-service/pkg/handler/evaluation_done_event_handler_test.go
gatekeeper-service/pkg/handler/handler.go
gatekeeper-service/pkg/handler/handler_test.go

This PR corrects that the gatekeeper requests the approval for the next stage as described in the spec https://github.com/keptn/spec/blob/master/shipyard.md. 
In the following, an example event flow is shown:
**Shipyard**
```
stages:
- name: "dev"
deployment_strategy: "direct"
test_strategy: "functional"
- name: "staging"
approval_strategy: 
pass: "manual"
warning: "manual"
deployment_strategy: "blue_green_service"
test_strategy: "performance"
- name: "production"
deployment_strategy: "blue_green_service"
remediation_strategy: "automated"
```
**Desired event stream**

#1737 Request approval for the next stage

---

test/assets/quality_gates_standalone_slo_step1.yaml
test/assets/quality_gates_standalone_slo_step2.yaml
test/assets/quality_gates_standalone_slo_step3.yaml

This PR tweaks our integration tests for quality-gates, as the thresholds defined in the SLO throughput with +- 10 % was violated sometimes (but not always).
```
{
"score": 0,
"status": "fail",
"targets": [
{
"criteria": "<=+10%",
"targetValue": 28387.7,
"violated": true
},
{
"criteria": ">=-10%",
"targetValue": 23226.3,
"violated": false
}
],
"value": {
"metric": "throughput",
"success": true,
"value": 30748
}
},
```

Increase SLO thresholds for integration tests for quality-gates

---

installer/manifests/keptn/keptn-api-virtualservice.yaml

In PR #1854 I forgot to remove `api.keptn` in the hosts section of this manifest.
This PR fixes my oversight.

#1797 removed another occurance of api.keptn in the hosts section

---

.travis.yml
bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.spec.ts
bridge/client/app/_components/ktb-event-item/ktb-event-item.component.spec.ts
bridge/client/app/_components/ktb-events-list/ktb-events-list.component.spec.ts
bridge/client/app/_components/ktb-expandable-tile/ktb-expandable-tile.component.spec.ts
bridge/client/app/_components/ktb-horizontal-separator/ktb-horizontal-separator.component.spec.ts
bridge/client/app/_components/ktb-http-loading-bar/ktb-http-loading-bar.component.spec.ts
bridge/client/app/_components/ktb-http-loading-spinner/ktb-http-loading-spinner.component.spec.ts
bridge/client/app/_components/ktb-project-list/ktb-project-list.component.spec.ts
bridge/client/app/_components/ktb-project-tile/ktb-project-tile.component.spec.ts
bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.spec.ts
bridge/client/app/_components/ktb-selectable-tile/ktb-selectable-tile.component.spec.ts
bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.spec.ts
bridge/client/app/_services/api.service.spec.ts
bridge/client/app/_services/data.service.spec.ts
bridge/client/app/app-header/app-header.component.spec.ts
bridge/client/app/app.component.spec.ts
bridge/client/app/dashboard/dashboard.component.spec.ts
bridge/client/app/project-board/project-board.component.html
bridge/client/app/project-board/project-board.component.spec.ts
bridge/karma.conf.js
bridge/package.json
codecov.yml

This PR enhances travis-ci with the unit tests implemented in #1873 
In addition, I noticed that several import statements in the spec files were creating troubles, therefore I tried to reduce the imports to `AppModule` where possible.
@ermin-muratovic please take a look at my changes, and as discussed via Slack, adapt the imports if you believe that it is necessary (e.g., http loading spinner should not need the full appmodule)

#1486 Automate unit tests for Keptn Bridge

---

.travis.yml
test/test_quality_gates_standalone.sh
test/utils/k3s_create_cluster.sh
test/utils/minikube_create_cluster.sh

Implements integration test of k3s requested in #1896 
This PR includes:
* Travis-CI stuff to execute an integration test (quality-gates) using a specified version of k3s
* Utility Script to download k3s and create a k3s cluster
* Fixed a typo in minikube create cluster utility script

#1896 Added integration tests for k3s

---

installer/scripts/common/setupIstio.sh
installer/scripts/common/setupNginx.sh

Fixes #1824.
This PR addresses a problem with newer Istio Versions (1.5 and newer) that don't have istio-pilot.
In addition, the only thing we really need to make sure people can reach API and Bridge right now is the ingress controller, therefore I streamlined the checks for nginx and istio.

Reduce compatibility checks for ingress when ingress_install_option reuse is active

---

bridge/package-lock.json

This PR replaces PR #1890  by depend-a-bot

Bump websocket-extensions from 0.1.3 to 0.1.4 in /bridge

---

cli/cmd/install.go

To test the implementation, I set the constraint to >=1.15 and <=1.18 and connected to a K8s cluster version 1.14:
Now, the CLI first asks for the cluster-info and then checks the version:

#1871 Moved K8s version check after entering cluster info

---

api/go.sum
api/handlers/configure.go
api/handlers/configure_test.go

Closes #1830 
The api-service will now check if the keptn-domain ConfigMap contains a Port in the baseURL. To avoid generating invalid Ingress/VirtualService rules, the port is excluded from the host property of those rules.

#1830 do not include port in host for VirtualService and Ingress rules

---

installer/scripts/common/setupKeptn.sh
installer/scripts/openshift/setupKeptn.sh

Since the `remediation-service-problem-distributor` has been replaced by the `remediation-service-distributor` the instruction to wait for the deployment had to be changed

fixed wait command for remediation-service-distributor

---

.travis.yml

This PR adds notifications to slack in case of travis-ci failed builds on the master or release branch.
Please note: The token is required to be in .travis.yml in an [encrypted form as per their documentation](https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications):

Added notifications to slack for travis-ci failed builds

---

configuration-service/deploy/service.yaml
installer/manifests/keptn/rbac.yaml

Fixes RBACs for the `api-service` and the `configuration-service`:
- `api-service` requires `deletecollection` for deleting all Bridge pods when exposing the Bridge
- `configuration-service` requires roles to manage secrets for the Git token.

#1862 Fix RBAC for configuration-service, api-service

---

configuration-service/common/projects_materialized_view.go
configuration-service/handlers/event.go
configuration-service/handlers/remediation.go
configuration-service/handlers/service_approval.go
installer/manifests/keptn/continuous-operations.yaml
remediation-service/deploy/service.yaml
remediation-service/handler/action_finished_handler.go
remediation-service/handler/evaluation_done_handler.go
remediation-service/handler/handler.go
remediation-service/handler/problem_event_handler.go
remediation-service/handler/problem_open_handler.go
remediation-service/main.go

Closes #1848 #1849
This PR fixes a couple of problems that were caused by race conditions in the configuration-service that caused remediation status updates sent by the remediation service to be lost.
Further, the cleanup of completed remediations by the remediation-service has been fixed.
Finally, the wait time for the remediation-service has been made configurable via an environment variable

#1849 remediation workflow fixes

---

lighthouse-service/event_handler/evaluate_sli_handler.go

Closes #1585
With this PR, a message to indicate that the preceding test execution has failed is included in the `evaluationResults.result` property.

#1585 include comprehensive error message in lighthouse result

---

cli/cmd/install.go

Up to now, the installer RBACs were not applied for OpenShift. 
This resulted in a failing installer job. 
This PR also applies the RBAC rules also for OpenShift.

Apply RBACs for installer also for OpenShift

---

.travis.yml
remediation-service/handler/handler.go
remediation-service/handler/problem_open_handler.go
test/assets/self_healing_problem_open_event.json
test/assets/self_healing_remediation.yaml
test/assets/self_healing_shipyard.yaml
test/test_self_healing.sh
test/utils.sh

Closes #1846 
This PR adds integration tests for the self healing use case. The checks for remediation.finished events have been disabled for now, since we do not have a timeout mechanism for action.triggered events in the remediation service (this will be solved in 0.8.0 by the shipyard controller)

#1846 self healing test

---

installer/manifests/keptn/continuous-deployment.yaml
installer/manifests/keptn/rbac.yaml

When creating a service, the helm service needs to read the configMap. The required RoleBinding has been moved from installer/.../continuous-deployment.yaml to installer/.../rbac.yaml

added permission to read keptn-domain configmap for helm-service

---

cli/go.mod
cli/go.sum

Closes 1942
This PR updates the kubernetes-utils dependency to incorporate the latest changes regarding the retrieval of a local Kuebeconfig file. If the `KUBECONFIG` env var, this will be used to get the kube config file, otherwise it will be `~/.kube/config` per default

#1942 updated dependency to kubernetes utils

---

mongodb-datastore/handlers/events.go
upgrader/upgrade-062-070/mongodb-upgrade/main.go

Closes #1907
This PR implements a more efficient way of retrieving root events for a project/service. Previously, this has been done using an expensive distinct query (to retrieve all available keptnContexts) in the events collection of a project with a subsequent query for each of the returned result.
With the new approach introduced in this PR, I have added a dedicated collection for the root events for each project (one collection per project). This makes retrieving all root events for a project easy, since we can use the same filtering logic as for other queries without using distinct queries.

#1907 root event query tuning

---

test/test_self_healing_scaling.sh

This PR adds a statement to wait for the prometheus-service distributor before executing the configure monitoring command in the integration test

wait for prometheus-service distributor

---

cli/cmd/install.go
cli/cmd/installAKS.go
cli/cmd/installEKS.go
cli/cmd/installGKE.go
cli/cmd/installKubernetes.go
cli/cmd/installOpenShift.go
installer/scripts/common/install.sh

Closes #1856 #1928 
This PR adds additional log output to the `install` command of the CLI that will be displayed.
The error described in #1856 might be caused by the automatic deletion of the installer pod after the installer job has been finished - my guess is that caused the CLI to not retrieve the `installation complete` command and thus run into an error. That's why I have added a short sleep of 10s to the end of the installer job. In any case, I was not able to reproduce this Issue locally, so we will have to keep an eye on that to see if that resolved the issue.
For #1928, I have added several log outputs with logLevel=Verbose, to log all kubectl commands that are executed by the CLI, and their outputs. Also attempted connections to the K8s cluster are logged more thoroughly to …

#1856 #1928 Keptn Install log output

---

.gitignore
.travis.yml

This PR fixes the CLI build on the master branch, as it was only triggered for changed files (which does not make sense for type=cron on master).
In addition, I've added the examples repo to gitignore, as it constantly pops up locally for me when I run integration tests.

Fix CLI Build for master branch

---

jmeter-service/go.mod
jmeter-service/go.sum
jmeter-service/jmeterUtils.go
jmeter-service/jmeterUtils_test.go

Closes #1480 
In this PR, the jmeter-service marks a test as failed if an error is returned by the configuration-service when retrieving the test script. The only exception is when the configuration-service returns a 404 - which means that no test has been specified and can therefore be skipped.

#1480 handle configuration service errors in jmeter-service

---

.travis.yml

While fixing this in PR #1980, I made a mistake and introduced the wrong `TAG=` statement.
This lead to the latest cli being built not being uploaded to our google cloud storage under the directory `latest`, but `master+YYYYMMDD`.
Please note:
```
export TAG="latest"
```
is set in line 261, therefore overwriting it with `TAG=${VERSION}` was deleted.

build_cli on master needs to build latest

---

helm-service/go.mod
helm-service/go.sum
helm-service/main.go

Fixes #1808 
The helm-service now properly uses the `CONFIGURATION_SERVICE` environment variable. Furthermore, the go-utils now check whether this variable is not empty.
If no `CONFIGURATION_SERVICE` environment variable is specified, the error message is now 
`Error when getting config service url: Provided environment variable CONFIGURATION_SERVICE has no valid value`
If the configuration-service cannot be accessed using the `CONFIGURATION_SERVICE` environment variable, the error message is now
`Error when reading chart carts-generated from project sockshop: Get http://configuratio-service.keptn.svc.cluster.local:8080/v1/project/sockshop/stage/dev/service/carts/resource/helm%2Fcarts-generated.tgz: dial tcp: lookup configuratio-service.keptn.svc.cluster.local: no such host`

#1808 Update go-utils

---

installer/scripts/common/setupKeptn.sh
installer/scripts/openshift/setupKeptn.sh
lighthouse-service/event_handler/start_evaluation_handler.go

There might have been a merge conflict in the past, as we removed wait-service, but re-introduced it in one of the scripts again.
This PR fixes it.

Remove wait service from installer

---

test/test_self_healing.sh
test/test_self_healing_scaling.sh

The integration test for self healing was failing because the Prometheus service was not granted the required RBAC permissions (due to applying the wrong manifest for the service). This has been fixed in this PR

fixed integration tests for self healing

---

test/test_self_healing_scaling.sh

To avoid a timeout on travis (which occurs after 10m of no console output), I've added some echoes during the waiting period until the problem.open event occurs

added some log messages during wait for problem event

---

shipyard-service/main.go
shipyard-service/main_test.go

Refactor old, unused HTTP client handling, which was misleading (e.g. that a timeout of 5sec was used).

Refactor old, unused HTTP client handling

---

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
bridge/client/app/_models/trace.ts

The bar chart for evaluation results now shows categories on the xAxis instead of timeline
If the event has labels and a label with the key `buildId` is provided, that label will be used as category. Otherwise the time will be used as category.

Show categories on xAxis in BarChart instead of timeline

---

helm-service/controller/configuration_changer.go
helm-service/controller/helm/generated_chart_handler.go
helm-service/controller/mesh/ingress_config.go
helm-service/controller/onboarder.go
helm-service/controller/onboarder_test.go
helm-service/deploy/service.yaml
helm-service/go.sum
helm-service/main.go
installer/manifests/keptn/core.yaml
installer/manifests/keptn/ingress-config.yaml

Closes #1986 
This PR makes the name of the ingress gateway configurable in the helm-service. To set the value for the gateway, the `ingress-config` ConfigMap is used. This ConfigMap now has the following format:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
name: ingress-config
namespace: keptn
data:
ingress_hostname_suffix: ""
ingress_protocol: ""
ingress_port: ""
istio_gateway: ""
```

#1986 added ingress gateway env var

---

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html
bridge/client/app/app.component.ts
bridge/client/app/app.module.ts
bridge/client/app/app.routing.ts
bridge/client/app/evaluation-board/evaluation-board.component.html
bridge/client/app/evaluation-board/evaluation-board.component.scss
bridge/client/app/evaluation-board/evaluation-board.component.spec.ts
bridge/client/app/evaluation-board/evaluation-board.component.ts

The Bridge now provides a new view showing only the evaluation result as Heatmap/Chart.
With this view there are also to new deep links introduced:
`bridge.keptn.mykeptndomain/evaluation/{keptnContext}`: this shows all evaluations with the provided `keptnContext`
`bridge.keptn.mykeptndomain/evaluation/{keptnContext}/{stage}` or `bridge.keptn.mykeptndomain/evaluation/{keptnContext}/{eventId}`: this shows the evaluation with the provided `keptnContext `on the specified `stage `or with the specified `eventId`

Implement evaluation board to show Heatmap with deep link

---

installer/manifests/keptn/charts/control-plane/templates/core.yaml

For the control-plane only installation, we don't create the ingress-config ConfigMap. To enable the helm service to start nevertheless, the reference to this CM has to be marked as optional

make ingress-config CM optional

---

cli/cmd/add_resource.go
cli/cmd/auth.go
cli/cmd/configure_monitoring.go
cli/cmd/create_project.go
cli/cmd/create_service.go
cli/cmd/delete_project.go
cli/cmd/generate_support_archive.go
cli/cmd/get_event_approvalTriggered.go
cli/cmd/get_event_approvalTriggered_test.go
cli/cmd/get_event_evaluationDone.go
cli/cmd/get_projects.go
cli/cmd/get_services.go
cli/cmd/get_stages.go
cli/cmd/onboard_service.go
cli/cmd/root.go
cli/cmd/send_event.go
cli/cmd/send_event_approvalFinished.go
cli/cmd/send_event_approvalFinished_test.go
cli/cmd/send_event_evaluationStart.go
cli/cmd/send_event_newArtifact.go
cli/cmd/update_project.go
cli/pkg/websockethelper/websocket_helper.go

Closes #1948 
This PR removes the hidden flag --scheme, which allowed to override the used scheme.
With this PR, the scheme can be specified in the endpoint URL provided with `keptn auth`.

#1948 Use scheme from provided endpoint

---

helm-service/go.mod
helm-service/go.sum

The helm service was not able to create websocket connections due to a wrong URL used in a previous version of `keptn/go-utils`. This has been fixed by updating the dependency

updated go-utils dependency

---

configuration-service/deploy/service.yaml
gatekeeper-service/deploy/service.yaml
helm-service/deploy/service.yaml
installer/manifests/keptn/charts/continuous-delivery/charts/openshift/templates/route-service-openshift.yaml
installer/manifests/keptn/charts/continuous-delivery/templates/continuous-deployment.yaml
installer/manifests/keptn/charts/control-plane/templates/continuous-operations.yaml
installer/manifests/keptn/charts/control-plane/templates/core.yaml
installer/manifests/keptn/charts/control-plane/templates/mongodb-datastore.yaml
installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml
jmeter-service/deploy/service.yaml
lighthouse-service/deploy/service.yaml
mongodb-datastore/deploy/mongodb-datastore.yaml
platform-support/openshift-route-service/deploy/service.yaml
remediation-service/deploy/service.yaml
shipyard-service/deploy/service.yaml

As the distributors now run as a sidecar next to the respective service, we can forward the events using `127.0.0.1`. By this, we don't leave the networking boundary of the pod. This was a problem in Openshift.
Furthermore, I intentionally did not remove the unused services of e.g. the `shipyard-service` because the `helm-service` still requires a distributor which cannot run as a sidecar.

Use localhost for pub-sub-recipient in distributors

---

test/test_install_minishift_quality_gates.sh

Some times the tests on minishift fail because the route to the api-service does not seem to be available right away.

wait some time after exposing oc route

---

cli/cmd/configure_bridge.go

Since we don't support the backward compatibility of the API, the endpoint for `keptn configure bridge` was broken.

Add /api to endpoint for configure bridge

---

test/assets/quality_gates_standalone_slo_step1.yaml
test/assets/quality_gates_standalone_slo_step2.yaml
test/assets/quality_gates_standalone_slo_step3.yaml

Sometimes the quality gates standalone tests were failing because the example service we are using to retrieve values for takes slightly longer than the defined threshold. This should not lead to a failed test as long as the mechanics of retrieving and evaluating SLIs are working

increase thresholds for response time SLOs

---

cli/cmd/install.go
installer/manifests/keptn/charts/control-plane/values.yaml
test/test_install_gke.sh
test/test_install_kubernetes_full.sh
test/test_install_kubernetes_quality_gates.sh

The flag name `keptn-api-service-type` was misleading for users, because this service is also used to expose the Bridge.

Rename install flag keptn-api-service-type into endpoint-service-type

---

.travis.yml
test/test_install_gke.sh
test/test_install_kubernetes_full.sh
test/test_install_kubernetes_quality_gates.sh
test/test_install_minishift_quality_gates.sh
test/utils.sh
test/utils/gke_authenticate_at_cluster.sh
test/utils/gke_authenticate_at_keptn.sh
test/utils/gke_create_cluster.sh

Closes #2102 
In this PR, the GKE clusters created in part 1 of the integration tests of the full installation are reused in the seconds part. 
Additionally, I have added a retry mechanism to the authentication in the integration test scripts because some builds were failing because of networking issues

#2102 Re-use GKE cluster in integration tests

---

cli/cmd/add_resource.go
cli/cmd/add_resource_test.go

For add-resource command,
If len(args) > 0 -> then abort this command.
Resolving [#1735 ](https://github.com/keptn/keptn/issues/1735l)

Better parameter/flag checking of the keptn add-resource command.

---

api/deploy/service.yaml
bridge/deploy/bridge.yaml
configuration-service/deploy/pvc.yaml
configuration-service/deploy/service.yaml
distributor/deploy/distributor.yaml
eventbroker/deploy/eventbroker.yaml
gatekeeper-service/deploy/service.yaml
helm-service/deploy/service.yaml
jmeter-service/deploy/service.yaml
lighthouse-service/deploy/service.yaml
mongodb-datastore/deploy/mongodb-datastore.yaml
platform-support/openshift-route-service/deploy/service.yaml
remediation-service/deploy/service.yaml
shipyard-service/deploy/service.yaml

This PR adds the recommended K8s labels to the local manifest files. 
As a result, `skafold` is working again. This has been validated with each manifest.

#2147 Adapted K8s labels in local manifests

---

test/utils.sh

- Fixed `verify_image_of_deployment` method by removing the extra parenthesis and `\n`
- Replaced invalid error codes with valid ones so that the script exits when an error is thrown

#2161 Fixed integration test function and replaced invalid error codes 

---

test/test_keptn_uninstall.sh
test/test_quality_gates_standalone.sh
test/test_self_healing.sh

- The commands are expected to throw an error and therefore don't need to print the error message

#2149 Suppressing kubectl error messages

---

cli/cmd/install.go
cli/cmd/uninstall.go

The CLI asks the user when installing and uninstalling Keptn for his/her input. The user can then confirm with "y" or "yes". 
With this PR we ignore the case of the input.

Ignore case for user input

---

bridge/client/app/project-board/project-board.component.html

If there is an open approval the service is expanded automatically, so that the user can easier see and approve the pending approvals. Especially in case that the service hasn't been deployed yet to the stage, it was not obvious to the user, that he has to expand the tab. See #2151 
Fixes #2151

#2151 Expand service automatically if there is an open approval

---

.travis.yml
shipyard-controller/db/event_repo.go
shipyard-controller/db/mongodb_event_repo.go
shipyard-controller/go.mod
shipyard-controller/handlers/event.go
shipyard-controller/handlers/event_test.go

Closes #2159 
To avoid timing Issues, I have added a retry mechanism to the retrieval of triggered/started events. This way, it should not matter if events do not arrive in the expected order (triggered->started->finished).

#2159 Shipyard Controller: manage .started events

---

shipyard-controller/handlers/event.go

The response of the GET /event/triggered endpoint returned N copies from the same event. This has been fixed in this PR

fixed paginated /event response

---

api/deploy/service.yaml
api/restapi/configure_empty.go
api/swagger-ui/index.html
configuration-service/deploy/service.yaml
configuration-service/restapi/configure_configuration_service.go
installer/manifests/keptn/charts/control-plane/templates/core.yaml
installer/manifests/keptn/charts/control-plane/templates/mongodb-datastore.yaml
mongodb-datastore/deploy/mongodb-datastore.yaml
mongodb-datastore/restapi/configure_mongodb_datastore.go

With feature #2124, the Helm-chart now allows to set a prefix for the Keptn path. 
This PR adds this prefix to the swagger.yaml, which then allows to use the Swagger-UI.

#2124 Correct basePath of swagger.yamls

---

cli/cmd/get_event.go
cli/cmd/get_event_approvalTriggered.go
cli/cmd/get_event_evaluationDone.go
test/test_delivery_assistant.sh
test/utils.sh

The JSON output of the three `get event` CLI commands returned an invalid output for multiple returned events:
```
{
"contenttype": "application/json",
"type": "sh.keptn.event.approval.triggered",
...
}
{
"contenttype": "application/json",
"type": "sh.keptn.event.approval.triggered",
...
}
```
Valid JSON array output should look like this:
```
[
{
"contenttype": "application/json",
"type": "sh.keptn.event.approval.triggered",
...
},
{
"contenttype": "application/json",
"type": "sh.keptn.event.approval.triggered",
...
}
]
```
- Fixed output when returning multiple events
- Updated Integration tests

Properly format output of get event command

---

bridge/client/app/_components/ktb-approval-item/ktb-approval-item.component.scss
bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html
bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html
bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.scss
bridge/client/app/_components/ktb-selectable-tile/ktb-selectable-tile.component.scss
bridge/client/app/_components/ktb-selectable-tile/ktb-selectable-tile.component.ts
bridge/client/app/_models/root.ts
bridge/client/app/_models/trace.spec.ts
bridge/client/app/_models/trace.ts
bridge/client/index.html

#2139 Improve coloring coding for problem event

---

cli/cmd/install.go
cli/cmd/version.go

- Do not use namespace a root context for `keptn install`
- User message improvements for `keptn version`

#2195 Do not use namespace a root context

---

bridge/client/app/_models/project.ts
bridge/client/app/_models/trace.ts
bridge/client/app/project-board/project-board.component.html

Fixes #2112 
Now checking for deployment.finished or evaluation.done event and if `image` and `tag` are provided on the evaluation event, that will be displayed as `Last processed artifact`.

#2112 Fix missleading message "service not deployed yet" in quality gates use-case

---

bridge/client/app/_models/project.ts
bridge/client/app/_models/root.ts
bridge/client/app/_models/trace.ts
bridge/client/app/project-board/project-board.component.html
bridge/client/app/project-board/project-board.component.scss
bridge/client/app/project-board/project-board.component.ts
bridge/client/index.html

The environment screen now allows to easily see problems on a specific stage and remediation actions.
The stage tile shows the problem icon in red and a count how many services on this stage are "broken".
By clicking on the stage and expanding the details for a service you get the details about the problem and the remediation actions that are executed with the evaluation score after each remediation action. By hovering over the score, you can see the evaluation details in a popup.

#2085 Show remediation workflow in environment screen

---

lighthouse-service/event_handler/evaluate_sli_handler.go
lighthouse-service/event_handler/evaluate_sli_handler_test.go

Closes #2231 
Added a fix to check for empty pass/warning criteria arrays in addition to check for nil values. This avoids marking Info SLIs as being failed and sets the status to `info` instead.

#2231 Mark info SLI correctly when empty pass/warning array is provided

---

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html
bridge/client/app/_components/ktb-event-item/ktb-event-item.component.ts

When the value of a label is an URL, the value is linked and opens in a new tab.
Fixes #2061

#2061 Make links in labels clickable

---

bridge/angular.json
bridge/client/app/_models/event-labels.ts
bridge/client/app/_models/project.ts
bridge/client/app/_models/root.ts
bridge/client/app/_models/trace.spec.ts
bridge/client/app/_models/trace.ts
bridge/client/app/app.module.ts
bridge/client/app/project-board/project-board.component.html
bridge/client/app/project-board/project-board.component.scss
bridge/client/app/project-board/project-board.component.ts

Now the event types are displayed as toggle buttons with the details as labels.
By activating the toggle button, you will see only services with this event type.

#2087 Allow to filter services in environments screen by event type

---

configuration-service/common/projects_materialized_view.go

The log messages of the configuration service were misleading. When a service has been added to the materialized view successfully, the logs said that the service already exists. This has been fixed with this PR

Fixed log messages for adding services to the database

---

.travis.yml
distributor/cmd/main.go

Closes #2220 
The Endpoint can be configured using the env var `HTTP_EVENT_FORWARDING_ENDPOINT`
The API token can be configured using the env var `HTTP_EVENT_ENDPOINT_AUTH_TOKEN`
Further changes:
The env var for configuring the endpoint for polling events via HTTP has been renamed to `HTTP_EVENT_POLLING_ENDPOINT`

#2220 Added endpoint for forwarding events to Keptn API

---

SECURITY.md

While browsing the security document, I found that the link for the security contacts did not work as expected. This PR fixes it.

Fixed link to security contacts

---

installer/manifests/keptn/charts/continuous-delivery/templates/continuous-deployment.yaml
jmeter-service/deploy/service.yaml
jmeter-service/go.mod
jmeter-service/go.sum
jmeter-service/main.go
jmeter-service/main_test.go

Closes #2263 
WIth this PR, the jmeter-service will send sh.keptn.event.test.started events whenever a test is being executed, and a sh.keptn.event.test.finished when it is finished.
Instead of listening to sh.keptn.events.deployment-finished events it now listens to sh.keptn.event.test.triggered events

#2263 update jmeter service to use next-gen events

---

api/Dockerfile
api/swagger.yaml
configuration-service/Dockerfile
configuration-service/swagger.yaml
mongodb-datastore/Dockerfile
mongodb-datastore/swagger.yaml

Fixes #2328 
This PR drops `scheme` from swagger.yaml, as well as from the docker builds.
This allows swagger-ui to automatically determine the correct scheme by using the scheme that is used to access swagger-ui.

#2325 Remove anything scheme related to let swagger automatically determine the scheme

---

bridge/README.md
bridge/client/app/_services/api.service.ts
bridge/client/app/app-header/app-header.component.html
bridge/deploy/bridge.yaml
bridge/package-lock.json
bridge/server/api/index.js
bridge/server/app.js
installer/manifests/keptn/charts/control-plane/templates/core.yaml

This PR introduces a download-link for Keptn CLI.
In addition, I added the `rel="noopener noreferrer"` in the app-header component.
Other changes:
* Updated `deploy.yaml` with the download link
* Updated bridge installer manifest to also contain the download link to the github releases page based on appVersion
* Moved the `index` api endpoint of `bridge/api/` to `bridge/api/bridgeInfo` (this goes along with what it is called in the Angular UI)
* Whatever has been done to the package.lock.json is beyond my knowledge

#2319 Added functionality to show a download link to Keptn Bridge CLI

---

CONTRIBUTING.md

This PR tackles two tasks:
* Introduction of a bug-first policy
* More comprehensive description of the development process
Preview: https://github.com/keptn/keptn/blob/patch/contributing-issues/CONTRIBUTING.md

Improve development process within contribution guide; introduce bug first policy

---

configuration-service/common/git.go

The changes made in PR #2338 introduced an unintended nil pointer access. This is fixed with this PR

Fixed nil pointer access

---

installer/manifests/keptn/charts/control-plane/charts/mongodb/templates/secret.yaml
installer/manifests/keptn/charts/control-plane/templates/core.yaml

This PR increases the entropy of the api-token to >= 256 bit (Calculation: 62 possible characters (so almost 6 bit), 45 places -> 45 * 6 = 270 bit)
Also, I've increased the entropy of the mongo db admin password (I believe that's also one of those that can benefit)

#2295 Increase password and token entropy

---

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html

use safe operator for access to getShortImageName() on currently deployed artifact and show 'N/A' if no image deployed yet

#2354 use safe operator for access to getShortImageName()

---

mongodb-datastore/handlers/events.go

When a project is created, an internal event is sent by the API. This event also contains the git user and git token of the user, which should not be persisted. Therefore, this PR introduces a check for that specific event type in the mongodb-datastore, which makes sure that those properties are not persisted by removing them from the incoming payload

Remove credentials before storing event

---

cli/.gitignore
cli/cmd/generate_support_archive.go

Fixes #2340 
(also requires backport for release-0.7.2 branch)
- Add a hint that no Keptn installation could be found in the respective namespace (and use `-n ...`) to specify a namespace
- Add a yes/no question on whether the correct cluster is used
- Exit the command if no Kubectl connection could be made[1]
- Exit the command if no Keptn installation was found on the cluster[1]
[1] We require a working kubectl connection to fetch logs. If this is not working, the support-archive might be empty, which is no help at all.
```console
$ ./cli generate support-archive
Retrieving kubectl version
Checking whether kube context points to Keptn cluster
Please confirm that this is the cluster Keptn is running on: 
Cluster: gke_some-cluster
Is this all correct? (y/n)
y
Retrieving logs from cluster …
```

#2340 Improve robustness and user-experience of generate support-archive

---

installer/.gitignore
installer/manifests/keptn/charts/control-plane/templates/core.yaml

Our CI build currently exits with the following error message:
```
Installing Keptn ...
Start upgrading Helm Chart keptn in namespace keptn
Could not complete Keptn installation: Error when installing/upgrading Helm Chart keptn in namespace keptn: parse error at (keptn/charts/control-plane/templates/core.yaml:178): unexpected "}" in operand
Error: Error when installing/upgrading Helm Chart keptn in namespace keptn: parse error at (keptn/charts/control-plane/templates/core.yaml:178): unexpected "}" in operand
[keptn|ERROR] [2020-09-21 08:59:06] keptn install --platform=openshift --chart-repo=https://storage.googleapis.com/keptn-installer/keptn-0.7.2.tgz - failed
[keptn|ERROR] [2020-09-21 08:59:06] Keptn test step failed
The command "test/test_install_minishift_quality_gates.sh" exited with …
```

Fix error in helm chart

---

bridge/client/app/_components/ktb-copy-to-clipboard/ktb-copy-to-clipboard.component.html
bridge/client/app/_components/ktb-copy-to-clipboard/ktb-copy-to-clipboard.component.scss
bridge/client/app/_components/ktb-copy-to-clipboard/ktb-copy-to-clipboard.component.spec.ts
bridge/client/app/_components/ktb-copy-to-clipboard/ktb-copy-to-clipboard.component.ts
bridge/client/app/app-header/app-header.component.html
bridge/client/app/app-header/app-header.component.scss
bridge/client/app/app.module.ts

The api token and keptn auth command are now initially hidden and only a label is visible. By clicking on the toggle button, you can see the value, but the copy button still works in visible or hidden state.

#2257 Hide api token and keptn auth command

---

bridge/client/app/_components/ktb-project-tile/ktb-project-tile.component.html
bridge/client/app/_components/ktb-project-tile/ktb-project-tile.component.scss
bridge/client/styles.scss

The project overview now also shows the git upstream link if available or an information how to update the project with link to the docs.

#1335 show git upstream link in project overview or info how to update project

---

lighthouse-service/event_handler/evaluate_sli_handler.go
lighthouse-service/event_handler/evaluate_sli_handler_test.go
lighthouse-service/go.mod
lighthouse-service/go.sum

Closes #2388
This PR adds a list of event IDs that were used for a comparison-based evaluation of SLOs.
Also, the PR removes the filtering logic on the SLI level and instead applies the compare_results_with filter on an event level.

#2388 include event IDs of compared events

---

bridge/server/app.js

This enables caching for static files in express by adding the appropriate header.
This allows upstream proxies (such as our api-gateway-nginx) to cache such a file in memory, if wanted/needed.

#2408 Enable caching for static files in express

---

travis-scripts/build_release_installer.sh

I have disabled uploading index.yaml 2 weeks ago for the time being, so that we don't break our index.yaml in the process of creating the new release (also, to avoid accidental upgrades to 0.7.2).
With this PR I'm reverting this change.

Installer: Re-Enable uploading of index.yaml to google cloud

---

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts

This is a backport of a small bug fix for the "highlighting in the heatmap" feature.

#1640 highlighting in the heatmap - backport 0.7.2

---

.travis.yml

With PR #2414 we introduced an error in .travis.yml.
This PR fixes it.
*Note*: Already backported for 0.7.2

#2411 fix pipeline error

---

cli/cmd/update_project.go
cli/pkg/version/version_checker.go

Closes #2293 
`keptn version` now outputs the following message, which contains the link to the upgrade instructions
```
Keptn CLI version 0.7.1 is available! Please visit https://keptn.sh/docs/0.7.1/operate/upgrade/ for more information.
To disable this notice, run: './keptn set config AutomaticVersionCheck false'
Keptn CLI version: 0.7.0
Daily version check is enabled. 
Keptn will collect statistical data and will notify about new versions and security patches for Keptn. Details can be found at: https://keptn.sh/docs/0.7.x/reference/version_check
---------------------------------------------------
* To disable the daily version check, please execute:
- keptn set config AutomaticVersionCheck false
```
Please note that this requires that the alias in the docs is porperly set, e.g.
``` …
```

#2293 Point user to upgrade docs, fix bug in update project

---

cli/.gitignore
cli/cmd/auth.go

As the feature request in this issue #2300, I have added the support for exporting the current configuration i.e api-token and endpoint.
The configuration is exported to stdout due to undefined structure of config file based on multi-cluster support.

Added support to export endpoint and api-token

---

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.scss
bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
bridge/client/app/_models/trace.ts

If the comparedEvents are provided, those events are highlighted in the heatmap, so that the user now can easily see the selected event and with which it was compared with.

#2389 Highlight comparedEvents in heatmap

---

api/Dockerfile
api/evaluation_model.yaml
api/handlers/evaluation.go
api/models/evaluation.go
api/restapi/embedded_spec.go
api/swagger.yaml
cli/cmd/send_event_evaluationStart.go
cli/go.mod
cli/go.sum
test/test_quality_gates_standalone.sh
test/utils.sh

Closes #2387
The properties from and to for triggering an evaluation have been renamed to start end end.
This PR also fixes an issue with the swagger-ui which caused the model description for triggering evaluations to be empty.
Further changes: adapted integration tests

#2387 Rename properties for triggering an evaluation

---

api/Dockerfile
api/evaluation_model.yaml
api/handlers/evaluation.go
api/models/evaluation.go
api/restapi/embedded_spec.go
api/swagger.yaml
cli/cmd/send_event_evaluationStart.go
cli/go.mod
cli/go.sum
test/test_quality_gates_standalone.sh
test/utils.sh

Closes #2387
The properties `from` and `to` for triggering an evaluation have been renamed to `start` end `end`.
This PR also fixes an issue with the swagger-ui which caused the model description for triggering evaluations to be empty.
Further changes: adapted integration tests

#2387 Rename properties of evaluation

---

.travis.yml

The installation of Keptn via Helm currently fails on MicroK8s 1.19. There is already an issue on the microk8s repo: https://github.com/ubuntu/microk8s/issues/1605 
Until this is fixed we should disable the Integration tests for MicroK8s 1.19

Disabled Microk8s 1.19 integration test

---

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
bridge/client/app/_models/trace.ts

The Heatmap has now labels on the xAxis (either the timestamp or the `buildId` label if it is provided on the event payload is used)

#2131 Show labels on xAxis in Heatmap

---

.gitignore
Makefile
make-scripts/build/build-cli.sh
make-scripts/install_golint.sh
make-scripts/install_helm.sh
make-scripts/run_cli_test.sh
make-scripts/start_bridge.sh
make-scripts/utils/spinner.sh

This PR adds functionality to the Makefile to speed up the local development process. Some of the features and newer additions in this needs discussion. The following commands have currently been added to the Makefile:
* `build-cli`: For building the CLI binary and saving it in a `./bin` directory.
* `start-bridge`: For starting the bridge server
* `fmt`
* `lint`
* `clean`
* `test-unit-cli`: For running unit tests on the CLI
* `prepare-for-pr`: To format, lint and check for commits to prepare it for PR.
Some points that are open for discussion are:
* Should there be commands to deploy the different services as well? This is because all of them are mostly `kubectl -f ...`
* How should the end-to-end tests be tackled in the Makefile? Since they are a set of scripts, what should be the best …

#2405 Add build and run targets in the Makefile 

---

cli/cmd/generate_support_archive.go
cli/cmd/root.go
cli/cmd/version.go
cli/cmd/version_test.go
cli/pkg/version/keptn_version_checker_test.go
cli/pkg/version/ketpn_version_checker.go
cli/pkg/version/version_checker.go
cli/pkg/version/version_checker_test.go
cli/pkg/version/version_fetcher_test.go

Backport of https://github.com/keptn/keptn/pull/2419 for release-0.7.2
I had to remove one function call from the original PR to make it compatible with 0.7.2

#2412 CLI: print keptn cluster version backport (#2419)

---

cli/pkg/credentialmanager/handler.go
cli/pkg/credentialmanager/handler_linux.go

Referring to #2450 which was missing the multiple plans using `KEPTNCONFIG` for mac and windows.

Added support for mac and windows as well

---

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html
bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.scss
bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts

Issue #1997   
Added a copy button to the SLO definition dialog utilizing the clipboard service created for #1977

Added copy button for SLO definition in bridge UI

---

Makefile
make-scripts/build/build-docker.sh

Fixes #2464
The building of all docker images can be launched using the `make build-docker` command.

Makefile: Add a way to build all Dockerfile. Fixes #2464

---

cli/cmd/configure_monitoring.go

Closes #2483 
Note: currently only the dynatrace-service and prometheus service report back using WebSockets. Therefore, when used with any other type, the command has to be called with the `--suppress-websocket` parameter

#2483 allow all monitoring types for configure monitoring cmd

---

installer/manifests/keptn/charts/control-plane/templates/core.yaml

The distributor container in api-service deployment is not querying any Topic and `PUBSUB_RECIPIENT` is undefined/unset hence it is throwing "No pubsub recipient defined" error resulting in the Error state of the distributor container, which eventually puts the pod in CrashLoopBackOff. Hence removing the distributor container from api-service in control-plane helm chart

Removing distributor from api-service in control-plane helm chart

---

bridge/client/index.html

fix incorrect file path when using deep link in portforwarded bridge by setting always an absolute path for base href
fixes #2301

#2301 Incorrect file path

---

cli/main.go

Closes #2504 
`KubeServerVersionConstraints` is explicitely checked for empty string to fall back to default kube constraints.

Handle case when KUBE_CONSTRAINTS is set to ""

---

cli/cmd/create_project.go

The content that is fetched via HTTP client is never passed while creating the project and it ended up trying reading the file for the URL as well. Fixing #2511 
Feature requested in #1648

#2511 Fixed the bug in creating project via http shipyard file

---

configuration-service/common/git.go
configuration-service/handlers/project_resource.go
configuration-service/handlers/service_default_resource.go
configuration-service/handlers/service_resource.go
configuration-service/handlers/stage.go

Closes #2487 
This PR changes the configuration service to retrieve the name of the default branch of the upstream repository (if specified).
For this purpose, the output of the following command is used:
```
$ git remote show origin
remote origin
Fetch URL: https://github.com/my-git-repo
Push  URL: https://github.com/my-git-repo
HEAD branch: master
Remote branches:
dev        new (next fetch will store in remotes/origin)
master     tracked
production new (next fetch will store in remotes/origin)
staging    new (next fetch will store in remotes/origin)
Local branch configured for 'git pull':
master merges with remote master
Local ref configured for 'git push':
master pushes to master (local out of date)
```
The line containing `HEAD branch:` will tell us the name of the default branch …

#2487 Use default branch of origin

---

shipyard-controller/api/event.go
shipyard-controller/api/event_test.go
shipyard-controller/go.mod

Closes #2529 
This PR adds a built-in evaluation task sequence for the shipyard-controller. Now, if a `<stage-name>.evaluation.triggered` event reaches the shipyard controller, it will first check if a matching task sequence is available in the shipyard for the corresponding project/stage. If yes, then that task sequence will be used. If not, a default task sequence with one task (`evaluation`) will be generated and triggered.

#2529 Added built-in task sequence for evaluations

---

.travis.yml
test/test_quality_gates_standalone.sh
test/test_self_healing.sh
test/test_self_healing_scaling.sh
test/utils.sh

This PR makes sure that the versions of the keptn-contrib services used in the integration tests are the ones that are compatible with the respective release

Set versions of keptn-contrib services based on tested keptn version

---

README.md
docs/README.md
docs/install_master.md
docs/integration_tests.md

This PR  adds docs on how to install the current master branch on K8s.
During this task I also noticed that the developer docs need an update regarding k3s and `keptn install`

Added docs on how to install the current master branch

---

helm-service/main.go

Since the helm-service both listens to, as well as generates `service.delete.finished` events, it needs to ignore its own events.

Helm service: ignore events that have been generated by itself

---

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html
bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.scss
bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
bridge/client/app/_components/ktb-events-list/ktb-events-list.component.html
bridge/client/app/_components/ktb-events-list/ktb-events-list.component.ts
bridge/client/app/_models/event-labels.ts
bridge/client/app/_models/event-types.ts
bridge/client/app/_models/trace.ts
bridge/client/app/_services/api.service.ts
bridge/client/app/_services/data.service.ts
bridge/client/app/app.module.ts

The evaluation tile now allows to invalidate evaluation results from the bridge by clicking on the "Ignore for comparison"-Button.
It will ask the user for confirmation and allow to provide a reason as well.

#2548 allow to invalidate evaluation results from bridge

---

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html
bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.scss
bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
bridge/client/app/_components/ktb-events-list/ktb-events-list.component.html
bridge/client/app/_components/ktb-events-list/ktb-events-list.component.ts
bridge/client/app/_models/event-labels.ts
bridge/client/app/_models/event-types.ts
bridge/client/app/_models/trace.ts
bridge/client/app/_services/api.service.ts
bridge/client/app/_services/data.service.ts
bridge/client/app/app.module.ts

The evaluation tile now allows to invalidate evaluation results from the bridge by clicking on the "Ignore for comparison"-Button.
It will ask the user for confirmation and allow to provide a reason as well.

#2548 allow to invalidate evaluation results from bridge - backport 0.7.3

---

bridge/client/app/_services/data.service.ts
bridge/client/app/app-header/app-header.component.html
bridge/client/app/app-header/app-header.component.ts
bridge/client/app/project-board/project-board.component.html
bridge/client/app/project-board/project-board.component.ts
bridge/deploy/bridge.yaml
bridge/server/api/index.js

If keptn is not used as "quality gates only" installation, the bridge shows all core use-cases on integrations page.
The installation type is configured by providing `KEPTN_INSTALLATION_TYPE` environment variable, see _bridge/deploy/bridge.yaml_

#2565 Show all core use-cases on integrations page - backport 0.7.3

---

bridge/client/app/_services/data.service.ts
bridge/client/app/app-header/app-header.component.html
bridge/client/app/app-header/app-header.component.ts
bridge/client/app/project-board/project-board.component.html
bridge/client/app/project-board/project-board.component.ts
bridge/deploy/bridge.yaml
bridge/server/api/index.js
configuration-service/go.sum

If keptn is not used as "quality gates only" installation, the bridge shows all core use-cases on integrations page.
The installation type is configured by providing `KEPTN_INSTALLATION_TYPE` environment variable, see _bridge/deploy/bridge.yaml_

#2565 Show all core use-cases on integrations page

---

installer/manifests/keptn/charts/continuous-delivery/templates/continuous-deployment.yaml

In reviewing the resource quota of deployments, I recognized that the jmeter-service is missing the resource configuration.
All the other deployments have a resource config.

Configure resource request and limit for jmeter-service

---

cli/pkg/credentialmanager/handler.go
cli/pkg/credentialmanager/handler_linux.go

In regards to #2300 
```
contexts:
- api_token: blablabla
endpoint: http://91.xxx.xx.xx.nip.io/api
name: keptn-test
- api_token: blablablah
endpoint: http://localhost:8080/api
name: keptn-demo
namespace: keptn-demo
```

Added support for KEPTNCONFIG environment variable

---

api/deploy/service.yaml
configuration-service/deploy/service.yaml
distributor/deploy/distributor.yaml
gatekeeper-service/deploy/service.yaml
helm-service/deploy/service.yaml
jmeter-service/deploy/service.yaml
lighthouse-service/deploy/service.yaml
mongodb-datastore/deploy/mongodb-datastore.yaml
shipyard-controller/deploy/service.yaml

Closes #2536 
The livenessProbes have been removed from the individual service manifests that are used for developing. The manifests of the installer helm chart have been left untouched.
After removing the livenessProbe from the mongodb-datastore I was able to use the remote debugging feature again with no pod restarts

#2563 Removed livenessProbes from development manifests

---

bridge/client/app/_services/data.service.ts

When merging the feature https://github.com/keptn/keptn/commit/7dea4c95dc4abc4feb4f8de7db12f862ede1436d#diff-b63bb8da34d1fc6e6a5e1114fe4faa39aed2ddf2ff0369cffe5595cae4d1f68b to master, some lines where dropped. The Bridge should load the bridgeInfo first and then projects.

Load bridgeInfo first and then projects

---

bridge/client/app/_models/service.ts
bridge/client/app/_services/data.service.ts
bridge/client/app/project-board/project-board.component.html
bridge/client/app/project-board/project-board.component.ts

Closes #2543 
This issue was noticed on the _Services_ screen in the Bridge, but impacted also the _Environments_ screen. On the Environments page the Bridge shows all deployed services on a specific stage.
At initial page load the Bridge loads maximal 20 root events, and if those 20 root events are Problem events or Evaluation events (not Configuration change events), the Bridge looses the information about the last deployment and displayes that the service hasn't been deployed yet. But when retrieving the services from the API, the _deployedImage_ is provided as a separate attribute.
Now the Bridge is not only polling for root events, but also is polling the service details for each stage (only while in the detail view) and uses the `deployedImage` from service details to show currently …

#2543 Use deployedImage from service

---

cli/cmd/root.go

Closes #2571 
I re-added the version check into the root command again. And also added a check if CLI and cluster versions are equal, which fixes #2590 

#2571 Re-add the version check into the root command

---

.travis.yml

This PR moves most integration tests to cron (executed during the night).
This helps saving some travis-ci build credits for now.
I've left on k3s test in travis for the time being.

#2753 Move most integration tests to cron (nightlies)

---

.travis.yml
docs/integration_tests.md
test/test_delivery_assistant.sh
test/test_install_kubernetes_quality_gates.sh
test/test_install_on_kubernetes.sh
test/test_self_healing.sh
test/utils.sh

Closes #2771
This PR adds the integration tests for the self healing use case, as well as for the delivery assistant to the tests executed in K3s/Minikube. 
Open questions: Those two tests do add 5min to the execution time. Do we want to execute those additional tests both on Microk8s and K3s, or should we add those tests to only one platform, i.e. K3s?
Further changes: To be able to test the delivery assistant, I added the `--use-case=continuous delivery` flag to the installation command and renamed the containing script accordingly.

#2771 Execute self healing and delivery assistant use case in k3s and microkube

---

.github/workflows/detect_stale_images.yml
gh-actions-scripts/detect_stale_images.sh

This PR introduces a new action that checks for stale images based on Github release tags.
FYI, I've executed the script locally and for now all release images should be "not stale".

#2710 Detect stale release images and pull them

---

cli/pkg/credentialmanager/handler.go

The issue was because we weren't using QueryEscape to convert `/` which resulted in creating new dir in gpg and resulting in the error. 
Signed-off-by: ankitjain28may <ankitjain28may77@gmail.com>

Fixed the gpg pass issue

---

.travis.yml
travis-scripts/build_cli.sh

We are still consuming too many credits on travis. This PR removes the OSX builds for now.

#2715 Remove osx build stage to save credits

---

test/assets/evaluation_triggered_event_template.json
test/assets/mongodb-datastore_evaluation_triggered_template.json
test/assets/mongodb-performance.jmx
test/assets/self_monitoring_sli.yaml
test/assets/self_monitoring_slo.yaml
test/assets/shipyard-quality-gates-self-monitoring.yaml
test/test_keptn_performance.sh
test/utils.sh

Closes #2759
**Performance Test Setup:**
- Configured my Keptn installation to be monitored by Dynatrace, and created **keptn-selfmonitoring** project in my Keptn installation.
- Added each core service to the **keptn-selfmonitoring** project. Note: For the sake of this Issue, only the **mongodb-datastore** is needed, but having all services available for doing evaluations does not harm.
**Test protocol**:
1. Created a project
1. Create a service
1. Send 100 evaluation.triggered events
1. Send evaluation.triggered event for the **mongodb-datastore** - This triggers the **evaluation** task sequence which first performs a load tests using the jmeter service, and then evaluates the results using monitoring data from my DT tenant.
1. Send 10 evaluation.invalidated events
1. Trigger another …

#2759 mongodb performance investigation

---

jmeter-service/main.go
lighthouse-service/event_handler/evaluate_sli_handler.go

Closes #2751 
The desired behavior was already mostly implemented by the services. There were some places additional where I have added the functionality to send .finished events to get a better overview in the event trace

#2751 Core services: send .finished events when errors occur

---

shipyard-controller/api/event.go
shipyard-controller/api/event_test.go

Closes #2816
This PR also makes sure that the shipyard controller does not trigger a sequence in another stage if the last task.finished event does not a `data.result` field with its value set to `pass`

#2816 Properly set result field of <task>.triggered event

---

installer/manifests/keptn/charts/continuous-delivery/charts/openshift/templates/route-service-openshift.yaml
installer/manifests/keptn/charts/continuous-delivery/templates/continuous-deployment.yaml
installer/manifests/keptn/charts/control-plane/templates/continuous-operations.yaml
installer/manifests/keptn/charts/control-plane/templates/core.yaml
installer/manifests/keptn/charts/control-plane/templates/mongodb-datastore.yaml
installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml
installer/manifests/keptn/templates/_helpers.tpl

This PR fixes #2649 by 
* reducing memory and cpu resources limits/requests for distributors,
* adding a helper template function for those limits/requests
**todo: update https://github.com/keptn/keptn.github.io/pull/683**
If you want to test it, here is the helm chart: 
[keptn-0.1.0.zip](https://github.com/keptn/keptn/files/5697186/keptn-0.1.0.zip) (please extract the zip file, and use ``helm upgrade keptn keptn --install -n keptn --create-namespace --wait --repo=./keptn-0.1.0.tgz `` )
Question to @agrimmer 
is it okay to have the function
```
{{- define "keptn.distributor.resources" -}}
resources:
requests:
memory: "16Mi"
cpu: "25m"
limits:
memory: "32Mi"
cpu: "250m"
{{- end }}
```
in helpers.tpl? I opted for …

#2649 Reduce memory and cpu resource requests/limits for distributors in helm-chart

---

.github/workflows/CI.yml

* Fixed issue with environment variables for partial builds not correctly set
* Fixed issue for KUBE_CONSTRAINTS not being set
* Enabled MacOS unit tests and builds

#2824 Various CI fixes

---

gh-actions-scripts/build_installer_helm_chart.sh

This PR replaces `appVersion: latest` with (e.g.) `appVersion: 0.7.4-dev-PR-2824` in the helm-chart that is being built and published as an artifact.
It's a requirement for #2811.

#2824 Replace helm-chart appVersion of latest with the actual version

---

installer/manifests/keptn/charts/continuous-delivery/templates/continuous-deployment.yaml

The `continuous-deployment.yaml` references template features from `_helpers.tpl` of the `control-plane` chart;  `continuous-deployment.yaml` has to take the template features from `_helpers.tpl` of the `continuous-delivery` chart.
Note: It is not nice that the chart is called continuous-**delivery** and the main fail of the chart is called continuous-**deployment**. This should be addressed by another issue.

Fixed false reference to control-plane template

---

.github/workflows/CI.yml
gh-actions-scripts/build_installer_helm_chart.sh

This PR fixes artifact names for
* CLI (remove the file-ending, e.g., `.exe` from the .tar.gz archive)
* installer (name the file name keptn-installer-${VERSION}.tgz instead just keptn-${VERSION}.tgz)

#2824 Fix artifact names for cli and installer

---

.gitignore
gh-actions-scripts/build_installer_helm_chart.sh
installer/.gitignore

In https://github.com/keptn/keptn/pull/2858 I introduced the new helm-chart name `keptn-installer-${VERSION}`. Unfortunately there are some more places where this is needed, which I fixed with this PR.
In addition I improved our `.gitignore` file to ignore files when generating the installer helm chart locally.

#2824 Fix Building of helm-charts

---

cli/cmd/version.go

While generating docs for 0.8.x alpha I noticed that we need to reflect the version change in version.go within the CLI.

Fixed Keptn Release Docs URL

---

configuration-service/common/projects_materialized_view.go
configuration-service/common/projects_materialized_view_test.go
configuration-service/handlers/project_resource.go
configuration-service/models/expanded_project.go
configuration-service/restapi/embedded_spec.go
configuration-service/swagger.yaml

Closes #2804 
It turned out that up until now, the shipyard content was only persisted after updating a shipyard.yaml for a project, but not during the project creation. This has been fixed with this PR. 

#2804 Added shipyardVersion property to GET /project response

---

configuration-service/common/projects_materialized_view.go
configuration-service/handlers/project.go
shipyard-controller/api/project.go

Closes #2879 
In case there already was an upstream repository defined before updating the project with the wrong one, the previous credentials will be restored.

#2879 delete upstream repo credentials if there was an error

---

bridge/client/app/_components/ktb-events-list/ktb-events-list.component.html
bridge/client/app/_components/ktb-events-list/ktb-events-list.component.ts
bridge/client/app/_models/event-types.ts
bridge/client/app/_models/trace.ts

Since the `.triggered`, `.started` and `.finished` events of any type are now "merged" in the Bridge into one `Trace`, the heatmap was not showing up, since the results are provided with the `.finished` event, which now is not showing up as a separate tile anymore. 
This makes it easier to read the tasks that were executed, but also had to be considered for showing the evaluation results correctly.

#2625 Heatmap not showing up in Bridge

---

helm-service/pkg/helm/generated_chart_handler.go
helm-service/pkg/helm/generated_chart_handler_test.go
installer/manifests/keptn/charts/continuous-delivery/templates/continuous-deployment.yaml

Closes #2362 
In the original PR for this Issue (PR #2882), the hostname template was only used for generating the public deployment URI for the CloudEvent, but not for the actual creation of the rule for the VirtualService. This has been added with this PR

#2362 use HOSTNAME_TEMPLATE in generated VirtualServices

---

shipyard-controller/api/event.go
shipyard-controller/deploy/service.yaml

I just went through the logs of shipyard-controller and saw that there are missing spaces, which I hereby fixed.
Also, I've set the distributor image to 0.8.0-alpha so we can use skaffold again to test it.

Fixed missing spaces in logging output in shipyard-controller

---

.github/workflows/CI.yml
gh-actions-scripts/build_docker_image.sh

Based on #2824, this PR enhances the CI workflow, specifically the Docker Build process in the following ways:
* Added some sanity checks for `docker_build.sh`
* Ensured that forked PRs don't run docker login (it's not possible, secrets are not shared with forked PRs by GH action)

#2824 Only login to dockerhub if we are on the original repo, not on a fork

---

.github/workflows/CI.yml
gh-actions-scripts/build_docker_image.sh

This PR adds a feature to our CI build where we post a comment with the updated docker images of the PR.
The comment is updated every time a new commit is built (so the previous comment gets deleted).
If no Docker Images have been updated, it looks like this:
And if an image is built, it looks like this:

#2824 Report Docker Build to PR

---

test/utils.sh
test/utils/send_new_artifact_sockshop.sh

During log analysis of our integration tests I noticed two things:
1. Our "wait timeouts" are way too high, leading to integration tests that are running for ages
2. While we waited for `carts-db` to be deployed, we never exited
This PR tries to fix both.

Improve integration tests for new-artifact

---

test/utils/gke_create_cluster.sh
test/utils/install_istio.sh

This PR addresses the first parts of #2976 and #2973:
* Upgrade Istio to 1.8.2 in integration tests
* Use GKE Shielded Nodes in integration tests
* In addition, I used the time to remove the istio addon from our GKE installation (we don't want to be forced to use the old version of istio)
We still need to adapt our docs.

#2976 #2973 Upgrade istio, enable GKE shielded nodes

---

cli/cmd/auth.go
cli/cmd/upgrade.go

The new flag `--patch-namespace` was introduced in the PR #2733 but the calling function was later being removed somehow because of which the CLI was throwing error/crashing as the issue raised in #2912 
This has been fixed and also added the error message while running `keptn auth` without patching the namespace.
Signed-off-by: ankitjain28may <ankitjain28may77@gmail.com>

Fixed the patch-namespace flag and also added the error message to run auth  command without upgrade

---

configuration-service/handlers/project.go
configuration-service/handlers/service.go
configuration-service/handlers/stage.go

As part of #2754, this PR changes the configuration-service behavior to return projects, services, and stages in alphabetical order per default.

added alphabetical sorting of projects, services and stages in keptn backend

---

.github/workflows/cleanup_images.yml
.github/workflows/detect_stale_images.yml
gh-actions-scripts/cleanup_docker_images.sh
gh-actions-scripts/detect_stale_images.sh

* This PR fixes the failed workflows for stale and outdated images
* Set OS to ubuntu-20.04 (instead of `ubuntu-latest`)
* added c-py/action-dotenv-to-setenv@v2 for loading .ci_env
* added more (older) services for outdated tag check
* added a check for images/tags based on commit hashes that are outdated
* added some more debug messages
* added sanity checks
In addition, I've ran the script locally and cleaned up old/outdated-images on `keptn` organization on hub.docker.com.

#2824 Fix stale images script

---

.github/workflows/CI.yml
.github/workflows/integration_tests.yml
gh-actions-scripts/build_installer_helm_chart.sh

This PR partially implements #2824, by doing the following:
* CI: When setting the label `CI:trigger-build-everything` on a PR, we are forcing the CI to build all docker images and the CLI
* CI: Export build-environment/build-config as an artifact, such that it can be re-used in the integration-test workflow
* CI: Add option for installer helm-chart to contain datetime for docker image tags
* Integration Tests: Create a Pre-Release (if `inputs.publish_as_release` is set to 1 - it defaults to 0 atm), including build reports, CLI and helm-chart artifacts
Example Release: https://github.com/keptn/keptn/releases/tag/0.8.1-dev-PR-2965
You can actually use this as follows:
```console
curl -sL https://get.keptn.sh | …
```

#2824 Improve integration test workflow, create a pre-release

---

test/test_quality_gates_standalone.sh

This will make debugging failing tests (such as https://github.com/keptn/keptn/runs/1759499122?check_suite_focus=true) easier

Added log output of lighthouse service and dynatrace-sli-service

---

test/test_quality_gates_standalone.sh

in the previous PR (#2984), the logs were retrieved after the dynatrace-sli-service has already been deleted. This is fixed with this PR

Added log output of lighthouse service and dynatrace-sli-service 

---

.github/workflows/CI.yml

Fixes #2975 by disabling the PR report feature of our CI pipeline for forks (same as with `docker login`).

#2975 Disable PR report for forks

---

.github/workflows/CI.yml

Due to a resource shortage on GitHub, our build tasks running on macOS were failing frequently due to running into a timeout. This caused the CLI to not be built and therefore changes made to the CLI were not tested in the integration tests. This PR disables the macOS tasks for now.

Disable build tasks on macOS

---

test/assets/quality_gates_standalone_sli_dynatrace_step1.yaml
test/assets/quality_gates_standalone_sli_dynatrace_step2.yaml

This should solve the problem of not receiving any data from the DT metrics API in our qg integration tests

Changed DT entity tag filters for qg integration test

---

cli/cmd/install.go
cli/cmd/upgrade.go
cli/pkg/helm/helm_helper.go

Closes #2988 
Added a timeout of 10minutes to the helm upgrade command - QQ: would it make sense to make this configurable as a parameter to the install command? 
In case of a timeout, added a hint to check the status of the installation via `kubectl get pods -n <keptn-namespace>`. In issue #2988 it was suggested to specifically check for an `ImagePullBackOff` in the deployments, but given that a timeout might have numerous reasons, I was thinking a more general hint might be better suited in this case.

#2988 added timeout to helm install

---

cli/cmd/install_upgrade_params.go
cli/cmd/upgrade.go
cli/cmd/upgrade_test.go

Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
This PR adds a new flag to the keptn's cli upgrade command that allows the user to skip the upgrade compatibility check.
closes #2689

Added flag to skip upgrade compatibility check

---

.github/workflows/CI.yml
.gitignore
codecov.yml

This PR tries to fix #2929 by doing the following:
* Added codecov reporting to CLI tests
* Added codecov call to every unit test (instead of a single call for all of them)
* Added a flag (`-F flagname`) when running codecov to split tests and codecov by directory
* Added `-c` flag to cleanup after sending the report (to avoid having a mix of reports)
* Added `coverage.txt` to .gitignore
* Added the `carryforward` flag for all directories, such that it *should* carry over the coverage from the last build (e.g., master branch) - this is recommended for monorepos, but it remains to be seen if it also works as expected.
Whether those changes have the desired effect or not can not be seen within this PR, but after it …

#2929 Improve CodeCoverage reporting

---

mongodb-datastore/handlers/events.go

Closes #2925
So far the results seem promising. I executed the same test as described in #2812, and the response time pretty much stays constant at a median of 100ms, and 95th percentile of 200ms:
In addition to the indexes mentioned in #2925, adding an index for the property `type` in the collections containing a project's events proved to be beneficial (e.g. for loading the evaluation heatmap which queries a specific event type)

#2925 add indexes to mongodb collections

---

bridge/client/app/_models/trace.spec.ts
bridge/client/app/_models/trace.ts

Fixes #3021
I also added a unit test to cover this behaviour

#3021 Fixed missing image from artifact-delivery events in Bridge

---

.github/workflows/CI.yml
.github/workflows/integration_tests.yml
test/utils/k8s_collect_resources.sh

Last improvement based on #2824 (upgrading to the latest get-next-semver action).
Plus: I found that our master builds are always using builds from PRs, e.g.:
In addition, I found that existing release were not detected properly, e.g.:
With this PR I am using the `extract_branch` steps output `BRANCH` in the download-artifact step for publishing the release. Also, I fixed the problem with the release-check.

Several smaller fixes for integration test workflow

---

bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html
bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts
bridge/client/app/app.module.ts

Switched SLI evaluation breadown to a barista table. 
Open issues:

#2478 SLI evaluation breakdown as barista table

---

.github/dependabot.yml

Dependabot is creating roughly 100 PRs as we have some dependencies that we could update... This PR tries to lower the amount of PRs and disables rebase strategy for now (to lower the strain on our CI).

Slow down dependabot

---

cli/cmd/check_endpoint_status.go
cli/cmd/configure_bridge.go

Fixes #3058
I've removed it in go-utils as well, see https://github.com/keptn/go-utils/pull/237

#3058 Remove XipIoResolver

---

distributor/cmd/main.go

The log output removed in this PR was only used for debugging and was not intended to stay here

Remove payload of received response from distributor logs

---

.github/workflows/integration_tests.yml
test/test_self_healing.sh

"Fixes" #2951 by disabling the quality gates integration test for minishift (we can't fix it, see #2951 for details).
This PR also cleans up the self healing test.

#2951 Disable quality gates integration test for minishift, cleanup self healing test

---

.github/workflows/create_release_branch.yml

This PR adds a workflow to automate the creation of a release branch (and copying of release notes).
In addition, the workflow checks if the release name adheres to semver :) 
FYI: This workflow is not very specific to keptn/keptn itself, it can be copied to our keptn-contrib/sandbox services aswell. Might be worth to extract some functionality as another gh-action.

Added a workflow to automatically create a release branch

---

jmeter-service/common.go

GetStageResource was called with a URL containing two slashes, e.g. `/project/{projectName}/stage/{stageName}/resource//{resourceURI}`

Remove duplicate / in URL

---

helm-service/controller/deployment_handler.go
helm-service/controller/deployment_handler_test.go
helm-service/pkg/helm/generated_chart_handler.go
helm-service/pkg/helm/generated_chart_handler_test.go
helm-service/pkg/helm/helm_mock_executor.go

Closes #2764 
This PR fixes the inferring of the URL as follows: In case a user uses deployment strategy `direct` or `blue_green_service`, the `DeploymentURIsLocal` and `DeploymentURIsPublic` are always inferred regardless they are already present in the incoming event.

#2764 Fix inferring urls

---

distributor/cmd/main.go

This PR fixes bugs when the distributor is used as a proxy.
More precisely, it forwards the query parameters when sending the request and returns the headers.
Unit tests require a refactoring of the function `APIProxyHandler`. A contribution would be more than welcome! 

Forward query parameters and headers

---

cli/cmd/send_event_approvalFinished.go
shipyard-controller/handler/shipyardcontroller.go
shipyard-controller/handler/shipyardcontroller_test.go

Closes #3199 
Additional change: the delivery assistant of the CLI was showing the git commit ID of the deployment.finished event associated with the approval. Since the `configurationChange` property is now included in the approval.triggered event, we can now easily determine the image of the service that should be approved

#3199 Shipyard controller: propagate properties of .triggered event

---

.github/workflows/integration_tests.yml

Fixes #3243 
With this PR I ensure that a GKE cluster is always deleted (using `if: always()`).
In addition, due to resource constraints within our Google Project, I have moved from us-central1-a to us-east1-b, e.g.:

#3243 Fix GKE cluster delete, move to another GKE region

---

.github/workflows/CI.yml
installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml

Fixes #3320.
This PR adds an annotation to the deployment which should lead to a restart every time the helm chart gets applied/installed/upgraded.
In addition, I have fine tuned the resource requirements of the pod according to my current measurements.

#3320 Always restart api-gateway-nginx deployment on changes

---

shipyard-controller/handler/shipyardcontroller.go
shipyard-controller/handler/shipyardcontroller_test.go

Related to #3224
This PR ensures that the shipyard controller updates the deployed image of a service when receiving a deployment.finished event

#3224 Fixed updating events for service in shipyard controller

---

bridge/client/app/_models/project.ts

The score was not displayed, because the evaluation event was not found.
Now it should load the evaluation for approval-item correctly, taking the `.finished` event from the evaluation task:

Show evaluation score for approval-item

---

bridge/client/app/_models/event-types.ts
bridge/client/app/_services/api.service.ts

Rename `evaluation.invalidated` and set `triggeredid` for `evaluation.invalidated` same as for `evaluation.finished`
Fixes #3290

#3290 Invalidation of evaluation

---

shipyard-controller/db/events_operations.go
shipyard-controller/db/mock/events_operations_mock.go
shipyard-controller/handler/shipyardcontroller.go
shipyard-controller/handler/shipyardcontroller_test.go

Closes #3335 
This PR makes sure to regularly update the shipyard content of a project in the materialized view (whenever an event for that project is received). This makes sure to achieve eventual consistency, between the information stored in the db and the actual state of the shipyard in the git repo.

#3335 update shipyard content of project when receiving event

---

bridge/client/app/_services/api.service.ts
bridge/client/app/_services/data.service.ts
bridge/client/app/_views/ktb-service-view/ktb-service-view.component.ts
bridge/client/app/project-board/project-board.component.ts

Load root events per service to ensure that for each service the latest root events are displayed and take services from GET /project response (actually no separate API calls needed)
Fixes #3223 

#3223 Load root events per Service

---

.github/workflows/integration_tests.yml

I'm not sure what's going on, but it seems that *draft* releases that I have published are being deleted after some time, e.g., https://github.com/keptn/keptn/releases/tag/0.8.0-dev.202102221215
Either there is an error in GitHub UI (when I delete draft releases manually), or there is a problem with our CI job.
For the sake of sanity, I've commented out the part where it should delete the draft release in the CI job.

Stop deleting draft releases

---

test/test_linking_stages.sh

Due to the introduced limitation regarding the length of a service name (see https://github.com/keptn/keptn/issues/2948), the `linking_stages.sh` integration tests were failing. This PR shortens the name of the service to be compliant with this limitation.

Renamed service name in linking-stages integration test

---

.github/workflows/integration_tests.yml
test/test_self_healing.sh

Before merging, check for availability of: 
- [Dynatrace-sli-service 0.8.0](https://hub.docker.com/repository/docker/keptncontrib/dynatrace-sli-service/tags?page=1&ordering=last_updated&name=0.8.0)
- [Unleash-service 0.3.0](https://hub.docker.com/repository/docker/keptncontrib/unleash-service/tags?page=1&ordering=last_updated&name=0.3.0)

Use release versions of contrib services for integration tests

---

.github/workflows/CI.yml

This PR allows us to trigger the CI build manually, potentially fixing https://github.com/keptn/keptn/issues/3393

Allow running CI build manually

---

.github/workflows/create_release_branch.yml

Fixes #3393
This PR adds a personal access token to the create-release-branch workflow. This ensures that CI tests are running after the release branch has been created (a known limitation of GH action)

#3393 Added PAT to the create release branch workflow

---

.github/workflows/integration_tests.yml
gh-actions-scripts/build_helm_charts.sh
gh-actions-scripts/upload_helm_chart_to_google_cloud.sh

This PR adds a final step for uploading helm charts to google cloud.
In addition, I renamed the packaged helm chart `keptn-installer-${VERSION}.tgz` to `keptn-${VERSION}.tgz`, as this is what we are expecting in the CLI when calling `keptn install`
https://github.com/keptn/keptn/blob/b2ba2f7ecf58b06f13f97a76c65fa43ed9f97121/cli/cmd/install_upgrade_params.go#L15-L26

Added a step to upload helm charts

---

helm-service/.dockerignore
helm-service/chart/templates/deployment.yaml
helm-service/skaffold.yaml
installer/manifests/keptn/charts/continuous-delivery/templates/continuous-deployment.yaml
jmeter-service/chart/templates/deployment.yaml
jmeter-service/chart/values.yaml
jmeter-service/deploy/service.yaml
jmeter-service/main.go
jmeter-service/skaffold.yaml

Fixes #3418
* helm-service/charts
* added `SHIPYARD_CONTROLLER`, `EVENTBROKER` and `HOSTNAME_TEMPLATE` environment variables
* Fixed `CONFIGURATION_SERVICE` pointing to the wrong URL
* installer/ continuous-delivery charts: helm-service
* removed `CANARY` variable as it is not needed nor consumed anywhere 
* removed `EVENTBROKER`
* jmeter-service: Properly set resource requests to something that makes sense
* jmeter-service/charts
* Fixed `CONFIGURATION_SERVICE` pointing to the wrong URL
* Properly set resource requests to something that makes sense
* jmeter-service
* removed relevant source code for `EVENTBROKER`
* skaffold related
* Updated `skaffold.yaml` for helm-service and jmeter-service
* Updated helm-charts …

#3418 Sync helm-charts (installer, jmeter-service, helm-service)

---

.github/workflows/CI.yml

There is still an issue with the latest release-branch we pulled, where the CI workflow is triggered for both, the Pull Request and the Push on the release branch.
https://github.com/keptn/keptn/pull/3428
With this PR I am disabling CI Builds for Pull-Requests if the base-branch is "release-"*.
See https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables for docs regarding GITHUB_HEAD_REF.

Abort PR build for releases

---

bridge/client/app/_models/event-icons.ts

This PR reverts the typo fix for `perfromance-health`, which is a legimatimate icon in barista:  https://barista.dynatrace.com/resources/icons/perfromance-health

Revert typo fix for perfromance in bridge

---

shipyard-controller/docs/docs.go
shipyard-controller/docs/swagger.json
shipyard-controller/docs/swagger.yaml
shipyard-controller/handler/servicehandler.go

Fixed #3456 by
* changing `/project/{project}/service/{service}` URL to `/project/{project}/service/{stage}` in  shipyard-controller/handler/servicehandler.go (please note: the remaining changes are automatically generated using `swag init`)
This not only fixes the endpoint description in swagger UI, but also makes a new endpoint visible:

Fix wrong URL parameter in shipyard-controllers swagger

---

configuration-service/.dockerignore
configuration-service/Dockerfile
configuration-service/deploy/service.yaml
configuration-service/skaffold.yaml
docs/debugging.md
lighthouse-service/Dockerfile
lighthouse-service/deploy/service.yaml
lighthouse-service/skaffold.yaml
shipyard-controller/.dockerignore
shipyard-controller/Dockerfile
shipyard-controller/deploy/service.yaml
shipyard-controller/skaffold.yaml

While investigating issue #3421 I noticed several smaller issues with our skaffold setup, which I addressed for the following microservices:
* shipyard-controller
* lighthouse-service
* configuration-service
Mainly:
* Add a `.dockerignore` to speed up the build while using `skaffold dev`
* Added `SKAFFOLD_GO_GCFLAGS` in favor of `debugBuild` (see https://github.com/GoogleContainerTools/skaffold/blob/master/examples/getting-started/Dockerfile for an example)
* Set distributor to use 0.8.0
* Improve memory request/limits (limits is set to 512 Megabytes on those containers, it should be more than enough; requests does not need to be that high)
* Upgraded skaffold version in skaffold.yaml (you might require a newer …

#3421 Improve debugging experience in configuration-service, shipyard-controller and lighthouse-service

---

helm-service/Dockerfile
helm-service/skaffold.yaml
jmeter-service/Dockerfile
jmeter-service/skaffold.yaml

This PR fixes #3421 by performing some changes to skaffold.yaml, which will allow us to debug jmeter and helm service again.
In addition, I have included similar changes as in PR https://github.com/keptn/keptn/pull/3467, e.g.: using `SKAFFOLD_GO_GCFLAGS` instead of `debugBuild`, memory settings for distributor, fixing distributor tag to 0.8.0

#3421 Fix debugging for jmeter and helm-service

---

.github/actions/spelling/patterns.txt
.github/workflows/integration_tests.yml

Fixes #3166
Also added `perfromance` aswell as `uses: *`  to the spelling exceptions (patterns)
Example:
https://github.com/keptn/keptn/issues/3474

#3166 Added a workflow step to post errors of integration test failures

---

make-scripts/build/build-cli.sh

This fixes #3475 by adding CGO_ENABLED=0. I tried using the other approach described in #3475, but it didn't work.

#3475 Fix CLI builds for platforms that dont have dynamic linking support

---

.github/workflows/CI.yml

With the changes in this PR a `docker login` is also triggered when manually **manually** starting the CI Workflow via the GH UI.
This is necessary for beeing able to push the built Docker image to the Docker registry.

#3489: added trigger for doing docker login at workflow dispatch

---

bridge/client/app/_components/ktb-evaluation-info/ktb-evaluation-info.component.html
bridge/client/app/_components/ktb-evaluation-info/ktb-evaluation-info.component.scss
bridge/client/app/_components/ktb-evaluation-info/ktb-evaluation-info.component.spec.ts
bridge/client/app/_components/ktb-evaluation-info/ktb-evaluation-info.component.ts
bridge/client/app/_components/ktb-services-list/ktb-services-list.component.html
bridge/client/app/_components/ktb-services-list/ktb-services-list.component.scss
bridge/client/app/_components/ktb-services-list/ktb-services-list.component.spec.ts
bridge/client/app/_components/ktb-services-list/ktb-services-list.component.ts
bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html
bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.ts
bridge/client/app/_components/ktb-stage-overview/ktb-stage-overview.component.html
bridge/client/app/_components/ktb-stage-overview/ktb-stage-overview.component.ts
bridge/client/app/_models/event-icons.ts
bridge/client/app/_models/project.ts
bridge/client/app/_models/service.ts
bridge/client/app/_models/stage.ts
bridge/client/app/_services/data.service.ts
bridge/client/app/_views/ktb-environment-view/ktb-environment-view.component.html
bridge/client/app/_views/ktb-environment-view/ktb-environment-view.component.ts
bridge/client/app/app.module.ts
bridge/client/app/project-board/project-board.component.html

Services are shown in the stage tile in the environments screen as table, also showing the recent sequence and the status of that sequence and if available also the evaluation result for that sequence on that stage.
closes #2289

#2289 Show services and recent sequence in stage tile as table

---

test/assets/quality_gates_standalone_slo_step1.yaml
test/assets/quality_gates_standalone_slo_step2.yaml
test/assets/quality_gates_standalone_slo_step3.yaml

Closes #3546 
This PR significantly increases the response time threshold for the demo service we are retrieving the metrics for. Imho the integration tests should not depend on the response time of a demo service.

#3546 increase response time thresholds for demo service

---

shipyard-controller/docs/docs.go
shipyard-controller/docs/swagger.json
shipyard-controller/docs/swagger.yaml
shipyard-controller/handler/evaluationhandler.go
shipyard-controller/handler/servicehandler.go
shipyard-controller/handler/stagehandler.go

The swagger def of the shipyard controller is invalid.
Fix in `*.go` files.

fixed errors in swagger definition of shipyard controller

---

helm-service/main.go

This commit prevents that the helm-service exists after discovering that
it does not have admin access when checking the available RBAC. Instead,
it logs a warning and continues to operate.
This is a temporary workaround for supporting fine-granular RBAC in the
helm-service to deploy kubernetes workloads (#3511).

Print warning in case of non-admin rights in helm-service

---

bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html
bridge/client/app/_models/trace.ts

take deploymentURI from finished event (not from triggered)
closes #3535

#3535 take deploymentURI from finished event (not from triggered)

---

shipyard-controller/docs/docs.go
shipyard-controller/docs/swagger.json
shipyard-controller/docs/swagger.yaml
shipyard-controller/handler/servicehandler.go
shipyard-controller/main.go

This PR fises the API path for _getting all services in a stage of a project_.
Also it fixes the swagger API title.
Changes in: 
* servicehandler.go
* main.go

swagger-ui: fixed "get services in stage" endpoint description and title

---

installer/manifests/keptn/charts/control-plane/templates/rbac.yaml

apigroup field was missing preventing the secret service from creating roles

fix apiGroup

---

jmeter-service/main.go

**Changes**
* Added Quick DNS lookup check for service Url with a relevant message for failure
* Added message parameter to `sendTestsFinishedEvent` method
**Related Issue**
Closes #3559

Enhance JMeter result message

---

installer/manifests/keptn/charts/control-plane/templates/core.yaml

Liveness probes are inserted into all containers through the template,
but some resources have duplicate explicit livenessProbes.
The duplicates can cause issues with othering tooling in advanced
install use cases, such as helm templating. Where other tools are less
forgiving of the duplicates.
This change removes the additional explicit livenessProbe definitions
and leaves all containers to be populated only by the template.
closes #3768

Remove duplicate livenessProbes

---

.github/actions/spelling/expect.txt
api/Dockerfile
approval-service/Dockerfile
bridge/Dockerfile
configuration-service/Dockerfile
configuration-service/restapi/configure_configuration_service.go
distributor/Dockerfile
installer/manifests/keptn/charts/control-plane/charts/mongodb/templates/deployment.yaml
installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml
installer/manifests/keptn/charts/control-plane/templates/continuous-operations.yaml
installer/manifests/keptn/charts/control-plane/templates/core.yaml
installer/manifests/keptn/charts/control-plane/templates/mongodb-datastore.yaml
installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml
installer/manifests/keptn/charts/control-plane/values.yaml
lighthouse-service/Dockerfile
mongodb-datastore/Dockerfile
remediation-service/Dockerfile
shipyard-controller/Dockerfile
statistics-service/Dockerfile

This PR adds securityContext properties to all services of the Keptn control-plane.
Out of scope of this PR:
- helm-service
- jmeter-service
- platform-support/openshift-route-service
Signed-off-by: Andreas Grimmer <andreas.grimmer@dynatrace.com>

Run containers as non-root

---

.github/workflows/CI.yml
.github/workflows/shellcheck.yml

1. the `types` field is not spelled `type` -- this could mean that the CI pull_request case has been unintentionally doing something totally out of character. -- per https://github.com/keptn/keptn/pull/3752#discussion_r614576353 we've decided that we want `labeled`, `unlabeled`, and the normal `types` defaults (`opened`,`synchronize`, `reopened`).
2. the `runs-on` field wants either a string for a GH hosted runner, or an array for a self-hosted. But shellcheck was using an array for a GH hosted.

CI workflow tweaks

---

helm-service/pkg/helm/helmv3_executor.go

The behaviour introduced in this PR ensures that a deployment gets deleted when the initial installation fails and upgrades get reverted when they fail. Further reading: https://medium.com/polarsquad/check-your-helm-deployments-ffe26014804

Make helm operations atomic

---

.github/workflows/CI.yml

Fixes #3826
As discussed in #3826, I have completely removed `types` in the CI workflow to not have duplicate runs when opening a PR with a label.

#3826 Run pull_request CI workflow regardless of type

---

bridge/client/app/_services/api.service.ts
bridge/client/app/app-header/app-header.component.html
bridge/client/app/app-header/app-header.component.ts

Closes #3668 
Related PR: https://github.com/keptn/keptn.github.io/pull/791

#3668 improved version check

---

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html
bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.scss
bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts

Closes #3645 and #2546
Now shows `displayName` instead of `metricName`

#3645 #2546 improved tooltip and y-axis in evaluation chart

---

installer/manifests/keptn/charts/control-plane/templates/rbac.yaml

An error was introduced in https://github.com/keptn/keptn/pull/3782 whereas the roleRef of a rolebinding was changed.
This leads to a problem when upgrading from an older version, e.g.:
```
Start upgrading Helm Chart keptn in namespace keptn
Error: Could not complete Keptn upgrade: Error when installing/upgrading Helm Chart keptn in namespace keptn: cannot patch "keptn-configuration-service-manage-secrets" with kind RoleBinding: RoleBinding.rbac.authorization.k8s.io "keptn-configuration-service-manage-secrets" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"Role", Name:"keptn-get-secrets"}: cannot change roleRef 
```
Together with @bacherfl we decided that renaming the rolebinding should fix this problem (and this also ensures that the …

#3781 Rename rolebinding to get-secrets

---

cli/cmd/upgrade.go

When calling `keptn upgrade`, I noticed the following output:
```
Start upgrading Helm Chart keptnhelm-service in namespace keptn
Finished upgrading Helm Chart keptnhelm-service in namespace keptn
Start upgrading Helm Chart keptnjmeter-service in namespace keptn
Finished upgrading Helm Chart keptnjmeter-service in namespace keptn
```
When looking at the code, it became clear that we were calling the helm release `"keptn" + serviceName`, which is suboptimal. 
As we recommend our users to just use serviceName (e.g., `helm-service`, `jmeter-service` - see https://keptn.sh/docs/0.8.x/operate/multi_cluster/ ), I have change the code accordingly.
In addition, in `install.go` we already use just the service name: 
https://github.com/keptn/keptn/blob/e48cf151297622ad790cdd98f84df78333978dd9/cli/cm …

#3350 Fix release name of service charts when upgrading

---

.github/workflows/CI.yml

We are currently having a problem with macOS builds not starting on GH actions.
This PR disables MacOS builds for now.

Disable MacOS builds due to an issue of GH action environments

---

helm-service/chart/templates/deployment.yaml
jmeter-service/chart/templates/deployment.yaml

Sets the value of `HTTP_SSL_VERIFY` based on the string representation of the boolean value set with `.Values.remoteControlPlane.api.apiValidateTls`.
E.g. usage:
```console
$ pwd
.../keptn/jmeter-service/chart
$ # Still works with apiValidateTls=true
$ helm template . -f values.yaml \
--set remoteControlPlane.enabled=true \
--set remoteControlPlane.api.hostname=keptn.replaceme.com \
--set remoteControlPlane.api.token=xxx \
--set remoteControlPlane.api.apiValidateTls=true \
| grep -a1 "HTTP_SSL_VERIFY"
value: "xxx"
- name: HTTP_SSL_VERIFY
value: "true"
$ # Now works with apiValidateTls=false
$ helm template . -f values.yaml \
--set remoteControlPlane.enabled=true \
--set remoteControlPlane.api.hostname=keptn.replaceme.com \
--set remoteControlPlane.api.token=xxx \
--set …
```

Set HTTP_SSL_VERIFY based on remoteControlPlane.api.apiValidateTls

---

installer/manifests/keptn/charts/control-plane/templates/core.yaml

Adds new `env` value for `configurationService` and `bridge` which allows additional environment variables to be added to the `Deployment` manifests. This allows `HTTPS_PROXY` and other environment variables to be passed to the services.
E.g.
```console
$ pwd
xxx/keptn/installer/manifests/keptn
$ helm template . -f values.yaml \
--set control-plane.configurationService.env.HTTPS_PROXY=https://proxy:3128 \
--set control-plane.configurationService.env.NO_PROXY=localhost \
--set control-plane.bridge.env.HTTPS_PROXY=https://proxy:3128 \
--set control-plane.bridge.env.NO_PROXY=localhost \
| grep -a3 "HTTPS_PROXY"
value: "true"
- name: KEPTN_INSTALLATION_TYPE
value: "QUALITY_GATES,CONTINUOUS_OPERATIONS"
- name: HTTPS_PROXY
value: "https://proxy:3128"
- name: NO_PROXY
value: "localhost"
--
-- …
```

Add new 'env' Helm chart value to add additional environment variables

---

.github/workflows/integration_tests.yml

This PR uses the updated action of download-artifact, which allows download artifacts based on an event type (in our case: push).
This makes sure that integration tests always fetch the artifact from a push to a branch (full build), rather than a pull-request to a branch (partial build).
Related issue: https://github.com/dawidd6/action-download-artifact/issues/68
Demo Integration Test: https://github.com/keptn/keptn/actions/runs/784891993

Upgrade download-artifact action and specify event type push

---

.github/workflows/CI.yml

We disabled macos builds for the 0.8.2 release as the respective VMs on GitHub were no longer working.
With this PR we are re-enabling macos builds.

Re-enable macos builds

---

.github/workflows/create_release_branch.yml

This PR fixes a problem I discoverd with the create-release-branch action:
Essentially the action was unable to checkout a certain branch (except for master), which should be fixed by setting `fetch-depth: 0` in the checkout step.

Fix create release branch checkout

---

bridge/client/app/project-board/project-board.component.html
bridge/client/app/project-board/project-board.component.scss

Improves #3643 
Use icons instead of labels for the menu.
When hovering over it the DT Overlay shows the name of the page to navigate to.

Use icons for keptn menu instead of text

---

.github/actions/spelling/expect.txt
.github/workflows/integration_tests.yml
test/test_new_artifact.sh
test/utils.sh

Fixes #3843
* made sure that errors are logged using `print_error` rather than just `echo` (`print_error`does an `echo "::error::...."` in the background)
* added verify steps that were missing in several places
* added echo statements that help troubleshooting in the future
* added filename and line number for integration test errors (print_error function)
**Example (from current master branch):**
**Example with release-0.8.2 branch**
https://github.com/keptn/keptn/actions/runs/785731421

#3843 Fixing CD integration test

---

.github/actions/spelling/excludes.txt
.github/actions/spelling/expect.txt
.github/workflows/reviewdog.yml
.reviewdog.yml

Fixes #3019
I also disabled spellchecks for .reviewdog.yml, as I believe this is a file that does not need to be spell checked but will regularly introduce false positive spelling errors.
Example:

#3019 added golang ci lint

---

bridge/server/user/oauth.js
bridge/server/user/session.js

The PR fixes #3880
PR contains the implementation of the contract as explained by the solution proposal - [Proposal](https://github.com/keptn/keptn/issues/3880#issuecomment-829871496)
As a summary,
- Bridge checks for rp_logout support status when reading OAuth service discovery
- Bridge stores logout_hint if present in the token decision response to user session
- When user logout, bridge consumes the rp_logout endpoint to obtain the required redirection location

OIDC RP Initiated logout 

---

bridge/client/app/_models/root.ts

Retrieve correct evaluation event in case that the sequence and the evaluation event have the same name.
Fixes #3927

#3927 Broken UI in quality gates only

---

bridge/client/app/_pipes/keptn-url.pipe.ts
bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.spec.ts

Unit tests are failing randomly, because of "keptnInfo" being null. This PR should fix this.

Fix unit test in Bridge

---

bridge/angular.json
bridge/karma-headless.conf.js
bridge/karma.conf.js
bridge/package-lock.json
bridge/package.json

This PR enhances our karma configuration for Bridge such that it reports failing unit tests by name (generated out of the spec file).
For this I had to add the karma-spec-reporter.
In addition, I enabled `sourceMap` such that we get stacktraces with typescript files, not the generated js files.

Report failing unit tests

---

.github/actions/spelling/advice.md
.github/workflows/spelling.yml

Follow-up to #3951
The comment handler needs to be included, otherwise it doesn't work (oops).
The advice file is tunable, this one is from https://github.com/check-spelling/spell-check-this/blob/main/.github/actions/spelling/advice.md

Check spelling 0.0.18 updates

---

.github/workflows/spelling.yml

It's experiential. And this repository identified a logic issue:
There's code to check for:
* Is the commenter allowed to make a request
* Is the comment addressed to the bot
* Does the comment have an action
Unfortunately, right now, it provides feedback for the first thing, but it should only do that if it knows it's being addressed.
I'll fix it (hopefully tonight after work), but it'll need a new release.

Turn off talk-to-bot feature

---

codecov.yml

This PR disables the codecov PR annotation feature.

disabled annotations from codecov

---

.github/workflows/reviewdog.yml

Fixes #4000
The fix is as simple as setting `GO111MODULE=off ` (see https://github.com/golangci/golangci-lint/issues/1833)

#4000 Fix golangci-lint problem with Go 1.16

---

.github/workflows/integration_tests.yml

Installing the remote execution plane at the beginning of the tests messed up parts of the integration tests where those were not needed. Therefore, the setup of the remote execution plane has been moved to be executed right before this feature is tested
Integration test run: https://github.com/keptn/keptn/runs/2543064370?check_suite_focus=true

#4011 move setup of remote execution plane

---

.github/actions/spelling/expect.txt
bridge/server/app.js

Fixes #3876 by introducing a function that prevents .HTML files from being cached.
Installed it on my Kubernetes cluster and verified it works.

#3876 do not cache index.html

---

bridge/client/app/app-header/app-header.component.html
bridge/client/app/app-header/app-header.component.ts

Fixes #3944
I noticed that routing for this case is not implemented using angular router, but using a switch/case statement in project board:
https://github.com/keptn/keptn/blob/da5859fb8291894c6b019d60781834db4192eb09/bridge/client/app/project-board/project-board.component.html#L64-L71
This leads to call kind of strange effects, like the fact that the route itself is not really changing. Hence I needed to 
a) implement the hacky `getRouterLink` to handle the case of the environment screen (you can't route to `/projects/${PROJECTNAME}/environment` nor `/projects/${PROJECTNAME}/environment`, as it redirects you to `service/environment` or `/service/` respectively,
b) add implementation to the router events (for the case of `NavigationEnd`) to parse the URL and extract a certain part of the …

#3944 Allow switching the project while keeping the context

---

bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.ts

Show the current time instead of ${currentTime} in trigger evaluation command in integrations page.
Fixes #3961 

#3961 Show current time instead of ${currentTime}

---

cli/internal/cespec/genspec.go

The header for the get-action event was missing in the cloudevent spec generation

Added header for get-action event

---

test/test_self_healing.sh

Closes #4100
On minishift, we had a timing issue because we were not waiting long enough for the `remediation.finished` event to be available. This PR makes the self healing test more robust by using the `get_event_with_retry` function to fetch the `remediation.finished` event.
Integration test run: https://github.com/keptn/keptn/actions/runs/853587298

Use retry function for fetching .finished event

---

helm-service/chart/values.schema.json
jmeter-service/chart/values.schema.json

As AWS repositories often start with digits and the current JSON schema does not allow this at the moment, this has been added.

Helm Schema: Repository might contain a digit on the start

---

.github/actions/spelling/expect.txt
cli/cmd/set_config.go
cli/pkg/config/cli_config.go
cli/pkg/config/cli_config_test.go
cli/pkg/credentialmanager/handler.go

fixes #3666 
The user is now able to permanently disable the kube context check via `keptn set config KubeContextCheck false`

CLI: Disable Kubernetes Context Check

---

cli/cmd/configure_bridge.go

Tries to address #3688.
The output of
```shell
keptn configure bridge -o
```
now looks like this
```shell
Your Keptn Bridge is available under: https://yourkeptn.com/bridge
These are your credentials
user: keptn
password: Axxxxxxxx
```

#3688 Show bridge URL when executing keptn configure bridge --output

---

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html
bridge/client/app/_models/event-types.ts
bridge/client/app/_models/root.ts
bridge/client/app/_models/service.ts
bridge/client/app/_models/trace.ts

Determine remediation sequence correctly as faulty, if all actions are faulty and show running remediation or last faulty remediation in environments screen.
All actions failed:
Last action succeeded:
But, Delivery failed, although Rollback sequence is last and "succeeded":

#4143 Determine remediation sequence correctly as faulty

---

bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.html
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts

Fixes #4051
The traces of the sequences were only loaded when a detail was opened.
Now it checks regularly, if there are any running sequences and loads traces for them.
Also the currently selected sequence is also excluded by this mechanism, because it gets already loaded.

Load traces in the sequence screen for not selected sequences

---

shipyard-controller/db/mongodb_uniformrepo_test.go
shipyard-controller/handler/uniformintegrationhandler.go
shipyard-controller/handler/uniformintegrationhandler_test.go
shipyard-controller/models/uniform.go
test/go-tests/go.mod
test/go-tests/go.sum
test/go-tests/uniform_test.go

Related to #4041 - This PR changes the shipyard controller to use the uniform models of `keptn/go-utils` instead of the ones that were temporarily created within the shipyard controller

#4041 use go-utils models for uniform structs

---

bridge/client/_variables.scss
bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.html
bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.scss
bridge/client/app/_components/ktb-stage-badge/ktb-stage-badge.component.html
bridge/client/app/_components/ktb-stage-badge/ktb-stage-badge.component.scss

Closes #3948
Timeline in service screen:
Timeline in sequence screen:

#3948 highlight stages in timelines with color

---

.github/actions/spelling/excludes.txt
CODEOWNERS

@jetzlstorfer @johannes-b @warber I have updated CODEOWNERS as agreed on.
Please note it is possible to reference a team (e.g., @keptn/maintainers )

Updated CODEOWNERS to be in sync with keptn/community

---

bridge/client/app/_components/ktb-deployment-stage-timeline/ktb-deployment-stage-timeline.component.html
bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.html
bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.scss

Fixes #4262 
Timeline in sequence screen:
Timeline in services screen:

#4262 fix color for loading stages in timeline

---

README.md

Kept community link was moved, so I updated it.
Because right now the community link redirecting to this repo https://github.com/keptn/community, where its written:
Please note that we have migrated the community page to keptn.sh/community! ⚠️
So I think it should be better to get direct link to community page.

Update Readme.md outdated community link

---

bridge/client/app/_models/project.ts
bridge/client/app/_models/root.ts

Call hasFailedEvaluation() on root event to prevent endless loop of calling "isFailedEvaluation()"

#4155 Bridge breaks on "sh.keptn.event.evaluation.triggered" root event

---

bridge/client/app/_components/ktb-deployment-stage-timeline/ktb-deployment-stage-timeline.component.html
bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html
bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.html
bridge/client/app/_components/ktb-services-list/ktb-services-list.component.html
bridge/client/app/_models/root.ts
bridge/client/app/_models/trace.spec.ts
bridge/client/app/_models/trace.ts
bridge/client/app/_services/data.service.ts

Fixes #4073 
- Changed implementation of `isFaulty`, `isSuccessFul`, `isWarning`. They now return `boolean` and have a parameter for the stage name.

#4073 fixed sequence and trace status for traces without a stage

---

.github/workflows/CI.yml

**This PR**
* adds the timestamp to built images that come from a PR build
Fixes #4191

Use image version tag with timestamp for PR builds

---

.github/workflows/integration_tests.yml

**This PR**
* only creates GH issues for failing integration tests on `master`
* creates a PR comment on PR builds where the integration tests fail
* in both cases the message is the integration test report
Closes #3772

#3772 Only create issue for failing integration tests on master branch

---

bridge/client/styles.scss

Closes #3801
Service screen:
Environment screen:

#3801 allow text break for info-group content

---

secret-service/docs/docs.go
secret-service/docs/swagger.json
secret-service/docs/swagger.yaml
secret-service/main.go
shipyard-controller/docs/docs.go
shipyard-controller/docs/swagger.json
shipyard-controller/docs/swagger.yaml
shipyard-controller/main.go
statistics-service/docs/docs.go
statistics-service/docs/swagger.json
statistics-service/docs/swagger.yaml
statistics-service/main.go

Fixes #3423 
This is what I did:
Edit statistics-service/main.go, secret-service/main.go, shipyard-controller/main.go and switch the authentication parameter to `key`.
Then I executed `swag init --parseDependency` in all of these three directories, which resulted in the changes shown in the PR.
Last but not least, I manually switched the dependency of `github.com/alecthomas/template` back to `text/template`.
Please note that I am only responsible for the changes regarding authentication. All other changes are not made by me, but they must have been forgotten by the contributors before.

#3423 Switch authentication param to key

---

cli/cmd/upgrade.go

Fixes #3841
Basically I added a for loop that iterates over all helm releases from the history, and choose the one that has status deployed.

#3841 fix keptn ugprade using wrong keptn helm version

---

installer/manifests/keptn/charts/control-plane/Chart.yaml
installer/manifests/keptn/charts/control-plane/values.yaml

Finally fix #2479 by switching to nats 0.8.0.
Apparently something has changed with the service-naming, hence I needed to add `fullnameOverride`.
Integration Tests: https://github.com/keptn/keptn/actions/runs/938419801

#2479 Switch to nats 0.8.0

---

installer/manifests/keptn/charts/control-plane/Chart.yaml
installer/manifests/keptn/charts/control-plane/values.yaml

Reverts keptn/keptn#4316 as we ran into an issue when upgrading from an older Keptn version:
Error: Could not complete Keptn installation: Error when installing/upgrading Helm Chart keptn in namespace keptn: cannot patch "keptn-nats-cluster" with kind StatefulSet: StatefulSet.apps "keptn-nats-cluster" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

Revert "#2479 Switch to nats 0.8.0"

---

.ci_env

**This PR**
* bumps the keptn version for meta keptn to 0.8.3
* other things that were done on the meta keptn instance
* replaced istio with nginx ingress controller 0.47.0 (using helm)
* added cert-manager 1.3.1 plus Let's Encrypt ClusterIssuer for SSL certificate handling (using helm)
Closes #4185 

#4185 bump meta keptn version to 0.8.3

---

.github/workflows/integration_tests.yml

**This PR**
* adjusts the URLs for the helm and jmeter services in keptn on keptn
Fixes #4185 

#4185 fix jmeter and helm service urls

---

distributor/pkg/lib/uniformlog.go

addition for #4030: With this PR, the distributor also considers .finished events with `result=fail`, in addition to `status=errored`

Also forward messages of .finished events with result=fail

---

.github/actions/spelling/excludes.txt
.github/actions/spelling/expect.txt
.github/workflows/integration_tests.yml
test/assets/creds.sav
test/assets/keptn-on-keptn/endpoints-helm-service.yaml
test/assets/keptn-on-keptn/endpoints-jmeter-service.yaml
test/assets/keptn-on-keptn/endpoints-keptn.yaml
test/assets/keptn-on-keptn/ingress.yaml

**This PR**
* adds ingress k8s manifests to all keptn-on-keptn stages
* adds SSL certificates automatically through LE and cert-manager
* makes use of the `endpoints.yaml` file instead of sending the deployment URIs with the cloud events to trigger deliveries
* removes unused `creds.sav` file
Fixes #4180 

#4180 keptn-on-keptn stages with ingress and SSL, use endpoints.yaml files

---

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts

Closes #3943 
- Tick interval is now determined by component width.
- Last and first label are always displayed

#3943 show every nth label starting from the end

---

.github/workflows/integration_tests.yml

**This PR**
* introduces new pipeline steps that check if the delivery of {keptn,jmeter-service,helm-service} went through on the keptn-on-keptn instance.
* all steps have a timeout of 5 minutes and fail if the delivery didn't go through in that timeframe
Fixes #4186

#4186 Check delivery and fail tests if delivery failed

---

helm-service/chart/values.schema.json
jmeter-service/chart/values.schema.json

Fixes #4422
This PR modifies helm-charts for helm-service and jmeter-service such that any host/port combination can be used for the repository, e.g.:
* localhost:5000/keptn/helm-service was not valid before, but is valid now
* docker.io/keptn/helm-service is still valid

#4422 Allow host/port for jmeter-service/helm-service repository in helm charts

---

.github/workflows/CI.yml

**This PR**
* replaces all hardcoded occurrences of a go version with a global env variable that is set at the beginning of the CI workflow

#4331 Unify go versions in CI workflow

---

installer/manifests/keptn/charts/control-plane/templates/core.yaml
installer/manifests/keptn/charts/control-plane/values.yaml

Fixes #4476
needs backport to 0.8.4-hotfix1

#4476 Add Bridge Look And Feel URL to Installer Manifest

---

.github/actions/spelling/expect.txt
.github/workflows/integration_tests.yml
installer/airgapped/install_keptn.sh
installer/airgapped/pull_and_retag_images.sh
installer/manifests/keptn/charts/continuous-delivery/values.yaml
installer/manifests/keptn/charts/control-plane/templates/core.yaml
test/test_airgapped_images.sh
test/utils/download_and_install_k3d.sh

Fixes #4183
Note: it's not possible to have a cluster that's completely locked down, but it is possible to use a local registry with K3d (hence I also used K3d for the integration test).
The integration test now checks that all images that are pulled are coming from the local registry from K3d, rather than anywhere else (with the exception of k3s/rancher based images, as they are needed internally by K3d).
Example:

#4183 Airgapped installation

---

gh-actions-scripts/build_helm_charts.sh

Fixes #4403
```
$ helm ls -n keptn
NAME          	NAMESPACE	REVISION	UPDATED                                 	STATUS  	CHART                           	APP VERSION                   
helm-service  	keptn    	1       	2021-06-23 16:04:47.30580055 +0200 CEST 	deployed	helm-service-0.8.5-dev-PR-4490  	0.8.5-dev-PR-4490.202106231228
jmeter-service	keptn    	1       	2021-06-23 16:04:57.480667732 +0200 CEST	deployed	jmeter-service-0.8.5-dev-PR-4490	0.8.5-dev-PR-4490.202106231228
keptn         	keptn    	4       	2021-06-23 16:05:41.716710766 +0200 CEST	deployed	keptn-0.8.5-dev-PR-4490         	0.8.5-dev-PR-4490.202106231228
```

#4403 Use image versions in helm charts

---

.github/workflows/CI.yml

Fixes #3987
**Note**: Apparently we need to enable CGO when cross compiling from amd64 to a**r**m64. I've enabled it for both MacOS builds.
This might change the resulting CLI binary size.

#3987 Enable Apple Silicon Build

---

.github/workflows/integration_tests.yml

**This PR**
* removes some debug steps from the integration test pipeline
**Notes**
Removing the debug steps should be ok since they were there for minishift and some were expected to fail. This resulted in error annotations on the integration test builds that didn't contain any useful information

#4385 Remove debug build steps

---

bridge/client/app/dashboard/dashboard.component.ts
bridge/package.json

Protractor waits for async tasks to complete - in case of rxjs timer they do not finish so the tests time out
To tackle this it is necessary to run this kind of tasks in ngZone.runOutsideAngular in order to not block Angular.
https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular

Fix e2e test timeout

---

.github/workflows/auto-update-keptn-spec.yml

**This PR**
* adds a new workflow to update the spec submodule to the latest release
* the workflow is triggered by a `repository_dispatch` event coming from the keptn/spec repo
* creates a PR with the updated submodule
Fixes #4366

#4366 Auto update spec when a new version is released

---

installer/manifests/keptn/charts/control-plane/templates/continuous-operations.yaml
remediation-service/deploy/service.yaml

Cleanup: Just removing some outdated environment variables from the `remediation-service` deployment resource.

Remediation-Service: removed outdated environment variables
