keptn/keptn

.gitignore, core/auth/buildAndDeploy.sh, core/auth/config/authenticator-build.yaml, core/auth/config/authenticator.yaml, core/auth/deploy.sh, core/control/buildAnddeploy.sh, core/control/config/control-build.yaml, core/control/config/control.yaml, core/eventbroker-ext/buildAndDeploy.sh, core/eventbroker-ext/config/event-broker-ext-build.yaml, core/eventbroker-ext/config/event-broker-ext.yaml, core/eventbroker-ext/deploy.sh, core/eventbroker/buildAndDeploy.sh, core/eventbroker/config/event-broker-build.yaml, core/eventbroker/config/event-broker.yaml, core/eventbroker/deploy.sh, install/scripts/deployServices.sh, install/scripts/setupKnative.sh
pull images for services from docker hub
=> Prerelease

core/control/src/config/ConfigController.spec.ts, core/control/src/lib/log/Logger.ts, core/control/src/svc/CredentialsService.ts, core/control/src/svc/MessageService.spec.ts, core/control/src/svc/MessageService.ts, core/control/src/svc/WebSocketService.ts, core/eventbroker/src/docker/DockerService.ts, core/eventbroker/src/lib/log/Logger.ts, core/eventbroker/src/svc/MessageService.ts, travis-scripts/setup_functions.sh
=> Error handling and improved logging

install/scripts/upgradeKeptn.sh, install/scripts/utils.sh
adding upgrade script to update a cluster with keptn 0.2.0 installed to keptn 0.2.1
=> adding upgrade script

install/scripts/upgradeKeptn.sh
fix outdated image version for core components and fixed that temp files have not been removed previously when running the scripts
=> adapting image versions & remove temp files

core/control/package-lock.json, core/eventbroker-ext/package-lock.json, core/eventbroker/package-lock.json
Travis tests failed because of **axios** version. Hence, update axios version
=> Update axios version

install/scripts/deployDynatrace.sh, releasenotes/releasenotes_V0.2.2.md
As last step in the deployDynatrace.sh the dynatrace-service gets deployed.
=> Deploy the dynatrace-service when executing deployDynatrace.sh

install/scripts/uninstallKeptn.sh, travis-scripts/setup_functions.sh
- improve travis script to abort if keptn install fails (otherwise travis will continue and fail a couple of minutes later)
- fix incorrect version of knative uninstall
=> Abort if keptn install fails

install/scripts/applyAutoTaggingRules.sh
- check if autotagging rules in dynatrace are already existing. if so, delete them and create them again, otherwise the script receives an error
=> check if rules already existing

core/control/src/svc/MessageService.ts, core/eventbroker/src/svc/MessageService.ts, releasenotes/releasenotes_V0.2.2.md
- Correct typos in control and eventbroker
- Update release notes
=> #332 Correct typos

cli/cmd/auth.go, cli/cmd/configure.go, cli/cmd/create_project.go, cli/cmd/install.go, cli/cmd/onboard_service.go, cli/cmd/root.go, cli/utils/githubSettingChecker.go, cli/utils/logPrinter.go, cli/utils/websockethelper/websocketHelper.go, cli/utils/websockethelper/websocketHelper_test.go, releasenotes/releasenotes_V0.2.2.md
- Use flags verbose and quiet in install command
- Refactoring of log levels and install command
- Additionally, ask user whether provided input is correct
=> #272 Use log levels in install, additional query for user input, refactoring

install/scripts/applyAutoTaggingRules.sh
- included flag `-f` in `curl` for error handling
=> #352 include flag for error handling

travis-scripts/cronjob_main.sh
=> #327 Update travis scripts

releasenotes/releasenotes_V0.2.2.md
Add collection of features and fixed issues for 0.2.2
=> Update release notes

cli/cmd/install.go, releasenotes/releasenotes_V0.2.2.md
When creating the release, a wrong path has been identified.
=> Merge hotfix into develop

.travis.yml
Update kubectl command; needed for nightly build
=> #327 Add kubectl update

travis-scripts/cronjob_main.sh, travis-scripts/setup_functions.sh
Move nightly functionality into cronjob file
=> #327 Travis nighlty build

test/testOnboarding.sh
Correct paths due to split of repos
=> #327 Fix nightly build

test/testOnboarding.sh
=>  #327 Nightly build

README.md
Update of README to reflect the current status of this repository. Additionally, a listing of all artifacts for 0.2.2 is provided
=> Update of README to reflect the current status

travis-scripts/cronjob_main.sh
In keptn/installer the name of the utils script changed so that travis build failed.
=> Name of utils script file changed in installer

cli/cmd/install.go
Check whether the cluster IP CIDR or the service IP CIDR is empty.
=> #490 Add checks for IP CIDRs

cli/cmd/install.go
feature 567 skip tls verify 
Updated flags to skip tls verification feature.
=> feature 567 skip tls verify

shipyard-service/Gopkg.lock, shipyard-service/main.go
Note: Tests have not been refactored.
=> #727 Refactor: use go-utils, use entire shipyard

cli/Gopkg.lock, cli/cmd/configure_monitoring.go, cli/cmd/configure_monitoring_test.go
For now, these files will be added beforehand with the add-resource command
=> #850 exclude SRE files from configure monitoring command

installer/manifests/istio/helm/istio/templates/install-custom-resources.sh.tpl
Just capitalized the first word
=> Fixed small typo

installer/scripts/common/utils.sh
This fixes issue #932 only partially.
There are some other references to the uninstall.sh script that I can not fix right now, as they are happening within the cronjobs where we do not have a working keptn CLI installation.
=> #932 proper uninstall message

.travis.yml
* git diff wasn't working properly on pushes on the `develop` branch (it should now)
* added nightly image builds for all images
=> #946: Fix issue with git diff and provide nightly builds

api/handlers/event.go, api/handlers/event_test.go
- The ChannelInfo for the websocket communication was not added within the data object of the CloudEvent
=> #893 Correct adding channel info

.travis.yml, test/testOnboarding.sh, test/test_install_gke.sh, test/test_new_artifact.sh, test/test_onboard_service.sh, test/utils.sh, test/utils/gke_create_cluster.sh, test/utils/gke_delete_cluster.sh
* Fixes nightly cronjob
* Restructures test for nightly cron
* Move nightly cronjob from osx to linux for better performance and availability of the cronjob
* Added more log output to the cronjob
Waiting on #990 to be merged.
=> #946 Fix nightly cronjob, restructure tests

api/handlers/event.go, api/swagger.yaml, cli/cmd/add_resource.go, cli/cmd/create_project.go, cli/cmd/delete_project.go, cli/cmd/get_event_evaluationDone.go, cli/cmd/install.go, cli/cmd/onboard_service.go, cli/cmd/uninstall.go
This PR has three topics:
- refactors logging in API
- improves Keptn CLI UX
- bug fix in error message handling for `get event` command
=> Improved logging in API and bugfix in error message handling

README.md, helm-service/controller/configuration_changer.go, helm-service/controller/workflow_engine_replacer.go
- Send image and tag in deployment-finished event
- undo downscaling when canary version is deployed again
=> #1045 send image and tag in deployment-finished event

wait-service/Dockerfile, wait-service/go.mod, wait-service/go.sum, wait-service/main.go, wait-service/skaffold.yaml
As asked in #1078 by @johannes-b 
I also added a proper Dockerfile and skaffold.yaml for debugging purpose.
=> #1078 Wait-Service needs to use tests-finished event from keptn/go-utils

.idea/runConfigurations/keptn_configuration_service__Kube_ContDeploy_.xml, configuration-service/.gitignore, configuration-service/Dockerfile, configuration-service/common/git.go, configuration-service/deploy/service.yaml, configuration-service/skaffold.yaml
- Directly clone into the desired project directory
- Remove the "mv" command
- Added debug stuff (skaffold.yaml and Dockerfile updates)
- Decrease requested memory for configuration service (it needs 20 megabytes usually)
- Increase memory limit for configuration service (debugging it requires more memory)
=> #1095 Fix issue with git cloning and moving directory

bridge/client/components/TraceList/index.vue, bridge/server/config/index.js, lighthouse-service/event_handler/evaluate_sli_handler.go, lighthouse-service/event_handler/evaluate_sli_handler_test.go, lighthouse-service/go.mod, lighthouse-service/go.sum, mongodb-datastore/handlers/events.go
Changes:
- Add SLO file content in Evaluation-Done events to make the result more comprehensible
- Adapt to new Evaluation-Done event format in bridge
=> #1058 Adapted EvaluationDetails and display information in bridge

lighthouse-service/examples/slo.yaml
As spec is released at version 0.1.0 we should change the example slo files accordingly
=> #1059 change slo file spec version to 0.1.0

lighthouse-service/event_handler/common.go, lighthouse-service/event_handler/evaluate_sli_handler.go, lighthouse-service/event_handler/evaluate_sli_handler_test.go, lighthouse-service/event_handler/handler.go, lighthouse-service/event_handler/start_evaluation_handler.go
* Added debug logs to show received events, processing steps, and sent events.
=> Improve debug logging for lighthouse service

.gitmodules, specification/README.md
I added the keptn spec as a git submodule.
=> Specification

README.md
Added the "number of downloads" badge
=> Update badges for README

bridge/Dockerfile, bridge/client/components/RootList/index.vue, bridge/client/components/TraceList/index.vue, bridge/server/lib/services/DatastoreService.js, bridge/skaffold.yaml, installer/manifests/keptn/continuous-operations.yaml, remediation-service/actions/featuretoggler.go, remediation-service/deploy/service.yaml, remediation-service/main.go
Adding the ability to toggle feature flags in the Unleash feature toggle framework as a remediation action.
Please do not merge yet.
=> #1104 Adding feature toggling as remediation actions

releasenotes/releasenotes_V0.6.0.md
Includes feedback from @AloisReitbauer
=> Synced release notes with tag

installer/scripts/common/setupKeptn.sh, installer/scripts/openshift/setupKeptn.sh
In PR https://github.com/keptn/keptn/pull/1361 the distributors have been merged into a single distributor.
This change also needs to be reflected in the installer.
=> #1357 Remove check for distributors that have been removed

.travis.yml, cli/buildCLI.sh, cli/cmd/install.go, cli/go.mod, cli/go.sum, cli/main.go, cli/utils/kubeUtils.go, cli/utils/kubeUtils_test.go, travis-scripts/build_cli.sh
=> Check compatibility based on Kubernetes cluster version before installing

bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.ts
Fixes the error in project deeplink and I also added an empty state view, if the project is not existing at all:
=> #1377 Fix error in project deeplink

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
Docker image for testing:
`keptn/bridge2:feature.1379.20200221.1051`
=> #1379 Show warning state in evaluation result properly

.travis.yml, README.md, cli/cmd/get_event.go, eventbroker/main.go, helm-service/controller/workflow_engine_replacer.go, lighthouse-service/event_handler/start_evaluation_handler.go
- added codecov.io for code coverage
- added go report card for code quality
- fixed codestyle errors detected by `go fmt`
=> Added code coverage to travis ci; added go report card badge

bridge/.dockerignore, bridge/Dockerfile, bridge/package-lock.json, bridge/server/app.js
- Use multi-stage docker setup for bridge to improve size of bridge image (used to be 650 MB, is now down to roughly 150 MB)
- Improve handling of static files
depends on https://github.com/keptn/keptn/pull/1435 (please merge #1435 first!)
=> Improve bridge docker build with a multi-stage image

travis-scripts/build_develop.sh, travis-scripts/build_feature.sh, travis-scripts/build_release.sh
Travis should terminate if building a docker image fails
=> Added travis terminate to build scripts

ADOPTERS.md
Adding template for Keptn adopters
=> add adopters file

ADOPTERS.md
Adding ERT as Adopter for keptn.
=> Adding ERT as Adopter

bridge/package-lock.json, bridge/package.json
This update seems to fix #1442
=> #1442 Update barista-components from 5.1.1 to 5.3.1

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_components/ktb-event-item/ktb-event-item.component.ts, bridge/client/app/_models/trace.ts
Showing now "Problem resolved" for event "sh.keptn.events.problem" if the State is "RESOLVED"
=> #1448 Problem workflow with Dynatrace

bridge/client/app/_services/data.service.ts
=> Keep order of projects/stages while fetching detail data

.travis.yml, test/test_install_gke.sh, test/test_install_kubernetes_full.sh, test/test_install_kubernetes_quality_gates.sh, test/test_install_minishift_quality_gates.sh, test/utils/download_and_install_keptn_cli.sh, test/utils/download_and_install_oc_cli.sh, test/utils/minishift_create_cluster.sh
This PR adds automated tests for minishift with quality gates standalone.
An initial try with this works nicely with travis-ci, see https://travis-ci.org/github/keptn/keptn/jobs/661145286
=> Added automated tests for minishift with quality gates standalone

installer/scripts/common/utils.sh, upgrade-060-061/scripts/utils.sh
=> #1536 increase wait timeout for ip of ingress gateway

bridge/client/app/_components/ktb-events-list/ktb-events-list.component.html, bridge/client/app/_components/ktb-events-list/ktb-events-list.component.scss, bridge/client/app/_components/ktb-events-list/ktb-events-list.component.ts, bridge/client/app/_components/ktb-expandable-tile/ktb-expandable-tile.component.html, bridge/client/app/_components/ktb-expandable-tile/ktb-expandable-tile.component.scss, bridge/client/app/_components/ktb-expandable-tile/ktb-expandable-tile.component.ts, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.ts, bridge/client/app/_services/data.service.ts, bridge/client/app/app.routing.ts, bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.ts, bridge/client/styles.scss
=> #1316 Provide deep links to project/service/shkeptncontext

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_components/ktb-event-item/ktb-event-item.component.scss, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.scss, bridge/client/app/_models/trace.ts, bridge/client/styles.scss, platform-support/openshift-route-service/go.sum
https://github.com/keptn/keptn/issues/1352#issuecomment-595781977
=> #1352 Show icons for certain events for better accessibility

bridge/client/app/_components/ktb-events-list/ktb-events-list.component.ts, bridge/client/app/_models/root.ts, bridge/client/app/_models/trace.ts, bridge/client/app/_services/data.service.ts, bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.ts
=> Read project and service from traces if not available on root event

CONTRIBUTING.md, docs/fork.md
Our current docs don't provide any information on how to work on a fork and keep the fork up2date.
I also added reference links to GitHub help pages for this.
=> Added more infos about creating forks

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
=> Show 'failed' result same as 'fail' result (error) in Heatmap

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_models/trace.ts, bridge/client/app/project-board/project-board.component.html
=> Show short image name (name:tag) in root event

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.scss, bridge/client/app/_models/root.ts, bridge/client/app/_models/trace.ts
=> Indicate warning state on stage tag in root event

cli/cmd/generate_docs_test.go
Another failing unit test (based on PR #1644)
=> Fix unit tests for generate docs

shipyard-service/main.go
* #1705 Add missing new line in deleting message
* #1705 Fix typo messages (exuecute -> execute)
=> Add missing new line and typo fix

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
=> Fix bug when clicking in heatmap

upgrader/upgrade-061-062/Dockerfile, upgrader/upgrade-061-062/scripts/upgradeKeptn.sh, upgrader/upgrade-061-062/scripts/utils.sh, upgrader/upgrade-061-062/upgrade-job.yaml
The upgrader job is responsible for upgrading Keptn from version 0.6.1 to 0.6.2.
In addition to updating the service images, it configures the api ingress gateway as described in #1660
=> #1660 upgrade Job for 0.6.1 -> 0.6.2

configuration-service/handlers/project.go, configuration-service/handlers/project_resource.go, configuration-service/handlers/service.go, configuration-service/handlers/service_default_resource.go, configuration-service/handlers/service_resource.go, configuration-service/handlers/stage.go, configuration-service/handlers/stage_resource.go
Provide additional log messages for errors in configuration-service.
=> #1637 Provide additional log messages for errors

bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts
=> Fix error due to long list of SLIs

bridge/client/app/project-board/project-board.component.html
=> Remove duplicate tag info in Bridge

.travis.yml, test/test_install_gke.sh
This is a follow-up PR for https://github.com/keptn/keptn/pull/1722, which fixes the integration tests.
=> #1712 Correct flag name ingress-install-option

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
=> disable turboThreshold in Heatmap

bridge/client/app/_models/trace.ts
=> show "Problem closed" for event sh.keptn.events.problem with State "CLOSED"

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.scss, bridge/client/app/project-board/project-board.component.ts, bridge/client/styles.scss
As display in belows image, the bridge has now a menu with "Environment" and "Services" tabs.
=> Menu in bridge for "Environment" and "Services"

ADOPTERS.md
Added amasol AG to adopters list.
=> Updated ADOPTERS.md

gatekeeper-service/pkg/handler/approval_finished_event_handler.go, gatekeeper-service/pkg/handler/approval_triggered_event_handler.go
This PR adds log messages for errors that can occur when creating or closing an approval in the materialized view.
=> #1737 Add logging for errors

.travis.yml, test/utils/microk8s_create_cluster.sh
With this PR I'm adding tests for specific versions of Microk8s for the quality-gates use-case.
=> #1777 Increased test-matrix for Microk8s

api/handlers/configure.go
Closes #1805 
This PR creates an additional check to verify that nginx is used as an ingress for Keptn when exposing the bridge.
=> #1805 check if keptn-ingress is available in ingress-nginx

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_utils/date.utils.ts
Calculate time difference correctly and show dates in format YYYY-MM-DD HH:mm
=> Calculate time difference correctly

cli/cmd/send_event_approvalFinished.go, cli/cmd/send_event_approvalFinished_test.go, cli/go.mod, cli/go.sum
Closes #1835 
This PR implements the behavior described in #1835
=> #1835 delivery assistant for CLI

cli/cmd/create_project.go, cli/cmd/create_service.go, cli/cmd/delete_project.go, cli/cmd/onboard_service.go, cli/go.mod, cli/go.sum, helm-service/controller/onboarder_test.go, helm-service/go.mod, helm-service/go.sum, shipyard-service/go.mod, shipyard-service/go.sum, shipyard-service/main.go
Use newly introduced apiUtils (https://github.com/keptn/go-utils/pull/171) for creating, deleting projects and for creating services.
=> # 1861 Correct API endpoint in create project

.travis.yml, test/utils/gke_delete_cluster.sh
In addition for #1872 this should slightly improve the handling of our tests in travis-ci
- Fixed some typos
- Added `set -e` to fail certain steps "faster"
- Added `set +e` at the end of those steps
=> #1872 Improve travis-ci yaml for failing quicker

bridge/client/app/_components/ktb-notification-bar/ktb-notification-bar.component.html, bridge/client/app/_components/ktb-notification-bar/ktb-notification-bar.component.scss, bridge/client/app/_components/ktb-notification-bar/ktb-notification-bar.component.spec.ts, bridge/client/app/_components/ktb-notification-bar/ktb-notification-bar.component.ts, bridge/client/app/_models/notification.spec.ts, bridge/client/app/_models/notification.ts, bridge/client/app/_services/notifications.service.spec.ts, bridge/client/app/_services/notifications.service.ts, bridge/client/app/app-header/app-header.component.html, bridge/client/app/app-header/app-header.component.scss, bridge/client/app/app.component.html, bridge/client/app/app.component.scss, bridge/client/app/app.component.ts, bridge/client/app/app.module.ts, bridge/client/styles.scss
I provided the ability to provide message to user as "info", "success", "warning" or "error".
=> Provide possibility to notify user in bridge

eventbroker/main.go
Closes #1901 
With this PR, the eventbroker maintains a mapping between event types and NATS connections. For each incoming event, the existing NATS connection for that event's topic is reused instead of creating a new connection for each event.
=> #1901 maintain constant amount of nats connections

cli/cmd/create_project.go
Resolves https://github.com/keptn/keptn/issues/1840
=> Show warning when creating a project without Git upstream

installer/manifests/logging/mongodb/pvc.yaml, mongodb-datastore/deploy/manifests-db/pvc.yaml
#1900 Updated volume claim value to 5Gi
=> #1900 issue changed mangodb pvc from 1Gi to 5Gi

cli/cmd/uninstall.go
Resolves https://github.com/keptn/keptn/issues/1781
=> Skip openshift and kube namespaces

.travis.yml, test/assets/delivery_assistant_shipyard.yaml, test/assets/evaluation_done_event_template.json, test/test_delivery_assistant.sh, test/test_self_healing.sh, test/utils.sh
Closes #1750
This PR adds integration tests for the delivery assistant use case
=> #1750 Integration tests for delivery assistant

bridge/README.md
This updates the local development guidelines for Keptn Bridge
=> Update Local development for Keptn Bridge

.travis.yml, test/assets/self_healing_scaling_remediation.yaml, test/assets/self_healing_slo.yaml, test/assets/shipyard_self_healing_scale.yaml, test/test_self_healing_scaling.sh, test/utils.sh
Closes #1847 
This PR adds an integration test for the self healing with prometheus use case.
=> #1847 Integration test: Self healing w/ Prometheus

test/assets/self_healing_scaling_remediation.yaml
Set the spec version of the remediation used in the self healing integration test to the correct version
=> updated remediation spec version

bridge/client/_variables.scss, bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_components/ktb-event-item/ktb-event-item.component.scss, bridge/client/app/_components/ktb-event-item/ktb-event-item.component.ts, bridge/client/app/_models/json-serializable.ts, bridge/client/app/_services/clipboard.service.spec.ts, bridge/client/app/_services/clipboard.service.ts, bridge/client/app/app.module.ts
Issue #1794 
* Add a clipboard-utils service with a simple test
* Add a "copy"-button to the event payload dialog component (shown in the screenshot below)
* Format/cleanup code according to tslint-rules
* Remove unused method `getDuration`
* Remove redundant `OnInit`-implementation
=> #1794: Provide a “COPY JSON" button on the Bridge UI

CODEOWNERS
Added @dominikmessner as a codeowner for bridge
=> Added dominikmessner as a codeowner/reviewer for bridge

CODEOWNERS
Added @samuelfahrngruber as a reviewer/codeowner for bridge
=> Added samuelfahrngruber as a reviewer for bridge

cli/cmd/configure_domain.go, cli/cmd/configure_domain_test.go
Fix broken link on #2007 
Signed-off-by: Imre Nagi <imre.nagi2812@gmail.com>
=> Update link on command example

cli/cmd/root.go
Resolve https://github.com/keptn/keptn/issues/1864
=> Prevent error output of versioncheck by default

cli/cmd/generate_support_archive.go
Closes #1941 
This PR adds ingress configuration information to the generated support-archive
=> #1941 check ingress configuration

.travis.yml, test/assets/shipyard_self_healing_scale.yaml, test/test_onboard_service.sh, test/test_self_healing.sh, test/test_self_healing_scaling.sh
The integration tests for the full installation on GKE exceeded the timeout of 50m, so I've split this job into multiple parts
=> Split up integration tests to avoid timeout on travis

bridge/angular.json, bridge/client/app/_components/ktb-events-list/ktb-events-list.component.scss, bridge/client/app/_components/ktb-events-list/ktb-events-list.component.ts, bridge/client/app/_components/ktb-expandable-tile/ktb-expandable-tile.component.html, bridge/client/app/_components/ktb-expandable-tile/ktb-expandable-tile.component.scss, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.scss, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.ts, bridge/client/app/app-header/app-header.component.html, bridge/client/app/app-header/app-header.component.scss, bridge/client/app/app.module.ts, bridge/client/app/project-board/project-board.component.scss, bridge/client/styles.scss
- The background color for the menu and dialog changed to gray.
- Removed the shadow from the header
- Failed root events are more visible (red border left and stage is marked red with background instead of border)
- Fixed the path to Fonts (uses now OpenSans correctly)
=> Update UI look and feel

installer/manifests/keptn/charts/continuous-delivery/charts/openshift/templates/route-service-openshift.yaml, platform-support/openshift-route-service/deploy/service.yaml, platform-support/openshift-route-service/main.go
The namespace of the ServiceAccount `keptn-openshift-route-service` was missing its namespace.
=> Correct ClusterRoleBinding for Openshift

upgrader/upgrade-062-070/scripts/upgradeKeptn.sh, upgrader/upgrade-062-070/upgrade-job-helm3.yaml, upgrader/upgrade-062-070/upgrade-job.yaml
Updated the configuration of the upgrader manifests
=> updated upgrader configuration

bridge/client/app/project-board/project-board.component.html
I also changed "Project doesn't existing" into "Project doesn't exist", which sounds better to me.
=> fix image path for keptn_logo in "Project doesn't exist" use-case

remediation-service/handler/handler.go
=> added end property to start-evaluation event

bridge/client/app/app-header/app-header.component.ts, cli/cmd/generate_docs.go, cli/cmd/version.go
=> #1930 Print version check info

installer/manifests/keptn/Chart.yaml, installer/manifests/keptn/charts/continuous-delivery/Chart.yaml, installer/manifests/keptn/charts/continuous-delivery/charts/openshift/Chart.yaml, installer/manifests/keptn/charts/control-plane/Chart.yaml, installer/manifests/keptn/charts/control-plane/charts/mongodb/Chart.yaml, travis-scripts/build_latest_installer.sh
Fixed the installer build
Set the `appVersion` to `latest` in the helm charts
=> fix installer build

cli/cmd/install.go
=> #1944 Immediately return error if kube server version check error

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_models/trace.ts
=> Fix error in heatmap when labels on cloud native event

cli/cmd/update_project.go, configuration-service/common/git.go, configuration-service/handlers/project.go, configuration-service/handlers/service_default_resource.go
=> #2125 Push origins after updating project

helm-service/controller/configuration_changer.go, helm-service/controller/workflow_engine_replacer.go
This fixes #2128 
Here is the proof that it works
=> forwarding incoming labels to send deployment event

api/handlers/event.go
Resolving #1655
Signed-off-by: Imre Nagi <imre.nagi2812@gmail.com>
=> Return 404 when no event is found in /event endpoint

bridge/client/app/_services/api.service.ts, configuration-service/common/git.go
=> Fix setting upstream and pushing, pass labels in approval.finished

bridge/client/app/_services/api.service.ts, configuration-service/common/git.go
=> Fix passing labels in bridge, fix setting upstream

shipyard-service/main.go
=> Update info message

test/test_onboard_service.sh, test/test_self_healing.sh
- Removed hard coded  project names from utility script
- Suppress kubectl error message from builds
=> #2149 Suppressed kubectl error message and made project name dynamic

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_models/trace.ts, bridge/client/app/_services/api.service.ts
=> #2138 Show labels in event payload correctly

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
=> Set height for chart and maxHeight for legend

cli/cmd/get_event.go, cli/cmd/get_event_test.go, cli/go.mod, cli/go.sum
- Get event by specific event type
- Specify the amount of returned events using the `page-size` and `num-of-pages` flags
- Query events using different parameters e.g. project, stage
=> #2171 Get event command implementation to get any event type 

cli/cmd/generate_support_archive.go, cli/cmd/generate_support_archive_test.go, cli/cmd/install.go, cli/cmd/installKubernetes.go, cli/cmd/installOpenShift.go, cli/cmd/install_test.go, cli/cmd/uninstall.go, cli/cmd/version.go
=> #2186 Introduce build tag nokubectl

bridge/client/index.html
=> Dynamically set base-href

shipyard-controller/deploy/service.yaml
Removed a reference to an unneeded volume
=> fixed config for shipyard controller

test/utils.sh
- Daemonset bash utility for waiting until a daemonset is ready for use.
=> Added daemonset bash utility

bridge/client/app/_models/project.ts, bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.ts, bridge/client/index.html
=> Don't filter the faulty event if deploymentstrategy is "direct"

bridge/client/app/_components/ktb-approval-item/ktb-approval-item.component.html, bridge/client/app/_components/ktb-approval-item/ktb-approval-item.component.scss, bridge/client/app/_components/ktb-approval-item/ktb-approval-item.component.spec.ts, bridge/client/app/_components/ktb-approval-item/ktb-approval-item.component.ts, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_components/ktb-event-item/ktb-event-item.component.ts, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.scss, bridge/client/app/_components/ktb-selectable-tile/ktb-selectable-tile.component.scss, bridge/client/app/_components/ktb-selectable-tile/ktb-selectable-tile.component.ts, bridge/client/app/_models/project.ts, bridge/client/app/_models/root.ts, bridge/client/app/_models/trace.ts, bridge/client/app/app.module.ts, bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.ts, bridge/client/index.html, bridge/client/styles.scss
Resolves #2142 and resolves #2135
=> Provider better indication and workflow for artifacts waiting for approval

api/handlers/configure.go, api/handlers/configure_test.go, cli/cmd/auth.go, cli/cmd/generate_support_archive.go, cli/cmd/install.go, cli/cmd/uninstall.go, configuration-service/common/git.go, configuration-service/deploy/service.yaml, installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml, lighthouse-service/deploy/service.yaml, lighthouse-service/event_handler/configure_monitoring_handler.go, lighthouse-service/event_handler/configure_monitoring_handler_test.go, lighthouse-service/event_handler/start_evaluation_handler.go
- Allow the user to specify a namespace for installing Keptn
- Replaced hard coded namespace variables with dynamic environment variables
=> #2195 Define namespace for Keptn installation and other operations

api/deploy/service.yaml, api/handlers/metadata.go, cli/cmd/install.go, installer/manifests/keptn/charts/control-plane/templates/core.yaml
- Path prefix for Keptn installation in custom namespaces
- Changed helm environment variable names to match Golang constants
=> Keptn installation path prefix

installer/manifests/keptn/charts/control-plane/charts/mongodb/templates/pvc.yaml, installer/manifests/keptn/charts/control-plane/charts/mongodb/values.yaml, installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/values.yaml
=> #2190 Allow to set storage and storageClass of PVC in values.yaml

.travis.yml, test/test_self_healing.sh
- GKE 1.14 is not available anymore - set version to 1.15
- Set namespace when deploying unleash-service
=> #2149 Fix problems in TravisCI for building/testing

configuration-service/handlers/service.go, distributor/cmd/main.go, helm-service/controller/helm/helmv3_executor.go, installer/manifests/keptn/charts/control-plane/templates/core.yaml, shipyard-service/deploy/service.yaml, shipyard-service/main.go
Fixes #2199 
- Adds topic `sh.keptn.internal.event.service.delete` to distributor of shipyard-service.
- Corrects and improves logs
=> Fixes delete service

cli/cmd/get_projects.go, cli/cmd/get_services.go, cli/cmd/get_stages.go
This PR adds messages if a specified project or service does not exist.
=> Add messages if project or service does not exist

bridge/client/app/_components/ktb-approval-item/ktb-approval-item.component.scss, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.scss, bridge/client/app/_models/project.ts, bridge/client/app/_models/root.ts, bridge/client/app/_models/trace.ts, bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.scss, bridge/client/app/project-board/project-board.component.ts
=> #2086 Show failed quality gates in environment screen

bridge/client/app/_services/api.service.ts, bridge/client/app/_services/data.service.ts, bridge/client/app/_services/mock-data.service.ts, bridge/client/app/app-header/app-header.component.html, bridge/client/app/app-header/app-header.component.scss, bridge/client/app/app-header/app-header.component.ts, bridge/client/app/app.module.ts, bridge/server/api/index.js
Fixes #2197 
Provide API token and keptn auth command in user menu and allow to copy it easily to clipboard
=> #2197 Provide API token and keptn auth command in user menu

bridge/client/styles.scss
=> #2174 Make $fonts-dir relative

.travis.yml, test/test_delete_project.sh, test/test_install_kubernetes_quality_gates.sh, test/test_quality_gates_standalone.sh, test/utils.sh
Added tests for:
- delete service
- install Keptn into custom namespace and go through Quality-gates standalone use-case
=> Additional integration tests

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_models/project.ts, bridge/client/app/_models/trace.ts, bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.ts, bridge/package-lock.json, bridge/package.json
=> #2275 Minor bridge enhancements 0.7.1

.travis.yml
=> #2273 Include shipyard-controller in release pipeline

SECURITY.md
As discussed with @agrimmer I've added myself as a security contact.
=> Added myself (Christian Kreuzberger) as a security contact

upgrader/upgrade-062-070/upgrade-job-helm3.yaml
=> #2327 corrected env vars for upgrader with helm release upgrade

api/Dockerfile, api/swagger.yaml, configuration-service/Dockerfile, configuration-service/swagger.yaml, mongodb-datastore/Dockerfile, mongodb-datastore/swagger.yaml
Backport (or actually forward-port? :D) of #2328
=> #2325 Remove anything scheme related to let swagger automatically determine the scheme

configuration-service/common/git.go, configuration-service/common/git_test.go, configuration-service/handlers/project.go
Closes #2336
This PR allows to use an HTTP URL for a project upstream
=> #2336 Allow http for git repo urls

bridge/README.md, bridge/client/app/_services/api.service.ts, bridge/client/app/app-header/app-header.component.html, bridge/deploy/bridge.yaml, bridge/package-lock.json, bridge/server/api/index.js, bridge/server/app.js, installer/manifests/keptn/charts/control-plane/templates/core.yaml
=> #2319 Added functionality to show a download link to Keptn Bridge CLI

configuration-service/common/git.go
The changes made in PR #2337 introduced an unintended nil pointer access. This is fixed with this PR
=> Fixed nil pointer access

configuration-service/swagger.yaml, mongodb-datastore/swagger.yaml
=> #2348 Set swagger version to develop which is finally replaced for releases

lighthouse-service/event_handler/common.go, lighthouse-service/event_handler/handler.go, lighthouse-service/event_handler/handler_test.go, lighthouse-service/event_handler/start_evaluation_handler.go, lighthouse-service/event_handler/start_evaluation_handler_test.go
=> #2318 Default SLI provider; Send get-sli event when no SLO file is available

installer/manifests/keptn/charts/control-plane/charts/mongodb/templates/secret.yaml, installer/manifests/keptn/charts/control-plane/templates/core.yaml
Backport of #2345 for release-0.7.2
=> #2295 Increase password and token entropy

cli/.gitignore, cli/cmd/generate_support_archive.go
Backport of #2375 for release-0.7.2
=> #2340 Improve robustness and user-experience of generate support-archive

travis-scripts/build_latest_installer.sh, travis-scripts/build_release_installer.sh
This PR verifies that the helm template that are being created are valid.
Hint: they are currently not valid.
=> Verify helm templates before uploading them

bridge/client/app/_services/data.service.ts, bridge/client/app/app-header/app-header.component.html, bridge/client/app/app-header/app-header.component.ts, bridge/deploy/bridge.yaml, bridge/server/api/index.js, bridge/server/app.js, installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/values.yaml
=> #2320 Feature toggle for version check and api token info into master

installer/.gitignore, installer/manifests/keptn/charts/control-plane/templates/core.yaml
=> Fix error in helm chart

test/test_quality_gates_standalone.sh, test/utils.sh
Updated tests to reflect the changes that have been made in #2317 and #2318
=> Added new test cases for modified lighthouse service behavior

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
Highlight the currently selected evaluation in the Heatmap
=> #1640 Enable highlighting in heatmap chart 

.travis.yml, cli/main.go
Addresses parts of #2411 (unsure about docs updates)
=> Add 1.19 to Travis and CLI Supported Versions

.travis.yml, cli/main.go
Backport of #2414 for 0.7.2 (closes #2411).
=> Add 1.19 to Travis and CLI Supported Versions - Backport

bridge/client/app/_models/event-icons.ts, bridge/client/app/_models/event-labels.ts, bridge/client/app/_models/trace.ts
=> #2371 Bridge: show actual state in approval finished events

cli/pkg/platform/platform_manager.go
=> #2425 Fixed the infinite loop bug

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.scss, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_models/trace.ts
Backport of PR #2424 for release 0.7.2
=> #2389 Highlight comparedEvents in heatmap - backport 0.7.2

.travis.yml, test/test_quality_gates_standalone.sh
=> #2335 Fix integration tests

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html, bridge/client/app/_models/trace.ts, bridge/client/styles.scss
Backport PR #2406 for release-0.7.2
=> #2305 Evaluation tile rework - backport 0.7.2

bridge/client/app/_services/data.service.ts, bridge/client/app/app-header/app-header.component.html, bridge/server/api/index.js
=> #2430 Fixed broken link

cli/cmd/create_project.go, cli/cmd/create_project_test.go, cli/go.mod, cli/go.sum
=> #1648 YAML input support for URIs

bridge/client/app/_services/data.service.ts, bridge/client/app/app-header/app-header.component.html
* #2430 Fix broken link
* Reverted the change on the server
=> #2430 Fixed broken link - backport to 0.7.2

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_models/trace.ts
Backport of PR #2432 for release-0.7.2
=> #2131 Show labels on xAxis in Heatmap - backport 0.7.2

cli/cmd/generate_support_archive.go, cli/cmd/root.go, cli/cmd/version.go, cli/cmd/version_test.go, cli/pkg/version/keptn_version_checker_test.go, cli/pkg/version/ketpn_version_checker.go, cli/pkg/version/version_checker.go, cli/pkg/version/version_checker_test.go, cli/pkg/version/version_fetcher_test.go
=> #2412 CLI: print keptn cluster version

.travis.yml, travis-scripts/install_pluto.sh
Closes #2382
Passing build: https://travis-ci.org/github/anukul/keptn/jobs/731298886
Failing build: https://travis-ci.org/github/anukul/keptn/jobs/731299627
=> #2382 CI: add pluto to check deprecated Kubernetes apiVersions

cli/cmd/auth.go
=> #2445 Added endpoint in output while keptn auth

README.md
Issue #2454 
Added installation instructions for K3s and updated installation docs link in README.md.
=> Updated Usage section of README.md

cli/go.mod, cli/go.sum, lighthouse-service/go.mod, lighthouse-service/go.sum
=> Update go utils and specification dependencies 

configuration-service/common/git.go, configuration-service/handlers/project.go, configuration-service/handlers/stage.go
Closes #2487 
This PR ensures that the master branch in the upstream repository is available when creating/updating a project
=> #2487 Configuration service: ensure availability of master branch

bridge/client/index.html
Backport PR #2503 for release-0.7.2
=> #2301 Incorrect file path

installer/manifests/keptn/charts/continuous-delivery/charts/openshift/templates/route-service-openshift.yaml, installer/manifests/keptn/charts/continuous-delivery/templates/continuous-deployment.yaml, installer/manifests/keptn/charts/control-plane/charts/mongodb/templates/deployment.yaml, installer/manifests/keptn/charts/control-plane/templates/continuous-operations.yaml, installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/templates/mongodb-datastore.yaml, installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml
=> #2518 set imagePullPolicy to IfNotPresent in installer

bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.ts
Update variables and timeframe such that API Call and CLI Call are consistent
Fixes #2517
=> #2517 Update Integrations page

bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.ts
Update variables and timeframe such that API Call and CLI Call are consistent
Fixes #2517
=> #2517 Update Integrations page - master

.travis.yml
This PRs adds cron integration jobs with GKE for travis
=> Run integration tests on GKE for release branch

mongodb-datastore/models/keptn_context_extended_c_e.go, mongodb-datastore/restapi/embedded_spec.go, mongodb-datastore/restapi/operations/mongodb_datastore_api.go, mongodb-datastore/swagger.yaml
=> mongodb-datastore: added triggeredid

releasenotes/releasenotes_V0.7.1.md, releasenotes/releasenotes_V0.7.2.md
Cherry-picked release-notes for 0.7.2
=> #2431 Initial release notes for 0.7.2 (#2462)

bridge/client/app/_interceptors/http-default-interceptor.spec.ts, bridge/client/app/_interceptors/http-default-interceptor.ts, bridge/client/app/_services/api.service.ts, bridge/client/app/app.module.ts
=> #1987 Use an HTTP interceptor to set default headers

bridge/client/app/app.component.spec.ts, bridge/client/index.html
=> #2564 Fix base href in bridge

bridge/client/app/app.component.spec.ts, bridge/client/index.html
=> #2564 Fix base href in bridge - backport 0.7.3

cli/cmd/check_endpoint_status.go, cli/cmd/check_endpoint_status_test.go, cli/cmd/root.go
Hey guys, this PR contains:
- Addi 5 seconds of a timeout to avoid hanging connection
- Remove version check for root calls
@christian-kreuzberger-dtx  @warber 
FIxing #2505
=> #2505 Remove version check for root cmds

configuration-service/common/git.go, configuration-service/common/projects_materialized_view.go, configuration-service/handlers/project.go
=> #2577 Update git upstream infos in materialized view

helm-service/controller/action_handler.go, helm-service/controller/configuration_changer.go, helm-service/controller/onboarder.go, helm-service/go.mod, helm-service/go.sum
=> #2578 added timeout when waiting for deployment to be rolled out

helm-service/go.mod, helm-service/go.sum
=> #2578 Updated kubernetes-utils dependency

cli/cmd/install.go
Closes #2584 
Modify the help comment for --use-case flag
=> #2584 Modify the help comment for --use-case flag

cli/cmd/version.go
=> #2589 Added timeout of 5 seconds to server version check

mongodb-datastore/restapi/embedded_spec.go, mongodb-datastore/swagger.yaml
=> #2582 Removed cloudevents+json from list of produced content types

cli/cmd/install.go, cli/pkg/common/quick_access_instructions.go, cli/pkg/common/quick_access_instructions_darwin.go, cli/pkg/common/quick_access_instructions_linux.go, cli/pkg/common/quick_access_instructions_windows.go
=> #2576 Print platform specific access instructions

cli/cmd/create_project.go, cli/cmd/onboard_service.go, cli/cmd/onboard_service_test.go, test/assets/delivery_assistant_shipyard.yaml, test/assets/shipyard_onboard_service.yaml, test/test_onboard_service.sh
=> #2557 Update shipyard files in integration tests

cli/cmd/install.go, cli/pkg/common/quick_access_instructions.go, cli/pkg/common/quick_access_instructions_darwin.go, cli/pkg/common/quick_access_instructions_linux.go, cli/pkg/common/quick_access_instructions_windows.go, test/test_install_gke.sh, test/test_install_kubernetes_full.sh, test/test_install_kubernetes_quality_gates.sh, test/test_install_minishift_quality_gates.sh
* Merge with master
Co-authored-by: Johannes <johannes.braeuer@dynatrace.com>
=> #2444 Improved post installations steps for nodeport and loadbalancer (#2486)

cli/cmd/install.go, installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/values.yaml
=> #2609 Added installation type env var to bridge

configuration-service/common/projects_materialized_view.go
=> #2639 fix create project with upstream creds

bridge/client/app/project-board/project-board.component.ts
=> #2620 Print start time for example start-evaluation in UTC - backport 0.7.3

installer/manifests/keptn/charts/control-plane/values.yaml
=> #2651 Update nginx version

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html
=> #2585 Show evaluation timeframe of selection evaluation

bridge/client/app/_services/api.service.ts, bridge/client/app/_services/data.service.ts, bridge/deploy/bridge.yaml, bridge/server/api/index.js
Fixes #2631 
Please merge https://github.com/keptn/keptn/pull/2607 first!
=> #2631 Allow to load more than 20 services/projects in bridge - backport 0.7.3

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html
=> #2585 Show evaluation timeframe of selection evaluation - backport 0.7.3

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
=> #2545 Read value from SLO file with and without apostrophe

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
=> #2545 Read value from SLO file with and without apostrophe - backport 0.7.3

bridge/client/app/_services/api.service.ts, bridge/client/app/_services/data.service.ts, bridge/deploy/bridge.yaml, bridge/server/api/index.js
Fixes #2631
Please merge #2606 first!
=> #2631 Allow to load more than 20 services/projects in bridge

releasenotes/releasenotes_V0.7.3.md
**Stop** TravisCI build to not build the images.
=> Patch release notes to set correct NGNIX image

lighthouse-service/event_handler/start_evaluation_handler.go, lighthouse-service/event_handler/start_evaluation_handler_test.go, remediation-service/handler/action_finished_handler.go, remediation-service/handler/action_finished_handler_test.go, remediation-service/handler/evaluation_done_handler.go, remediation-service/handler/evaluation_done_handler_test.go, remediation-service/handler/handler.go, remediation-service/handler/problem_open_handler.go, test/test_self_healing.sh
Closes #2663 
As mentioned in Issue #2663, The integration test `test_self_healing_scaling.sh` depends on the completion of Issue #2558
=> #2663 Remediation Workflow for Keptn 0.8

ADOPTERS.md
Signed-off-by: ksatchit <karthik.s@mayadata.io>
=> (update)adopters: add mayadata as an adopter

.github/workflows/reviewdog.yml, shipyard-controller/operations/project.go
=> #2694 replace commands using add-path

shipyard-controller/api/project.go
=> #2697 Send project.delete.finished after deleting a project

test/test_install_kubernetes_full.sh, test/test_install_kubernetes_quality_gates.sh, test/test_install_minishift_quality_gates.sh, test/utils/download_and_install_keptn_cli.sh
=> #2701 Move keptn version command in Integration tests

cli/pkg/credentialmanager/handler_linux.go, test/test_install_gke.sh, test/test_install_kubernetes_full.sh, test/test_install_kubernetes_quality_gates.sh, test/test_install_minishift_quality_gates.sh
Closes #2712 
Additional changes: removed outdated checks from the test scripts
=> #2712 fixed name of credentials file, removed obsolete checks

bridge/client/app/app.component.html
=> #2693 Show notification about new Keptn version

cli/cmd/delete_project.go
Correct messages in the CLI command `keptn delete project`
=> Correct output messages

configuration-service/common/git.go, configuration-service/go.sum, configuration-service/handlers/project.go, installer/manifests/keptn/charts/control-plane/templates/rbac.yaml, shipyard-controller/api/project.go, shipyard-controller/api/project_test.go, shipyard-controller/common/secret_store.go, shipyard-controller/common/secret_store_test.go, shipyard-controller/go.sum
=> #2708 Updating existing upstream

cli/cmd/root.go, test/test_quality_gates_standalone.sh, test/utils.sh
Closes #2724 
Closes #2761
This PR contains minor fixes to make the integration tests work
=> #2724 CLI log fixed, adapted test scripts

test/assets/evaluation_invalidated_event_template.json
Fix payload for invalidating evaluation
=> #2724 fixed event for invalidating events

test/utils/send_new_artifact_sockshop.sh
The parameters for the script were not handled correctly. This has been corrected with this PR
=> Fixed test script for sending new artifact

mongodb-datastore/deploy/manifests-db/secret.yaml
=> #2770 Add comment about usage of this secret

configuration-service/common/git.go, configuration-service/deploy/service.yaml
=> #2735 Fixed order in which branches are pushed to upstream

.travis.yml, test/utils/gke_authenticate_at_cluster.sh, test/utils/gke_create_cluster.sh, travis-scripts/install_gcloud.sh
=> #2789 Fix GKE integration tests

cli/cmd/auth.go, cli/cmd/install.go, cli/cmd/install_upgrade_params.go, cli/cmd/upgrade.go, cli/go.mod, cli/go.sum
Signed-off-by: ankitjain28may <ankitjain28may77@gmail.com>
=> Keptn Smart Auth: Autofetch keptn endpoint and api-token

remediation-service/handler/handler.go, remediation-service/handler/problem_open_handler_test.go
=> #1917 Include triggeredid in status.changed and .finished events

ADOPTERS.md
Signed-off-by: Sumit Nagal <sumit_nagal@intuit.com>
=> Addition for adopters from Intuit

README.md
=> Removed Travis-CI, added GH Actions Badge

api/handlers/metadata.go, cli/cmd/auth.go, shipyard-controller/api/event_test.go
=> #2849 Fix spelling mistakes

.github/workflows/integration_tests.yml, test/test_onboard_service.sh, test/test_self_healing_scaling.sh
This PR fixes the GH action for integration tests, and introduces a new parameter for the Keptn examples repo.
=> #2824 Fix integration test action

releasenotes/releasenotes_V0.8.0-alpha.md, releasenotes/releasenotes_develop.md
This PR sets the spec version and preliminary release notes for Keptn 0.8.0-alpha and spec 0.2.0-alpha.
=> Releasenotes, spec change for 0.8.0-alpha

README.md
This PR updates the quickstart instructions in our main readme file to be in line with the latest changes on get.keptn.sh
=> Update quickstart instructions in readme

cli/cmd/version.go, releasenotes/releasenotes_V0.8.0-alpha.md, releasenotes/releasenotes_develop.md
Release Issue https://github.com/keptn/keptn/issues/2807
Already released, please merge whenever ready ;)
=> Release 0.8.0 alpha

.github/stale.yml
This PR exempts several labels from stale bot.
=> Exempt help-wanted, known-issue and integrations from stale bot

helm-service/go.sum, helm-service/pkg/mesh/ingress_config.go, helm-service/pkg/mesh/ingress_config_test.go
=> #2362 Use HOSTNAME_TEMPLATE env var to generate HostName

cli/cmd/auth.go, cli/pkg/credentialmanager/handler.go
=> #2834 missing KUBECONFIG file does not cause CLI to break anymore

shipyard-controller/api/event.go, shipyard-controller/db/mongodb_connection.go
Closes #2905
**Memory consumption before the fix:**
**Memory consumption after the fix:**
=> #2905 fixed potential memleaks

shipyard-controller/api/event.go, shipyard-controller/api/event_test.go, shipyard-controller/common/keptn_helpers.go
=> #2803 Check version of shipard file before starting task sequence

.github/workflows/CI.yml, helm-service/pkg/helm/generated_chart_handler.go, helm-service/pkg/helm/generated_chart_handler_test.go
=> #2932: fixed hostname template processing in helm service

test/test_self_healing.sh
=> fixed test_self_healing.sh assertions

test/test_self_healing.sh
=> #2830 fix integration tests for self healing

.github/workflows/CI.yml
This PR uses the brand-new GH action "keptn/gh-action-extract-branch-name@main", which can be found here: https://github.com/keptn/gh-action-extract-branch-name
This is part of #2824, but does not fully implement everything asked in #2824.
=> #2824 Use keptn/gh-action-extract-branch-name

bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts, bridge/client/app/app.module.ts
Switched the SLI evaluation breakdown to a barista table for #2478. Criteria Type will be added in a separate issue as it requieres changes to the cloud events and lighthouse service.
=> #2478 SLI breakdown in table 

bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.html, bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.scss, bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.spec.ts, bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.ts, bridge/client/app/_models/root.ts, bridge/client/app/_models/trace.ts, bridge/client/app/app.module.ts, bridge/client/app/project-board/project-board.component.html
=> #2907 create sequence timeline

helm-service/controller/deployment_handler.go, helm-service/controller/deployment_handler_test.go
=> #2980 fixed port retrieval, added unit tests

.github/workflows/CI.yml, .github/workflows/integration_tests.yml, test/utils/gke_create_cluster.sh, test/utils/install_istio.sh
Fixes several issues [in our integration test workflow](https://github.com/keptn/keptn/actions/runs/509826911).
1. Input variable needs `github.event` in front
1. Istio installation needs a `-y` for confirmation
1. In addition, istio does not need the demo profile (and we actually don't recommend it in our tutorials either)
1. Fix GKE label must be lowercased
1. Docker Login was not executed on master branch (needed to add the if type == push)
1. Added some timeouts for certain steps to prevent tasks that run for ever
=> Fix integration tests

cli/cmd/helpers.go, cli/cmd/helpers_test.go
=> #2995 fixed json output

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_services/data.service.ts
=> #1499 fixed order of SLOs in evaluation

cli/cmd/create_project.go, cli/cmd/create_project_test.go, shipyard-controller/api/project.go, shipyard-controller/common/keptn_helpers.go
=> #2914 check project name and stage names during project creation

helm-service/sequence_diagrams/action-triggered-source.txt, helm-service/sequence_diagrams/deployment-triggered-source.txt, helm-service/sequence_diagrams/release-triggered-bg-promote-source.txt, helm-service/sequence_diagrams/release-triggered-bg-rollback-source.txt, helm-service/sequence_diagrams/release-triggered-direct-source.txt, helm-service/sequence_diagrams/service-created-source.txt, helm-service/sequence_diagrams/service-deleted-source.txt
=> #2592 Add sources for sequence diagrams

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_models/root.ts, bridge/client/app/_models/trace.ts, bridge/client/app/_services/data.service.ts
=> #2901 fixed confirmation dialog of approval

shipyard-controller/handler/eventhandler.go, shipyard-controller/handler/eventhandler_test.go, shipyard-controller/handler/fake/shipyardcontroller.go, shipyard-controller/handler/shipyardcontroller.go, shipyard-controller/handler/shipyardcontroller_test.go
=> #2956 return 400 http status if no matching event, instead of 500

cli/cmd/completion.go
=> #2539 feat: cli bash and shell autocompletions

cli/cmd/upgrade.go, cli/pkg/version/version_checker.go
=> #2560 fix(cli): add better keptn upgrade message

api/go.mod, api/go.sum, api/handlers/metadata.go, api/handlers/metadata_test.go, cli/cmd/root.go, cli/cmd/root_test.go, cli/cmd/version.go
=> #2870 improved logging in case of cluster API downtime

bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.html, bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.scss, bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.ts, bridge/client/app/project-board/project-board.component.html
=> #3049 highlight selected stage in timeline

cli/cmd/root_test.go, cli/cmd/upgrade.go, cli/cmd/upgrade_test.go
Fixes failing unit tests for CLI
CC @bacherfl
=> Fix failing unit tests for CLI

.github/dependabot.yml
=> #2648 added dependabot.yml

cli/cmd/generate_ce_spec.go, cli/go.mod, cli/go.sum, cli/internal/cespec/data.go, cli/internal/cespec/genspec.go, cli/internal/cespec/md.go
=> #2926 added go generate cloud-events-spec command

ADOPTERS.md
Signed-off-by: jetzlstorfer <juergen.etzlstorfer@dynatrace.com>
=> adding Dynatrace

gatekeeper-service/go.sum, gatekeeper-service/main.go, gatekeeper-service/pkg/handler/approval_triggered_event_handler.go, gatekeeper-service/pkg/handler/approval_triggered_event_handler_test.go, gatekeeper-service/pkg/handler/handler.go, gatekeeper-service/pkg/handler/handler_test.go
Part of https://github.com/keptn/keptn/issues/3150
/cc @christian-kreuzberger-dtx
=> gatekeeper-service: format go import

shipyard-controller/controller/servicecontroller.go
=> #3167 fixed api route setup

bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.html, bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.scss, bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.spec.ts, bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.ts, bridge/client/app/app.module.ts, bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.scss, bridge/client/app/project-board/project-board.component.ts
=> #2942 Create integration-view component

lighthouse-service/README.md, lighthouse-service/event_handler/common.go, lighthouse-service/event_handler/common_test.go, lighthouse-service/event_handler/configure_monitoring_handler.go, lighthouse-service/event_handler/configure_monitoring_handler_test.go, lighthouse-service/event_handler/evaluate_sli_handler.go, lighthouse-service/event_handler/evaluate_sli_handler_test.go, lighthouse-service/event_handler/handler.go, lighthouse-service/event_handler/handler_test.go, lighthouse-service/event_handler/start_evaluation_handler.go, lighthouse-service/event_handler/start_evaluation_handler_test.go, lighthouse-service/main.go
Part of https://github.com/keptn/keptn/issues/3150
/cc @christian-kreuzberger-dtx
=> lighthouse-service: format go import

bridge/client/app/_models/event-types.ts, bridge/client/app/_services/api.service.ts, bridge/client/app/_services/data.service.ts
=> #3013 fix manual approval

CONTRIBUTING.md, README.md
I've added the boyscout rule to our contribution guide.
In addition, I've simplified our README file (some information is just outdated or not needed anymore).
=> Added boyscout rule to contributing guide, updated readme

.github/workflows/CI.yml, codecov.yml
This PR fixes the wrongly displayed partial codecoverage for distributor in PRs:
=> Fixed codecoverage for distributor

test/test_delivery_assistant.sh, test/test_quality_gates_standalone.sh, test/test_self_healing.sh
=> #3226 fixed API endpoints in integration tests

shipyard-controller/handler/projecthandler.go, shipyard-controller/handler/projecthandler_test.go
=> fix project param

configuration-service/common/git.go
=> #3237 fixed upstream repo communication

shipyard-controller/handler/evaluationmanager.go, shipyard-controller/handler/evaluationmanager_test.go, test/test_quality_gates_standalone.sh
=> fix time format in evaluation triggered event; made test more robust

configuration-service/common/git.go
=> #3237 fixed credentials retrieval

bridge/client/app/_components/ktb-project-tile/ktb-project-tile.component.html, bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html, bridge/client/app/_components/ktb-stage-overview/ktb-stage-overview.component.html, bridge/client/app/_pipes/keptn-url.pipe.ts, bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.html, bridge/client/app/app-header/app-header.component.html, bridge/client/app/app-header/app-header.component.ts, bridge/client/app/app.module.ts, bridge/client/app/dashboard/dashboard.component.html, bridge/client/app/evaluation-board/evaluation-board.component.html, bridge/client/app/project-board/project-board.component.html
=> #3205 update doc references

api/swagger-ui/index.html, bridge/client/app/_interceptors/http-default-interceptor.spec.ts, bridge/client/app/_services/api.service.ts, cli/cmd/add_resource.go, cli/cmd/delete_project.go, cli/cmd/generate_support_archive.go, cli/cmd/get_projects.go, cli/cmd/get_services.go, cli/cmd/get_stages.go, cli/cmd/onboard_service.go, cli/cmd/send_event_evaluationStart.go, cli/go.mod, cli/go.sum, distributor/README.md, distributor/cmd/main.go, distributor/cmd/main_test.go, installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml, shipyard-controller/Dockerfile, test/test_delivery_assistant.sh, test/test_quality_gates_standalone.sh, test/test_self_healing.sh
=> #3001 update paths to shipyard controller

configuration-service/handlers/service_resource.go
=> #1924 implement getting resource list for a service

distributor/README.md, distributor/cmd/main.go, distributor/cmd/main_test.go
=> #3262 Simplified event filtering for distributor

shipyard-controller/handler/shipyardcontroller.go, shipyard-controller/handler/shipyardcontroller_test.go
=> #3043 make sure the message property of a .triggered event is not propagated

cli/cmd/upgrade_project.go, cli/cmd/upgrade_project_test.go
=> updated cli upgrade_project command

.github/workflows/CI.yml, .gitmodules, gh-actions-scripts/build_installer_helm_chart.sh, installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/values.yaml, mongodb-datastore/deploy/mongodb-datastore.yaml, mongodb-datastore/models/keptn_context_extended_c_e.go, mongodb-datastore/restapi/embedded_spec.go, mongodb-datastore/swagger.yaml, shipyard-controller/common/keptn_helpers.go, shipyard-controller/common/keptn_helpers_test.go, shipyard-controller/deploy/service.yaml
=> #2983 added keptn spec version to events sent by shipyard-controller

cli/cmd/trigger_delivery.go, test/test_new_artifact.sh
=> #3007 fixed handling im --image parameter for trigger delivery command

cli/cmd/auth.go
=> #2877 cli: better keptn auth messages

api/swagger-ui/index.html
=> Rename shipyard-controller to controlPlane un swagger-ui

test/test_self_healing.sh
Better log output in case of failing tests for self healing use-case
=> #3325 added logs of remediation service to self healing integration test

cli/internal/cespec/data.go
=> add keySli to cloudevents

installer/manifests/keptn/charts/control-plane/templates/continuous-operations.yaml, remediation-service/handler/handler.go, remediation-service/main.go, shipyard-controller/deploy/service.yaml, test/test_self_healing.sh
=> #3325 adapted subscriptions of remediation service, removed noise in log output

shipyard-controller/common/configurationstore.go, shipyard-controller/common/configurationstore_test.go
=> 3334: fix update git upstream err

bridge/client/app/_components/ktb-sequence-tasks-list/ktb-sequence-tasks-list.component.ts, bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.spec.ts, bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.ts, bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html, bridge/client/app/_components/ktb-task-item/ktb-task-item.component.ts, bridge/client/app/_forwarder/forwarderGuard.ts, bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.scss, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.html, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.ts, bridge/client/app/app.routing.ts, bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.ts
Fixes #3207 
Associated PR [deep-links update](https://github.com/keptn/keptn.github.io/pull/757)
=> #3207 Deep Links

.github/workflows/integration_tests.yml, test/test_linking_stages.sh, test/test_onboard_service.sh, test/test_quality_gates_standalone.sh
This PR adds the following:
* Better checks for integration tests (e.g., did create project/service work).
* quality-gates-compatibility test to the results matrix
* keptn generate support-archive at the end of tests, upload it as an artifact
=> Added better checks for integration tests, added quality-gates-backwards-compat to results

shipyard-controller/db/projects_materialized_view.go, shipyard-controller/db/projects_materialized_view_test.go, shipyard-controller/go.sum, shipyard-controller/handler/shipyardcontroller.go, shipyard-controller/handler/shipyardcontroller_test.go
=> #3348 avoid trying to update event of unavailable project/service/stage

shipyard-controller/handler/shipyardcontroller.go, shipyard-controller/handler/shipyardcontroller_test.go
=> #3329 add triggeredid to sequence.finished events

shipyard-controller/handler/servicemanager.go, shipyard-controller/handler/servicemanager_test.go
This PR re-introduces the changes made in https://github.com/keptn/keptn/pull/3005 as they got lost when merging https://github.com/keptn/keptn/pull/3222
=> #2948 re-added service name length check

bridge/client/app/_services/data.service.ts
=> #3353 fix environment screen

cli/cmd/send_event_approvalFinished.go, cli/cmd/send_event_newArtifact.go, cli/cmd/trigger_delivery.go, cli/go.sum
=> feat: add labels to send events

cli/cmd/send_event_newArtifact.go, cli/cmd/trigger_delivery.go
=> fix description of label flag

bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html
=> #2696 link to evaluation from quality gate

bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html, bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.ts, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.html
=> #3332 Rename send event to trigger commands

api/go.mod, api/go.sum, approval-service/go.mod, approval-service/go.sum, cli/go.mod, cli/go.sum, configuration-service/go.mod, configuration-service/go.sum, distributor/go.mod, distributor/go.sum, helm-service/go.mod, helm-service/go.sum, jmeter-service/go.mod, jmeter-service/go.sum, lighthouse-service/go.mod, lighthouse-service/go.sum, mongodb-datastore/go.mod, mongodb-datastore/go.sum, remediation-service/go.mod, remediation-service/go.sum, shipyard-controller/go.mod, shipyard-controller/go.sum, statistics-service/go.mod, statistics-service/go.sum
needed for release (#3256)
This PR also updates the specification submodule
=> Updated dependencies to go-utils and kubernetes-utils

test/test_self_healing.sh
use `.data.status` instead of `.data.action.status` in jq check
=> fix self healing integration test

cli/cmd/send_event_approvalFinished.go
=> #3369 fixed sending approval.finished event

bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts
=> #3374 fixed empty sequence filter

bridge/client/app/_models/trace.ts
=> #3368 fixed task being incorrectly finished

bridge/client/app/_models/approval-states.ts
=> #3366 set result to 'fail' when sending approval.finished event for declining approval

bridge/client/app/_models/trace.ts
=> #3381 Mark sequence correctly as finished

cli/cmd/upgrade_project.go
=> #3384 added hint about known limitation regarding the shipyard version update

releasenotes/releasenotes_develop.md
=> #3256 Release notes for Keptn 0.8

helm-service/chart/values.schema.json, helm-service/chart/values.yaml, jmeter-service/chart/values.schema.json, jmeter-service/chart/values.yaml
=> #3387 Fixed json schema of Helm Charts

.github/workflows/CI.yml
=> CI Typo Environment

bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts
=> #3383 fixed wrong score in sli-breakdown

.github/workflows/cleanup_images.yml
As we can not fix #3041 for now, I'll disable the workflow.
=> #3041 Disable cleanup images for now

lighthouse-service/event_handler/start_evaluation_handler.go
=> #3411: introduced GetSLITriggeredEventDataExtended to fix event payload

releasenotes/releasenotes_develop.md
=> #3256 Release notes for final 0.8

cli/cmd/upgrade.go, cli/pkg/kube/kube_utils.go, cli/pkg/kube/kube_utils_test.go
=> #3399: added check for statistics service

.github/workflows/integration_tests.yml
This PR updates dynatrace-sli-service version to 0.8.0
=> #3256 Update dynatrace-sli-service version in integration test to 0.8.0

.github/workflows/integration_tests.yml
This PR fixes the helm chart upload
=> Fix helm chart upload

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.scss, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts, bridge/client/app/_services/data.service.ts, bridge/client/app/project-board/project-board.component.html, cli/go.mod, cli/go.sum, cli/internal/cespec/data.go, lighthouse-service/event_handler/evaluate_sli_handler.go, lighthouse-service/go.mod, lighthouse-service/go.sum
Related PRs:
[keptn/go-utils/#266](https://github.com/keptn/go-utils/pull/266)
[keptn/spec/#71](https://github.com/keptn/spec/pull/71)
Fixes #3345 
=> #3345 sli display name

bridge/client/app/_models/event-types.ts, bridge/client/app/_models/trace.ts
=> #3438 fixed missing quality gate in environment screen

helm-service/chart/values.schema.json, jmeter-service/chart/values.schema.json
See https://regex101.com/r/OLYXkq/1
Resolves #3450
=> Add Helm schema validation support for a 'remoteControlPlane.api.hostname' port value

.github/actions/spelling/expect.txt, shipyard-controller/README.md, shipyard-controller/docs/docs.go, shipyard-controller/docs/swagger.json, shipyard-controller/docs/swagger.yaml, shipyard-controller/skaffold.yaml
While working on https://github.com/keptn/keptn/issues/3456 I noticed that shipyard-controllers swagger docs are not updated according to what they should contain. 
This PR manually updates swagger docs.
Also, I've updated README to explain development using skaffold.
=> Updated swagger docs of shipyard-controller

.github/actions/spelling/expect.txt
In PR https://github.com/keptn/keptn/pull/3452 I also needed to add performance to exceptions
=> Added perfromance to exceptions

.github/workflows/integration_tests.yml, test/test_onboard_service.sh
=> #3214 integration test for remote execution plane

configuration-service/Dockerfile
=> #3486: bump version of git installation in docker file

.github/workflows/integration_tests.yml, test/assets/shipyard_onboard_service.yaml, test/test_delete_project.sh, test/test_onboard_service.sh, test/utils.sh, test/utils/gke_create_cluster.sh, test/utils/trigger_delivery_sockshop.sh
=> #2970 test parallel execution of continuous delivery use case

shipyard-controller/docs/docs.go, shipyard-controller/docs/swagger.json, shipyard-controller/docs/swagger.yaml, shipyard-controller/handler/projecthandler.go, shipyard-controller/handler/servicehandler.go, shipyard-controller/handler/stagehandler.go
=> #3489: fixed swagger doc

shipyard-controller/docs/docs.go, shipyard-controller/docs/swagger.json, shipyard-controller/docs/swagger.yaml, shipyard-controller/handler/projecthandler.go, shipyard-controller/handler/servicehandler.go, shipyard-controller/handler/stagehandler.go
=> Revert "#3489: fixed swagger doc"

.github/workflows/CI.yml, make-scripts/build/build-cli.sh
=> #3503 Fix CLI build

bridge/README.md, bridge/client/app/app-header/app-header.component.ts, bridge/package-lock.json
=> #3446 Fix message for updates from pre-releases

.github/actions/spelling/expect.txt
@warber @bacherfl: #3529 has made the bot unhappy...
=> spelling: Add Nooooooo

bridge/client/app/_services/api.service.ts
=> #3477 fixed decline approval

bridge/client/app/_services/data.service.ts
=> #3435 fixed order of events

installer/manifests/keptn/charts/control-plane/values.yaml
=> Remove unused values for eventbroker and shipyardService

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_components/ktb-stage-badge/ktb-stage-badge.component.html, bridge/client/app/_components/ktb-stage-badge/ktb-stage-badge.component.scss, bridge/client/app/_components/ktb-stage-badge/ktb-stage-badge.component.spec.ts, bridge/client/app/_components/ktb-stage-badge/ktb-stage-badge.component.ts, bridge/client/app/app.module.ts
=> #3425 Show evaluation result on root event next to stage

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html
=> #3537 Show all labels in service screen correctly

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts
=> #3567 Fallback to metric name if displayName is not set

distributor/README.md, distributor/cmd/main.go, distributor/cmd/main_test.go, distributor/go.sum
=> #3577 Allow a comma-separated list of values for distributor filters

.github/actions/spelling/excludes.txt, .github/actions/spelling/expect.txt
This adds the ADOPTERS file to the excludes list.
=> Ignore ADOPTERS.md

bridge/client/app/_services/api.service.ts, bridge/client/app/_services/data.service.ts
=> #3557 reduce send approval data, fix task mapper

.github/actions/spelling/expect.txt, bridge/client/app/_components/ktb-copy-to-clipboard/ktb-copy-to-clipboard.component.html, bridge/client/app/_components/ktb-copy-to-clipboard/ktb-copy-to-clipboard.component.scss, bridge/client/app/_components/ktb-copy-to-clipboard/ktb-copy-to-clipboard.component.ts
=> #3370 fix Safari input color not readable

.github/actions/spelling/expect.txt, releasenotes/releasenotes_develop.md
=> Release notes for 0.8.1

.github/actions/spelling/expect.txt
Signed-off-by: Josh Soref <jsoref@users.noreply.github.com>
=> Update spelling expect file

bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.ts, bridge/client/app/_views/ktb-environment-view/ktb-environment-view.component.scss
=> #3592 fix quality gate icon, fix problem selection not updating

bridge/client/app/_components/ktb-evaluation-info/ktb-evaluation-info.component.html, bridge/client/app/_components/ktb-evaluation-info/ktb-evaluation-info.component.ts, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.ts, bridge/client/app/_components/ktb-stage-badge/ktb-stage-badge.component.html, bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html, bridge/client/app/_models/root.ts, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.html, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.html, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.ts
=> #3578 UX navigation with smart linking

bridge/client/app/_components/ktb-sli-breakdown-criteria-item/ktb-sli-breakdown-criteria-item.component.html, bridge/client/app/_components/ktb-sli-breakdown-criteria-item/ktb-sli-breakdown-criteria-item.component.ts
=> #2757 show sli target value overlay

bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html
=> #3609 improve trace message formatting

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html
=> #3591 tile colour for all finished/waiting sequences

installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml
Fixes  #3672 by introducing conditional selection of scheme for X-Forwarded-Proto on bridge.
=> Improve x-forward-proto header handling for bridge

.github/workflows/integration_tests.yml
=> #3686: updated gke version from 1.15 to 1.17 in integration tests

installer/manifests/keptn/charts/continuous-delivery/charts/openshift/values.yaml, installer/manifests/keptn/charts/continuous-delivery/values.yaml, installer/manifests/keptn/charts/control-plane/values.yaml
=> #3328: added tag field to deployments in values.yaml

bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html
=> #3652 fix filter in environment screen

.github/actions/spelling/expect.txt
Signed-off-by: Josh Soref <jsoref@users.noreply.github.com>
=> chore(spelling): golangci

shipyard-controller/handler/projectmanager.go, shipyard-controller/handler/projectmanager_test.go
=> #3773 Do proper rollback in case of an error during stage creation

installer/manifests/keptn/charts/control-plane/templates/rbac.yaml
=> Clean up K8s role

installer/manifests/keptn/charts/control-plane/templates/rbac.yaml
=> Changed permissions of configuration-service from manage to read secrets

bridge/client/app/_services/api.service.ts, bridge/client/app/_services/data.service.ts, bridge/package-lock.json, shipyard-controller/handler/projectmanager.go, shipyard-controller/handler/projectmanager_test.go
=> #3699: return correct response when project not found

bridge/client/_variables.scss, bridge/client/app/_components/ktb-notification-bar/ktb-notification-bar.component.html, bridge/client/app/_components/ktb-notification-bar/ktb-notification-bar.component.scss, bridge/client/app/app-header/app-header.component.ts
=> Show version info condensed & improve notification bar

releasenotes/releasenotes_develop.md
=> Update of release notes

jmeter-service/go.sum, jmeter-service/main.go, jmeter-service/main_test.go
Added more reliable check for http endpoint reachability.
=> Fixed issue with existing target url reachability check

jmeter-service/main.go, jmeter-service/main_test.go
=> JMeter-Svc: more reliable check for target url reachability

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_components/ktb-sli-breakdown-criteria-item/ktb-sli-breakdown-criteria-item.component.html, bridge/client/app/_components/ktb-sli-breakdown-criteria-item/ktb-sli-breakdown-criteria-item.component.ts, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts, bridge/client/app/_models/project.ts
Cherry-pick bug fix into release 0.8.2
=> #3815 Bug/3815/evaluation nan shown as number into release 0.8.2

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html, bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.ts, bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html, bridge/client/app/_models/project.ts, bridge/client/app/_models/service.ts, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.html, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.ts
Fixes #3848 
Closes #3445 
deployment:
no deployment:
Quality-gates only use case:
=> #3445 #3848 adapt service deployed message

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html, bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.ts, bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html, bridge/client/app/_models/project.ts, bridge/client/app/_models/service.ts, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.html, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.ts
Cherry-pick bug fix into release 0.8.2
=> #3848 Bug/3848/service deployed message into release 0.8.2

installer/manifests/keptn/charts/control-plane/Chart.yaml
upgrade nats helm-chart to 0.7.4 according to #2479
=> #2479 upgrade nats to 0.7.4

bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html, bridge/client/app/_models/trace.ts
=> Show changed in sequence task when event was .changed

bridge/client/app/app-header/app-header.component.ts
=> Subscribe to router events to properly show project

installer/manifests/keptn/charts/control-plane/templates/core.yaml
=> #3884 Quote env var values

helm-service/main.go
Fixes #3888 by adding goroutines in helm-service
=> #3888 Ensure helm-service is handling events in goroutines

.github/workflows/integration_tests.yml
=> #3897 Allow download artifacts from a pull-request

releasenotes/releasenotes_V0.8.2-hotfix1.md
Preview: https://github.com/keptn/keptn/blob/patch/releasenotes_082_hotfix1/releasenotes/releasenotes_V0.8.2-hotfix1.md
~ToDo: Try out the helm upgrade command~ - works
=> Prepare release notes for 0.8.2-hotfix1

jmeter-service/jmeterUtils_test.go, jmeter-service/main.go, jmeter-service/main_test.go
Fixes #3916
I also added unit tests to verify that this is fixed
=> #3916 Fix JMeter not accepting URLs without ports

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
=> Fix reading of undefined error when loading heatmap

bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html, bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.ts, bridge/client/app/_components/ktb-stage-overview/ktb-stage-overview.component.html, bridge/client/app/_components/ktb-stage-overview/ktb-stage-overview.component.ts, bridge/client/app/_services/api.service.ts, bridge/client/app/_views/ktb-environment-view/ktb-environment-view.component.html
Closes #3759 
Before setting filter:
After setting filter:
=> #3759 environment service filter

bridge/client/_variables.scss, bridge/client/app/_components/ktb-deployment-stage-timeline/ktb-deployment-stage-timeline.component.html, bridge/client/app/_components/ktb-deployment-stage-timeline/ktb-deployment-stage-timeline.component.scss, bridge/client/app/_components/ktb-deployment-stage-timeline/ktb-deployment-stage-timeline.component.spec.ts, bridge/client/app/_components/ktb-deployment-stage-timeline/ktb-deployment-stage-timeline.component.ts, bridge/client/app/_components/ktb-evaluation-info/ktb-evaluation-info.component.html, bridge/client/app/_components/ktb-evaluation-info/ktb-evaluation-info.component.scss, bridge/client/app/_components/ktb-evaluation-info/ktb-evaluation-info.component.ts, bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.scss, bridge/client/app/_components/ktb-service-details/ktb-service-details.component.html, bridge/client/app/_components/ktb-stage-badge/ktb-stage-badge.component.html, bridge/client/app/_components/ktb-stage-badge/ktb-stage-badge.component.scss, bridge/client/app/_components/ktb-stage-badge/ktb-stage-badge.component.ts, bridge/client/app/_models/root.ts, bridge/client/app/app.module.ts
=> #3713 stage timeline for deployments

test/assets/quality_gates_standalone_sli_dynatrace_step1.yaml, test/assets/quality_gates_standalone_sli_dynatrace_step2.yaml
Fixes #3922 (failing integration tests for quality gates):
* changed secrets for this repository to access the correct DT environment
* changed SLI config 
Verification Integration Tests (for quality gates): https://github.com/keptn/keptn/issues/3934 / https://github.com/keptn/keptn/actions/runs/806839731
Please note: the integration test for "Continuous Delivery (Remote Exec)" is still failing and will be fixed in another issue/PR.
=> #3922 Switch from demo-staging to demo-live

cli/go.sum, cli/internal/cespec/data.go, cli/internal/cespec/genspec.go
=> Adapt spec to show correct configure monitoring event type and payload

distributor/cmd/main.go, distributor/cmd/main_test.go
=> #3938 do not use pointer in goroutine called in loop

.github/workflows/spelling.yml
=> Only run spellcheck for push on master/release branch, not all branches

distributor/cmd/main.go, distributor/cmd/main_test.go, distributor/pkg/lib/cloudeventscache.go, distributor/pkg/lib/cloudeventscache_test.go
Fixes #3893 by 
* adding a `ceCache.remove` function
* Unit testing the `remove` function
* Extending the unit test for testing the polling/forwarding behaviour
In addition, I've applied boyscout rule and slightly improved the code in main.go
=> #3893 Added ceCache.remove functionality

bridge/client/app/_services/notifications.service.ts, bridge/client/app/app-header/app-header.component.ts
=> Prevents duplicate notifications

bridge/client/app/_components/ktb-deployment-list/ktb-deployment-list.component.ts, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts, bridge/client/app/_models/trace.ts, bridge/client/app/app.routing.ts, bridge/client/app/evaluation-board/evaluation-board.component.html, bridge/client/app/evaluation-board/evaluation-board.component.scss, bridge/client/app/evaluation-board/evaluation-board.component.ts
=> #3538 back-navigation in evaluation-screen, fix order of SLIs

bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.ts, bridge/client/app/_components/ktb-stage-overview/ktb-stage-overview.component.ts, bridge/client/app/_services/api.service.ts
=> #3993 reset environment screen on project change, #3994 save service filter of all projects

bridge/client/app/_components/ktb-services-list/ktb-services-list.component.html, bridge/client/app/_components/ktb-services-list/ktb-services-list.component.ts
=> Link to sequence on environment screen

bridge/package.json
=> Fix minimist to 1.2.5

bridge/client/app/_components/ktb-approval-item/ktb-approval-item.component.html, bridge/client/app/_components/ktb-approval-item/ktb-approval-item.component.scss, bridge/client/app/_components/ktb-approval-item/ktb-approval-item.component.ts, bridge/client/app/_components/ktb-service-details/ktb-service-details.component.html, bridge/client/app/_components/ktb-service-details/ktb-service-details.component.scss, bridge/client/app/_components/ktb-service-details/ktb-service-details.component.ts, bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html
=> Show open approvals on all relevant screens

bridge/client/app/_components/ktb-service-details/ktb-service-details.component.html
=> Move link to sequence execution in service view to button

shipyard-controller/handler/eventdispatcher.go, shipyard-controller/handler/eventdispatcher_test.go
Closes #4096 
Integration test run: https://github.com/keptn/keptn/runs/2609413152?check_suite_focus=true
=> Set time property of event to time at which it is sent

cli/internal/cespec/genspec.go
This PR removes the bullet point for remediation events, as these are not present anymore in the coming release of keptn
=> removed remediation bullet point

helm-service/chart/templates/deployment.yaml
=> Added subscription for rollback task

.github/actions/spelling/expect.txt, releasenotes/releasenotes_develop.md
=> Release notes for 0.8.3

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_components/ktb-services-list/ktb-services-list.component.html, bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html
=> Show approval icon when approval is open

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html, bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.ts, bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html, bridge/client/app/_models/event-icons.ts, bridge/client/app/_models/event-types.ts, bridge/client/app/_models/root.ts, bridge/client/app/_models/service.ts, bridge/client/app/_models/trace.ts, bridge/package-lock.json
Showing remediation actions in environments screen correctly again:
Sequence screens also shows remediation sequences with a error icon and shows the last evaluation results in overview:
=> #3698 Remediation clean up in Bridge

cli/cmd/configure_bridge.go
=> #4135 fix output of bridge URL

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html
=> Omit undefined error when no problem object is defined

releasenotes/releasenotes_V0.8.3.md
Same as with
https://github.com/keptn/examples/pull/172
https://github.com/keptn/examples/pull/173
we need to increase the wait time to 15 minutes.
=> Increase wait time to 15m

bridge/client/app/_models/project.ts
=> #4130 allow non semantic version numbers

shipyard-controller/handler/shipyardcontroller.go, shipyard-controller/handler/shipyardcontroller_test.go, shipyard-controller/models/eventscope.go, shipyard-controller/models/tasksequence.go
Closes #4039
Integration test run: https://github.com/keptn/keptn/actions/runs/874410775
=> #4039 allow to use same task multiple times per sequence

.github/dependabot.yml
=> #4076 changed schedule of dependabot to weekly

.github/actions/spelling/expect.txt, cli/cmd/configure_bridge.go
=> fix configure bridge output when no secret could be fetched

bridge/client/app/_components/ktb-stage-overview/ktb-stage-overview.component.ts
=> Use load traces to show updates in environment screen

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
=> Trigger change detection for heatmap

.github/dependabot.yml
=> Add dependabot schedule for bridge / bridge-server

.github/actions/spelling/expect.txt, bridge/client/app/_components/ktb-deployment-list/ktb-deployment-list.component.html, bridge/client/app/_components/ktb-deployment-stage-timeline/ktb-deployment-stage-timeline.component.html, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_components/ktb-http-loading-bar/ktb-http-loading-bar.component.html, bridge/client/app/_components/ktb-notification-bar/ktb-notification-bar.component.html, bridge/client/app/_components/ktb-project-tile/ktb-project-tile.component.html, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_components/ktb-sequence-tasks-list/ktb-sequence-tasks-list.component.html, bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.html, bridge/client/app/_components/ktb-service-details/ktb-service-details.component.html, bridge/client/app/_components/ktb-services-list/ktb-services-list.component.html, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.html, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.html, bridge/client/app/app-header/app-header.component.html, bridge/client/app/dashboard/dashboard.component.html
=> #4038 added uitestids

.github/actions/spelling/expect.txt, .github/workflows/integration_tests.yml, bridge/.gitignore, bridge/e2e/protractor-ci.conf.js, bridge/e2e/protractor.conf.js, bridge/e2e/src/navigation.e2e-spec.ts, bridge/e2e/src/utils.ts, bridge/package-lock.json, bridge/package.json
#4142 
* Introduced selenium based e2e tests using protractor
* Added an integration test for those e2e tests + adapted test report accordingly
* Added a screenshots folder as an artifact for integration tests
=> #4142 Added protractor based e2e tests

releasenotes/releasenotes_develop.md
=> Empty release notes for develop

bridge/client/app/_components/ktb-deployment-stage-timeline/ktb-deployment-stage-timeline.component.html, bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_components/ktb-event-item/ktb-event-item.component.ts, bridge/client/app/_components/ktb-service-details/ktb-service-details.component.html, bridge/client/app/_components/ktb-service-details/ktb-service-details.component.scss, bridge/client/app/_components/ktb-service-details/ktb-service-details.component.ts, bridge/client/app/_models/deployment-stage.ts, bridge/client/app/_models/deployment.ts, bridge/client/app/_models/project.ts, bridge/client/app/_models/service.ts, bridge/client/app/_services/api.service.ts, bridge/client/app/_services/data.service.ts
=> #4056 #4055 fetch evaluations if the sequence does not have any

bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts
=> #4151 refresh sequence filter

helm-service/chart/values.yaml
=> #4250 Set resource limits/requests for helm-service

bridge/client/app/_services/data.service.ts, bridge/client/app/app-header/app-header.component.ts
=> #4165 Do not load versions.json if ENABLE_VERSION_CHECK is set to false

bridge/client/app/_components/ktb-services-list/ktb-services-list.component.html, bridge/client/app/_components/ktb-services-list/ktb-services-list.component.scss, bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html, bridge/client/app/_models/service.ts, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.html
Closes #4006 
Deployed image name: 
Deployed image version:
=> #4006 improve service image overflow

cli/cmd/generate_support_archive.go, cli/pkg/common/userinput.go, cli/pkg/common/userinput_test.go
Signed-off-by: Hemanth Krishna <hkpdev008@gmail.com>
Fixes #4225 
Potential Fix for #3959 
Results:
=> #4225 fix: askBool cli userInput issue on PowerShell

.github/actions/spelling/expect.txt, installer/manifests/keptn/charts/control-plane/templates/core.yaml
=> #4095 Custom look-and-feel support in Bridge

.github/workflows/integration_tests.yml
**This PR**
* fixes the multiline `if` conditionals in the integration test workflow
=> #3772 fix multiline strings

bridge/client/app/_views/ktb-environment-view/ktb-environment-view.component.html, bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.html, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.html, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.html, bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.html, bridge/client/app/_views/ktb-uniform-view/ktb-uniform-view.component.html, bridge/client/app/app.routing.ts, bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.ts
=> #4022 introduced nested routes for project board

bridge/client/app/_components/ktb-service-details/ktb-service-details.component.ts, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.html, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.ts
=> #4166 reset selected deployment on project change

.github/actions/spelling/expect.txt, distributor/cmd/main.go
=> Distributor: also react on sigterm and sigkill

.github/workflows/integration_tests.yml
**This PR**
* fixes failed integration test issue creation for CI builds
=> #3772 fix source branch for integration tests

secret-service/docs/docs.go, secret-service/docs/swagger.json, secret-service/docs/swagger.yaml, secret-service/main.go, shipyard-controller/docs/docs.go, shipyard-controller/docs/swagger.json, shipyard-controller/docs/swagger.yaml, shipyard-controller/main.go, statistics-service/docs/docs.go, statistics-service/docs/swagger.json, statistics-service/docs/swagger.yaml, statistics-service/main.go
=> Revert "#3423 Switch authentication param to key"

.github/workflows/integration_tests.yml
Fixes #4330  (Manage Secrets was missing)
=> #4330 Fix integration test report

.github/actions/spelling/expect.txt, distributor/cmd/main.go, test/go-tests/kubectl.go, test/go-tests/sequencestate_test.go, test/go-tests/sequencetrigger_test.go, test/go-tests/test_utils.go, test/go-tests/uniform_test.go
=> Added integration test for (un)registering keptn integration

cli/pkg/helm/helm_helper.go
Fixes #3890
I added a check and a proper error message in case an upgrade is still pending.
=> #3890 keptn install: check for pending operations

distributor/cmd/main.go
If the environment variables `K8S_DEPLOYMENT_NAME` , `K8S_NAMESPACE` are not set, then registration will be skipped. 
This ensures that implementations of keptn integration still work as expected even though they just use the newest version of the distributor, without setting additional environment variables to make the registration work...
=> skip registration if not all necessary environment variables are set

bridge/client/app/_components/ktb-sequence-list/ktb-sequence-list.component.ts, bridge/client/app/project-board/project-board.component.html
=> #4388 fixed error on loading sequence

remediation-service/handler/get_action_event_handler.go, remediation-service/handler/get_action_event_handler_test.go, remediation-service/handler/test/remediation-without-default.yaml
=> Remediation: Added fallback to "default" problem type

.github/actions/spelling/expect.txt, bridge/client/app/_components/ktb-create-secret-form/ktb-create-secret-form.component.html, bridge/client/app/_components/ktb-create-secret-form/ktb-create-secret-form.component.scss, bridge/client/app/_components/ktb-create-secret-form/ktb-create-secret-form.component.spec.ts, bridge/client/app/_components/ktb-create-secret-form/ktb-create-secret-form.component.ts, bridge/client/app/_components/ktb-keptn-services-list/ktb-keptn-services-list.component.html, bridge/client/app/_components/ktb-keptn-services-list/ktb-keptn-services-list.component.scss, bridge/client/app/_components/ktb-keptn-services-list/ktb-keptn-services-list.component.ts, bridge/client/app/_components/ktb-secrets-list/ktb-secrets-list.component.html, bridge/client/app/_components/ktb-secrets-list/ktb-secrets-list.component.scss, bridge/client/app/_components/ktb-secrets-list/ktb-secrets-list.component.spec.ts, bridge/client/app/_components/ktb-secrets-list/ktb-secrets-list.component.ts, bridge/client/app/_interceptors/http-error-interceptor.ts, bridge/client/app/_models/secret.ts, bridge/client/app/_services/api.service.ts, bridge/client/app/_services/data.service.ts, bridge/client/app/_views/ktb-uniform-view/ktb-uniform-view.component.html, bridge/client/app/_views/ktb-uniform-view/ktb-uniform-view.component.scss, bridge/client/app/_views/ktb-uniform-view/ktb-uniform-view.component.ts, bridge/client/app/app.module.ts, bridge/client/app/app.routing.ts, bridge/server/app.js
Allow to list, delete and add secrets in Bridge
Closes #4062
=> #4062 Allow to list, delete and add secrets in Bridge

bridge/client/app/_views/ktb-service-view/ktb-service-view.component.ts
=> #4396 fixed reset of selected deployment on project update

bridge/client/app/app.component.spec.ts, bridge/client/app/dashboard/dashboard.component.ts, bridge/tslint.json
=> #4170 regularly update projects in dashboard

releasenotes/releasenotes_develop.md
Part of https://github.com/keptn/keptn/issues/4294
=> Empty release notes

.github/actions/spelling/expect.txt, bridge/server/app.js, bridge/server/package-lock.json, bridge/server/package.json
=> #4257 set x-frame-options to SAMEORIGIN

bridge/client/app/_components/ktb-project-tile/ktb-project-tile.component.ts, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.ts, bridge/client/app/_components/ktb-subscription-item/ktb-subscription-item.component.ts, bridge/client/app/_views/ktb-environment-view/ktb-environment-view.component.ts, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.ts, bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.ts, bridge/client/app/project-board/project-board.component.html, bridge/client/app/project-board/project-board.component.ts
=> #4188 refactoring of observables

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.scss
Fixes #3976 
* Improved hovering
* Improved visibility of selected item
=> Improve sequence selection UX

.github/workflows/integration_tests.yml
**This PR**
* adds a line for who triggered the integration tests in the report
* fixes issue creation step for failing integration tests
Closes #3999
=> #3999 Add github actor to integration test report

bridge/package-lock.json, bridge/package.json, bridge/server/package-lock.json, bridge/server/package.json
=> Fix audits and dependabot update

installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/values.yaml, releasenotes/releasenotes_V0.8.4-hotfix1.md
Backport of https://github.com/keptn/keptn/pull/4481 + release notes
=> Backport of #4481 to 0.8.4-hotfix1

.github/workflows/auto-update-keptn-spec.yml
**This PR**
* corrects the environment variables used in the spec auto update workflow
Fixes #4366
=> #4366 Correct env vars for spec auto update workflow

remediation-service/handler/get_action_event_handler.go
Fixes #4412 
Hey @johannes-b, how does this look?
Let me know if this needs any changes! Thanks
=> Language: Improve error messages for remediation-services

installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/values.yaml, releasenotes/releasenotes_V0.8.5.md
=> #4481 add LOOK_AND_FEEL_URL to helm chart, updated releasenotes

bridge/client/app/_models/trace.ts, bridge/client/app/evaluation-board/evaluation-board.component.html
=> #4384 fallback if configuration change image is not a string

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.scss, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.spec.ts, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_models/trace.ts, bridge/client/app/_services/_mockData/evaluations-top10.mock.ts, bridge/client/app/_services/_mockData/evaluations.mock.ts
=> Show only 10 SLIs with the possiblity to extend heatmap when more are configured

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
=> Show proper dataset for reduced heatmap

bridge/angular.json, bridge/client/app/_components/ktb-markdown/ktb-markdown.component.ts, bridge/package-lock.json, bridge/package.json
=> Bump highlights.js from 10.4.1 to 11.0.1 in bridge

bridge/Dockerfile
**This PR**
* updates the bridge to node v14
* pins the used alpine version to 3.13
Fixes #4578 
=> #4578 upgrade node to v14

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_components/ktb-sequence-list/ktb-sequence-list.component.ts, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.scss, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.spec.ts, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts, bridge/client/app/_models/sli-result.ts, bridge/client/app/_services/_mockData/evaluations.mock.ts
Part of #4305
Collapsed:
Negative change:
Positive change:
=> #4305 Display comparison value and absolute/relative delta of SLI

installer/manifests/keptn/charts/control-plane/templates/_helpers.tpl, installer/manifests/keptn/charts/control-plane/values.yaml
=> Allow to set the metadata for the node and namespace

releasenotes/releasenotes_V0.8.6.md
=> Release notes for release-0.8.6

bridge/client/app/_components/ktb-deployment-list/ktb-deployment-list.component.ts, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_components/ktb-service-details/ktb-service-details.component.ts, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.html, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.ts
=> #4491 fix refresh on polling, #4438 wrong selected stage

bridge/client/app/_models/trace.ts
=> #4392 fixed traces being in the wrong stage

bridge/client/app/_components/ktb-copy-to-clipboard/ktb-copy-to-clipboard.component.html, bridge/client/app/_components/ktb-create-secret-form/ktb-create-secret-form.component.html, bridge/client/app/_components/ktb-deployment-stage-timeline/ktb-deployment-stage-timeline.component.html, bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html, bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html, bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html, bridge/client/app/_models/trace.ts
Closes #3803 
Also fixes traces being in the wrong sequence.
=> #3803 hover text for icon-buttons

bridge/client/app/_models/project.ts, bridge/client/app/_models/service.ts, bridge/client/app/_services/data.service.ts, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.ts, bridge/client/app/project-board/project-board.component.ts
=> #4446, #4521 fixed error on approval if the service has not been updated since creation

bridge/README.md, bridge/server/app.js
=> #4323 throttle auth in bridge

bridge/server/app.ts
=> #4658 wrong http-status-code

bridge/client/app/_components/ktb-services-list/ktb-services-list.component.ts, bridge/client/app/_services/data.service.ts
=> #4667 fix sequences not showing up in environment screen

bridge/package-lock.json, bridge/package.json
=> Fix missing package for e2e tests

installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml
=> increase buffer size on nginx

installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml
Backport of #4663
Thanks to @jskelin <jure.skelin@dynatrace.com> for the original commit
=> Backport of #4663

bridge/server/app.js
Thanks to @Kirdock for the original commit
=> Backport of #4658

bridge/client/app/_components/ktb-keptn-services-list/ktb-keptn-services-list.component.html, bridge/client/app/_components/ktb-uniform-registration-logs/ktb-uniform-registration-logs.component.ts
=> style: Replace error logs string with error events (#4426)

bridge/client/app/_components/ktb-notification-bar/ktb-notification-bar.component.scss, bridge/client/app/_services/data.service.ts, bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.ts, bridge/client/styles.scss, bridge/package-lock.json
=> fix: Improve set Git upstream error / success handling (#4374)

bridge/client/app/_components/ktb-create-secret-form/ktb-create-secret-form.component.html, bridge/client/app/_components/ktb-create-secret-form/ktb-create-secret-form.component.ts, bridge/client/app/_components/ktb-secrets-list/ktb-secrets-list.component.ts, bridge/client/app/_models/secret.spec.ts, bridge/client/app/_models/secret.ts, bridge/package-lock.json
Fixes #4622 
Fixes #4660 
Fixes #4633
=> Bug fixes in secrets view

cli/cmd/set_config.go, cli/pkg/credentialmanager/handler.go
=> fix(cli): Fixed KubeConfigCheck configuration flag (#4553)

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.ts, bridge/client/app/_services/api.service.ts, bridge/client/app/evaluation-board/evaluation-board.component.ts
=> fix(bridge): Fixed empty evaluation-board (#4767)

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.ts, bridge/client/app/_models/sequence.ts
=> fix(bridge): fix error in sequence screen if a sequence does not have any events (#4774)

.github/workflows/integration_tests.yml
- exchanges the tag name for a branch name to make GH CLI happy
=> ci: use branch instead of tag ref for draft release

bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html, bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html, bridge/client/app/_models/trace.ts
=> feat(bridge): show remediation action name (#4410)

bridge/client/app/_services/data.service.ts, bridge/client/app/app-header/app-header.component.ts, bridge/client/app/evaluation-board/evaluation-board.component.ts
=> fix(bridge): set selected project on evaluation page (#4759)

api/Dockerfile, approval-service/Dockerfile, bridge/Dockerfile, configuration-service/Dockerfile, distributor/Dockerfile, docs/debugging.md, helm-service/Dockerfile, installer/airgapped/install_keptn.sh, installer/airgapped/pull_and_retag_images.sh, jmeter-service/Dockerfile, lighthouse-service/Dockerfile, mongodb-datastore/Dockerfile, platform-support/openshift-route-service/Dockerfile, remediation-service/Dockerfile, secret-service/Dockerfile, shipyard-controller/Dockerfile, statistics-service/Dockerfile
- sets alpine to 3.14 explicitely
Follow-up to #4845
=> build(deps): Upgrade alpine to 3.14

cli/cmd/abort.go, cli/cmd/abort_sequence.go, cli/cmd/pause.go, cli/cmd/pause_sequence.go, cli/cmd/resume.go, cli/cmd/resume_sequence.go, cli/cmd/sequencecontrol.go, cli/go.mod, cli/go.sum
this PR contains the implementation for controlling the sequence execution state using the keptn CLI
closes #3785
=> feat(cli): Implemented CLI commands to control the execution state of a sequence (#3785)

bridge/client/app/_components/ktb-project-settings-git/ktb-project-settings-git.component.spec.ts, bridge/client/app/_components/ktb-project-settings-git/ktb-project-settings-git.component.ts, bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.ts
=> fix(bridge): Trigger change detection to show proper git settings on project change (#4781)
