bridge/client/app/_components/ktb-stage-overview/ktb-stage-overview.component.html
bridge/client/app/_components/ktb-stage-overview/ktb-stage-overview.component.scss

Closes #4146 
When only 3 tiles are available the size of the tiles is adapted so that all of them fit on the screen:
When more than 3 tiles are available in the row, the panel size is reduced to show that it can be scrolled:

Improve tile width for environment screen

---

shipyard-controller/db/mongodb_staterepo.go
shipyard-controller/db/mongodb_staterepo_test.go
shipyard-controller/docs/docs.go
shipyard-controller/docs/swagger.json
shipyard-controller/docs/swagger.yaml
shipyard-controller/handler/sequence_migrator.go
shipyard-controller/handler/sequencehooks/sequencestate.go
shipyard-controller/handler/statehandler.go
shipyard-controller/handler/statehandler_test.go
shipyard-controller/models/state.go

closes #4433 
I've introduced an additional query parameter go fetch sequence enpoints by keptn context.
Note, that I've named the paramter `keptnContext` instead of `shkeptncontext`.
I would also propose to switch to just `keptnContext` in other places as well.
This needs to be backwards compatible, though.
Please comment your opinion on that.

Added keptnContext query parameter to sequence state GET endpoint

---

helm-service/pkg/helm/generated_chart_handler.go
helm-service/pkg/helm/helm_mock_executor.go

See related issue #4540 - this adds the `-primary` suffix for the labeled service to be consistent with the modifications of the pod labels. This won't change any behavior within the Kubernetes cluster, the labels are usually not referenced in ServiceMesh components.
Signed-off-by: Tolleiv Nietsch <github@tolleiv.de>

#4540 Helm-Service Adjust primary service labels for more consistency

---

installer/manifests/keptn/charts/control-plane/templates/_helpers.tpl
releasenotes/releasenotes_V0.8.6.md

* Changes that were made on the release-0.8.6 branch: (`value: .Values.distributor.metadata.namespace` --> `value: {{ .Values.distributor.metadata.namespace }}` )
are merged into master. 
* Including the release notes for 0.8.6. 
After merging, this PR https://github.com/keptn/keptn/pull/4607 can be closed. 

Merge changes from release-086 to master

---

distributor/cmd/main.go
distributor/pkg/config/envconfig.go
distributor/pkg/config/envconfig_test.go
distributor/pkg/lib/events/receiver.go

fixes #4516
I was not able to try it out on a cluster with enabled TLS.
Review carefully.

Distributor: using scheme from `KEPTN_API_ENDPOINT` environment variable for uniform api

---

codecov.yml

**This PR**
* reduces the sections in the PR comment from codecov. Now only the diff and impacted files show up and the heatmap and flags table are ommitted.

chore: Reduce amount of overhead in codecov report comment

---

cli/cmd/set_config.go
cli/pkg/credentialmanager/handler.go

fixes #4553 
With this PR without having a`~/.kube/config` file, the CLI behaves as follows.
**`KubeContextCheck` enabled (default)**
```
$ ~ ./keptn set config KubeContextCheck true
$ ~ ./keptn get project
Warning: could not parse KUBECONFIG file: Cannot find file /home/bernd/.kube/config
Hint: If you don't have 'kubectl' installed you can disable this check via 'keptn-local set config KubeContextCheck false'
NAME			CREATION DATE			SHIPYARD VERSION
...
```
**`KubeCOntextCheck` disabled**
```
$ ~ ./keptn set config KubeContextCheck false
$ ~ ./keptn get project
NAME			CREATION DATE			SHIPYARD VERSION
...
```
**`--help` text**
```
$ ~ keptn set config --help
Sets flags of the CLI configuration, which is stored in $HOME/.keptn/config.
This command takes a key and a new value as arguments …
```

fix(cli): Fixed `KubeConfigCheck` configuration flag

---

.github/pull_request_template.md
.github/semantic.yml
CONTRIBUTING.md

* adds a PR template
* adds the configuration for the [semantic PR GitHub action](https://github.com/zeke/semantic-pull-requests)
* adds new sections to the contribution guidelines with the updates naming schemes for commits, branches and PRs
Related to #4585

chore: Add PR template, semantic PR config file, update contribution guidelines (#4585)

---

.github/workflows/send-event-on-release-push.yml

**This PR**
* adds a workflow that sends an event to the keptn docs repo so that the CLI docs can be generated automatically.

ci: Add workflow to auto generate CLI docs (#2927)

---

.github/workflows/integration_tests.yml

- changes the integration test pipeline so that a GH draft release is always published regardless of the integration test results

ci: Publish draft release without integration tests

---

approval-service/pkg/handler/approval_triggered_event_handler.go
approval-service/pkg/handler/approval_triggered_event_handler_test.go
approval-service/pkg/handler/handler.go
bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html
bridge/client/app/_models/sequence.ts
bridge/client/app/_models/trace.ts
bridge/client/app/_services/data.service.ts
cli/cmd/send_event_approvalFinished.go
test/go-tests/deliveryassistant_test.go

fix(approval-service): skip timeout for manual approvements (#4620)

---

.github/dependabot.yml
.github/semantic.yml

- changes the dependabot config so that conventional commit messages are followed

build: Update dependabot configuration to follow new commit message scheme

---

.github/workflows/CI.yml

- fixes the CI pipeline when building master on push

ci: Fix bug where CI pipeline does not build all docker images on push to master (#4825)

---

.github/workflows/CI.yml

- fixes a bug where the docker image version in the helm chart and on dockerhub were not the same resulting in fails to pull docker images from dockerhub

ci: Fix bug where docker image and helm chart version datetime were not the same

---

.github/semantic.yml

- adds `deps-dev` to the semantic PR allowed scopes. Dependabot uses this scope for npm dev dependencies

ci: Update semantic PR config to take dev deps from npm into account

---

cli/cmd/install.go

Signed-off-by: Jimil Desai <jimildesai42@gmail.com>
- Allows users to install Keptn from a draft release by pointing to a chart repo on the local filesystem, eg:
```
download keptn-installer-0.8.4-dev.tgz # download or build helm charts
keptn install --chart-repo=./dist/keptn-installer-0.8.4-dev.tgz
```
Fixes #4325 
1. Download Keptn
2. Install Keptn by pointing to chart repo in the local filesystem: `keptn install --chart-repo=./keptn-0.8.7.tgz`

feat(cli): allow to specify local directory as a chart-path

---

api/middleware/ratelimiter.go
api/middleware/ratelimiter_test.go
api/middleware/tokenauth.go

- Changes the logic of the `/auth` endpoint's rate limiter to be applied before any token validation is done.
- If the incoming API token is valid, this will reset the limiter in order to prevent subsequent valid requests to be throttled
- With this logic, the caller of the API cannot automatically assume that the provided token was invalid when receiving a HTTP 429 (Too many requests) response since now also a request with a valid token can be throttled if there were too many invalid requests before.
Closes #4906

fix(api): Apply rate limiter before token is validated (#4906)

---

bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html

fix(bridge): moved 'View evaluation button' to the next row (#4760)

---

bridge/client/app/_components/ktb-expandable-tile/ktb-expandable-tile.component.html
bridge/client/app/_components/ktb-expandable-tile/ktb-expandable-tile.component.scss
bridge/client/app/_components/ktb-expandable-tile/ktb-expandable-tile.component.spec.ts
bridge/client/app/_components/ktb-expandable-tile/ktb-expandable-tile.component.ts
bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html
bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html
bridge/client/app/_views/ktb-service-view/ktb-service-view.component.html

- allows to set expandable tile as disabled, which will prevent the user to expand an empty tile
- sets all expandable tiles (environments screen, service screen and sequence screen) to disabled if empty
Closes #4057

feat(bridge): Prevent expanding empty tile (#4057)

---

helm-service/chart/templates/deployment.yaml

The continuous delivery integration tests were failing because the helm-service pod was restarting during the execution of the test. This PR should validate whether a recent decrease of the resource limits was the reason for that.
Update: with the memory limit set to 128Mi, the helm service runs into an OOM error when multiple deployments are happening at once:
```
│   helm-service:                                                                                                                                                                       │
│     Container ID:   docker://3de064bb154dbb30d2adc38c66ea6655a3072939ae7b222ce0972f586f2e5d90                                                                                         │
│     Image: …
```

fix(helm-service): increase resource limits for helm-service (#4935)

---

bridge/client/app/_components/ktb-project-settings-git/ktb-project-settings-git.component.html
bridge/client/app/_components/ktb-project-settings-git/ktb-project-settings-git.component.ts
bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.html
bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.scss
bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.spec.ts
bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.ts
bridge/client/styles.scss
bridge/package-lock.json

Closes #4677 
For create project, there will be no notification.
In the settings, when the git form is set to valid, the user now gets a notification that there are pending changes. In this notification, he/she has the option to save or discard the changes. As the notification would overlay the delete section, the delete section is now moved above the notification.

feat(bridge): Show dialog when settings / create project is changed (#4677)

---

.github/workflows/CI.yml

- fixes the macOS CLI builds by using the correct platform handle
Proof: https://github.com/keptn/keptn/runs/3358147973?check_suite_focus=true

ci: fix macOS builds

---

.github/workflows/CI.yml
.github/workflows/integration_tests.yml

- fixes a small bug where the pipeline could not find the last successful run ID on master if the run was more than 30 runs ago

ci: fix Run ID bug in GH actions pipelines

---

.github/workflows/CI.yml
README.md
api/Dockerfile
approval-service/Dockerfile
bridge/Dockerfile
configuration-service/Dockerfile
distributor/Dockerfile
helm-service/Dockerfile
jmeter-service/Dockerfile
lighthouse-service/Dockerfile
mongodb-datastore/Dockerfile
platform-support/openshift-route-service/Dockerfile
remediation-service/Dockerfile
secret-service/Dockerfile
shipyard-controller/Dockerfile
statistics-service/Dockerfile

- introduces 2 additional container registries for releases (GH container registry, quay.io)
- release images are pushed to the new registries as well
- adds a readme paragraph to describe the new feature
- adds OCI labels to all dockerfiles
Closes #3314 
Previous release images were pushed by hand starting from version `0.8.0`.
They can be found on [quay.io](https://quay.io/organization/keptn) and [GHCR](https://github.com/orgs/keptn/packages?repo_name=keptn)

feat: Release images are now also on quay.io and ghcr.io (#3314)

---

CONTRIBUTING.md
bridge/IntelliJ.xml
bridge/README.md
bridge/settings.json

Closes #4739
Adds documentation and setting files for IntelliJ and Visual Studio code on how to set up the IDE.

docs(bridge): Add documentation and settings for IntelliJ and VSCode(#4739)

---

bridge/tslint.json

Adds a linting rule to enforce return types for functions.

style(bridge): added linting rule for return types

---

cli/cmd/configure_bridge.go
cli/cmd/configure_bridge_test.go

Closes #4435 
This PR prints the commands needed for reading or updating the login credentials for the bridge

feat(cli): Adapt output for configure bridge command (#4435)

---

jmeter-service/README.md

docs(jmeter-service): remove deprecated link to a tutorial

---

bridge/client/app/_components/ktb-modify-uniform-subscription/ktb-modify-uniform-subscription.component.html
bridge/client/app/_components/ktb-modify-uniform-subscription/ktb-modify-uniform-subscription.component.spec.ts
bridge/client/app/_components/ktb-modify-uniform-subscription/ktb-modify-uniform-subscription.component.ts
bridge/client/app/_models/uniform-registrations.mock.ts
bridge/client/app/_services/api.service.ts
bridge/client/app/_services/data.service.ts
bridge/server/api/index.ts
bridge/server/services/api-service.ts
bridge/server/services/data-service.ts
bridge/shared/interfaces/uniform-registration-locations.ts

- Adds default tasks `evaluation` and `test`.
- Limits task suffixes to `triggered` if the uniform registration is not in the control-plane.

chore(bridge): added default task 'evaluation', set task suffixes to available ones

---

mongodb-datastore/handlers/events.go

Signed-off-by: Andreas Grimmer <andreas.grimmer@dynatrace.com>
corrects the log level to info for print messages that a root event already exists in the database.

fix: Correct log level for storing root events

---

shipyard-controller/handler/sequence_migrator.go

fix(shipyard-controller): Avoid endless loop (#5096)

---

shipyard-controller/handler/error.go
shipyard-controller/handler/eventhandler.go
shipyard-controller/handler/eventhandler_test.go
shipyard-controller/handler/projecthandler.go
shipyard-controller/handler/projecthandler_test.go
shipyard-controller/handler/projectmanager.go
shipyard-controller/handler/projectmanager_test.go
shipyard-controller/handler/servicehandler.go
shipyard-controller/handler/servicehandler_test.go
shipyard-controller/handler/servicemanager.go
shipyard-controller/handler/shipyardcontroller.go
shipyard-controller/handler/shipyardcontroller_test.go
shipyard-controller/handler/stagehandler.go
shipyard-controller/handler/stagehandler_test.go
shipyard-controller/handler/stagemanager.go
shipyard-controller/handler/stagemanager_test.go

Closes #5132
This PR introduces the following behavior:
Instead of returning a 500 error code when no available .triggered events for a particular project are found, now either a 200 response with an empty result set ist returned, if the project is available. If a query for a non-existing project is sent, a 404 response with the message that the project could not be found is sent.

fix(shipyard-controller): Adapted HTTP status codes of GET /event endpoint (#5132)

---

configuration-service/common/common.go
configuration-service/handlers/project.go
configuration-service/handlers/project_resource.go
configuration-service/handlers/service.go
configuration-service/handlers/service_default_resource.go
configuration-service/handlers/service_resource.go
configuration-service/handlers/stage.go
configuration-service/handlers/stage_resource.go
configuration-service/restapi/embedded_spec.go
configuration-service/restapi/operations/service_default_resource/put_project_project_name_service_service_name_resource_resource_uri_parameters.go
configuration-service/swagger.yaml

Closes #5136
Note: The code of the configuration service in general needs some refactoring - hence the relatively high number of Sonar Code smells (most of them are about multiple occurrences for various string literals that are used for logging, so nothing critical). The refactoring should be done in a separate issue.

fix(configuration-service): Implemented endpoints for deleting service and stage resources (#5136)

---

.github/ISSUE_TEMPLATE/bug_report.md

docs: add disclamer to avoid security vulnerabilities to be reported as bugs

---

installer/manifests/keptn/charts/control-plane/charts/mongodb/templates/deployment.yaml
installer/manifests/keptn/charts/control-plane/templates/mongodb-datastore.yaml

Signed-off-by: Andreas Grimmer <andreas.grimmer@dynatrace.com>
Fixes #5196
This PR increases the memory limits of the mongodb and mongodb-datastore based on monitoring data.

fix: Increase memory limits for mongodb-datastore and mongodb (#5196)

---

distributor/pkg/lib/controlplane/uniformlog.go
distributor/pkg/lib/controlplane/uniformlog_test.go

fix(distributor): Only interpret events with status=errored as error logs (#5170)

---

shipyard-controller/handler/sequencedispatcher.go

fix(shipyard-controller): Adapted log output when no queued sequence is found (#5138)

---

configuration-service/handlers/project.go
shipyard-controller/handler/projectmanager.go
shipyard-controller/handler/projectmanager_test.go

fix: Fall back to previous git credentials when updating upstream fails (#5064)

---

.github/semantic.yml

fix: Use correct artifact name for mongodb-datastore in semantic PR setup

---

cli/cmd/root.go
cli/cmd/root_test.go

- skips version check on `keptn install`
Fixes #3158
1. Run `keptn install` locally without a cluster running. You should not see a `Warning` message like [this](https://user-images.githubusercontent.com/31009634/106847806-ace9c200-66d5-11eb-96c8-1b3a5540de79.png).
2. Run any other command like `keptn auth` or `keptn uninstall` without a cluster running and you should see a `Warning` message like [this](https://user-images.githubusercontent.com/31009634/106847806-ace9c200-66d5-11eb-96c8-1b3a5540de79.png).

fix(cli): skip version check on install

---

cli/cmd/install.go
cli/cmd/upgrade.go
cli/pkg/credentialmanager/fake/credential_manager_mock.go
cli/pkg/credentialmanager/handler.go
cli/pkg/credentialmanager/handler_darwin.go
cli/pkg/credentialmanager/handler_linux.go
cli/pkg/credentialmanager/handler_windows.go
cli/pkg/platform/platform_manager.go
cli/pkg/platform/platform_manager_test.go

Closes #4583
This PR adds a check whether the current Kubectl context matches the current Keptn CLI context before starting with the execution of the helm chart upgrade. If those contexts do not match, the upgrade will not be performed. 
Follow up tasks: The CLI needs some refactoring as it is currently really hard to add any unit tests. Some work has already been done for making the `install` command more testable by introducing a struct that handles the install command and provides the means to inject its dependencies. A similar approach should be done for the `upgrade` command.
Also, the `CredentialManager` stuff that checks for context changes in the kubectl CLI and the current Keptn context is hard to maintain and to understand (relies heavily on global state, effects of functions on …

fix(cli): Check if kubectl context matches Keptn CLI context before applying upgrade (#4583)

---

.github/workflows/integration_tests.yml
shipyard-controller/handler/sequence_migrator.go
shipyard-controller/handler/sequence_migrator_test.go
shipyard-controller/handler/shipyardcontroller.go
shipyard-controller/handler/shipyardcontroller_test.go
test/go-tests/go.sum
test/go-tests/sequencestate_test.go

Closes #5137
This PR makes sure that event when a sequence cannot be started by a `<sequence>.triggered` event, the state of the failed attempt is properly reflected and can be displayed by the bridge.
The following scenarios have been handled and are covered by integration tests:
- Shipyard file could not be retrieved
- Shipyard could be retrieved, but does not have the correct version
- Valid Shipyard is available, but no matching sequence definition found
In these cases, a sequence state will be created and immediately be set to `finished`, and the `lastFailedEvent` property will be set, so the bridge can display it as a failed sequence. The resulting `<sequence>.finished` event then contains information about why it has failed in the `data.message` property.

fix(shipyard-controller): Adapted sequence state representation for case where sequence can not be started (#5137)

---

jmeter-service/main.go
jmeter-service/main_test.go

If a valid parsed deployment url has an empty path add '/' to it, added corresponding one line in the unit test to check this 
Fixes #3612

fix(jmeter-service): prevent failure if deploymentURIs does not end with a '/'(#3612)

---

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.ts
bridge/client/app/_services/data.service.mock.ts
bridge/client/app/_services/data.service.ts
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.html
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts

Fixes #5085
This also changes the `sequence` `BehaviorSubject` to `Subject` in order to reduce redundancy and just emit update notifications.

fix(bridge): fixed missing update on sequence screen (#5085)

---

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html
bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.html
bridge/client/app/_models/sequence.ts
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.html
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts
bridge/client/app/app.module.ts
bridge/shared/models/sequence.ts

- makes sure that the abort/resume/pause buttons are disabled correctly in case sequence is timedOut
- notifies the user about waiting status in case other sequences are blocking the execution
I could not reproduce the issue with grouping sequence tasks, which feels actually like a bug in the shipyard-controller.
But I reported another bug to the shipyard-controller, see #5259.
Fixes #5154

fix(bridge): grouping sequence after pause #5154

---

bridge/client/app/_services/api.service.ts
bridge/server/api/index.ts
bridge/server/services/api-service.ts
bridge/server/services/data-service.ts
bridge/shared/interfaces/event-result.ts

- makes sure that all traces of a sequence are loaded without pageSize limit
Fixes #5056

fix(bridge): load sequence with more than 100 events correctly #5056

---

cli/cmd/send_event_evaluationStart_test.go
cli/cmd/trigger_evaluation.go
cli/cmd/trigger_evaluation_test.go
shipyard-controller/handler/evaluationmanager.go
shipyard-controller/handler/evaluationmanager_test.go

Checked that all calls to our timeutils uses time.Now().UTC() or that the time constant passed has zones
Changed a couple of those when missing
Fixed CLI and Shipyard controller tests 
Fixes #4788

fix(cli): added zones to times format according to (ISO8601) (#4788)

---

cli/go.mod
cli/go.sum
configuration-service/go.mod
configuration-service/go.sum
gh-actions-scripts/auto-update-utils.sh
helm-service/go.mod
helm-service/go.sum
platform-support/openshift-route-service/go.mod
platform-support/openshift-route-service/go.sum
test/go-tests/go.mod
test/go-tests/go.sum

* updates `go-utils` and `kubernetes-utils` after the history change that happened due to release automation being enabled now

build(deps): Update go-utils and kubernetes-utils after history change

---

installer/manifests/keptn/charts/control-plane/templates/ingress.yaml
installer/manifests/keptn/charts/control-plane/values.yaml

Signed-off-by: bradmccoydev <bradmccoydev@gmail.com>
This PR is to add the ability to optionally add an ingress of the Keptn Deployment when using the helm chart. 
- add ingress.yaml
- update values file with enabled:false as default
https://github.com/keptn/keptn/issues/5066
Fixes #5066 
Documentation: https://github.com/keptn/keptn/issues/5297
This has been tested in different clusters and scenarios and i confirm it works.
helm install control-plane --generate-name --dry-run --debug
```
ingress:
enabled: true
annotations: {}
host:
[]
path: /
pathType: Prefix
tls:
[]
---
null
---
ingress:
enabled: true
annotations: {}
host:
[]
path: /
pathType: Prefix
tls:
[]
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: ingress
labels:
app.kubernetes.io/name: ingress …
```

feat(installer): Add option for ingress to control-plane helm chart keptn installer (#5066)

---

bridge/client/app/_interceptors/http-error-interceptor.ts
bridge/client/app/_interceptors/http-generic-retry-strategy.ts

- adapts the retry mechanism for HTTP calls to only retry if they are one of the following status codes: 500, 502, 503, 504
Closes #4867 

chore(bridge): adapt retry-mechanism (#4867)

---

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html
bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.ts
bridge/client/app/_components/ktb-sequence-state-info/ktb-sequence-state-info.component.html
bridge/client/app/_components/ktb-sequence-state-info/ktb-sequence-state-info.component.scss
bridge/client/app/_components/ktb-sequence-state-info/ktb-sequence-state-info.component.spec.ts
bridge/client/app/_components/ktb-sequence-state-info/ktb-sequence-state-info.component.ts
bridge/client/app/_components/ktb-sequence-state-list/ktb-sequence-state-list.component.html
bridge/client/app/_components/ktb-sequence-state-list/ktb-sequence-state-list.component.ts
bridge/client/app/_models/sequence.ts
bridge/client/app/app.module.ts
bridge/client/styles.scss

- introduces a component that displays sequence state info the same way across multiple screens
Fixes #5150 
Dashboard:
Sequence Screen:

feat(bridge): Align the way how sequence states are displayed #5150

---

distributor/pkg/lib/events/forwarder.go
distributor/pkg/lib/events/forwarder_test.go

Closes #5402 
This PR fixes a go routine leak in `forwarder.go`

fix(distributor): Fixed leaking go routines in `distributor::forwarder.go`

---

shipyard-controller/handler/sequencewatcher.go

The log output of the sequence watcher was getting too verbose when too many events with a time stamp that does not match the default time format are available. To reduce the noise in the logs, an error is now only logged if the timestamp can not be logged at all.

fix(shipyard-controller): Reduce log noise for sequence watcher component

---

bridge/client/app/_components/ktb-create-secret-form/ktb-create-secret-form.component.html
bridge/client/app/_components/ktb-create-secret-form/ktb-create-secret-form.component.scss
bridge/client/app/_components/ktb-create-secret-form/ktb-create-secret-form.component.spec.ts
bridge/client/app/_components/ktb-create-secret-form/ktb-create-secret-form.component.ts
bridge/client/app/_models/secret.ts
bridge/shared/interfaces/secret-scope.ts

- adds a dropdown to select a scope while creating a secret
Fixes #5269 

feat(bridge): Allow to create secret with scope selection #5269

---

bridge/package-lock.json
bridge/server/user/session.ts
installer/manifests/keptn/charts/control-plane/templates/core.yaml
installer/manifests/keptn/charts/control-plane/values.yaml

Fixes #5449
PR improves the configurability of OAuth session cookie timeout. Further, it increases the default timeout to 60mnts in code level.
Installer argument `SESSION_TIMEOUT_MS` is set in Helm template.
#3448
If #3448 fulfilling OAuth provider is present for Bridge, this can be tested easily.  Timeout can be configured by using env. variable `SESSION_TIMEOUT_MS`, then validate the console output for correct value extraction and verify session timeouts in Bridge. 
Note - refactored method signatures in `session.ts` to improve code quality.

feat(bridge): Make session cookie timeout configurable and set default value to 60 minutes

---

.github/dependabot.yml

* disable auto-rebasing for dependabot since it overwhelms our CI pipeline

ci: Disable auto rebasing for dependabot

---

.github/workflows/dependencies-and-licenses.yml

chore: This PR adds the two modules `gosdk` and `webhook-service` to the dependencies&licenses check

chore: Added go-sdk and webhook-service to dependencies-and-licenses check

---

distributor/pkg/lib/events/receiver_test.go

This PR reduces the chance of failing distributor unit tests due to a race condition between the test and implementation code.

chore: Mitigating racecondition in unit tests

---

bridge/cypress/fixtures/bridgeInfo.mock.json
bridge/cypress/fixtures/get.approval.json
bridge/cypress/fixtures/get.approval.testproj.json
bridge/cypress/fixtures/get.uniform.json
bridge/cypress/fixtures/multi.projects.mock.json
bridge/cypress/integration/navigation-buttons-evaluation-screen-test.ts
bridge/cypress/integration/page-data-update-project-switch.spec.ts
bridge/cypress/integration/project-delete.spec.ts
bridge/cypress/integration/uniform-integrations.spec.ts
bridge/cypress/support/pageobjects/BasePage.ts
bridge/cypress/support/pageobjects/EnvironmentPage.ts
bridge/cypress/support/pageobjects/ServicesPage.ts
bridge/cypress/support/pageobjects/SettingsPage.ts
bridge/cypress/support/pageobjects/UniformPage.ts

in scope of this PR:
1. added test case to verify data among pages based on project change - page-data-update-project-switch.spec.ts.
2. made improvements in support/commands.ts
3. improved bridge/cypress/integration/uniform-integrations.spec.ts to store locators in page object classes as constants

test: added test case to verify data among pages based on project change and refactoring of other tests

---

installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml
lighthouse-service/event_handler/configure_monitoring_handler.go
lighthouse-service/event_handler/configure_monitoring_handler_test.go
lighthouse-service/event_handler/evaluate_sli_handler.go
lighthouse-service/event_handler/evaluate_sli_handler_test.go
lighthouse-service/event_handler/handler.go
lighthouse-service/event_handler/start_evaluation_handler.go
lighthouse-service/event_handler/start_evaluation_handler_test.go
lighthouse-service/main.go

- adds context with cancel to all handlers
- pass a wait group via context 
- uses the wait group to to ensure the service terminates before shutdown
- introduces a pre-stop hook to the distributor to delay its shutdown so that the service can communicate 
- adjust the graceperiod of the pod
Fixes #5304 
This can be replicated in most services,  pre-stophook does not add downtime: Pods that shut down slowly cannot continue to serve traffic as load balancers (like the service proxy) remove the Pod from the list of endpoints as soon as the termination grace period begins, that is contemporary to the start of the pre-stophook. 
This ensure the services will stop receiving traffic and thus events as soon as the SIGTERM is sent independently …

feat(lighthouse-service): Added SIGTERM for lighthouse handlers (#5304)

---

installer/airgapped/install_keptn.sh

- fixes a small bug where the airgapped installer had a double slash in the MongoDB image name after setting up a private registry
Fixes #5938

fix: Fixed bug where MongoDB would not come up in airgapped setup

---

test/go-tests/init_test.go
test/go-tests/sequencetrigger_test.go

chore: Cancel integration tests when mismatch between CLI and kube context is detected (#5743)

---

.github/workflows/CI.yml

- changes the behaviour of the CI pipeline so that it builds all docker images if the `build-everything` tag is present on the PR at hand

ci: Build everything builds should always build everything

---

bridge/server/app.ts

As described in the [Express](https://expressjs.com/en/advanced/best-practice-security.html) documentation, helmet is one of the best choices to prevent XSS. I did a small research of the headers that are set when calling `app.use(helmet());` and chose the ones that make most sense for Keptn Bridge.
A detailed description of which headers are set can be found in the helmetjs [docs](https://helmetjs.github.io/).
```
app.use(helmet.contentSecurityPolicy());
app.use(helmet.hidePoweredBy());
app.use(helmet.noSniff());
app.use(helmet.permittedCrossDomainPolicies());
app.use(helmet.referrerPolicy());
app.use(helmet.frameguard());
app.use(helmet.xssFilter());
```

fix(bridge): Use helmet middlewares to prevent XSS

---

api/restapi/embedded_spec.go
api/swagger.yaml

-  since Swagger does not support OpenAPiI 3.0 changed  type [" object" , " string "] to  type object 
Fixes #5948

fix(api): Remove multiple types in event model (#5948)

---

mongodb-datastore/go.mod
mongodb-datastore/go.sum

Closes #5968
The previous version of the go-utils that was imported by the mongodb-datastore was still using the `MONGO_DB_NAME` env var to determine the name of the mongodb database. This has recently been changed to `MONGODB_NAME` and therefore the go-utils needed to be upgraded to the latest version to account for that.

chore: Updated go-utils dependency in mongodb-datastore (#5968)

---

shipyard-controller/common/keptn_helpers.go
shipyard-controller/common/keptn_helpers_test.go
shipyard-controller/db/mongodb_project_mv_repo.go
shipyard-controller/handler/sequence_migrator.go
shipyard-controller/handler/sequencehooks/sequencestate.go

Closes #5979
Note: The problem described in #5979 that prevented the delivery sequence was caused by a misconfiguration of the remote-exec plane helm-service. However, the missing `configurationChange` property should not be interpreted as an error since `deployment.triggered` events do not have the strict requirement of having this property.

chore(shipyard-controller): Do not interpret absence of configurationChange property as an error (#5979)

---

cli/cmd/auth.go
cli/cmd/configure_monitoring.go
cli/cmd/create_project.go
cli/cmd/delete_project.go
cli/cmd/install.go
cli/cmd/uninstall.go
cli/cmd/update_project.go
cli/cmd/upgrade.go
cli/cmd/upgrade_project.go
cli/cmd/version.go
cli/main.go
make-scripts/build/build-cli.sh

Closes #5762
The reason why the keptnReleaseDocsURL was not set properly was the order of the initialization within the cli project:
The commands, including their description including the `keptnReleaseNotesURL` are located in the `cmd` subpackage and are therefore initialized before the `main` package, where the `Version` property was set using the ldflags.

fix(cli): Make sure the release version is set in command descriptions (#5762)

---

test/go-tests/webhook_test.go
webhook-service/handler/handler.go
webhook-service/handler/handler_test.go

Closes #5954 
This fixes a problem that caused the webhook service to respond with <task>.finished.finished or <task>.started.finished events when the webhook execution failed

fix(webhook-service): Avoid .finished.finished/.started.finished events (#5954)

---

.github/workflows/CI.yml

- removes the docker cache steps from the CI pipeline since they cause more errors and pains than they serve their purpose

ci: Remove docker cache because of pipeline errors

---

configuration-service/common/common.go
configuration-service/deploy/service.yaml
configuration-service/handlers/service_resource.go

…g resources to services
- fixes bad order of extracting and adding resources to services
-  follow-up task: https://github.com/keptn/keptn/issues/6035
Fixes #5975
This issue is caused only by bad order of the actions when adding new resources to the service. Currently, by looping through the (helm) resource(s), the code actually adds the resource to the git repository and then tries to extract it. From my POV, we should first extract the file and check if it is valid and if yes, then add it to the repository.

fix(configuration-service): changed bad order of extracting and adding resources to services (#5975)

---

bridge/client/index.html
bridge/package.json
bridge/server/app.ts

I removed the script that caused the page to load entirely and replaced it with the `--base-url` argument for the `yarn build` script. Also I removed the `upgrade-insecure-requests` header part of the CSP header in order to not cause switching requests from http to https - which causes `ERR_CONNECTION_REFUSED` errors on the client.

fix(bridge): Remove inline script for base url and upgrade-insecure-requests header part

---

.github/workflows/CI.yml
bridge/Dockerfile

- fixes a regression where the UI test screenshots from cypress were not attached to CI pipeline runs anymore
Fixes #5897 
Here is a proof that this PR works: https://github.com/keptn/keptn/actions/runs/1475503194

test(bridge): Fix bug where UI test screenshots were not attached to CI runs anymore

---

jmeter-service/Dockerfile

This PR bumps the jmeter version to **v5.4.1**
closes #6031 
Integration Test Run: https://github.com/keptn/keptn/actions/runs/1471910850

chore(jmeter-service): bump version of jmeter binary to 5.4.1

---

shipyard-controller/handler/sequencedispatcher.go

The message indicating that a sequence is currently blocked was logged with an `error` level, which should not be the case. Changed it to `info` instead

chore(shipyard-controller): Adapted log level

---

distributor/cmd/main.go
distributor/pkg/config/envconfig.go
distributor/pkg/lib/controlplane/uniformlog.go
distributor/pkg/lib/events/forwarder.go
distributor/pkg/lib/events/nats_connection_handler.go
distributor/pkg/lib/events/poller.go
distributor/pkg/lib/events/receiver.go
distributor/pkg/lib/events/uniformwatch.go
distributor/pkg/lib/events/utils.go

closes #6007 
This PR contains:
* cleaned up logging
* detangling of weird Forwarder::Start logic with graceful shutdown
Integration Test Run: https://github.com/keptn/keptn/actions/runs/1471867743

fix(distributor): Sanitized logs and cleaned up forwarder lifecycle

---

cli/cmd/auth.go
cli/cmd/auth_test.go

- fixes problem with missing http(s):// in --endpoint during `keptn auth`
Fixes #6013

fix(cli): problem with missing http(s) in endpoint flag during keptn auth

---

distributor/cmd/main.go
distributor/pkg/lib/events/receiver.go
distributor/pkg/lib/events/receiver_test.go
test/go-tests/uniform_test.go

Closes #6074
This PR also updates the `uniform_registration` integration test to make sure the `echo-service` is using the same `distributor` image as the installed version of Keptn

fix(distributor): Fix message filtering in distributor (#6074)

---

cli/cmd/upgrade.go

- creates user warning about changed database model when upgrading to keptn 0.11.*
Fixes #6070

feat(cli): created user warning about changed database model in keptn 0.11.*

---

.github/workflows/integration_tests.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml

- moves the helm chart upload step from the integration test pipeline to the new release pipelines where the charts are now built and uploaded from
Fixes #6149

ci: Upload release helm charts from release pipelines instead of integration tests pipeline

---

.github/workflows/CI.yml

This PR adds a condition for bot triggered builds to the docker login and docker build steps in the CI pipelines.
This change ensures that builds that were triggered by dependabot or the renovate bot still pass and become green automatically.
Fixes #5521

ci: Pass bot triggered builds by not pushing docker images

---

bridge/client/index.html
bridge/package.json
bridge/server/app.ts

* The X-Powered-By header removal from helmetjs should not be used when using express, as stated in the docs. I moved the removal by `app.disable` to the configurations for the other headers to have it in one place.
* I also re-added the functionality for the inline script to execute the redirect, as route `/bridge` (without ending slash) will not work otherwise. I therefore added the script hash to Content-Security-Policy header to ensure it can be executed.
* Logging was not correctly returning the 401 response so that the server returned a 500 error
Fixes #6150

fix(bridge): Fix problem with redirect and headers on cluster

---

test/go-tests/uniform_test.go
test/go-tests/webhook_test.go

Closes #6171 
The problem was likely caused by a race condition during the update of several properties of the `echo-service` deployment.
Additionally, the PR fixes a misleading log message in the webhook integration test
Integration test run: https://github.com/keptn/keptn/actions/runs/1502776018

fix: Fix uniform integration test (#6171)

---

.github/workflows/pre-release.yml
.github/workflows/release.yml

- fixes a bug where the release pipeline would fail because the branch protection rules were not correctly disabled for non-default branches

ci: Fix bug where release cannot be pushed to protected maintenance branch

---

.github/renovate.json

- adds labels to the different package ecosystems that are tracked by Renovate. This makes renovate PRs easier to sort and filter

ci: Add more descriptive labels to renovate PRs

---

.github/renovate.json

- fixes a config bug in the renovate config where the wrong package manager name was given
Fixes #6210

ci: Fix renovate config bug

---

.github/workflows/integration_tests.yml

- disables backup_restore_test due to integration tests failures
The backup/restore test needs some rework and further debugging, which is why it is disabled for now. We have created a dedicated ticket to keep track of that issue:  #6239

test: Temporarily disable backup/restore test

---

cli/cmd/auth.go
cli/cmd/auth_test.go

* fix(cli): wrong handling of HTTPS in auth command
* added unit tests for regressions
- fixes wrong handling of HTTPS in auth command
Fixes #6267

fix(cli): wrong handling of HTTPS in auth command

---

lighthouse-service/deploy/service.yaml
lighthouse-service/event_handler/evaluate_sli_handler.go
lighthouse-service/event_handler/evaluate_sli_handler_test.go
lighthouse-service/go.mod
lighthouse-service/go.sum

When receiving an SLI result each metric is compared with previous values, those are aggregated following a certain aggregation strategy defined in the SLO. In case of comparison criterias this values stays the same for all comparisons and influence the target values used to decide whether the metric passes or fails. 
In this PR we store the aggregated value in each evaluation result as ComparedValue, to facilitate understanding of why the metric passes or fails a comparison criteria. 
For criterias with fixed targets the pass or fail is dependent only on the TargetValue, anyhow ComparedValue is calculated.
- unit tests modified
- integration test checked
Fixes #5496

feat(lighthouse-service): Add compared value to payload (#5496)

---

installer/manifests/keptn/charts/control-plane/templates/ingress.yaml

- Removes a hardcoded namespace reference from the installer
- Hardcoded namespace affects custom Kubernetes deployments in different namespaces.

fix: Remove hardcoded namespace reference in installer

---

bridge/client/app/_models/keptn-info.ts
bridge/client/app/_services/_mockData/api-responses/bridgeInfo-response.mock.ts
bridge/client/app/_services/api.service.mock.ts
bridge/client/app/_services/api.service.ts
bridge/client/app/_services/data.service.ts
bridge/client/app/_services/feature-flags.service.spec.ts
bridge/client/app/_services/feature-flags.service.ts
bridge/client/environments/environment.dynamic.ts
bridge/client/environments/environment.prod.ts
bridge/client/environments/environment.test.ts
bridge/client/environments/environment.ts
bridge/server/.jest/setupServer.ts
bridge/server/api/index.ts
bridge/server/app.ts
bridge/server/feature-flags.ts
bridge/server/test/environment.utils.spec.ts
bridge/server/utils/environment.utils.ts
bridge/shared/interfaces/feature-flags.ts
bridge/shared/interfaces/keptn-info-result.ts

Closes #6073
Feature flags are now split into `Server` and `Client`. Only the `Client` feature flags are sent to the client.

feat(bridge): Feature flags for bridge server (#6073)

---

go-sdk/go.mod
go-sdk/go.sum
go-sdk/pkg/sdk/keptn.go
go-sdk/pkg/sdk/keptn_fake.go
go-sdk/pkg/sdk/keptn_test.go
go-sdk/pkg/sdk/log.go
remediation-service/go.mod
remediation-service/go.sum
remediation-service/main.go
webhook-service/go.mod
webhook-service/go.sum
webhook-service/main.go

closes #5945 
Added possibility to configure the logger implementation used by the SDK:
```go
func main() {
log.Fatal(sdk.NewKeptn(
serviceName,
sdk.WithTaskHandler(
getActionTriggeredEventType,
handler.NewGetActionEventHandler()),
sdk.WithLogger(logrus.New()),
).Start())
}
``` 
adjusted `remediation-service` and `webhook-service` to pass an instance of the logrus logger.

feat: introduce swappable logger in `go-sdk`

---

bridge/client/app/_components/ktb-tree-list-select/ktb-tree-list-select.component.html
bridge/client/app/_components/ktb-tree-list-select/ktb-tree-list-select.component.scss
bridge/client/app/_components/ktb-tree-list-select/ktb-tree-list-select.component.ts
bridge/client/app/_components/ktb-variable-selector/ktb-variable-selector.component.ts
bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.html

* Add an (optional) hint with an overlay to the variable picker for more information.
* Text adaptions to have more emphasis on keptn-webhook-scope for secret selection.
Closes #5576

feat(bridge): Add hint for tree list select component and change texts (#5576)

---

configuration-service/common/git.go
configuration-service/common/git_test.go
configuration-service/handlers/project.go
configuration-service/restapi/configure_configuration_service.go
installer/manifests/keptn/charts/control-plane/templates/core.yaml
installer/manifests/keptn/charts/control-plane/values.yaml

Closes #6315 
This PR changes the behavior of the configuration service by moving the git config setup to the individual project repositores instead of doing it globally during the startup. This way, we also do not need the `initContainer`, which required enhanced privileges, anymore.
Also, the `fsGroup` used by the configuration service has been changed to `1001` per default (see #6315 for further details).  This `fsGroup` value can be overridden using the `configurationService.fsGroup` option in the installer helm chart.

fix(configuration-service): Fix permission issues for configuration service (#6315)

---

installer/manifests/keptn/charts/control-plane/values.yaml

Closes #6316 
The PR disables the nats config reloader per default. If it is needed nevertheless, it can be enabled using the option `nats.reloader.enabled` of the control plane helm chart

fix(installer): Disable nats config reloader per default (#6316)

---

statistics-service/db/migrator.go
statistics-service/db/migrator_test.go

part of #6266
This PR also considers the `KeptnServiceExecutions` key which could also contain dots, during migration.

fix(statistics-service): migration of keptn service execution data

---

installer/manifests/keptn/charts/control-plane/values.yaml

Backport of #6318
Closes #6316

fix(installer): Disable nats config reloader per default (#6316) 

---

configuration-service/handlers/service_resource.go

During the unarchive operation the configuration service tried to create a tmp directory in the file system root - since it does not have the permissions to write anything there, the temp directory is now created within /data/config

fix(configuration-service): Create tmpdir for unarchiving in /data/config

---

test/go-tests/webhook_test.go
webhook-service/main.go

This PR adds the localhost loopback address of the webhook service to the list of unallowed URLs
integration test run: https://github.com/keptn/keptn/runs/4532822978?check_suite_focus=true

fix(webhook-service): Disallow requests to loopback addresses

---

bridge/client/app/_components/ktb-modify-uniform-subscription/ktb-modify-uniform-subscription.component.html
bridge/client/app/_components/ktb-modify-uniform-subscription/ktb-modify-uniform-subscription.component.scss
bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.html
bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.scss
bridge/client/styles.scss
bridge/cypress/integration/uniform-integrations.spec.ts

Closes #5706 
* Subscription and webhook forms are now a bit cleaner and more aligned
* Webhook URL is a textarea with standard row size 1 and can be expanded
* The buttons for payload and secret variables are now in the header of both textareas because it would otherwise overlap the content and the expand handle

feat(bridge): Use textarea for webhook url config and adapt styles (#5706)

---

installer/manifests/keptn/charts/control-plane/templates/core.yaml
installer/manifests/keptn/charts/control-plane/values.yaml

Closes #6385 
The problem described in the linked issue occurs because the configuration service runs in a different `fsGroup` than it used to in previous versions - this was done because of compatibility issues on openshift installations.
Therefore, the fsGroup of the configuration has been set to the previous value, but can be changed via the `control-plane.configurationService.fsGroup` variable of the helm chart.
To ensure that project directories created with <0.11.3 and >0.11.3 have the same fsGroup, the initContainer that was removed in 0.11.3, can now be enabled or disabled with the value `control-plane.configurationService.initContainer`

fix(installer): Use previous fsGroup per default, provide option to execute init container (#6385)

---

configuration-service/common/git.go
configuration-service/common/git_test.go

Closes #6398 
How to test:
Create a project with an empty upstream repository.

fix(configuration-service): Creating projects from empty upstream (#6398)

---

bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.spec.ts
bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.ts
bridge/cypress/integration/uniform-integrations.spec.ts

fix(bridge): Remove .event suffix from payload variables in webhook (#6396)

---

lighthouse-service/README.md

- when criteria are specified under a single criteria lighthouse verifies them with logical AND  ex "<10, >2"
- when multiple criteria are there it is enough for one to pass, aka logical OR  ex
- "<10"
-  ">2"  
as shown below putting two opposing condition in an AND will in fact result in a fail
Fixes #6160

fix(lighthouse-service): Modified criteria example in SLO (#6106)

---

.github/workflows/integration_tests.yml
test/go-tests/backuprestore_test.go

Closes #6408
This PR disables the installation of gitea on k3d, and aims to increase the robustness of the backup/restore integration test by ensuring the complete delivery sequence has been finished before starting the backup/restore procedure

fix: Disable gitea installation on k3d (#6408)

---

installer/manifests/keptn/charts/control-plane/values.yaml

- removes some unused values from the keptn installer helm chart

fix(installer): Remove unneeded helm chart values

---

.github/workflows/integration_tests.yml
test/go-tests/sequencestate_test.go

Integration test run: https://github.com/keptn/keptn/actions/runs/1607320058
Note: the minishift error seems to have happened temporarily, as well as the graceful shutdown test on GKE 1.21 (this one is currently unstable on master).

test: Move installation of remote exec plane to beginning of tests

---

cli/cmd/create_project.go

- adds warning for missing upstream when using cli
Fixes #6306

feat: Add warning for missing upstream during 'keptn create project'

---

.github/workflows/integration_tests.yml
test/assets/gitea/values.yaml

This PR removes a deprecated option provided to the gitea helm chart. Also, this PR sets the version of the gitea helm chart to 5.0.0

test: Remove deprecated option from gitea helm chart

---

.github/renovate.json

- adds `keptn/go-sdk` to the ignore list of Renovate since it will be updated in Dev PRs for now

ci: Ignore keptn/go-sdk in Renovate

---

.github/renovate.json

- automatically runs `go mod tidy` after a go module was updated by Renovate

ci: Automatically run go mod tidy after renovate updated a go dependency

---

.github/workflows/CI.yml

- Removes the dependency between unit tests and docker builds to speed up CI build time

ci: Remove dependency between unit tests and docker builds to speed up CI build time

---

.github/renovate.json

- enables renovate patch update PRs to be auto-merged. This will be achieved by also installing the https://github.com/apps/renovate-approve GitHub Integration. that will auto-approve Renovate PRs that are ready for auto-merging
Related to #5825

ci: Enable auto-merging of patch PRs by Renovate

---

.github/workflows/CI.yml
codecov.yml

- adds paths to the different codecov flags that are used as identifiers for the monorepo sub-projects
- adds the `flags` report to the PR comment which shows coverage per keptn service
- removes verbose output from pipeline codecov upload step
- fixes a small bug where bridge coverage was uploaded multiple times
Fixes #6384

ci: Fix codecov reporting and monorepo setup

---

bridge/client/app/_models/sequence.ts
bridge/server/fixtures/project-details-response.mock.ts
bridge/server/fixtures/sequence-response.mock.ts
bridge/server/services/data-service.ts
bridge/shared/fixtures/open-remediations-response.mock.ts

- makes sure that the Bridge reads the problem title from GET /sequence endpoint and therefore it doesn't need to load the traces of the sequence anymore, only if also the actions are needed (e.g. environments screen)
Fixes #4206 
A remediation should not end up in `waiting` state when the action is finished, but it is waiting for the evaluation task. Therefore the `isWaiting` check ignores now remediation sequences. This will be improved with #5526

feat(bridge): Read problem title from GET /sequence endpoint

---

.github/renovate.json

- disables auto-merging for the MongoDB and NATS helm chart since it would break the airgapped setup as soon as the underlying mongodb docker image tags are changed

ci: Disable automerging for MongoDB and NATS Helm Charts

---

bridge/.gitignore
bridge/README.md
bridge/client/app/_components/ktb-user/ktb-user.component.html
bridge/client/app/_components/ktb-user/ktb-user.component.spec.ts
bridge/client/app/_components/ktb-user/ktb-user.component.ts
bridge/client/app/_services/api.service.ts
bridge/client/app/_services/data.service.ts
bridge/server/.jest/global.d.ts
bridge/server/.jest/setupServer.ts
bridge/server/.jest/shutdownServer.ts
bridge/server/app.ts
bridge/server/global.d.ts
bridge/server/jest.config.js
bridge/server/package.json
bridge/server/test/bridge-info.spec.ts
bridge/server/test/intersect-events.spec.ts
bridge/server/test/oauth.spec.ts
bridge/server/test/project.spec.ts
bridge/server/test/service-deployment.spec.ts
bridge/server/test/service-remediations.spec.ts
bridge/server/test/service-states.spec.ts
bridge/server/test/task-names.spec.ts
bridge/server/user/oauth-routes.ts
bridge/server/user/oauth.ts
bridge/server/user/session.ts
bridge/server/yarn.lock
bridge/shared/interfaces/end-session-data.ts
installer/manifests/keptn/charts/control-plane/templates/core.yaml
installer/manifests/keptn/charts/control-plane/values.yaml

Closes #6076
Closes #6077 
- adds support to login via a custom OpenID provider
The following environment variables have to be set
- `OAUTH_ENABLED`: true
- `OAUTH_BASE_URL`: e.g. http://localhost:3000 or http://myBridgeInstallation.com
- `OAUTH_DISCOVERY`: https://api.login.yahoo.com/.well-known/openid-configuration
- `OAUTH_CLIENT_ID`: myClientID
- `OAUTH_CLIENT_SECRET` (optional): myClientSecret
- `OAUTH_ID_TOKEN_ALG` (optional): myAlg (e.g. `ES256`). Default is `RS256`
- `OAUTH_NAME_PROPERTY` (optional): The property of the ID token that identifies the user (e.g. `username`). Default is `name`

feat(bridge): Login via OpenID (#6076) (#6077)

---

configuration-service/handlers/service_resource.go
configuration-service/handlers/service_resource_test.go

fix(configuration-service): Make check for helm chart archives more strict (#6447)

---

cli/pkg/credentialmanager/handler.go

Closes #6449 
**How to test:**
- Prerequisite: Authenticated Keptn CLI
1. Execute a Keptn command that uses the API, e.g. `keptn get project` - This should list the projects of the Keptn instance the CLI is connected to
2. Disable the context check: `keptn set config KubeContextCheck false`
3. Execute `keptn get project` again - this was failing previously, but should work now with the fix provided in this PR.

fix(cli): Set CLI context before attempting to check for K8s context change (#6449)

---

.github/workflows/integration_tests.yml
test/go-tests/init_test.go
test/go-tests/testsuite_k3d_test.go

This PR removes the unintential execution of the configuration service integration test on K3D. Additionally, the keptn CLI authentication is moved to the go-tests. This should improve the stability especially on minishift where sometimes the keptn auth command fails on the first try due to the api server not being ready yet, and the retry mechanism written in bash was not functioning correctly (my guess is that the `authenticate_keptn_cli` step was failing as soon as `keptn auth` was returning an error code, without proceeding with the retry logic)

test: Move Keptn CLI authentication to go tests (#6573)

---

cli/cmd/upgrade.go

fix(cli): project without upstream is defined as project without `GitRemoteUri`

---

.github/workflows/check-docker-image-digests.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
gh-actions-scripts/check-image-digests.sh

- adds a new pipeline that checks the docker image digests from dockerhub against the digests that are attached to the releases of keptn
- adds the upload of a `digests.csv` file to the (pre)release pipeline
- streamlines image upload to quay.io and ghcr.io (now, the images are not first released and then copied to the other registries, instead, they are pushed directly at the same time to all 3 registries)
Fixes #5738

ci: Add pipeline to nightly check docker image digests

---

.github/workflows/check-docker-image-digests.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml

- runs the docker digest check pipeline every night instead of just on workday nights
- simplifies some bash for loop to just wildcard expansions

ci: Minor pipeline improvements

---

.github/workflows/CI.yml

- remove pushing of docker images for forked branches. This was not possible before anyways since the docker login step was not executed in those cases. But now, the docker build fails completely because pushing is not dependent on the fork/non-fork branch condition anymore. This was added back

ci: Only push docker images if not from a forked repo

---

.github/workflows/check-docker-image-digests.yml
gh-actions-scripts/check-image-digests.sh

- adds the `GITHUB_TOKEN`  so that the `gh` CLI has access to the keptn github repo
- fixes the digest checker script (the digest file download always loaded the digests from the latest release)

ci: Fix digest checker pipeline

---

CONTRIBUTORS.md

- adds @Im5tu as a keptn contributor
- contribution: https://github.com/keptn/keptn/pull/6312

chore: Add @Im5tu as a contributor

---

installer/manifests/keptn/Chart.yaml

- adds metadata to the keptn helm chart
Fixes #5530
The artifacthub repo was already switched to point to the github helm chart repository.
Adding an icon to the artifacthub repo is not possible without more effort. This would only be possible by having the unpackaged, but fully versioned chart in the https://github.com/keptn/helm-charts repo on master branch with a corresponding readme file.

chore(installer): Added metadata to keptn helm chart

---

.github/workflows/dco.yml
.lift.toml

- removes the DCO pipeline. Since the DCO bot was not taken offline after all, we don't need a custom pipeline
- removes the now unneeded Sonatype Lift config file

ci: Remove unneeded pipelines and config files

---

MAINTAINERS

FTR: https://github.com/keptn/community/issues/94
Signed-off-by: Thomas Schuetz <thomas.schuetz@dynatrace.com>
- adds @thschue to MAINTAINERS

chore: promote @thschue to maintainers

---

configuration-service/common/git.go
configuration-service/common/git_test.go
configuration-service/handlers/project.go

Closes #6645 
Closes #6651 
This PR ensure that the `git.user` and `git.email` config values are set before attempting to commit/push to a project's configuration repository.
Integration test run: https://github.com/keptn/keptn/runs/4896206083?check_suite_focus=true

fix(configuration-service): Ensure that git user and email are set before committing (#6645)

---

cli/cmd/add_resource.go
cli/cmd/authenticator.go
cli/cmd/configure_monitoring.go
cli/cmd/create_project.go
cli/cmd/create_service.go
cli/cmd/delete_project.go
cli/cmd/delete_service.go
cli/cmd/generate_support_archive.go
cli/cmd/get_event.go
cli/cmd/get_event_approvalTriggered.go
cli/cmd/get_event_evaluationFinished.go
cli/cmd/get_projects.go
cli/cmd/get_services.go
cli/cmd/get_stages.go
cli/cmd/main_test.go
cli/cmd/secret.go
cli/cmd/send_event.go
cli/cmd/send_event_approvalFinished.go
cli/cmd/sequencecontrol.go
cli/cmd/trigger_delivery.go
cli/cmd/trigger_evaluation.go
cli/cmd/update_project.go
cli/cmd/upgrade.go
cli/cmd/version.go
cli/go.mod
cli/go.sum
cli/internal/api.go

This PR contains the code adaptations for CLI to be compatible with the newest codebase in `go-utils` see: https://github.com/keptn/go-utils/pull/378

chore: adapted CLI to newest state of `APISet` in go-utils

---

.github/workflows/integration_tests.yml

- enhances the `jq` command that filters the GH actions runs on master to find the latest successful build.
- Now, the filter takes bot builds into account, since those don't push any images which in turn makes the integration tests fail during keptn installation
Integration test run where the correct Run ID was extracted from previous master runs:
https://github.com/keptn/keptn/runs/4934107939?check_suite_focus=true#step:8:36

ci: Fix intergation tests taking master artifacts from bot commits

---

bridge/client/app/_components/ktb-markdown/ktb-markdown.component.ts
bridge/client/app/_components/ktb-modify-uniform-subscription/ktb-modify-uniform-subscription.component.spec.ts
bridge/client/app/_components/ktb-modify-uniform-subscription/ktb-modify-uniform-subscription.component.ts
bridge/shared/interfaces/event-types.ts

Fixes #6628 
Fix for the special case of updating an 'sh.keptn.*' subscription.
The additional prefix of 'sh.keptn.event' is now not added anymore and the format is preserved.

fix(bridge): When updating an all events subscription, keep sh.keptn.> format (#6628)

---

bridge/client/app/_components/ktb-markdown/ktb-markdown.component.ts
bridge/client/app/_components/ktb-sequence-tasks-list/ktb-sequence-tasks-list.component.html
bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html
bridge/client/app/_components/ktb-task-item/ktb-task-item.component.ts

Fixes #5985 
It was agreed on a minimal variant, as we only have the info if a sequence has traces or not. So we show the root event with the event payload button and a message that no events can be found. Any further implementation is not needed.

fix(bridge): Add message that no events are available when sequence has no traces (#5985)

---

installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml

#6302 
This PR fixes the nginx location configuration for bridge so that it works without a trailing `/` after

fix: Fixed wrong nginx location for bridge urls

---

cli/cmd/authenticator.go
cli/internal/auth/mocks.go
cli/internal/auth/oauth.go
cli/internal/auth/oauth_test.go
cli/internal/auth/redirect.go
cli/internal/auth/state.go
cli/internal/auth/state_test.go

This PR enhances the CLI SSO feature to make use of the OAuth `state` parameter to protect against CSRF attacks.
closes #6700 
Also, the PR contains a small adjustment to the message shown to the user when using sso without a specific api token.

feat(cli): Use `state` param during Oauth flow

---

cli/cmd/auth.go
cli/internal/auth/oauth.go
cli/internal/auth/oauth_test.go

This PR adds the `--sso-scopes` flag to the CLI, supporting the use case of using custom scopes.
No matter what values the user passes, the scope "openid" will always be used.
closes #6707

feat(cli): Added `--sso-scopes` flag to cli

---

bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.ts

- Adds to the error notification the information about the project-creation error
Fixes #6615

fix(bridge): Display additional error information when creating a project

---

.github/workflows/pre-release.yml
.github/workflows/release.yml
gh-actions-scripts/generate-k8s-resource-stats.sh

- adds a new shell script to generate k8s resource consumption data from the Keptn Helm Chart
- doesn't use an actual installation for the gathering of data but rather parses the rendered helm chart to get the data
- attaches the resource data to (pre-)releases
Fixes #6178 
Markdown result for the release notes can be checked here: https://github.com/keptn/keptn/runs/5018553305?check_suite_focus=true

chore: Add k8s resource stats to release notes

---

CONTRIBUTORS.md

- adds @lmmarsano as a contributor
He worked on #5456 which will be used as inspiration from the keptn team in #6043 and #6042

chore: Add @lmmarsano as a contributor

---

go-sdk/pkg/sdk/keptn_fake.go
webhook-service/go.mod
webhook-service/go.sum
webhook-service/lib/eventmod.go

- adds  commitid to webhook
BREAKING CHANGE:  in keptn sdk the keptn_fake interfaces have been updated to have api.GetOption in their signature (see [goutils change)](https://github.com/keptn/go-utils/pull/375/files#diff-245aca76b6ab2043d44c217312e1b9d487545aca0dd53418fb2106efacaec7b3)
Closes #6349

feat: Added get options to fake keptn in go-sdk

---

.github/workflows/integration_tests.yml
test/utils.sh
test/utils/install_istio.sh

The checks performed in the step that has been removed with this PR are covered by helm. Therefore this step has become obsolete

test: Remove obsolete check of deployments

---

installer/manifests/keptn/charts/control-plane/templates/mongodb-credentials.yaml

When upgrading keptn and setting a new external connection string it will use the existing one from the `mongodb-credentials`.
This PR just changes the order to use the provided value if there is one.

fix(installer): External connection string not used while helm upgrade

---

bridge/server/app.ts

Fixes #6750 
`style-src` `unsafe-inline` has to be used for Angular applications. https://github.com/angular/angular/issues/37631

fix(bridge): Fix style content security policy (#6750)

---

bridge/Dockerfile
bridge/cypress/integration/notification.spec.ts
bridge/cypress/run-tests.sh

- fixes a bug where the UI test screenshots from the bridge were not attached to the pipeline runs if the tests failed. This should now be fixed by introducing a small runner shell script that takes care of moving the screenshots to the correct folder.
Fixes #6765
Here is a CI run that had a failing UI test and still has screenshots attached: https://github.com/keptn/keptn/actions/runs/1811645354

test(bridge): Fix UI test screenshots not being attached when UI tests fail

---

.github/workflows/CI.yml

- disables the manual trigger of the CI pipeline since it is not supported
Fixes #5815

ci: Disable manual triggers of the CI pipeline

---

.github/renovate.json

- sets Renovates stability days setting to 3 to be faster with auto-merging patch dependencies
- this should prevent scenarios where a new package version is release for something but 7 days have not yet passed since the last versions so Keptn never gets the updates

ci: Set minimum days of package stability to 3 for Renovate to auto-merge

---

helm-service/chart/templates/deployment.yaml
jmeter-service/chart/templates/deployment.yaml

fix: Avoid nil pointer access for undefined value in helm charts

---

.github/workflows/pre-release.yml
.github/workflows/release.yml

- sets the build matrix in both release pipelines to `fail-fast: false`. This has the effect that even if one matrix job fails, the others continue running instead of being cancelled immediately.

ci: Ensure that build matrix runs as far as possible

---

api/Dockerfile
approval-service/Dockerfile
bridge/Dockerfile
configuration-service/Dockerfile
distributor/Dockerfile
helm-service/Dockerfile
jmeter-service/Dockerfile
lighthouse-service/Dockerfile
mongodb-datastore/Dockerfile
remediation-service/Dockerfile
resource-service/Dockerfile
secret-service/Dockerfile
shipyard-controller/Dockerfile
statistics-service/Dockerfile
webhook-service/Dockerfile

- fixes the OCI labels for all Keptn docker images
- The labels had some whitespace in between which meant that they were not interpreted correctly
Before:
After:

fix: Fix container image OCI labels

---

configuration-service/common/git.go
configuration-service/common/git_test.go

Closes #6881
The problem was that instead of a `Couldn't find remote ref HEAD` when trying to pull from a branch that is not yet on the upstream we now get a `divergent branches` error message. Since we explicitly checked for the Couldn't find remote ref before proceeding with pushing the branch, setting the upstream failed at this point.
This PR changes the behavior of the configuration service to print a warning to the logs, if an unexpected output is returned by git in this case, but instead of aborting the process of setting the upstream immediately, it will try to push the branches. 
I tested the following scenarios (manually):
Installing keptn 0.10.0 -> Create a project without upstream -> Upgrading to Keptn 0.12.1 -> update the configuration service to the image built for this PR …

fix(configuration-service): Adapt to different response from git CLI when upstream branch is not there yet

---

api/Dockerfile
approval-service/Dockerfile
codecov.yml
configuration-service/Dockerfile
distributor/Dockerfile
helm-service/Dockerfile
jmeter-service/Dockerfile
lighthouse-service/Dockerfile
mongodb-datastore/Dockerfile
remediation-service/Dockerfile
resource-service/Dockerfile
secret-service/Dockerfile
shipyard-controller/Dockerfile
statistics-service/Dockerfile
test/assets/mongodb-datastore_evaluation_triggered_template.json
webhook-service/Dockerfile

- introduces `gotestsum` as the test runner for all go-based Keptn services
- simplifies some Dockerfiles where duplicate code was present (mongodb-datastore, resource-service, shipyard-controller, statistics-service)
- removes some unneeded comments from travis-ci times
Successful integration tests: https://github.com/keptn/keptn/actions/runs/1822968567
Fixes #5946

test: Introduce gotestsum as test runner for all go based services

---

.github/workflows/CI.yml

- fixes a small issue where helm charts can not be uploaded from builds triggered by fork based PRs

ci: Only upload dev helm chart for non-fork PRs

---

lighthouse-service/event_handler/start_evaluation_handler.go

is a backport of https://github.com/keptn/keptn/pull/6922 (I hope I did it right...)
- Makes sure that the indicators array is passed as a pointer, so it can be modified within `computeObjects`
Fixes #6921

fix: ensure indicators are set in computeObjectives

---

README.md

- Updates README.md to use K3d 5.3.0 for developing.
Reason: I ran into problems using the K3d 4.x versions (which are no longer being updated, it seems) on Ubuntu 20.04:
```
keptn-mongo-56c8c56bd7-tbn7t             0/1     CrashLoopBackOff   2          78s
```
```
mongodb 15:05:00.70 
mongodb 15:05:00.71 Welcome to the Bitnami mongodb container
mongodb 15:05:00.71 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 15:05:00.71 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 15:05:00.71 
mongodb 15:05:00.71 INFO  ==> ** Starting MongoDB setup **
mongodb 15:05:00.73 INFO  ==> Validating settings in MONGODB_* env vars...
mkdir: cannot create directory '/bitnami/mongodb': Permission denied …
```

docs: Use K3d 5.3.0 in README for developing

---

test/go-tests/test_qualitygate.go

This PR extends the quality gates integration test by adding a check for the error that was reported in #6921

test: Verify content of get-sli.triggered event

---

resource-service/handler/project_resource_handler.go
resource-service/handler/resource_manager.go
resource-service/handler/resource_manager_test.go
resource-service/handler/service_resource_handler.go
resource-service/handler/stage_resource_handler.go
test/go-tests/init_test.go
test/go-tests/k8s_utils.go
test/go-tests/test_resourceservice.go
test/go-tests/test_utils.go
test/go-tests/testsuite_gke_test.go
test/go-tests/testsuite_k3s_test.go
test/go-tests/testsuite_openshift_test.go

Closes #6918
Note: the new integration test is not enabled, as it will fail with configuration-service, which is the default one, it works with resource-service

fix(resource-service): Make sure to delete "/" prefix in resourcePath when resolving git commit id

---

.github/workflows/integration_tests.yml

- also cleans up `ClusterRoles` and `ClusterRoleBindings` in the integration test pipeline now
Fixes #6914

ci: Fix cleanup in integration tests to also include clusterroles and clusterrolebindings

---

.github/workflows/pre-release.yml
.github/workflows/release.yml

- fixes a bug in the release and pre-release pipeline that prevented them from pushing the helm charts to our charts repository

ci: Fix release pipeline not uploading helm charts correctly

---

distributor/README.md
distributor/pkg/config/const.go
distributor/pkg/config/envconfig.go
distributor/pkg/config/envconfig_test.go
distributor/pkg/lib/client/client.go

Closes #6935
The timeout of 5s for the distributor's API Proxy was too low, which lead to the helm service running occasionally running into timeouts when trying to push the changes made to the helm chart of a service, when an external upstream repository was used.
This PR sets the default value for the timeout to 30s, and adds an environment variable to make this configurable as well

fix(distributor): Increase timout of http client to 30s

---

.github/workflows/integration_tests.yml

ci: Fix integration test pipeline not starting if there were 404ing CI pipeline runs in the source branch

---

installer/manifests/keptn/charts/control-plane/templates/secret-service.yaml

- Adds `keptn-prometheus-service` as a scope to secret-service, such that it also appears in Keptn Bridge
Part of https://github.com/keptn-contrib/prometheus-service/issues/274

feat: Add prometheus-service scope to secret-service

---

distributor/pkg/lib/events/poller.go
distributor/pkg/lib/events/poller_test.go

Closes #6964 
As discussed, we agreed to apply the filter properties only if one project/stage/service has been set for the subscription respectively. 
However, this is only a (very) short term solution for the RBAC use case.
In the long term, we should just pass the subscription ID in the request, since the backend knows the required filters associated with the subscription.

fix(distributor): Include event filter for project, stage, service

---

distributor/pkg/lib/events/poller.go
distributor/pkg/lib/events/poller_test.go

Forward port of #6968 (see description of this PR for an explanation of this solution)
Closes #6964

fix(distributor): Include event filter for project, stage, service 

---

.github/workflows/integration_tests.yml
.github/workflows/pre-release.yml

- fixes an issue where the pipeline run would fail when there were no resources found by `kubectl` during cleanup.
- The loop would still start iterating and then the `kubectl annotate` command would fail because no resource name is provided since the array is empty
Intergation test run where everything is red, but the cleanup worked: https://github.com/keptn/keptn/actions/runs/1887398297

ci: Fix resource cleanup in integration tests when resource arrays are empty

---

.github/workflows/integration_tests.yml
test/go-tests/k8s_utils.go
test/go-tests/test_backuprestore.go
test/go-tests/testsuite_gke_test.go
test/go-tests/testsuite_k3s_test.go
test/go-tests/testsuite_openshift_test.go

- fixes a bug in the integration test pipeline where the in-cluster execution plane was not installed on GKE 1.21 anymore since the change to include the resource-service in the tests
Fixes #7086
https://github.com/keptn/keptn/actions/runs/1951072160

test: Fix integration tests on GKE 1.21

---

installer/airgapped/pull_and_retag_images.sh

- fixes the k3d integration test setup by using the correct image version for nats (`nats:2.7.2-alpine`)
Part of #7098

test: Fix missing image in k3d integration test setup

---

bridge/client/app/_components/ktb-no-service-info/ktb-no-service-info.component.html
bridge/client/app/_components/ktb-no-service-info/ktb-no-service-info.component.spec.ts
bridge/client/app/_components/ktb-no-service-info/ktb-no-service-info.component.ts
bridge/cypress/fixtures/get.projects.empty.mock.json
bridge/cypress/fixtures/project.empty.mock.json
bridge/cypress/integration/environment.spec.ts
bridge/cypress/integration/notification.spec.ts
bridge/cypress/support/intercept.ts
bridge/cypress/support/pageobjects/EnvironmentPage.ts
bridge/cypress/support/pageobjects/ServicesSettingsPage.ts

Fixes #6997
The link now redirects to the create service page (so it's the same behavior as in the create project success notification).
On service creation, the user is redirected back to the environment page.

fix(bridge): Fix no-services message and link

---

bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.scss

Fixes #6989 
The quick filter is not intended to have a pre-defined height. However, this is fixed/implemented now.
Before:
and if the width of the page was a little bit smaller then the second scrollbar disappeared:
After:

fix(bridge): Fix quick filter overflow

---

bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.html
bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.spec.ts
bridge/client/app/_utils/form.utils.ts
bridge/server/models/webhook-config-yaml.spec.ts
bridge/server/models/webhook-config-yaml.ts
bridge/server/services/data-service.ts
bridge/server/utils/curl.utils.spec.ts
bridge/server/utils/curl.utils.ts

Fixes #7000 
- The user is now not allowed to enter spaces for the URL (it has to be encoded)
- If the webhook.yaml contains spaces inside the URL, the full URL is now returned instead of the first part before the space

fix(bridge): Prevent spaces in URL

---

bridge/cypress/integration/environment.spec.ts
bridge/cypress/integration/uniform-integrations.spec.ts
bridge/cypress/support/intercept.ts
bridge/cypress/support/pageobjects/EnvironmentPage.ts
bridge/cypress/support/pageobjects/UniformPage.ts

Sometimes some UI tests fail because of an empty page. To prevent this, we will wait until the metadata endpoint is called after the page is visited. Could be that this still does not work because of a bug in Cypress https://github.com/keptn/keptn/issues/7107

test(bridge): Fix flaky UI test

---

.github/workflows/integration_tests.yml
shipyard-controller/db/mock/tasksequencerepo_mock.go
shipyard-controller/db/mongodb_task_sequence_repo.go
shipyard-controller/db/mongodb_task_sequence_repo_test.go
shipyard-controller/db/repos.go
shipyard-controller/handler/eventdispatcher.go
shipyard-controller/handler/sequencehooks/fake/sequenceaborted.go
shipyard-controller/handler/sequencehooks/hooks.go
shipyard-controller/handler/sequencehooks/sequencestate.go
shipyard-controller/handler/shipyardcontroller.go
shipyard-controller/handler/shipyardcontroller_component_test.go
shipyard-controller/handler/shipyardcontroller_hooks.go
test/go-tests/test_sequencecontrol.go
test/go-tests/testsuite_gke_test.go
test/go-tests/testsuite_k3s_test.go
test/go-tests/testsuite_openshift_test.go

Backport for #7116 
This PR makes sure that the sequence queue is freed up for new sequences when a sequence is cancelled, even if there might be an error with retrieving certain entries from the database (e.g. the original sequence.triggered event)
Also, additional test cases for queueing/pausing/aborting sequences have been added
Integration test run: https://github.com/keptn/keptn/runs/5496316358?check_suite_focus=true
Note: the failing minishift test seems to be unrelated to the changes made in this PR
New integration test run: https://github.com/keptn/keptn/runs/5507244019?check_suite_focus=true

fix(shipyard-controller): Make sure sequence queue is free again after aborting a sequence

---

cli/cmd/generate_docs_test.go
cli/cmd/generate_support_archive_test.go
cli/cmd/set_config_test.go
cli/pkg/config/cli_config_test.go
jmeter-service/jmeterUtils_test.go
resource-service/common/files_test.go

A small testing enhancement.
Use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir

test: use `T.TempDir()` to create temporary test directory in unit tests

---

webhook-service/lib/curl_executor.go
webhook-service/lib/curl_executor_test.go

This PR contains additional checks for disallowing the usage of `@` inside `--data` argument of curl

fix(webhook-service): Disallow `@` file uploads inside data block

---

webhook-service/lib/curl_executor_test.go

This PR enhances the unit tests to also check whether the `--data` part of `curl` can contain `@` characters.

chore(webhook-service): added test for being able to use @ char inside payload

---

test/go-tests/test_sequencecontrol.go
test/go-tests/test_utils.go

This PR introduces a small delay between sending the two `started` and the `finished` events, to simulate the duration it takes a task executor to execute a task. Otherwise, if those three events are sent at roughly the same time, it might be the case that the finished event is being processed before the second started event, which will lead to a completion of the current task

test: Introduce small delay between started and finished events

---

test/go-tests/test_sequencecontrol.go
test/go-tests/test_utils.go

The assertions regarding the sequence state did not take the `waiting` state that was introduced in 0.13.x into consideration. Also, this PR includes the fix made in https://github.com/keptn/keptn/pull/7172 
Integration test run: https://github.com/keptn/keptn/runs/5567767074?check_suite_focus=true

test: Adapt sequence state assertions to waiting state

---

distributor/pkg/forwarder/forwarder_test.go

reduce the chance of test failure

fix(distributor): Added longer sleep for Nats down test in forwarder

---

cli/cmd/create_project.go
cli/cmd/create_project_test.go
cli/cmd/update_project.go
cli/cmd/update_project_test.go

There have been issues on windows with 
`git push https://<USER>:<TOKEN>@github.com/<REPO>`
to help users and for consistency, we decided to remove mandatory User from create ad update commands so that we can fall back on the URL :
`git push https://<TOKEN>@github.com/<REPO>`
Fixes #7180 
run a create command for a github repo without specifying the User
` keptn create project prova3 --shipyard=shipyard.yaml -t=$GIT_TOKEN -r=$GITHUB_REPO
`

fix(cli): Removed user check from create/update project and added simple tests

---

configuration-service/handlers/project.go
shipyard-controller/common/configurationstore.go
shipyard-controller/common/configurationstore_test.go

- Return 404 when token is invalid

fix(configuration-service): Return 404 when token is invalid

---

.github/workflows/pre-release.yml
.github/workflows/release.yml

- Adds a small sleep so that the GH API has time to store before we add files to the release that was just created

ci: Add timeout to catch unexpected not found error

---

.github/workflows/integration_tests.yml

- removes the buggy cleanup of clusterroles since it's not needed anyways. Keptn does not set up any clusterroles so nothing needs to be cleaned up

ci: Remove unneeded cleanup of ClusterRoles

---

bridge/client/app/_components/ktb-project-tile/ktb-project-tile.component.scss

- makes sure that project tiles width stays fixed and long texts break correctly
Fixes #7200

fix(bridge): Break words in project tile, to keep fix width

---

jmeter-service/Dockerfile

Updates the Dynatrace JMeter Extension that is installed into the jmeter-service from 1.3 to 1.8 (latest)
Fixes #6877 
No additional tests needed as this is just an update of a dependency

chore(jmeter-service): Updated Dynatrace JMeter extension to 1.8.0

---

shipyard-controller/handler/sequencehooks/sequencestate.go
shipyard-controller/handler/sequencehooks/sequencestate_test.go
test/go-tests/test_sequencestate.go
test/go-tests/testsuite_gke_test.go
test/go-tests/testsuite_k3s_test.go
test/go-tests/testsuite_openshift_test.go

This PR fixes an issue where the overall state of a sequence was set to finished, even though the sequence might not have been finished in all stages. That error appears when there are parallel sequences executed in multiple stages, the completion of one of those sequences, whose completion should not trigger any further sequences leads to the overall state being set to finished.
Integration test run: https://github.com/keptn/keptn/runs/5655845742?check_suite_focus=true 
The GKE tests are marked red because there is an issue with cleaning up the cluster, but the test cases were passing

fix(shipyard-controller): Consider parallel stages when trying to set overall sequence state to finished

---

bridge/server/services/data-service.ts

Fixes #7128 
The problem here is, that if we check if the `cachedSequence` exists, the property `latestEvaluationTrace` is set for the first stage but then will never be set for every following stage, as the sequence is already cached.
I removed the check for the `cachedSequence` and added one to check if the `latestEvaluationTrace` already exists for this particular stage. Then we don't have to set it again.

fix(bridge): Add latestEvaluationTrace to every stage

---

bridge/client/app/_services/data.service.ts
bridge/cypress/fixtures/bridgeInfoVersionCheck.mock.json
bridge/cypress/integration/dashboard.spec.ts
bridge/cypress/support/pageobjects/DashboardPage.ts

- makes sure that the dashboard loads projects also if `version.json` could not be loaded
Fixes #7120 
Reproduced issue:
Fixed issue:

fix(bridge): load projects, also if version.json could not be loaded

---

webhook-service/README.md
webhook-service/lib/curl_executor.go
webhook-service/lib/curl_executor_test.go
webhook-service/main.go

This PR replaces ocurrences of the word "unallowed" with "denied" and removed the wording "blacklist".

chore(webhook-service): replaced "unallowed" with "denied"

---

installer/manifests/keptn/charts/control-plane/templates/shipyard-controller.yaml

Pass helm value for max project name size as string

fix: Correct passing of projectNameMaxSize helm value with quotes

---

installer/manifests/keptn/charts/control-plane/templates/shipyard-controller.yaml

This PR adds a default value to projectNameMaxSize helm value

fix: add default helm value for project name max size

---

.github/workflows/CI.yml
.github/workflows/integration_tests.yml
.github/workflows/pipeline-queuetime.yml

- introduces ingestion of pipeline queue time metrics into Keptn's monitoring tenant
- adds ingestion for the CI and integration test pipelines

ci: Introduce pipeline queue time metrics

---

.github/workflows/CI.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml

- re-uses different workflows from the current branch instead of always using master

ci: Remove master branch restriction from re-used workflows

---

bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.html
bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.scss
bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.spec.ts
bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.ts
bridge/client/app/_services/api.service.mock.ts
bridge/cypress/integration/uniform-integrations.spec.ts
bridge/cypress/support/pageobjects/UniformPage.ts
bridge/server/interfaces/webhook-config-yaml-result.ts
bridge/server/models/webhook-config-yaml.spec.ts
bridge/server/models/webhook-config-yaml.ts
bridge/server/services/data-service.ts
bridge/server/utils/curl.utils.spec.ts
bridge/shared/interfaces/webhook-config.ts
bridge/shared/models/webhook-config.ts

- allows the user to configure the sendStarted flag for a webhook configuration via Keptn Bridge
Fixes #6059

feat(bridge): Allow to configure sendStarted flag for webhook config

---

cli/cmd/add_resource.go
cli/cmd/auth.go
cli/cmd/authenticator.go
cli/cmd/configure_monitoring.go
cli/cmd/create_project.go
cli/cmd/create_service.go
cli/cmd/delete_project.go
cli/cmd/delete_service.go
cli/cmd/generate_support_archive.go
cli/cmd/get_event_evaluationFinished.go
cli/cmd/get_projects.go
cli/cmd/get_secrets.go
cli/cmd/get_services.go
cli/cmd/get_stages.go
cli/cmd/root.go
cli/cmd/send_event.go
cli/cmd/set_config.go
cli/cmd/update_project.go
cli/cmd/upgrade.go
cli/internal/api.go
cli/internal/api_test.go
cli/internal/auth/oauth.go
distributor/go.mod
distributor/go.sum
test/go-tests/test_continuous_delivery.go

```
Successfully authenticated against: https://mykeptn.url/api
Bridge URL: https://mykeptn.url/bridge
```
Fixes #7222
before  running auth run  keptn get services --project=podtato , run oauth command as described in https://keptn.sh/docs/0.13.x/operate/user_management/microsoft/ 
https://github.com/keptn/keptn/runs/5755512785?check_suite_focus=true

fix(cli): Cleaned up Oauth command  

---

.github/workflows/CI.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml

This PR passes datetime and git sha to the docker build also in the release workflow like it is already done for the ci workflow.
part of  #7296

ci: Pass datetime and git sha to docker build in release pipelines

---

bridge/client/app/_components/ktb-trigger-sequence/ktb-trigger-sequence.component.spec.ts
bridge/client/app/_components/ktb-trigger-sequence/ktb-trigger-sequence.component.ts
bridge/client/app/_models/trigger-sequence.ts
bridge/client/app/_services/api.service.mock.ts
bridge/client/app/_services/api.service.ts
bridge/client/app/_services/data.service.spec.ts
bridge/client/app/_services/data.service.ts

Fixes #7268 
I changed the endpoint to POST `/event` instead of POST `project/${project}/stage/${stage}/service/${service}/evaluation` to align the evaluation payload with what is used by the CLI.
The behavior is be the following:
* If a timeframe and no start date is given, we also do not send a start date. Lighthouse-service is then taking the current date and performs an evaluation to the past.
* If a timeframe and a start date is given, the backend calculates the end date from it. If the end date lies in the future, the error from dynatrace-service `no evaluation performed by lighthouse because SLI failed with message error validating time range` is expected. It was aligned, that no validation in the frontend is needed in this case.

fix(bridge): Do not send a start date for evaluation if none is given by the user

---

cli/cmd/upgrade.go
cli/pkg/helm/helm_helper.go

Closes #7315
This PR makes sure the values provided to the nats dependency are compatible with the currently used nats helm chart. Unfortunately this meas that in this case we also need to set the image of nats and the nats metrics exporter, since those are defined via the values file of the nats helm chart, and the values that have been used by the previous version are incompatible with the current chart.
For adding unit tests, a bigger refactoring will be needed, as outlined in https://github.com/keptn/keptn/issues/6439

fix(cli): Provide values needed for upgrading the nats dependency

---

bridge/client/app/_components/ktb-sequence-tasks-list/ktb-sequence-tasks-list.component.html
bridge/cypress/fixtures/get.events.29355a07-7b65-47fa-896e-06f656283c5d.mock.json
bridge/cypress/fixtures/get.events.cfaadbb1-3c47-46e5-a230-2e312cf1828a.mock.json
bridge/cypress/fixtures/get.events.cfaadbb1-3c47-46e5-a230-d0f055f4f518.mock.json
bridge/cypress/fixtures/get.project.sockshop.remediation.mock.json
bridge/cypress/fixtures/get.sequences.remediation.mock.json
bridge/cypress/integration/remediation-sequences.spec.ts
bridge/cypress/integration/sequences.spec.ts
bridge/cypress/support/pageobjects/SequencesPage.ts
bridge/shared/models/trace.ts

- makes sure that remediation sequences are displayed in default color (not red) while running
Fixes #7129

fix(bridge): Show remediation sequence in default color while running

---

bridge/client/app/_services/data.service.ts
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.html
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts

Some UI tests for the sequence screen may fail if a sequence is selected because Angular throws an error `expression changed after it has been checked`. This is because the time for `Last time fetched` is `undefined` at the start until the traces are loaded and then the current date is returned, which changes on every call.
Therefore if the date is undefined `Last time fetched: never` is displayed instead of the current date.

test(bridge): Fix flaky sequence UI test

---

.github/workflows/CI.yml
.github/workflows/pipeline-queuetime.yml

- adds a condition to only send queue time metrics when the build is not triggered by a forked PR
This will prevent errors like the one shown here: https://github.com/keptn/keptn/actions/runs/2096576846

ci: Send metrics only on non-fork builds

---

jmeter-service/jmeterUtils.go

Closes #7388
Integration test run: https://github.com/keptn/keptn/actions/runs/2107598753
Unfortunately the codecov diff check is failing, but in the service's current form we would need to add a test that actually performs a jmeter test using the jmeter CLI - which might be out of scope for the issue addressed with this PR

fix(jmeter-service): Avoid nil pointer access when logging results

---

resource-service/common/gitsuite_test.go

During the last PR to the resource-service, somehow a failing test was slipping through. This PR fixes that

test: Fixed unit test in resource service

---

resource-service/common/gitsuite_test.go
test/go-tests/test_gitcommitid.go
test/go-tests/test_provisioningURL.go
test/go-tests/test_utils.go
test/go-tests/testsuite_gke_test.go

Fixes #7408
https://github.com/keptn/keptn/runs/5987118021?check_suite_focus=true webhook test fails because of old master image 
CLI check also fails due to github issues

fix: URL-provisioning test should wait for pod restart

---

mongodb-datastore/db/mongodb_connection.go
shipyard-controller/db/mongodb_connection.go
shipyard-controller/handler/shipyardcontroller_component_test.go
statistics-service/db/mongodb_connection.go

fix: Disconnect MongoDB client before reconnecting

---

shipyard-controller/common/configurationstore.go
shipyard-controller/common/configurationstore_test.go
shipyard-controller/handler/servicemanager.go
shipyard-controller/handler/servicemanager_test.go

Closes #7446 
This PR adds a check for a `ErrServiceNotFound` error when trying to delete a service from the configuration service. If the shipyard controller detects such an error when attempting to delete a service from a project, it will proceed with deleting the service from the database as well, to keep the state of the project consistent with what is available in the project's git repo
How to test:
1. Create. project
2. Create a service within that project
3. Delete the service directory from the upstream (or the configuration-service, if no upstream is configured)
4. Try to delete the service via the Bridge
5. The service should now be deleted successfully
(6. Try to recreate the service with the same name - this should also work)

fix(shipyard-controller): Proceed with service deletion if the service is not present on the configuration service anymore

---

bridge/client/app/_components/ktb-trigger-sequence/ktb-trigger-sequence.component.html

Closes #7157 
* Button alignment is improved to have Next and Back button on a more intuitive place
* "Cancel and close" was renamed to "Cancel" to be more aligned with the rest of the Bridge

style(bridge): Adapt button position for triggering a sequence

---

installer/airgapped/pull_and_retag_images.sh
installer/manifests/keptn/charts/control-plane/Chart.yaml
installer/manifests/keptn/charts/control-plane/templates/core.yaml
installer/manifests/keptn/charts/control-plane/templates/mongodb-credentials.yaml
installer/manifests/keptn/charts/control-plane/templates/mongodb-datastore.yaml
installer/manifests/keptn/charts/control-plane/templates/shipyard-controller.yaml
installer/manifests/keptn/charts/control-plane/templates/statistics-service.yaml
installer/manifests/keptn/charts/control-plane/values.yaml

- upgrades the MongoDB chart to v11.1.5
- updates the values for mongo to conform to the new changes that came in with the update
- introduces some minor refactoring
I manually tested the following:
- Install keptn 0.14.1
- trigger a few deliveries with carts example project
- upgrade to the helm chart from this PR with MongoDB upgraded to v11
- check if the mongo-credentials secret was updated correctly
- trigger more sequences and check if everything still works and that no data was lost

chore(installer): Upgrade MongoDB to v11

---

resource-service/handler/common.go
resource-service/handler/pagination.go
resource-service/handler/project_handler.go
resource-service/handler/project_handler_test.go
resource-service/handler/resource_manager.go
resource-service/handler/resource_manager_test.go
resource-service/handler/service_resource_handler.go
resource-service/models/resource.go
resource-service/skaffold.yaml
shipyard-controller/common/configurationstore.go
shipyard-controller/handler/projecthandler.go
shipyard-controller/handler/projecthandler_test.go

Currently, the resource-service has some incompatibilities (I guess, this wasn't in place with the configuration-service)
`DELETE /project/{projectName}/resource/{resourceURI}`
`DELETE /project/{projectName}/stage/{stageName}/resource/{resourceURI}`
`DELETE /project/{projectName}/stage/{stageName}/service/{serviceName}/resource/{resourceURI}`
Previously the resourceURI was double escaped with `webhook%252Fwebhook.yaml` (`webhook%2Fwebhook.yaml` in the Swagger UI), but seems like this isn't working anymore. The GET endpoints seem to work.
**added query parsing to delete endpoint**
**added json format to the model**
**Now they return metadata**
**since the branches will be deprecated, it does not make sense to have this info.  This is also available in the URL of the endpoint 
so it does …

fix:  Resource-service clean-up 

---

shipyard-controller/main.go
shipyard-controller/nats/connection_test.go
shipyard-controller/nats/pullsubscription.go

Closes #7304
How to test:
1. Make sure the termination grace period of the shipyard controller is set
2. Shut down the shipyard controller pod
3. While shutting down, continue to send events to keptn (e.g. sequence.triggered events)
4. Make sure that during the grace period no events are processed by the old replica of the shipyard controller
5. Make sure that every event sent during the termination of the old pod is eventually picked up by the new replica of the shipyard controller

feat(shipyard-controller): stop pulling messages after receiving sigterm

---

cp-connector/pkg/controlplane/subscriptionsource.go
cp-connector/pkg/controlplane/subscriptionsource_test.go

This PR adds a `FixedSubscriptionSource` , an implementation of `SubscriptionSource` that allows to skip registering to or getting subscriptions from an actual keptn control plane. This is useful when you just want to process (known types of) events **without** actually registering as an integration to Keptn.
Usage:
```go
...
fss := cp.NewFixedSubscriptionSource(cp.WithFixedSubscriptions(models.EventSubscription{Event: "sh.keptn.>"}))
controlPlane := cp.New(fss, eventSource)
...
```

feat(cp-connector): Added `FixedSubscriptionSource`

---

configuration-service/common/git.go
configuration-service/common/git_test.go
shipyard-controller/handler/projectmanager.go
shipyard-controller/handler/projectmanager_test.go

Closes #7496 
A couple of adjustments had to be made in the shipyard-controller, as well as the configuration service in order to support setting the upstream without a user.

fix: Do not require git user being set when updating project upstream credentials

---

.github/workflows/integration_tests.yml

Lets trigger our nightly integration tests a bit earlier....

ci: Changed integration tests schedule from 3 AM to 1 AM UTC

---

api/middleware/ratelimiter.go
api/middleware/ratelimiter_test.go
api/restapi/configure_keptn.go
api/restapi/configure_keptn_test.go
installer/manifests/keptn/charts/control-plane/templates/api-service.yaml
installer/manifests/keptn/charts/control-plane/values.yaml

- add a helm value to enable/disable the rate limit
I also observed that `X-Forwarded-For` is more reliable to detect the request IP address

fix(api): Allow to enable/disable rate limit 

---

test/go-tests/test_sequencequeue.go
test/go-tests/test_uniform.go
test/go-tests/test_utils.go
test/go-tests/test_zerodowntime.go

Closes #7545
Integration test run: https://github.com/keptn/keptn/actions/runs/2207581509

test: increase wait time for scaling down deployments to adapt to newly introduced termination grace period

---

MAINTAINERS

- Adds @renepanzar as member
- Re-orders members to follow the ascending order rule
https://github.com/keptn/community/issues/142

chore: Add @renepanzar as member

---

bridge/client/app/_models/metadata.ts

Adds the automaticprovisioning to the metadata interface.
To be backwards compatible to configuration-service, the property has to be optional. This will only be set if resource-service is already configured in the Keptn installation.

feat(bridge): Introduce automaticprovisioning flag to metadata

---

bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html

- Stop event propergation when clicking on external link to prevent opening/closing of expandable tile
Fixes #5284

feat(bridge): Stop event propergation when clicking on external link

---

installer/manifests/keptn/charts/control-plane/templates/configuration-service.yaml

- reverts the configuration service to use the recreate update strategy instead of rollingUpdate. Rolling updates cannot be done here, because the attached volume is set to acecssMode `ReadWriteOnce`

fix(installer): Revert configuration-service back to update strategy recreate

---

shipyard-controller/common/utils.go
shipyard-controller/common/utils_test.go
shipyard-controller/models/sequence_execution.go
shipyard-controller/models/sequence_execution_test.go

Port of https://github.com/keptn/keptn/pull/7631
Closes https://github.com/keptn/keptn/issues/7627
Closes https://github.com/keptn/keptn/issues/7633
Closes https://github.com/keptn/keptn/issues/7642
Integration test run: https://github.com/keptn/keptn/runs/6301278126?check_suite_focus=true
note: the failing tests on GKE are related to a different problem regarding the usage of the kubectl library in our tests, and will be tackled in a separate PR shortly, as the changes in this PR are not related to that other issue)

fix(shipyard-controller): Fix order of merging properties for event payload

---

installer/manifests/keptn/charts/control-plane/values.yaml

- adds a custom readiness probe for mongodb since the default one has error in keptn
- the probe was copied from bitnami/mongodb and simplified since we don't have a secondary DB
References:
https://github.com/bitnami/charts/pull/9916
https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/common-scripts-cm.yaml#L33-L35

fix(installer): Custom readiness probe for MongoDB to fix default one

---

cli/cmd/configure_monitoring.go
cli/cmd/configure_monitoring_test.go

- add tests
- add test for prometheus and datadog code (check if project is not specified)
- Adds `datadog` as a valid argument/flag to the `keptn configure monitoring` command
- This is for https://github.com/keptn/keptn/issues/2652 . Datadog integration sits at https://github.com/keptn-sandbox/datadog-service
https://github.com/keptn/keptn/issues/2652
https://github.com/keptn-sandbox/datadog-service/issues/15
1. Run `datadog-service` in keptn using
Clone https://github.com/keptn-sandbox/datadog-service
```
datadog-service $ export DD_API_KEY="<your-datadog-api-key>" DD_APP_KEY="<your-datadog-app-key>" DD_SITE="datadoghq.com" 
```
Run 
```
datadog-service $ helm install datadog-service ./helm --set datadogservice.ddApikey=${DD_API_KEY} --set datadogservice.ddAppKey=${DD_APP_KEY} --set …
```

feat: add `datadog` flag to `keptn configure monitoring`

---

test/go-tests/test_backuprestore.go
test/go-tests/test_utils.go

Closes #7654 
At some points in the tests, we were using the kubectl CLI to retrieve the names of pods. Due to a deprecation notice regarding GCP, the output of the `kubectl get pods` command was polluted.
To reduce the risk of that happening again, pod names in the backup tests are now retrieved using the kubernetes lib

test: Retrieve pod names using kubectl library

---

CONTRIBUTORS.md
helm-service/chart/templates/deployment.yaml
helm-service/chart/values.yaml
installer/manifests/keptn/templates/_helpers.tpl
installer/manifests/keptn/templates/api-gateway-nginx.yaml
installer/manifests/keptn/templates/api-service.yaml
installer/manifests/keptn/templates/approval-service.yaml
installer/manifests/keptn/templates/configuration-service.yaml
installer/manifests/keptn/templates/core.yaml
installer/manifests/keptn/templates/lighthouse-service.yaml
installer/manifests/keptn/templates/mongodb-datastore.yaml
installer/manifests/keptn/templates/remediation-service.yaml
installer/manifests/keptn/templates/secret-service.yaml
installer/manifests/keptn/templates/shipyard-controller.yaml
installer/manifests/keptn/templates/statistics-service.yaml
installer/manifests/keptn/templates/webhook-service.yaml
installer/manifests/keptn/values.yaml
jmeter-service/chart/templates/deployment.yaml
jmeter-service/chart/values.yaml

Makes possible to inject your own custom resources values using the Helm Charts in the following pods:
from /helm-service
- `helm-service`
from /jmeter-service
- `jmeter-service`
from /installer
- `api-gateway-nginx`
- `approval-service`
- `resource-service`
- `configuration-service`
- `remediation-service`
- `bridge`
- `mongodb-datastore`
- `secret-service`
- `shipyard-controller`
- `statistics-service`
- `webhook-service`
This resources values were hardcoded before in the templates.
Closes #6981 
Init Containers aren't included in the changes, as they had no specified resources. Hence, they use the [default K8s values](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources).
All `control-plane` distributor pods use the same resources properties (they all use the …

feat: Make deployment resources customizable in helm charts

---

cp-connector/pkg/controlplane/controlplane.go
cp-connector/pkg/controlplane/controlplane_test.go
helm-service/chart/values.yaml
installer/manifests/keptn/charts/control-plane/templates/shipyard-controller.yaml
installer/manifests/keptn/charts/control-plane/values.yaml
jmeter-service/chart/values.yaml
shipyard-controller/config/envconfig.go
shipyard-controller/main.go

Part of #7613
This PR changes the default values of the preStop hook time and grace period to 5s/60s respectively.
For the shipyard-controller, an internal preStop hook endpoint is introduced, which will take care of unsubscribing from nats and shutting down background tasks, such as the sequence dispatcher/event dispatcher, as well as waiting a defined number of seconds before the sigterm signal is sent to the container
Integration test run: https://github.com/keptn/keptn/actions/runs/2304981277

feat: Change default values of preStop hook time and grace period

---

approval-service/main.go

Since the nats event source uses the `registrationData.Name` property as the queue group identified, this needs to be set to the name of the deployment, instead of the pod name. Otherwise, each pod of the approval-service deployment would receive a copy of every event.

fix(approval-service): Use deployment name for registration name to fix queue group functionality

---

bridge/client/app/_services/api.service.ts
bridge/client/app/_services/app.init.ts
bridge/client/app/app-header/app-header.component.ts
bridge/client/app/app.module.ts
bridge/client/environments/environment.dynamic.ts
bridge/jest.setup.ts
bridge/package.json
bridge/server/app.ts
bridge/yarn.lock

- Removes dev dependency `jest-fetch-mock`
- Adapted fetching the config for the look and feel (with `HttpClient` instead of `fetch`)
- Removed data stored in `window.config` and instead correctly save it in the environment file
- Additional error check for fetching the look and feel zip file

chore(bridge): Remove dev-dependency jest-fetch-mock

---

installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml

fix: Correctly match nginx location for Bridge

---

approval-service/main.go

Part of #7613
This PR modifies the readiness probe of the approval service to consider the current state of the control plane connector. The service will now be considered ready, only when it's connected to the controlplane. Until that is the case, previous pods of the approval-service will not be terminated. This will ensure that there is always at least one replica available that is ready to receive events.
Integration test run: https://github.com/keptn/keptn/actions/runs/2313756860

feat(approval-service): Consider nats connection in readiness probe

---

bridge/client/app/_components/ktb-project-settings-git-extended/ktb-project-settings-git-extended.component.html
bridge/client/app/_components/ktb-project-settings-git-extended/ktb-project-settings-git-extended.component.spec.ts
bridge/client/app/_components/ktb-project-settings-git-extended/ktb-project-settings-git-extended.component.ts
bridge/client/app/_components/ktb-project-settings-git-https/ktb-project-settings-git-https.component.html
bridge/client/app/_components/ktb-project-settings-git-ssh/ktb-project-settings-git-ssh.component.html
bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.html
bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.ts
bridge/client/app/_interfaces/git-upstream.ts
bridge/client/app/_services/api.service.ts
bridge/client/app/_services/data.service.ts
bridge/client/app/_utils/git-upstream.utils.spec.ts
bridge/client/app/_utils/git-upstream.utils.ts
bridge/cypress/fixtures/metadata.ap-disabled.mock.json
bridge/cypress/fixtures/metadata.ap-enabled.mock.json
bridge/cypress/integration/project-create-extended.spec.ts
bridge/cypress/integration/project-settings.spec.ts
bridge/cypress/support/intercept.ts
bridge/cypress/support/pageobjects/NewProjectCreatePage.ts

Add the option for the git extended forms (create project & project settings) to configure no upstream when automation provisioning is true.

feat(bridge): Make git upstream optional when automatic provisioning url is provided

---

bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.html
bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.spec.ts
bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.ts
bridge/client/app/_utils/form.utils.ts

- Allows the user to use a secret for defining the URL for a Webhook.
Fixes #6727

fix(bridge): Allow Webhook configuration URL to be a secret

---

cp-connector/pkg/nats/nats.go
cp-connector/pkg/nats/nats_test.go

This PR extends the `Publish()` method of the cp-connector to make sure the timestamp of an event is always set to the current time

feat(cp-connector): Make sure event timestamp is always set 

---

cp-connector/go.mod
cp-connector/pkg/nats/nats.go
cp-connector/pkg/nats/nats_test.go

In addition to the event time, also an event ID and the CloudEvents spec version need to be set

feat(cp-connector): Ensure mandatory CloudEvent attributes are set

---

installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml
installer/manifests/keptn/charts/control-plane/values.yaml

- adds the ability to adjust the `client_max_body_size` parameter of nginx at install time (via helm values) to allow upload of larger resources if desired
Fixes #7567 
I'm not sure if we should already increase the default value to 5 MB or if 1 MB is sufficient for most workloads.

feat: Add ability to customize client_max_body_size in the nginx gateway

---

bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.html
bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.ts
bridge/cypress/integration/project-create-extended.spec.ts
bridge/cypress/support/pageobjects/NewProjectCreatePage.ts
bridge/server/api/index.ts
bridge/server/test/bridge-info.spec.ts
bridge/shared/interfaces/keptn-info-result.ts
installer/manifests/keptn/charts/control-plane/templates/core.yaml
installer/manifests/keptn/charts/control-plane/values.yaml

If automatic provisioning is enabled (git upstream is not required) and the message is set via helm value it is shown in the form.

feat(bridge): Show automatic provisioning message

---

installer/manifests/keptn/charts/control-plane/templates/shipyard-controller.yaml

This PR changes the preStop hook type of the shipyard-controller to `exec` instead of `http`.
During testing I noticed that the http preStop hook was not executed correctly, as indicated in the following `FailedPreStopHook` event:
```
6m8s        Warning   FailedPreStopHook   pod/shipyard-controller-5fd89499c8-5xqt7    HTTP lifecycle hook (operations/v1/pre-stop) for Container "shipyard-controller" in Pod "shipyard-controller-5fd89499c8-5xqt7_keptn(77ea19e9-2c59-4009-bc5d-2ad506af04f9)" failed - error: Get "http://localhost:8081/operations/v1/pre-stop": dial tcp 127.0.0.1:8081: connect: connection refused, message: ""
```
This lead to the pod being terminated immediately.
Changing the preStop hook to an `exec` type solved this issue

fix(installer): Use exec preStop hook for shipyard controller

---

cp-connector/pkg/controlplane/eventsource.go
cp-connector/pkg/controlplane/eventsource_test.go

This PR fixes the default event source used in `cp-connector` which did not pass the "deduplicated" slice of subjects to the nats component.

fix(cp-connector): fix passing deduplicated subjects to nats subscriber

---

cp-connector/pkg/controlplane/eventsource.go
cp-connector/pkg/controlplane/eventsource_test.go

This PR changes the `NatsEventSource` of the `cp-connector` to unsubscribe from its subscribed topics when the context is cancelled. Previously it was disconnecting from nats altogether, which means that the service using this lib was not able to send out events (e.g. finished events). when it was still processing an event at the time of cancellation

fix(cp-connector): Unsubscribe instead of disconnect from nats on cancel

---

approval-service/main.go
lighthouse-service/main.go

In the previous implementation of the `getGracefulContext()` function, we started a goroutine that waits for the waitGroup to be finished, but we did not wait for that goroutine - which lead to the pod being shut down prematurely even though there might still be some events being processed.
Also, during testing it seemed like addiing a small delay between cancelling the context (i.e. unsubscribing from nats) and calling `wg.Wait()` seemed to solve the problem where it was still the case that events were not fully processed before shutting down. My theory for that is that if `wg.Wait()` being called before an event handler has the chance to increase the wait group might lead to this behavior.

fix: Make sure that all events are being processed before shutting down lighthouse/approval service

---

go-sdk/pkg/sdk/keptn.go
remediation-service/go.mod
remediation-service/go.sum
webhook-service/go.mod
webhook-service/go.sum

minor fix: onEvent handler of sdk shall return when waitgroup for graceful shutodwn cannot be retrieved from context

fix(go-sdk): Return from event handler when wg for graceful shutdown cannot be retrieved from context

---

secret-service/pkg/backend/secretbackend_k8s.go
secret-service/pkg/backend/secretbackend_k8s_test.go

fixes #7786
latest integration test run: https://github.com/keptn/keptn/runs/6489169782?check_suite_focus=true
Create two secrets:
```
keptn create secret secret-1 --scope="keptn-prometheus-service" --from-literal="KEY=VALUE"
keptn create secret secret-2 --scope="keptn-prometheus-service" --from-literal="KEY=VALUE"
``` 
Check role  (expect 2 refs):
```
kubectl -n keptn get role keptn-prometheus-svc-read -oyaml
...
rules:
- apiGroups:
- ""
resourceNames:
- secret-1
- secret-2
resources:
- secrets
verbs:
- get
``` 
Delete secret without specifying the scope (expect error):
```
keptn delete secret secret-1
...
Error: Unable to delete secret: could not delete secret secret-1 in scope keptn-default: secret not found
```
Delete first secret:
```
keptn delete secret secret-1 --scope …
```

fix(secret-service): Deleting a secret does not remove references from related roles

---

test/go-tests/test_provisioningURL.go

- retry if gitea fails to create project in URL provisioning test 
Fixes #7785

fix: Added retry to url provisioning integration test

---

shipyard-controller/db/migration/sequence_execution_migration_test.go
shipyard-controller/db/models/sequence_execution/v1/sequence_execution.go
shipyard-controller/db/models/sequence_execution/v1/transformer.go
shipyard-controller/db/mongodb_sequence_execution_repo.go
shipyard-controller/db/mongodb_sequence_execution_repo_test.go
shipyard-controller/handler/sequencedispatcher.go
shipyard-controller/handler/sequencedispatcher_test.go
shipyard-controller/handler/shipyardcontroller.go
shipyard-controller/models/sequence_execution.go

- dispaches new sequences directly only if no older sequence is executed (in state triggered or started) in the same stage, service and project
- refactoring the Add() method
- adding unit tests
Fixes #7767
https://github.com/keptn/keptn/actions/runs/2369401694

fix(shipyard-controller): Dispatch new sequence directly only if no older sequence is waiting

---

installer/manifests/keptn/charts/control-plane/templates/shipyard-controller.yaml

On GKE 1.22 the preStop hook was failing with the error message `wget: can't open pre-stop: Read only file system`.
Redirecting the output to /dev/null should solve this

fix(installer): Redirect output of preStop hook command to /dev/null

---

test/go-tests/test_customendpoints.go
test/go-tests/test_webhook.go
webhook-service/lib/webhook_config.go
webhook-service/lib/webhook_config_test.go

When retrieving resources from git repository, the first step is decoding the content of webhook.yaml to a struct. Here we have two versions (alpha and beta) which are mostly normalized the same way except beta has a few additional checks. These checks were executed only if the version of the webhook-config was v1beta1, if it was different, additional checks were not executed. So actually the in the integration test, we had a valid webhook-config, so if the extra pre-check is or is not executed, it does not matter, the webhook is executed normally (and it's working), just the extra pre-checks were not executed. 
https://github.com/keptn/keptn/actions/runs/2372897926

fix(webhook-service): Added missing webhook-config version check

---

bridge/client/app/_components/ktb-heatmap/ktb-heatmap.component.spec.ts
bridge/client/app/_components/ktb-heatmap/ktb-heatmap.component.ts
bridge/client/app/_components/ktb-heatmap/testing/ktb-test-heatmap.component.html
bridge/client/app/_components/ktb-heatmap/testing/ktb-test-heatmap.component.ts

Fixes #7841
Additional changes:
The heatmap now only emits the selected identifier instead of the whole dataPoint.

fix(bridge): Fix D3 heatmap selection

---

.github/workflows/zero-downtime-tests.yml

- adds cypress test to ZD pipeline
- example run : https://github.com/keptn/keptn/runs/6556725066?check_suite_focus=true
- tests can be enabled at pipeline selecting it as in here
- test are run in parallel to zd and reported under **format cypress logs output** e.g.
- artifact of logs is generated as well
- scheduled a run for every Monday 
#7662

ci: Added cypress tests to Zero Downtime pipeline

---

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html
bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.spec.ts
bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.ts
bridge/client/app/_components/ktb-sequence-controls/ktb-sequence-controls.component.spec.ts
bridge/client/app/_components/ktb-sequence-state-info/ktb-sequence-state-info.component.spec.ts
bridge/client/app/_components/ktb-sequence-tasks-list/ktb-sequence-tasks-list.component.ts
bridge/client/app/_models/sequence.spec.ts
bridge/client/app/_services/_mockData/sequences.mock.ts
bridge/client/app/_services/api.service.mock.ts
bridge/client/app/_services/api.service.ts
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.html
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.scss
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.spec.ts
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts
bridge/client/app/app-header/app-header.component.ts
bridge/cypress/fixtures/sequences-page-2.sockshop.json
bridge/cypress/fixtures/sequences-page-3.sockshop.json
bridge/cypress/fixtures/sequences.sockshop.json
bridge/cypress/integration/sequences.spec.ts
bridge/cypress/support/commands.ts
bridge/cypress/support/intercept.ts
bridge/cypress/support/pageobjects/SequencesPage.ts

- makes sure that the filters in the sequence view are kept across page refresh
- sequence view can be shared with filters
Fixes #6182
The applied filters are stored as query parameters to the URL and also persisted to the local storage, so that it can be restored after changing views. For example:

feat(bridge): Make filters in sequence view stable across page refresh

---

bridge/client/app/dashboard/dashboard.component.spec.ts
bridge/client/app/dashboard/dashboard.component.ts

- Removes polling for projects
- Removes dependency on POLLING_INTERVAL_MILLIS
- Adapts spec
Resolves #7796 
No useful screenshots available.
1. Go to dashboard and open DevTools/Networking
2. No additional calls to `/api/controlPlane/v1/project?disableUpstreamSync=true&pageSize=50`

feat(bridge): Removes projects polling on dashboard #7796

---

.github/renovate.json

- increases the limit of concurrent renovate PRs
- this is done because the new keptn libraries will always have open PRs since they are commit hash based and those change all the time

ci: Increase concurrent dependency PR limit

---

test/go-tests/test_webhook.go

Fixes #7857 
https://github.com/keptn/keptn/actions/runs/2382865619

fix: Removed wrong beta11 from webhook integration test

---

bridge/cypress/integration/auth.spec.ts

https://github.com/keptn/keptn/pull/7812 removed the polling in the dashboard and https://github.com/keptn/keptn/pull/7794 added two checks here. Now without the polling, there is only one check for the response/error.

test(bridge): Fix failing auth.spec UI test

---

installer/manifests/keptn/charts/control-plane/values.yaml

makes the `resource-service` enabled by default.
As a follow-up, we should work on some clean-up tasks for the K8s service name and pipeline: #7827

feat: Enable Resource-Service by default

---

installer/manifests/keptn/charts/control-plane/templates/configuration-service.yaml
installer/manifests/keptn/charts/control-plane/values.yaml

This PR adapts the default values for the preStop hook times of the following services:
resource-service
mongodb-datastore
secret-service
Additionally, the memory limit for the resource-service has been increased to 256Mi

chore(installer): Adapted default values for preStop hook times and resource-service resource limits

---

cli/cmd/trigger_sequence.go
cli/cmd/trigger_sequence_test.go

- removed --sequence flag from command
Fixes #7884 
```Usage:
keptn trigger sequence [flags]
Aliases:
sequence, sequence
Examples:
keptn trigger sequence <sequence-name> --project=<project> --service=<service> --stage=<stage>
Flags:
--project string    The project containing the service for which the new artifact will be triggered
--sequence string   The sequence for which the new artifact will be triggered
--service string    The service for which the new artifact will be triggered
--stage string      The stage in which the new artifact will be triggered
```
```Usage:
keptn trigger sequence [flags]
Aliases:
sequence, sequence
Examples:
keptn trigger sequence <sequence-name> --project=<project> --service=<service> --stage=<stage>
Flags: …
```

fix(cli): Remove unnecessary `--sequence` flag from `keptn trigger sequence`

---

shipyard-controller/handler/shipyardcontroller.go
shipyard-controller/models/sequence_execution.go
shipyard-controller/models/sequence_execution_test.go

fix(shipyard-controller): Set the sequence execution state back to `started` when approval task has been finished 

---

mongodb-datastore/db/mongodb_event_repo.go
shipyard-controller/db/common.go
shipyard-controller/db/mongodb.go
shipyard-controller/db/mongodb_event_repo.go
shipyard-controller/db/mongodb_eventqueue_repo.go
shipyard-controller/db/mongodb_log_repo.go
shipyard-controller/db/mongodb_sequence_execution_repo.go
shipyard-controller/db/mongodb_state_repo.go
shipyard-controller/db/mongodb_uniform_repo.go
statistics-service/db/migrator.go
statistics-service/db/statistics_mongodb_repo.go

This PR adds a defer function in which `cur.Close()` after every initialitation of a mongodb cursor

fix: Ensure that all mongodb cursors are being closed after use

---

shipyard-controller/handler/shipyardcontroller.go
shipyard-controller/handler/shipyardcontroller_component_test.go
shipyard-controller/nats/connection_test.go

Closes #7898 
This PR also adjusts some of the intervals at which assertions are checked in the Nats connection unit tests since these tests had a few flaky runs recently

fix(shipyard-controller): Make sure result and status are set if sequence is timed out

---

go-sdk/pkg/sdk/config.go
go-sdk/pkg/sdk/keptn.go
go-sdk/pkg/sdk/keptn_test.go

fixes the error where the SDK is looking for `VERSION` instead of `K8S_DEPLOYMENT_VERSION` env var to set the integration version via the Uniform API

fix(go-sdk): Use the correct env var for setting the integration version

---

shipyard-controller/db/migration/project_mv_migration_test.go
shipyard-controller/db/migration/sequence_execution_migration_test.go
shipyard-controller/db/models/sequence_execution/v1/sequence_execution.go
shipyard-controller/db/mongodb_sequence_execution_repo_test.go
shipyard-controller/handler/shipyardcontroller_component_test.go

This PR should reduce the execution time of the shipyard controller tests by only setting up a memongo instance once per tested package, instead of setting it up in each test case. This reduces the execution time of the unit tests in our github actions to ~2m instead of previously 10m

chore: Reduce execution time of shipyard-controller tests

---

bridge/cypress/integration/trigger-sequence.spec.ts
bridge/cypress/support/pageobjects/TriggerSequenceSubPage.ts

On the first day of the month, some UI tests were not successful because it was not able to select two different days

test(bridge): Fix flaky UI test on first day of a month

---

shipyard-controller/db/mongodb_state_repo_test.go
shipyard-controller/db/mongodb_uniform_repo.go
shipyard-controller/db/mongodb_uniform_repo_test.go

Closes #7956
This PR changes the logic of the Uniform mongodb repo implementation to use an append-only approach for adding subscriptions to a registered integration
Also, deleting subscriptions will be done using $pull (also to avoid concurrency issues)
Integration test run: https://github.com/keptn/keptn/runs/6706093301?check_suite_focus=true

fix(shipyard-controller): Avoid lost writes to subscriptions due to concurrent writes

---

bridge/cypress/integration/evaluation-heatmap.spec.ts
bridge/cypress/support/intercept.ts
bridge/cypress/support/pageobjects/HeatmapComponentPage.ts

For the legend, there is a flaky UI test. To tackle that, we are waiting until the evaluations are loaded and only after then we are accessing the legend. Else the legend is repositioned (before and after evaluations fetch/render)
```
"should set tiles disabled/enabled via legend"
should set tiles disabled/enabled via legend:
CypressError: Timed out retrying after 4050ms: `cy.click()` failed because this element is detached from the DOM.
`<text x="10" class="legend-text">pass</text>`
Cypress requires elements be attached in the DOM to interact with them.
The previous command that ran was:
> `cy.contains()`
```

test(bridge): Potentially fix flaky heatmap UI tests

---

shipyard-controller/db/mongodb_uniform_repo.go
shipyard-controller/db/mongodb_uniform_repo_test.go
shipyard-controller/handler/uniformintegrationhandler.go
shipyard-controller/handler/uniformintegrationhandler_test.go
shipyard-controller/models/uniform.go

Closes #7996 
This PR removes the outdated logic that created the integration ID differently for integrations that were using the recently `integration.Subscription` property. To make sure that calls to Register() do not result in different integration IDs for updated integrations, the uniform handler will first look for existing integrations based on the integration's name and it's namespace.

fix(shipyard-controller): Update registration info based on integration name/namespace

---

cp-connector/pkg/controlplane/controlplane.go
cp-connector/pkg/eventsource/eventsource.go
cp-connector/pkg/logforwarder/logforwarder.go
cp-connector/pkg/nats/nats.go
cp-connector/pkg/subscriptionsource/subscriptionsource.go

closes #7681 
This PR adds the possibility to inject a custom logger implementation into the components of `cp-connector`

feat(cp-connector): Injectable logger implementation

---

bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.html
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts

- fixes showing an empty result before the filters are applied the first time
Fixes #7943 
- Open the sequence screen in the Bridge
- Go to another tab (e.g. service screen)
- Go back to sequence screen
- Should show loading indicator instead of `No sequences found that match your filter criteria.`

fix(bridge): Show loading indicator for sequences before filters are applied the first time

---

cp-connector/README.md
cp-connector/pkg/eventsource/eventsource.go
cp-connector/pkg/eventsource/eventsource_test.go
cp-connector/pkg/nats/nats.go
cp-connector/pkg/nats/nats_test.go

- adds `func New(connectURL string, opts ...func(connector *NatsConnector)) *NatsConnector` 
-  Changes Connect function to be run inside `NATSEventSource.Start`
#7715

feat(cp-connector): Connect to NATS only at event source startup

---

.github/workflows/integration_tests.yml

- fixes the uninstall step after the CLI uninstall command was deprecated in #8103

ci: Fix keptn uninstall in integration tests

---

cli/cmd/root.go
cli/cmd/root_test.go

fixes #7882 
This PR contains changes that causes the cli to skip the version check when the `auth` sub command is executed.
This makes the oauth handling more robust since there will be no intermediate call to the api when e.g. `keptn auth --oauth-logout` is executed with expired credentials.

fix(cli): Skip version check for auth sub command

---

.github/workflows/send-event-on-release-push.yml

- fixes a bug where also pre-release tags triggered the auto-generation of keptn CLI command docs. This should be fixed now.
Fixes #8098

fix: Only trigger CLI command docs auto-generation for full release tags

---

shipyard-controller/handler/repository_provisioner.go

- Adds the `Content-Type` and `Accept` headers to `application/json`, making it easier for provisioner applications to parse the request.
Fixes #8115

feat: Add headers to git provisioner

---

installer/manifests/keptn/templates/api-service.yaml
installer/manifests/keptn/templates/core.yaml
installer/manifests/keptn/templates/shipyard-controller.yaml
installer/manifests/keptn/values.yaml

```
features:
automaticProvisioning:
serviceURL: ""
message: ""
```
Closes #7752 
the helm chart is generated with the correct substitutions, eg. bridge and shipyard env vars 
https://github.com/keptn/keptn/runs/6999271761?check_suite_focus=true#step:3:2122 
https://github.com/keptn/keptn/runs/6999271761?check_suite_focus=true#step:3:2772

chore(installer): Moved automaticProvisionMsg under features

---

resource-service/common/credentials_test.go
resource-service/common_models/git.go
resource-service/common_models/git_test.go

Removes the necessity to enforce a token to set an upstream to a project.
Integration test run: https://github.com/keptn/keptn/runs/7067226222?check_suite_focus=true

fix(resource-service): Remove token enforcement

---

shipyard-controller/handler/projecthandler.go
shipyard-controller/handler/projecthandler_test.go
shipyard-controller/handler/projectmanager.go
shipyard-controller/handler/projectmanager_test.go

fix(shipyard-controller): Delete project should not return error if the upstream is failing 

---

shipyard-controller/handler/projecthandler.go
shipyard-controller/handler/projecthandler_test.go
shipyard-controller/handler/projectmanager.go
shipyard-controller/handler/projectmanager_test.go

- removes return in case deletion of provisioned upstream fail
- attempt removing configurations only after the DB is cleaned up, to avoid failure in case the upstream has been manually removed/ wrongly reconfigured  
Fixes #8159
integration test https://github.com/keptn/keptn/actions/runs/2568940174

fix(shipyard-controller): Project should be deleted even if upstream delete fails

---

api/restapi/configure_keptn.go
api/restapi/configure_keptn_test.go
api/swagger-ui/index.html
api/swagger.yaml
installer/manifests/keptn/templates/api-service.yaml
installer/manifests/keptn/templates/core.yaml
installer/manifests/keptn/values.yaml
mongodb-datastore/swagger.yaml
resource-service/handler/project_resource_handler.go
resource-service/handler/service_resource_handler.go
resource-service/handler/stage_resource_handler.go
secret-service/pkg/handler/scopehandler.go
secret-service/pkg/handler/secrethandler.go
shipyard-controller/handler/evaluationhandler.go
shipyard-controller/handler/loghandler.go
shipyard-controller/handler/projecthandler.go
shipyard-controller/handler/servicehandler.go
shipyard-controller/handler/stagehandler.go
shipyard-controller/handler/statehandler.go
shipyard-controller/handler/uniformintegrationhandler.go
statistics-service/api/event.go
statistics-service/api/statistics.go

introduces basic documentation about RBAC scopes planned for each API endpoint. 
Furthermore, it allows configuring if the rendering for deprecated endpoints should be rendered or not. 
Fixes #7352
Run:
- `helm template keptn .\installer\manifests\keptn --set control-plane.features.oauth.prefix="myPrefix:" --set control-plane.features.oauth.enabled=true  > out.yaml` 
- `helm template keptn .\installer\manifests\keptn --set control-plane.features.oauth.prefix="keptn:" --set control-plane.bridge.oauth.enabled=true  > out2.yaml`
and verify the output file are correct.

feat: Add OAuth scopes to swagger and add possibility to disable deprecated APIs

---

installer/airgapped/pull_and_retag_images.sh
installer/manifests/keptn/values.yaml

- reverts nginx back to 1.22.0-alpine which is the know-to-work version

revert: Revert nginx-unprivileged update to 1.23.0-alpine back to 1.22.0-alpine

---

helm-service/chart/README.md
helm-service/chart/templates/deployment.yaml
helm-service/chart/templates/service.yaml
helm-service/chart/templates/serviceaccount.yaml
helm-service/chart/templates/tests/test-api-connection.yaml
helm-service/chart/values.yaml
jmeter-service/chart/README.md
jmeter-service/chart/templates/deployment.yaml
jmeter-service/chart/templates/service.yaml
jmeter-service/chart/templates/serviceaccount.yaml
jmeter-service/chart/templates/tests/test-api-connection.yaml
jmeter-service/chart/values.yaml

- fixes a bug that prevented user from configuring multiple execution planes by allowing users to override the name of helm/jmeter svc which in turn puts the services into separate pubsub groups in NATS
Fixes #8055 
Integration test run: https://github.com/keptn/keptn/actions/runs/2590089094

fix: Change name label to respect the nameOverride

---

bridge/client/app/_components/ktb-danger-zone/ktb-danger-zone.component.html
bridge/cypress/support/pageobjects/ProjectSettingsPage.ts

Sometimes Cypress failed to get the delete-button.
My guess is when `cy.get(...).contains(...)` fetched the elements, the danger zone was not rendered yet.
I introduced a `uitestid` for the delete button, then cypress will look/wait for exactly this one.

test(bridge): Fix flaky UI test in project-delete.spec

---

remediation-service/main.go
webhook-service/main.go

This PR contains changes to pass the logrus StandardLogger instead of a new one to go-sdk so that changing the log level via `log.SetLevel` has an effect.

chore: Use logrus StandardLogger in webhook and remediation service

---

shipyard-controller/db/mongodb_project_repo.go
shipyard-controller/db/mongodb_project_repo_test.go
shipyard-controller/handler/projectmanager.go

Closes #8242
Note: The section of the shipyard retriever mentioned in the bug ticket now can rely on the project not being nil in case no error is returned by `projectRepo.GetProject()`.  Previously this returned `nil, nil`, which caused the nil pointer access shipyard retriever

fix(shipyard-controller): Return `ErrProjectNotFound` instead of `nil, nil` when project is not in the db

---

bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.html
bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.scss

- Fixes problem where a code block would be bigger than the screen (move outside the screen)
Fixes #8278
`ffFlex` change for `dt-menu` is now identical to other `dt-menu` inside `project-board.component.html`
https://github.com/keptn/keptn/blob/7a17271df64f3fb4947c6147a22ace3e29d16918/bridge/client/app/project-board/project-board.component.html#L66-L68
4k:
1080p:
Additionally the resizing of the settings-view improved in general:
Before:
Now:

fix(bridge): Settings view overflow problem

---

bridge/cypress/integration/project-settings.spec.ts
bridge/cypress/support/pageobjects/ProjectSettingsPage.ts

A UI test failed that a certain HTML element could not be found, even though the screenshot showed that the element is here. We don't really need this test anyway so I removed it.

test(bridge): Remove not needed and flaky UI test

---

bridge/client/app/dashboard-legacy/dashboard-legacy.component.spec.ts

- Refactor the unit tests which were not asserting and therefore always incorrectly succeed

test(bridge): Fix dashboard unit tests

---

.github/workflows/CI.yml
gh-actions-scripts/prepare_changed_artifacts.sh

- fixes a bug that also removed bridge UI tests and code style checks from master/maintenance branch builds, since they are just handled as build everything builds
- The change detection script now check for the `$GITHUB_REF_PROTECTED` env variable that is set by GH actions if the ref that triggered the workflow run, is protected, i.e. master, maintenance branches

ci: Fix change detection script to handle master/maintenance branches correctly

---

installer/manifests/keptn/templates/api-gateway-nginx.yaml
installer/manifests/keptn/values.yaml

PR to fix problems with having statistics service disabled via the helm chart

fix(installer): Fix Nginx not starting when statistics service is disabled

---

test/go-tests/testsuite_gke_test.go

This PR fixes the integration tests by removing a leftover reference to a test that has recently been removed

chore: Remove reference to removed test

---

api/handlers/event_test.go
api/handlers/metadata_test.go
api/importer/execute/keptn_endpoints_test.go
api/middleware/tokenauth_test.go
api/restapi/configure_keptn_test.go
cli/cmd/add_resource_test.go
cli/cmd/get_event_approvalTriggered_test.go
cli/cmd/get_event_test.go
cli/cmd/root_test.go
cli/cmd/send_event_approvalFinished_test.go
cli/cmd/trigger_delivery_test.go
cli/cmd/trigger_sequence_test.go
distributor/pkg/config/envconfig_test.go
helm-service/pkg/helm/generated_chart_handler_test.go
helm-service/pkg/mesh/ingress_config_test.go
jmeter-service/jmeterUtils_test.go
lighthouse-service/event_handler/evaluate_sli_handler_test.go
lighthouse-service/event_handler/handler_test.go
lighthouse-service/event_handler/start_evaluation_handler_test.go
mongodb-datastore/restapi/configure_mongodb_datastore_test.go
resource-service/common/credentials_test.go
secret-service/pkg/common/utils_test.go
shipyard-controller/common/keptn_helpers_test.go
statistics-service/controller/statistics_test.go
statistics-service/db/statistics_mongodb_repo_test.go
webhook-service/lib/secret_reader_test.go

This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv

test: use `T.Setenv` to set env vars in tests

---

resource-service/main.go

Fixes #8160
This is a breaking change
```
curl -X GET "http://keptn.nip.io/api/configuration-service/v1/project/podtato/stage/hardening/service/helloservice/resource/" -H "accept: application/json" -H "x-token: <token>" -v
> GET /api/configuration-service/v1/project/podtato/stage/hardening/service/helloservice/resource/ HTTP/1.1
> Host: keptn.nip.io
> User-Agent: curl/7.68.0
> accept: application/json
> x-token: <token>
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< server: istio-envoy
< date: Fri, 01 Jul 2022 05:50:11 GMT
< content-type: text/html; charset=utf-8
< content-length: 100
< location: /v1/project/podtato/stage/hardening/service/helloservice/resource
< x-envoy-upstream-service-time: 4
<
<a …
```

fix(resource-service): Return 404 with trailing slashes

---

api/deploy/service.yaml
api/importer/execute/default_api.go
api/importer/execute/default_api_test.go
api/importer/execute/executor.go
api/importer/execute/executor_test.go
api/importer/execute/fake/executor_mock.go
api/importer/execute/keptn_endpoints.go
api/importer/execute/keptn_endpoints_test.go
installer/manifests/keptn/templates/api-service.yaml

- adds the `create-secret` API action to the import endpoint

feat(api): Add create-secret api action to import endpoint

---

bridge/cypress/integration/dashboard.spec.ts
bridge/cypress/support/pageobjects/ProjectSettingsPage.ts

There was a flaky UI test that the projects call was not triggered (`should trigger loadProjects once per dashboard visit` in `dashboard.spec.ts`).
Probably the cause: The navigation to the create-project page and then the navigation back. The navigation-back was triggered too early and therefore canceled the navigation to the create page.

test(bridge): Fix flaky UI test in dashboard.spec

---

webhook-service/handler/handler.go
webhook-service/handler/handler_test.go

Closes #8334
This fixes a bug due to which the webhook service was responding with a `started` event if something went wrong with the retrieval of the webhook config (e.g. if the project has. been deleted at the point where the service received the event).

fix(webhook-service): Do not respond to anything else than .triggered event on pre execution error

---

bridge/client/app/_views/ktb-dashboard-view/ktb-project-list/ktb-project-tile.component.html
bridge/cypress/fixtures/projects.mock.json
bridge/cypress/integration/dashboard.spec.ts
bridge/cypress/support/pageobjects/DashboardPage.ts

- Removes “Keptn will not support a project without Git upstream repository in future releases.” warning message
- Adds UI test for “Set the Git upstream of your project” message
Resolves #8424

chore(bridge): Remove no Git upstream is set warning

---

api/handlers/zip_package_test.go
api/importer/model/execute.go
api/importer/model/manifest.go
api/importer/model/parser_test.go
api/importer/package_processor.go
api/importer/package_processor_test.go
api/importer/template.go
api/importer/template_test.go
api/test/data/import/rendered-sample-package/api/create-service.context.yaml
api/test/data/import/rendered-sample-package/api/create-service.json
api/test/data/import/rendered-sample-package/api/create-subscription.context.yaml
api/test/data/import/rendered-sample-package/api/create-subscription.json
api/test/data/import/rendered-sample-package/resources/webhook.context.yaml
api/test/data/import/rendered-sample-package/resources/webhook.yaml
api/test/data/import/sample-package/api/create-service.json
api/test/data/import/sample-package/api/create-subscription.json
api/test/data/import/sample-package/resources/webhook.yaml

Signed-off-by: Paolo Chila <paolo.chila@dynatrace.com>
- Adds support for simple context definition as a map<string, string> defined at task level
- Support templating both API payloads and resource contents

feat(api): Support simple templating for resource and api tasks in import manifests

---

.snyk

- adds lots of license ignore rules to the snyk config file. They are all for MPL-2.0 licensed dependencies

ci: Add license ignores to snyk config

---

cli/cmd/create_secret.go

* Fixes typo error in create_secret file
Signed-off-by: vanshaj <vanshajdhar@gmail.com>

docs(cli): Fix typo in create secret command

---

bridge/shared/models/trace.ts

Signed-off-by: ermin.muratovic <ermin.muratovic@dynatrace.com>
- fixes the evaluation board if `image` is missing in `configurationChange` in payload
Fixes #8506

fix(bridge): check if configurationChange has image

---

.github/workflows/CI.yml
.github/workflows/security-scans.yml
gh-actions-scripts/build-helm-charts.sh
installer/manifests/keptn/templates/_helpers.tpl

- adds back some `helm repo add` commands to make helm happy in all our builds
- adds some better logging in the build helm charts script for better readability
- adds a depenedncy in the CI build between docker build and helm chart upload so that only when there is a docker build, the helm chart will be uploaded

ci: Add back helm repo add commands in pipelines

---

installer/manifests/keptn/values.yaml

Closes #8522
This PR sets the `nats.cluster.enabled` option to `false`, due to the reasons described in #8522

fix(installer): Disable nats cluster due to unreliable behavior

---

bridge/client/app/_services/data.service.spec.ts
bridge/client/app/_services/data.service.ts
bridge/client/app/_views/ktb-environment-view/ktb-environment-view.component.html
bridge/client/app/_views/ktb-environment-view/ktb-environment-view.component.ts
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts
bridge/cypress.config.ts
bridge/cypress/integration/trigger-sequence.spec.ts
bridge/cypress/support/pageobjects/TriggerSequenceSubPage.ts

Only one test in `trigger-sequence.spec.ts` was executed because of `it.only`.
Removed the `only`, fixed two UI tests and fixed a bug in the environment screen regarding automatically opening the trigger-sequence form.
- Added a retry strategy for UI tests. A failed test will now run up to 2 additional times if it fails.

test(bridge): Fix ignored UI tests in trigger-sequence.spec

---

installer/manifests/keptn/templates/rbac.yaml
installer/manifests/keptn/templates/shipyard-controller.yaml
installer/manifests/keptn/values.yaml

Fixes an issue, where the role binding for shippy to acquire the lease for leader election was always installed. Now, it's only installed if leader election is actually enabled.
This PR also adjusts the helm value slightly to follow our own standards for helm values. (`disableLeaderElection` -> `leaderElection.enabled`)
Fixes #8534

fix(installer): RoleBinding is not installed if not needed for shippy leader election

---

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html
bridge/cypress/fixtures/get.sockshop.service.carts.evaluations.keysli.mock.json
bridge/cypress/integration/evaluations.spec.ts
bridge/cypress/support/pageobjects/EvaluationBoardPage.ts

- shows more details about failed Key SLIs
- shows failed SLIs in breakdown more prominent
Fixes #6639 
Failed score, 2 Key SLIs failed:
Failed score, no Key SLIs failed:
Acceptable score, 1 Key SLI failed:
Good score, no Key SLIs failed:

feat(bridge): Better visualization of failed Key SLIs

---

bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html
bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.scss
bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts
bridge/client/app/_interfaces/sli-result.ts
bridge/cypress/fixtures/get.sockshop.service.carts.evaluations.mock.json
bridge/cypress/integration/sli-breakdown.spec.ts
bridge/cypress/support/intercept.ts
bridge/cypress/support/pageobjects/HeatmapComponentPage.ts
bridge/cypress/support/pageobjects/ServicesPage.ts

Part of #6560 
Overlay if the result is pass:
Overlay if the result is failed:
Overlay if the result is warning:
Also added an underline to the score in order to make it more obvious that there is an overlay/info

feat(bridge): Improve indicator result score visualization

---

shipyard-controller/handler/uniformintegrationhandler.go
shipyard-controller/handler/uniformintegrationhandler_test.go

fix: Merge integration subscriptions into one, apply newly supplied subscriptions if existing ones are empty

---

helm-service/main.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>
- use `log.Println` instead of `log.Fatal` to avoid immediate exit.
Fixes #
`log.Fatal` source code see https://cs.opensource.google/go/go/+/refs/tags/go1.18.4:src/log/log.go;l=364-366;drc=2580d0e08d5e9f979b943758d3c49877fb2324cb
[Description](https://pkg.go.dev/log#Fatal) of `log.Fatal`: Fatal is equivalent to Print() followed by a call to os.Exit(1).

fix: log.Fatal will call os.Exit, use log.Println instead

---

test/assets/import/sample-package/manifest.yaml
test/go-tests/test_importer_test.go

- corrects ids in the import package manifest integration tests
Fixes #8642

test(api): Fix failing import package integration tests

---

bridge/client/app/_components/ktb-app-header/ktb-app-header.component.spec.ts
bridge/client/app/_services/_mockData/api-responses/bridgeInfo-response.mock.ts
bridge/client/app/_services/feature-flags.service.spec.ts
bridge/cypress/fixtures/bridgeInfo.mock.json
bridge/cypress/fixtures/bridgeInfoAuthMsg.mock.json
bridge/cypress/integration/project-create.spec.ts
bridge/cypress/support/pageobjects/ServicesPage.ts
bridge/server/feature-flags.ts
bridge/server/test/bridge-info.spec.ts
installer/manifests/keptn/values.yaml

chore(bridge): Enable D3 charts by default

---

api/README.md
api/models/import_summary.go
api/restapi/embedded_spec.go
api/restapi/operations/event/post_event.go
api/restapi/operations/import_operations/import.go
api/restapi/operations/metadata/metadata.go
api/restapi/server.go
api/swagger.yaml

enables the import endpoint.
I've adapted the swagger.yaml, then I ran (as it is described in the README.md) 
```bash
swagger generate server -A keptn -P models.Principal -f ./swagger.yaml
```
which lead to the changes in the .go files (and i'm not sure if all of them are expected/valid).

feat(api): Enable import endpoint

---

test/go-tests/test_importer_test.go

- Fixes the failing `Test_ImportCorrectManifestNonExistingProject` by changing the expected error message
Fixes #8654

test: Fix expected error message for importer

---

installer/manifests/keptn/templates/shipyard-controller.yaml
installer/manifests/keptn/values.yaml

- moves the `git.remoteURLDenyList` helm value key under the `features:` key
This is a breaking change

feat(installer): Move git remote URL deny list under features

---

shipyard-controller/handler/eventdispatcher.go
shipyard-controller/handler/eventdispatcher_test.go
shipyard-controller/handler/sequencedispatcher.go
shipyard-controller/handler/shipyardcontroller_component_test.go

Only sequences for the same service on the same stage and project should block each others, while this has been changed accordingly in shipyard, there was one place in the event dispatcher where we were still filtering only by stage. This created stuck sequences.
- adds service to filter of `tryToSendEvent`
- adds unit test
- adds component test
Fixes #8655

fix(shipyard-controller): Added service in the Event Dispatcher's filter

---

.github/workflows/validate-helm-docs.yml
gh-actions-scripts/generate-helm-docs.sh
installer/README.md
installer/manifests/keptn/README.md
installer/manifests/keptn/values.yaml

- adds a pipeline that checks whether the helm values documentation is up to date with the current set of helm values in a given PR
- adds a script to generate helm values documentation
- adds lots of documentation to the `values.yaml` file
- adds the generated readme to the helm chart
- adjusts the old readme in the installer folder
The helm docs pipeline will fail for this PR since the generated readme doesn't exist yet on master
https://github.com/keptn/keptn/issues/8686
https://github.com/keptn/keptn/issues/8687
Fixes #8463 
Closes #8448

ci: Add pipeline to check helm docs against master

---

shipyard-controller/main.go
shipyard-controller/main_test.go

Closes #8570
Backport of #8583

fix(shipyard-controller): Clean up event queue when cancelling a sequence

---

shipyard-controller/main.go
shipyard-controller/main_test.go

Closes #8570
Backport of #8583

fix(shipyard-controller): Clean up event queue when cancelling a sequence 

---

bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.html
bridge/cypress/integration/sequences.spec.ts
bridge/cypress/support/intercept.ts
bridge/cypress/support/pageobjects/SequencesPage.ts

- Fixes automatic navigation to latest stage when clicking `dt-tag` from `ktb-root-events-list`.
- Added UI tests for navigation to correct stage.
Fixes #8684
https://user-images.githubusercontent.com/36239763/185873075-f3c2a07e-faaf-4ce3-888a-a977437bc329.mp4

fix: Fixed automatic navigation to latest stage

---

lighthouse-service/event_handler/evaluate_sli_handler.go
lighthouse-service/event_handler/evaluate_sli_handler_test.go

- when failing due to empty result we should still append the indicator result to the evaluation.finished event. 
Part of #8602

fix(lighthouse-service): return a failed Evaluation Result for nil SLIs

---

secret-service/deploy/service.yaml
secret-service/docs/docs.go
secret-service/docs/swagger.json
secret-service/docs/swagger.yaml
secret-service/pkg/backend/fake/secretbackend_mock.go
secret-service/pkg/backend/secretbackend.go
secret-service/pkg/backend/secretbackend_k8s.go
secret-service/pkg/backend/secretbackend_k8s_test.go
secret-service/pkg/handler/secrethandler.go
secret-service/pkg/handler/secrethandler_test.go
secret-service/pkg/model/secret.go

- adds name and scope as non-mandatory parameters
- if none is defined the endpoint returns all secrets as before
- unit test 
Fixes #8474 
no integration test was provided since it would only be a redundant test of /gin + swagger 
run this version of secret service and use the GET endpoint, first with no parameters than only with name or scope finally with both.

feat: Add query parameters to GET secret endpoint

---

MAINTAINERS

- Add Brad McCoy as Member as per https://github.com/keptn/community/issues/163
Signed-off-by: Brad McCoy <bradmccoydev@gmail.com>

chore: add @bradmccoydev as member

---

shipyard-controller/main_test.go

This PR adds a component test for verifying that the `triggeredOn` property of a sequence within a shipyard file is applied properly

test(shipyard-controller): Added component tests for triggering sequences by another sequence

---

webhook-service/deploy/service.yaml
webhook-service/handler/handler.go
webhook-service/handler/handler_test.go

For each response, webhook attempts to convert it into an object and appends it to the finished event
closes #8256

feat(webhook-service): Added unmarshalling of curl responses 

---

lighthouse-service/deploy/service.yaml
lighthouse-service/event_handler/evaluate_sli_handler.go
lighthouse-service/main_test.go
test/go-tests/test_qualitygate.go

- tries to compute indicator results even if getSLI result is fail
- adds an integration test
Fixes #8602
using quality gates integration test SLO/SLI config I sent a fake getSLI finished event with result set to fail, the indicator results are computed

fix(lighthouse-service): If getSLI returns result fail make sure lighthouse fails only after computing indicator results

---

shipyard-controller/internal/controller/shipyardcontroller.go
shipyard-controller/internal/controller/shipyardcontroller_component_test.go
shipyard-controller/main_test.go

This PR changes the final update of a sequence execution to update the complete item instead of just setting the `state` property to `finished`
Closes #8808

fix(shipyard-controller): Update complete sequence execution after sequence is finished

---

.github/workflows/zero-downtime-tests.yml

Removing the ZD scheduled test, since we know we do have a regression due to MongoDB changes
Workflow can still be manually triggered https://github.com/keptn/keptn/actions/runs/3005279968

ci: Remove schedule for ZD test

---

cli/cmd/trigger_delivery.go
cli/cmd/trigger_evaluation.go
cli/cmd/trigger_sequence.go
cli/cmd/trigger_sequence_test.go

- supports --labels options in triggers sequence command
Fixes #8803

fix(cli): Support `--labels` option in `trigger sequence` command

---

cli/cmd/trigger_sequence.go
cli/cmd/trigger_sequence_test.go
cli/internal/textutils.go
cli/internal/textutils_test.go

closes #8803 
This PR introduces the `--data` option for the `trigger sequence` command in order to pass custom data fields contained in the `data` block of the cloude event emmitted by the CLI.
e.g.:
```bash
trigger sequence mysequence --project=ultimate-echo-project --stage=first-stage --service=myservice --data=test.strategy=direct,evaluation.timeframe=5m
```
Note that you cannot "overwrite" project,service,stage or labels with this.

feat(cli): Introduce `--data` option for `trigger sequence` command

---

shipyard-controller/internal/db/migration/project_credentials_migration_test.go
shipyard-controller/internal/db/project_credentials_repo.go
shipyard-controller/models/expanded_project_old.go

This PR fixes a problem where a project with `isUpstreamAutoProvisioned` set to true loses that value when it is migrated to use the new upstream git info structure

fix(shipyard-controller): Adopt previous value of IsUpstreamAutoProvisioned when migrating project with old git credentials structure

---

shipyard-controller/internal/db/models/projects_mv/projects_mv.go
shipyard-controller/internal/db/models/projects_mv/projects_mv_test.go
shipyard-controller/internal/db/mongodb_project_repo.go
shipyard-controller/internal/db/mongodb_project_repo_test.go

In DocumentDB, queries containing both `$`  and `$[<identifier>]` selectors are not supported. This PR changes the query to update a service within a project accordingly

fix(shipyard-controller): Adapt mongodb query to be compatible with DocumentDB

---

.github/workflows/CI.yml

- makes the helm chart build dependent on the docker image builds.
- This will ensure that the image timestamps used in the helm chart are equals to the ones that are pushed in the docker build step before.

ci: Make helm build dependent on container build

---

.github/workflows/CI.yml
.github/workflows/integration_tests.yml
.github/workflows/mongodb-version-check.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
.github/workflows/test-and-build-docker-images.yml
.github/workflows/zero-downtime-tests.yml

- changes all occurrences where environment variables are set during runtime in all workflows to the new way of setting them
Closes #9008 
Reference: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: Move to new way of setting env var in workflows

---

.github/workflows/CI.yml
.github/workflows/integration_tests.yml
.github/workflows/mongodb-version-check.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
.github/workflows/test-and-build-docker-images.yml
.github/workflows/zero-downtime-tests.yml

- fixes a previous mistake where variables were written to the github environment instead of the github step outputs

ci: Move variables to github outputs instead of github env

---

shipyard-controller/main_test.go

This PR should fix the flakyness of the parallel stages test in the shipyard controller's component tests

test: Fix timeout problem in check for sequence state

---

installer/manifests/keptn/templates/core.yaml

Signed-off-by: afzal442 <afzal442@gmail.com>
adds `CONTINUOUS DELIVERY` optional to bridge installiation type via helm
Fixes #8801 
Docs contains the `helm` installation type [here](https://keptn.sh/docs/quickstart/#helm)

fix: Add `CD` optional to bridge installation type via helm

---

bridge/client/app/_components/_dialogs/ktb-deletion-dialog/ktb-deletion-dialog.component.html
bridge/client/app/_components/_dialogs/ktb-deletion-dialog/ktb-deletion-dialog.component.spec.ts
bridge/client/app/_components/_dialogs/ktb-deletion-dialog/ktb-deletion-dialog.component.ts
bridge/cypress/integration/project-delete.spec.ts
bridge/cypress/support/pageobjects/ProjectSettingsPage.ts

- Added autofocus to deletion dialog input field
- Added onEnter delete functionality (only active if the project name was provided correctly)
Resolves #7521
https://user-images.githubusercontent.com/36239763/196683836-6f30399a-18dc-4815-b09c-f303861d760e.mp4
Signed-off-by: gilbert.tanner <gilbert.tanner@dynatrace.com>

feat(bridge): Added autofocus to deletion dialog input field

---

bridge/client/app/_components/ktb-expandable-tile/ktb-expandable-tile.component.scss
bridge/cypress/fixtures/sequence.traces.mock.json
bridge/cypress/integration/sequences.spec.ts
bridge/cypress/support/pageobjects/SequencesPage.ts
bridge/shared/models/trace.ts

- Fixes problem with incorrect color being displayed if one subtask fails, but the task passes.
Resolves #9054 
Signed-off-by: gilbert.tanner <gilbert.tanner@dynatrace.com>

fix(bridge): Show correct border color for task items in sequence view

---

resource-service/common/git.go

fix(resource-service): Delete tmp-origin before migrating repository

---

shipyard-controller/internal/common/error.go
shipyard-controller/internal/handler/common.go
shipyard-controller/internal/handler/projecthandler.go
shipyard-controller/internal/handler/projecthandler_test.go

- unified HTTP error response to 404 when upstream repository is not found
- return 409 HTTP error response when the upstream repository is already initialized when creating or updating project
BREAKING CHANGE: Keptn returns 404 instead of 400 HTTP error code when creation of the project fails when upstream repository is not found. Also returns 409 instead of 500 HTTP error code when creation or update of project fails due to upstream repository is already initialized.
Fixes #9038

fix(shipyard-controller): Return 4xx error responses for upstream repository problems

---

CODEOWNERS

Adding @heinzburgstaller as Bridge code-owner since he showed good understanding of the project and has driven many 
PR review improving the overall code quality

chore: Add heinzburgstaller as Bridge codeowner

---

bridge/client/app/_components/ktb-heatmap/ktb-heatmap-utils.spec.ts
bridge/client/app/_components/ktb-heatmap/ktb-heatmap-utils.ts
bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.spec.ts
bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts
bridge/cypress/fixtures/get.sockshop.service.carts.evaluations.heatmap.manyscores.mock.json

Fixes #9131 
Also adds numeration to duplicate SLI names to the sli-breakdown
Previous: 
Now:

fix(bridge): Fix incorrect SLI grouping in heatmap

---

bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.spec.ts
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts
bridge/cypress/integration/sequences.spec.ts
bridge/cypress/support/commands.ts
bridge/cypress/support/intercept.ts
bridge/cypress/support/pageobjects/SequencesPage.ts

Fixes #9136 
- Sequence polling for unfinished sequences is now cleared when switching the project

fix(bridge): Fix inconsistent sequence filter

---

MAINTAINERS

Signed-off-by: Jürgen Etzlstorfer <juergen.etzlstorfer@gmail.com>
my github handle was wrong due to a typo. now fixed to @jetzlstorfer

chore: github handle in MAINTAINERS

---

lighthouse-service/event_handler/evaluate_sli_handler.go
lighthouse-service/event_handler/evaluate_sli_handler_test.go

Closes #9196 
This PR fixes a problem where the SLO display names and pass/warning propertties are not set if the corresponding SLI value is not available

fix(lighthouse-service): Include SLO Display Name also when there is no SLI value available

---

bridge/client/app/_services/_mockData/sequence-filter.mock.ts
bridge/client/app/_services/_mockData/sequences.mock.ts
bridge/client/app/_services/data.service.ts
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.spec.ts
bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts
bridge/cypress/integration/sequences.spec.ts
bridge/cypress/support/intercept.ts

Fixes #9199
Also fixes another bug that the "go to blocking sequence" button did not work immediately (two clicks needed) if the blocking sequence was not initially loaded.

fix(bridge): Fix navigation to blocking sequence

---

CODEOWNERS

@TannerGilbert [contributed](https://github.com/keptn/keptn/pulls?q=author%3ATannerGilbert+sort%3Aupdated-desc+) extensively in the Bridge service.

chore: add @TannerGilbert to Bridge Code Owners

---

installer/manifests/keptn/README.md
installer/manifests/keptn/values.yaml

- changes the default registry for the installer to docker.keptn.sh which is connected to scarf to do some usage monitoring
- this is done to get information on which we can decide to extend LTS support for Keptn

feat(installer): Use scarf registry as default

---

.github/workflows/integration_tests.yml

Add explanation comment on why Dependency PR are not considered in the integration tests

ci: Add comment on why we skip bot PR from integration tests

---

.github/workflows/CI.yml

- fixes a bug in the CI pipeline when no new commits are there to release but we still try to calculate a new release version in the pipeline

ci: Fix error when unreleased commits are on master

---

.github/workflows/integration_tests.yml
.github/workflows/zero-downtime-tests.yml

- fixes kubectl access to the GKE clusters in the integration tests by removing the `use_auth_provider` setting for now
- changes the access pattern in the ZD tests to be the same as in the integration tests
Fixes #9328 
Integration test run where cluster access works: https://github.com/keptn/keptn/actions/runs/3730168580/jobs/6326903287

ci: Fix integration tests auth against GCP

---

.github/workflows/integration_tests.yml
.github/workflows/zero-downtime-tests.yml
CONTRIBUTORS.md

- executes the set permissions step for kubeconfig in integration/zdt pipeline just for GKE cluster

ci: Set kubeconfig permissions in GCP setup step

---

bridge/README.md
bridge/server/interfaces/configuration.ts
bridge/server/test/bridge-info.spec.ts
bridge/server/test/oauth.spec.ts
bridge/server/user/secrets.spec.ts
bridge/server/user/secrets.ts
bridge/server/utils/configuration.spec.ts
bridge/server/utils/configuration.ts
installer/manifests/keptn/templates/core.yaml

The following secrets are now read from the volume mount instead from environment variables
- mongodb user and password
- Basic user and password
- API token
Part of: #9331 

feat(bridge): Read secrets from volume mount instead from env var

---

shipyard-controller/internal/controller/sequencestate.go
shipyard-controller/internal/controller/sequencestate_test.go
shipyard-controller/main_test.go

This will prevent sequences that have been finished in one stage from being displayed as waiting when they are actually waiting in the next stage

fix(shipyard-controller): Add new stage to sequence state immediately after receiving triggered event

---

resource-service/common/git.go
resource-service/common/gitsuite_test.go

This PR fixes an issue caused by the go-git library (https://github.com/go-git/go-git/issues/590), where the library creates a new http client on its own when using the insecureSkipTLS parameter, rather than using the http client with the proxy options being set.

fix(resource-service): override insecureSkipTLS only if proxy is set to nil

---

.github/workflows/test-and-build-docker-images.yml
api/Dockerfile
approval-service/Dockerfile
bridge/Dockerfile
distributor/Dockerfile
lighthouse-service/Dockerfile
mongodb-datastore/Dockerfile
remediation-service/Dockerfile
resource-service/Dockerfile
secret-service/Dockerfile
shipyard-controller/Dockerfile
statistics-service/Dockerfile
webhook-service/Dockerfile

- fixes caching for docker builds both locally and in the pipelines, which should speed up builds a little bit
- the solution was to re-order the `ARG` steps so that they are exactly before the variables from `ARG` are used.
The caching bug occurred because all build arguments were set at the top of the dockerfile. But build arguments invalidate the cache as soon as a RUN step comes up since they are passed along to the cmd in the RUN step as env vars and docker doesn't know what happens inside the cmd, so the cache needs to be invalidated since the behaviour of the cmd could change depending on the variable value.
A better description from the docker docs can be found [here](https://docs.docker.com/engine/reference/builder/#impact-on-build-caching).
To see the docker caches in action, …

ci: fix docker build caching

---

.github/workflows/security-scans.yml

- changes github issue reporting for the security scan pipeline so that it only reports outcomes on scheduled runs and not on manually triggered runs

ci: Only report security scan result on scheduled runs

---

.github/workflows/release.yml

- generate SBOMs with Syft for all Keptn container images when a release is done
- SBOMs are attached to the release as separate `*.spdx.json` files
Fixes #7163

ci: Generate SBOMs for all container images on release

---

.github/workflows/release.yml

Signed-off-by: afzal442 <afzal442@gmail.com>
The release job is in the "release" group and will run on the latest version of Ubuntu, and the concurrency option is set to 1, so only 1 release job will run at a time, just to avoid race condition.

ci: add concurrency group to release pipeline to avoid race conditions

---

CONTRIBUTORS.md
docs/developer/README.md

- Fixes documentation
Fixes #9482

docs: hyperlink to `contributing.md` fixed

---

lighthouse-service/event_handler/evaluate_sli_handler.go
lighthouse-service/event_handler/evaluate_sli_handler_test.go
lighthouse-service/main_test.go
test/go-tests/test_qualitygate.go

- fixes inconsistent behaviour when SLI provider returns warning
Fixes #9494 
https://github.com/keptn/keptn/actions/runs/4121475886

fix(lighthouse-service): inconsistent behavior when SLI provider returns warning

---

gh-actions-scripts/cleanup_docker_images.sh

- updates the docker image cleanup script so that newer dev images are also cleaned up

chore: update docker cleanup script to also clean 2022 and 2023 images

---

installer/manifests/keptn/templates/api-service.yaml

- adds the missing `wait-for-nats` init container to the API service in the helm chart to set up launch dependencies between NATS and API service correctly
Fixes #9533

fix(installer): add missing NATS init container to API service

---

.github/workflows/CI.yml
.github/workflows/build-cli.yml
.github/workflows/build-helm-charts.yml
.github/workflows/integration_tests.yml
.github/workflows/release.yml
.github/workflows/security-scans.yml
.github/workflows/test-and-build-docker-images.yml
.github/workflows/zero-downtime-tests.yml
api/go.mod
approval-service/go.mod
cli/go.mod
distributor/go.mod
lighthouse-service/go.mod
mongodb-datastore/go.mod
remediation-service/go.mod
resource-service/go.mod
secret-service/go.mod
shipyard-controller/go.mod
statistics-service/go.mod
webhook-service/go.mod
webhook-service/lib/template_engine_test.go

Align Go version to what is used in the Dockerfile
Integration test run: https://github.com/keptn/keptn/actions/runs/4283773729

chore: update go.mod and pipeline to use the same Go version of Dockerfile

---

installer/manifests/keptn/templates/api-service.yaml

In #9534 we introduced init container for API-service. This PR changes the installer to introduce the init container for MongoDB iff there is not external connection string set.

fix(installer): Add MongoDB init container iff there is no external connection string

---

bridge/Dockerfile
installer/manifests/keptn/templates/core.yaml

- Adds an emptydir mounted in Bridge under `/tmp` so npm doesn't write on the root FS 
See https://github.com/npm/cli/issues/4996 and https://github.com/nodejs/docker-node/issues/1749
Fixes https://github.com/keptn/keptn/issues/9581

feat(bridge): Add support for NodeJS18 introducing a caching dir on an emptydir volume

---

test/go-tests/test_uniform.go

https://github.com/keptn/keptn/actions/runs/4554351852
https://github.com/keptn/keptn/actions/runs/4560806610
After adaptation:
https://github.com/keptn/keptn/actions/runs/4561515967
Fixes: #9598 #9600

test: adapt uniform integration tests to restart echo service after subscription change

---

.github/workflows/build-cli.yml
.github/workflows/integration_tests.yml
.github/workflows/security-scans.yml
.github/workflows/test-and-build-docker-images.yml

In order to fix the security vulnerability https://pkg.go.dev/vuln/GO-2023-1752 we need to use go 1.20.4 instead of 1.20.3, which is currently used by the GH action setting up the Go environment
Security scan: https://github.com/keptn/keptn/actions/runs/4938311643
Fixes: https://github.com/keptn/keptn/issues/9664

chore: check for latest version of go before installation

---

GOVERNANCE.md

- Fixes the link to community membership document which currently 404s

docs: fix community membership 404

---

cli/cmd/root.go

- adds EOL message to each CLI command
Part of: #9733 
1. Build cli with `go build . -o keptn`
2. Execute any command, for example `./keptn auth`

chore(cli): introduce EOL message

---

VERSIONING.MD

This PR enhances the clarity of the Compatibility Requirements section in `VERSIONING.md` by adding a clear definition of backwards-incompatible change. This would help to clarify what types of changes are allowed in stable releases and what types of changes should be avoided.
#9707

docs: add backwards-compatibility definition in compatibility requirements
