shipyard-controller/handler/sequencehooks/sequencestate.go, shipyard-controller/handler/sequencehooks/sequencestate_test.go
=> fix(shipyard-controller): fixed nil pointer exception in error message (#4797)

bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.ts
=> fix(bridge): update API URLs in integration page (#4830)

bridge/client/app/app-header/app-header.component.ts
=> fix(bridge): reduce version update notification to latest major and latest minor version (#4831)

releasenotes/releasenotes_V0.8.7.md
Adding the release notes of 0.8.7 into master
=> docs: release notes for 0.8.7

bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.spec.ts, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts, bridge/client/app/_models/sli-result.ts, bridge/client/app/_services/_mockData/evaluations.mock.ts, bridge/shared/interfaces/indicator-result.ts
=> feat(bridge): add weight to SLI breakdown (#4758)

bridge/client/app/_components/ktb-deployment-list/ktb-deployment-list.component.html, bridge/client/app/_components/ktb-deployment-list/ktb-deployment-list.component.ts, bridge/client/app/_components/ktb-service-details/ktb-service-details.component.html, bridge/client/app/_components/ktb-service-details/ktb-service-details.component.ts, bridge/client/app/_models/deployment.ts, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.html, bridge/client/app/_views/ktb-service-view/ktb-service-view.component.ts
=> fix(bridge): fix deployment selection (#4927, #4912)

helm-service/chart/templates/deployment.yaml, helm-service/chart/values.yaml
=> fix(helm-service): Fixed resource limit settings (#4940)

bridge/package-lock.json, bridge/server/user/oauth.ts, bridge/server/user/session.ts
Fixes #4947
- Enabled OAuth based login 
- Check session cookie value before the login 
- Check session cookie value after the login
- Validate that cookie value has changed
=> fix(bridge): fixes session fixation by regenerating the session cookie after login (#4947)

bridge/client/app/app.module.ts, bridge/client/environments/environment.dynamic.ts, bridge/client/environments/environment.prod.ts, bridge/client/environments/environment.ts, bridge/client/index.html, bridge/client/styles.scss
=> fix(bridge): Fix adapted problems with renamed app-root

.github/workflows/integration_tests.yml
=> chore: disable e2e test execution

bridge/client/app/_components/ktb-services-list/ktb-services-list.component.html, bridge/client/app/_components/ktb-services-list/ktb-services-list.component.spec.ts, bridge/client/app/_components/ktb-services-list/ktb-services-list.component.ts, bridge/client/app/_models/service.mock.ts, bridge/package-lock.json
Closes #4733 
Adds the service name to the sequence in the environment screen. Also, it changes the order of the columns to show the latest sequence first.
=> feat(bridge): Show service and image in sequence list (#4733)

shipyard-controller/handler/uniformintegrationhandler.go
This PR ads a hint to the description of the uniform api that this API shoud be considered to be in  BETA state
=> chore: mark uniform api as beta

bridge/package-lock.json
=> chore(bridge): npm audit fixes

bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.ts
=> fix(bridge): 'Create project' button was disabled if git related  inputs have not been changed (#5070)

releasenotes/releasenotes_V0.9.0.md
Release notes for Keptn 0.9..0
=> docs: Release notes for 0.9.0

api/go.mod, api/go.sum, approval-service/go.mod, approval-service/go.sum, cli/go.mod, cli/go.sum, configuration-service/go.mod, configuration-service/go.sum, distributor/go.mod, distributor/go.sum, helm-service/go.mod, helm-service/go.sum, jmeter-service/go.mod, jmeter-service/go.sum, lighthouse-service/go.mod, lighthouse-service/go.sum, mongodb-datastore/go.mod, mongodb-datastore/go.sum, remediation-service/go.mod, remediation-service/go.sum, secret-service/go.mod, secret-service/go.sum, shipyard-controller/go.mod, shipyard-controller/go.sum, statistics-service/go.mod, statistics-service/go.sum
=> build: Update go-utils to 0.9.0

releasenotes/releasenotes_V0.9.0.md
=> docs: Add known limitations

bridge/server/services/data-service.ts
https://github.com/keptn/keptn/pull/5119
=> fix(bridge): faded-out integrations were not excluded from unread-error-event check (#5118)

bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.spec.ts, bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.ts
https://github.com/keptn/keptn/pull/5092
=> fix(bridge): project delete dialog was not closed (#5091)

CONTRIBUTORS.md, helm-service/chart/templates/_helpers.tpl, helm-service/chart/templates/deployment.yaml, helm-service/chart/values.schema.json, helm-service/chart/values.yaml, installer/manifests/keptn/charts/continuous-delivery/charts/openshift/templates/route-service-openshift.yaml, installer/manifests/keptn/charts/continuous-delivery/charts/openshift/values.yaml, installer/manifests/keptn/charts/control-plane/charts/mongodb/templates/_helpers.tpl, installer/manifests/keptn/charts/control-plane/charts/mongodb/templates/deployment.yaml, installer/manifests/keptn/charts/control-plane/charts/mongodb/values.yaml, installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml, installer/manifests/keptn/charts/control-plane/templates/continuous-operations.yaml, installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/templates/mongodb-datastore.yaml, installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml, installer/manifests/keptn/charts/control-plane/values.yaml, installer/manifests/keptn/templates/_helpers.tpl, jmeter-service/chart/templates/_helpers.tpl, jmeter-service/chart/templates/deployment.yaml, jmeter-service/chart/values.yaml
allow user to provide values that customize image pull registry & pull secrets
closes #4933
follows [bitnami example](https://github.com/bitnami/charts/tree/master/bitnami/common/)
refactoring repetitive code into a [library chart](https://helm.sh/docs/topics/library_charts/) may be warranted
=> feat: customize helm chart image pull registry & pull secrets

bridge/client/app/_components/ktb-project-list/ktb-project-list.component.ts, bridge/client/app/_components/ktb-project-tile/ktb-project-tile.component.ts, bridge/client/app/_components/ktb-sequence-state-list/ktb-sequence-state-list.component.ts
=> fix(bridge): Redirect to service or sequence did not work on dashboard (#5126)

bridge/client/app/project-board/project-board.component.ts
=> fix(bridge): Polling of a project did not stop (#5094)

SECURITY.md
=> docs: add giovanni.liva as a security contact

.github/workflows/tutorial-tests.yml, test/utils/gcp-create-vm.sh, test/utils/gke_create_cluster.sh
- Adds a tutorial pipeline that will be further extended to run more tutorials in the furute
- Is only including setup work to enable further development on the topic
Prep work for #3770
=> ci: Setup work for automated execution of tutorials (#3770)

bridge/server/services/data-service.ts
=> fix(bridge): fixed error if sequence was not found (#5172)

lighthouse-service/event_handler/start_evaluation_handler.go, lighthouse-service/event_handler/start_evaluation_handler_test.go, test/go-tests/qualitygate_test.go
=> fix(lighthouse-service): Add message to event in case SLO parsing failed (#5130)

shipyard-controller/handler/shipyardcontroller.go, shipyard-controller/handler/shipyardcontroller_test.go
=> fix(shipyard-controller): Return error if a sequence for an unavailable stage is triggered (#4791)

configuration-service/common/common.go, configuration-service/handlers/project.go, configuration-service/handlers/project_resource.go, configuration-service/handlers/service.go, configuration-service/handlers/service_default_resource.go, configuration-service/handlers/service_resource.go, configuration-service/handlers/stage.go, configuration-service/handlers/stage_resource.go, configuration-service/restapi/embedded_spec.go, configuration-service/restapi/operations/service_default_resource/put_project_project_name_service_service_name_resource_resource_uri_parameters.go, configuration-service/swagger.yaml
=> fix(configuration-service): Implemented endpoints for deleting service and stage resources (#5136) 

test/go-tests/go.sum
=> fix: Updated go-dependencies in integration tests (#5200)

bridge/client/app/_models/service.ts
=> fix(bridge): Set empty array when open remediations are not a sequence

lighthouse-service/event_handler/common.go, lighthouse-service/event_handler/configure_monitoring_handler.go, lighthouse-service/event_handler/configure_monitoring_handler_test.go, lighthouse-service/event_handler/handler.go, lighthouse-service/event_handler/handler_test.go, lighthouse-service/go.mod, lighthouse-service/go.sum
=> fix(lighthouse-service): Added error logs for failing monitoring configuration (#5088)

ADOPTERS.md
Added triscon to adopters list
=> chore: Added triscon to Adopters

distributor/pkg/config/envconfig.go, distributor/pkg/config/envconfig_test.go, distributor/pkg/lib/controlplane/controlplane.go, distributor/pkg/lib/events/receiver.go, distributor/pkg/lib/events/receiver_test.go
=> fix(distributor): fix issue of having no initial pubsub topic defined

configuration-service/common/git.go, configuration-service/common/git_test.go
=> fix(configuration-service): Make sure upstream changes are pulled when updating upstream creds (#5149)

test/go-tests/test_utils.go
Closes #5241 
In some rare cases (which for some reasons all occur on GKE 1.19), the sequence control integration test was failing due to the shipyard controller, which has been restarted during the previous test was apparently not ready. This PR introduces a retry mechanism for the project creation helper function in the test utils. This should hopefully improve the robustness of the integration tests
=> fix: Added retry mechanism for creating projects in integration tests (#5241)

shipyard-controller/handler/projecthandler.go, shipyard-controller/handler/projecthandler_test.go, shipyard-controller/handler/projectmanager.go, shipyard-controller/handler/projectmanager_test.go
=> fix(shipyard-controller): Return proper error message in case project is not available (#4399)

.github/workflows/integration_tests.yml, shipyard-controller/handler/sequence_migrator.go, shipyard-controller/handler/sequence_migrator_test.go, shipyard-controller/handler/shipyardcontroller.go, shipyard-controller/handler/shipyardcontroller_test.go, test/go-tests/sequencestate_test.go
=> fix(shipyard-controller): Adapted sequence state representation for case where sequence can not be started (#5137) 

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.ts, bridge/client/app/_services/data.service.mock.ts, bridge/client/app/_services/data.service.ts, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.html, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts
=> fix(bridge): fixed missing update on sequence screen (#5085)

lighthouse-service/event_handler/evaluate_sli_handler.go, lighthouse-service/event_handler/evaluate_sli_handler_test.go
-  adds an error message to calcscore
Fixes #5142
=> fix(lighthouse-service): calcscore missing error msg (#5142)

shipyard-controller/handler/sequence_migrator.go
=> fix(shipyard-controller): Remove log noise in sequence migrator (#5096)

bridge/client/app/_interceptors/http-error-interceptor.spec.ts, bridge/client/app/_interceptors/http-error-interceptor.ts, bridge/server/app.ts
=> fix(bridge): Show proper error messages if not OAUTH is configured and prevent login loop (#5086)

releasenotes/releasenotes_V0.9.1.md
=> docs: add release notes for Keptn 0.9.1

MAINTAINERS
- adds @RealAnna to mantainers list
=> chore: Update Maintainers file

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.scss, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.spec.ts, bridge/package-lock.json
Closes #5141 
Just added the proper class:
=> style(bridge): Show a gray thick border when a running sequence is selected (#5141)

bridge/server/app.ts
=> fix(bridge): fixed redirect to login page if OAuth is configured (#5370)

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_components/ktb-service-details/ktb-service-details.component.html, bridge/server/api/index.ts
=> chore(bridge): remove heatmap selection if deployment-sequence does not have an evaluation (#4636)

bridge/server/models/remediation.ts, bridge/server/services/data-service.ts, bridge/shared/models/remediation-action.ts
=> fix(bridge): handle incorrect remediation sequences (#5383)

test/go-tests/secrets_test.go
=> chore: fix integration test

bridge/client/app/_components/ktb-project-settings-shipyard/ktb-project-settings-shipyard.component.html, bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.html
=> fix(bridge): fixed shipyard file selection, if the same file was chosen again (#5380)

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts
=> fix(bridge): 'Show SLO' button was removed after loading evaluation results (#5393)

distributor/go.mod, distributor/go.sum, distributor/pkg/lib/events/forwarder.go, distributor/pkg/lib/events/model.go, distributor/pkg/lib/events/poller.go, distributor/pkg/lib/events/poller_test.go, distributor/pkg/lib/events/receiver.go, distributor/pkg/lib/events/receiver_test.go, distributor/pkg/lib/events/utils.go, distributor/pkg/lib/events/utils_test.go
=> feat(distributor): pass along subscription id to service implementation

bridge/server/interfaces/shipyard.ts, bridge/server/services/data-service.ts
=> fix(bridge): fixed task retrieval if shipyard does not contain any sequences (#5409)

distributor/pkg/lib/events/receiver.go
=> fix(distributor): Ensure that the subscriptionID is passed to the event (#5405)

bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.ts
=> fix(bridge): include time zone for 'trigger evaluation' command (#5398)

configuration-service/common/git.go, configuration-service/handlers/project.go, shipyard-controller/common/configurationstore.go, shipyard-controller/handler/common.go, shipyard-controller/handler/projecthandler.go, shipyard-controller/handler/projecthandler_test.go
=> fix: handle error and use dedicated http err code when failing to update project due to wrong token

bridge/server/models/service.ts, bridge/server/services/data-service.ts
=> chore(bridge): set latest sequence depending on the latest event (#5148)

configuration-service/handlers/project_resource.go, configuration-service/handlers/service_resource.go, configuration-service/handlers/stage_resource.go
=> fix(configuration-service): fixed paths in git commit messages

bridge/IntelliJ.xml, bridge/README.md, bridge/settings.json
=> docs(bridge): IDE ESLint setup (#4648)

webhook-service/lib/curl_executor.go, webhook-service/lib/curl_executor_test.go
This PR introduces additional checks for the curl commands provided to the webhook service
=> feat: Additional curl command validation to increase security

lighthouse-service/event_handler/common.go, lighthouse-service/event_handler/common_test.go
=> fix(lighthouse-service): Check for nil entries in SLO objectives (#5522)

approval-service/main.go, configuration-service/restapi/configure_configuration_service.go, distributor/pkg/lib/events/forwarder.go, helm-service/main.go, installer/manifests/keptn/charts/control-plane/templates/_helpers.tpl, installer/manifests/keptn/charts/control-plane/templates/core.yaml, jmeter-service/main.go, lighthouse-service/main.go, mongodb-datastore/restapi/configure_mongodb_datastore.go, remediation-service/main.go, secret-service/main.go
-adds liveness and readiness probes
-modifies installer yaml files
-changes default probes 
Fixes #5303
=> fix: added probes for readiness and liveness (#5303)

distributor/cmd/main.go, distributor/pkg/lib/events/forwarder_test.go, distributor/pkg/lib/events/nats_connection_handler.go, distributor/pkg/lib/events/nats_connection_handler_test.go, distributor/pkg/lib/events/poller.go, distributor/pkg/lib/events/receiver.go, distributor/pkg/lib/events/receiver_test.go
=> fix(distributor): fix subscription handling after message broker reconnect

.github/workflows/integration_tests.yml
=> test: Increase timeout for sequence queue test (#5834)

test/go-tests/uniform_test.go
=> test: Increase the uniform TTL to its original value after testing the integration timeout  (#5834)

bridge/client/app/_components/ktb-notification-bar/ktb-notification-bar.component.scss, bridge/client/app/_components/ktb-project-settings-git/ktb-project-settings-git.component.html, bridge/client/app/_components/ktb-project-settings-git/ktb-project-settings-git.component.spec.ts, bridge/client/app/_components/ktb-project-settings-git/ktb-project-settings-git.component.ts, bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.html, bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.scss, bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.spec.ts, bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.ts, bridge/client/app/_services/data.service.mock.ts, bridge/client/app/_services/data.service.ts, bridge/client/app/app.routing.ts, bridge/cypress/integration/navigation-buttons-evaluation-screen-test.ts, bridge/cypress/integration/project-delete.spec.ts, bridge/cypress/tsconfig.json, bridge/server/tsconfig.json, bridge/server/tsconfig.spec.json, bridge/tsconfig.json
=> refactor(bridge): Refactoring of project settings / create project (#5100)

.github/dependabot.yml
- adds the webhook-service to dependabot
=> ci: Add webhook service to dependabot

bridge/client/app/_services/data.service.ts
=> fix(bridge): Fixed overwriting of data in environment screen (#5841)

bridge/client/app/_components/ktb-sequence-list/ktb-sequence-list.component.ts, bridge/client/app/_components/ktb-task-item/ktb-task-item.component.html, bridge/client/app/_models/trace.ts
=> fix(bridge): Show right event type (#5828)

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts, bridge/package.json, bridge/shared/interfaces/slo-config.ts, bridge/shared/models/trace.ts, bridge/yarn.lock
=> fix(bridge): Take SLI-weight out of SLO-file (#5782)

MAINTAINERS
=> chore: Add @RealAnna to Maintainers list

.github/ISSUE_TEMPLATE/bug_report.md
=> chore: Add the correct label for bug reports

api/restapi/configure_keptn.go, approval-service/main.go, configuration-service/restapi/configure_configuration_service.go, distributor/cmd/main.go, distributor/pkg/lib/events/forwarder.go, helm-service/chart/templates/deployment.yaml, helm-service/main.go, installer/manifests/keptn/charts/control-plane/templates/_helpers.tpl, installer/manifests/keptn/charts/control-plane/templates/continuous-operations.yaml, installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml, jmeter-service/chart/templates/deployment.yaml, jmeter-service/main.go, lighthouse-service/main.go, remediation-service/go.mod, remediation-service/go.sum, remediation-service/main.go, secret-service/main.go, webhook-service/go.mod, webhook-service/go.sum, webhook-service/main.go
- adds liveness and readiness
Fixes #5303
=> feat: added probes for readiness and liveness (#5303) 

.github/workflows/auto-update-go-utils.yml, .github/workflows/auto-update-k8s-utils.yml, .github/workflows/auto-update-keptn-spec.yml
- updates all auto-update GH actions pipelines so that they are conform with our guidelines and checks for semantic PRs
Fixes #5837
=> fix: Update auto-update pipelines to follow keptns semantic PR guidelines

go-sdk/pkg/sdk/keptn.go
=> fix: Adapt log level of SDK logs (#5920)

shipyard-controller/db/mock/eventrepo_mock.go, shipyard-controller/db/mock/projectrepo_mock.go, shipyard-controller/db/mock/tasksequencerepo_mock.go, shipyard-controller/db/mock/uniformrepo_mock.go, shipyard-controller/db/mongodb_event_repo.go, shipyard-controller/db/mongodb_task_sequence_repo.go, shipyard-controller/db/mongodb_task_sequence_repo_test.go, shipyard-controller/db/repos.go, shipyard-controller/handler/eventdispatcher.go, shipyard-controller/handler/eventdispatcher_test.go, shipyard-controller/handler/projectmanager.go, shipyard-controller/handler/projectmanager_test.go, shipyard-controller/handler/sequence_migrator.go, shipyard-controller/handler/sequencedispatcher.go, shipyard-controller/handler/sequencedispatcher_test.go, shipyard-controller/handler/shipyardcontroller.go, shipyard-controller/handler/shipyardcontroller_component_test.go, shipyard-controller/handler/shipyardcontroller_hooks.go, shipyard-controller/handler/shipyardcontroller_test.go, shipyard-controller/handler/shipyardcontroller_utils.go, shipyard-controller/handler/shipyardcontroller_utils_test.go, shipyard-controller/main.go, shipyard-controller/models/eventscope.go, shipyard-controller/models/eventscope_test.go, shipyard-controller/models/tasksequence.go
part of #5243
integration test run: https://github.com/keptn/keptn/actions/runs/1436224211
=> chore(shipyard-controller): cleanups & refactorings 2

jmeter-service/chart/templates/serviceaccount.yaml
- removes ClusterRoleBinding from jmeter chart 
#5543
=> chore: removed cluster role binding (#5543)

bridge/client/app/_views/ktb-integration-view/ktb-integration-view.component.ts
Fixes #5941 
I also edited the currentTime method to get not the current time, but 5 minutes earlier, as the lighthouse service will otherwise complain.
=> fix(bridge): Fix integration curl commands for api (#5941)

go-sdk/pkg/sdk/keptn.go, go-sdk/pkg/sdk/keptn_fake.go, go-sdk/pkg/sdk/keptn_test.go
- adds context with cancel to use for graceful shutdown of services
#4522
=> feat: Added context with cancel function to sdk (#4552)

bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.spec.ts, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts
=> fix(bridge): Fixed wrong weight of SLI (#5987)

go-sdk/pkg/sdk/keptn.go, go-sdk/pkg/sdk/keptn_test.go, webhook-service/deploy/service.yaml
- fixes invalid conversion of *.started eventType to *.finished eventType
Fixes #5953
- detailed description in issue https://github.com/keptn/keptn/issues/5953
=> fix(webhook-service): invalid conversion of eventType

bridge/client/app/app.module.ts, bridge/client/app/app.routing.ts, bridge/client/app/not-found/not-found.component.html, bridge/client/app/not-found/not-found.component.scss, bridge/client/app/not-found/not-found.component.spec.ts, bridge/client/app/not-found/not-found.component.ts
- adds a 404 page and handles all undefined route links
Fixes #4983
=> feat(bridge): Add 404 page (#4983)

.github/workflows/integration_tests.yml, jmeter-service/common.go, jmeter-service/eventhandler.go, jmeter-service/jmeterUtils.go, jmeter-service/jmeterUtils_test.go, jmeter-service/main.go, jmeter-service/main_test.go, jmeter-service/model.go, jmeter-service/testrunner.go
closes #5916 
This PR reduces the cognitive complexity of various parts of the JMeter Service.
Followup issue to increase test coverage: https://github.com/keptn/keptn/issues/6030
integration test run: 
https://github.com/keptn/keptn/actions/runs/1467751321 
integration tests after review:
https://github.com/keptn/keptn/actions/runs/1471352556
=> chore(jmeter-service): cleanups

configuration-service/common/common.go, configuration-service/common/git.go, configuration-service/deploy/service.yaml, configuration-service/handlers/project.go
- adds an error handling  failure in updating a git upstream as 404
Fixes #5977
=> fix: Handle upstream not found (#5977)

MAINTAINERS
- Adds @TannerGilbert as project member
- https://github.com/keptn/community/issues/58
=> chore: Add TannerGilbert as project member

approval-service/pkg/handler/approval_triggered_event_handler.go, approval-service/pkg/handler/approval_triggered_event_handler_test.go, approval-service/pkg/handler/handler_test.go, test/go-tests/deliveryassistant_test.go
=> fix(approval-service): Fall back to manual strategy when there is no result available (#6012)

configuration-service/handlers/service_resource.go, test/go-tests/go.sum
=> fix(configuration-service): Fix order of extracting and adding files to the repo (#6041)

configuration-service/common/git.go, configuration-service/common/git_test.go, configuration-service/handlers/service_resource.go
Closes #6050 
Integration test run: https://github.com/keptn/keptn/actions/runs/1477137808
=> fix(configuration-service): Completely replace previous helm chart directory when updating (#6050)

bridge/client/app/_components/ktb-service-details/ktb-service-details.component.ts, bridge/server/services/data-service.ts
Fixes #6053 
Also fixed the missing problem title of the remediations
=> fix(bridge): Fixed missing problem title and decode of remediation config (#6053)

MAINTAINERS
- adding odubajDT as a maintainer
Fixes #60
=> chore: Add odubajDT as maintainer

bridge/server/app.ts
- adjusts the log to not show the x-token when an error occurs
Fixes #6047
=> fix(bridge): don't log err (contains the x-token), only log err.message (#6047)

.github/workflows/integration_tests.yml
=> chore: Increase timeout of DeliveryAssistant integration test (#6067)

helm-service/controller/action_handler.go, helm-service/controller/action_handler_test.go, helm-service/controller/delete_handler.go, helm-service/controller/delete_handler_test.go, helm-service/controller/deployment_handler.go, helm-service/controller/deployment_handler_test.go, helm-service/controller/release_handler.go, helm-service/controller/release_handler_test.go, helm-service/controller/rollback_handler.go
- reduce information in error message
=> chore(helm-service): More meaningful error messages

bridge/client/app/evaluation-board/evaluation-board.component.scss
=> feat(bridge): Prevent cut off of evaluation board (#5279)

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.scss, bridge/client/app/_components/ktb-sequence-list/ktb-sequence-list.component.html, bridge/client/app/_components/ktb-sequence-state-info/ktb-sequence-state-info.component.html, bridge/client/app/_components/ktb-sequence-timeline/ktb-sequence-timeline.component.html, bridge/client/app/_components/ktb-services-list/ktb-services-list.component.html, bridge/client/app/_models/sequence.ts
=> fix(bridge): Correctly show warning state (#6003)

cli/cmd/upgrade.go
=> chore: use correct link in CLI upgrade message

.github/workflows/CI.yml
This PR fixes the behavior of the `build-everything` CI runs for Pull requests
=> ci: Build everything should always build everything

.github/workflows/CI.yml, shipyard-controller/db/mongodb_state_repo.go, shipyard-controller/db/mongodb_state_repo_test.go, shipyard-controller/handler/statehandler.go, test/go-tests/sequencestate_test.go, test/go-tests/test_utils.go
Closes #6056
Integration test run: https://github.com/keptn/keptn/actions/runs/1495544214
=> feat(shipyard-controller): Allow to filter sequence states by multiple keptnContext IDs (#6056)

bridge/client/index.html, bridge/package.json, bridge/server/app.ts
=> fix(bridge): Fix problem with redirect and headers on cluster

bridge/client/app/_services/data.service.ts
=> fix(bridge): Fixed removal of sequences if project endpoint of bridge server responds before projects endpoint of shipyard (#6183)

bridge/client/app/_components/ktb-variable-selector/ktb-variable-selector.component.spec.ts
Fixes the failing unit test in master.
=> test(bridge): Fixed unit test

.github/workflows/pre-release.yml, .github/workflows/release.yml
- fixes a bug where the enforced release version was not taken into account during release pipeline runs
=> ci: Fix bug where enforced release version was not respected in the release pipelines

remediation-service/handler/get_action_event_handler.go
This PR closes #5548
- add problem title to event message 
Signed-off-by: Brad McCoy <bradmccoydev@gmail.com>
=> fix(remediation-service): add problemTitle to event message

approval-service/main.go, approval-service/pkg/handler/handler.go, go-sdk/pkg/sdk/keptn.go, installer/manifests/keptn/charts/control-plane/templates/_helpers.tpl, installer/manifests/keptn/charts/control-plane/templates/continuous-operations.yaml, installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml, installer/manifests/keptn/charts/control-plane/values.yaml, platform-support/openshift-route-service/main.go, remediation-service/go.mod, remediation-service/go.sum, secret-service/main.go, statistics-service/controller/gracefulshutdownmiddleware.go, statistics-service/main.go, webhook-service/go.mod, webhook-service/go.sum, webhook-service/handler/test/events/test-webhook.finished.json, webhook-service/handler/test/events/test-webhook.started.json, webhook-service/handler/test/events/test-webhook.triggered-0.json, webhook-service/handler/test/events/test-webhook.triggered-no-subscription-id.json
- updates sdk and import it
- adds sigterm to secret service
- adds sigterm to statistic service
- adds sigterm to approval service
- adds to distributors prestop hooks
- adds shorter grace period 
Fixes #4522 
create chaos testing to verify graceful shutdown
=> feat: Finalize graceful shutdown (#4522)

bridge/client/app/_views/ktb-service-view/ktb-service-view.component.ts, bridge/cypress/fixtures/get.projects.json, bridge/cypress/integration/navigation-project-change.spec.ts, bridge/cypress/support/pageobjects/BasePage.ts
=> fix(bridge): Update services on project change (#6252)

mongodb-datastore/db/mongodb_connection.go, mongodb-datastore/db/mongodb_event_repo.go, mongodb-datastore/db/mongodb_event_repo_test.go
=> fix(mongodb-datastore): Ensure MongoDB Client is not nil before retrieving database (#6251)

cli/internal/cespec/data.go, cli/internal/cespec/genspec.go
=> fix(cli): Added rollback events to generated spec (#3722)

bridge/server/app.ts
=> fix(bridge): Allow server inline script for base href (#6248)

webhook-service/handler/handler.go, webhook-service/lib/template_engine_test.go, webhook-service/lib/webhook_config.go, webhook-service/lib/webhook_config_test.go
- adds unit tests for webhook-config and improved error messages
Fixes #5692
=> feat: Added unit tests for webhook-service and improved error messages

.github/workflows/integration_tests.yml, test/go-tests/backuprestore_test.go, test/go-tests/test_utils.go
- fixed minor issue in backup_restore.go test regarding waiting for deployment in production for unstable version 0.1.1
Fixes #6239
=> fix: Backup and restore integration test

bridge/server/.jest/setupServer.ts, bridge/server/.jest/test.utils.ts, bridge/server/app.ts, bridge/server/fixtures/project-details-response.mock.ts
Fixes currently failing tests of the bridge-server
=> fix(bridge): Fixed bridge server tests

MAINTAINERS
Signed-off-by: Oleg Nenashev <o.v.nenashev@gmail.com>
Fixes #1234523
=> chore: Add @oleg-nenashev to the list of contributors

secret-service/README.md
=> chore(secret-service): Updated README.md

cli/cmd/auth.go, cli/cmd/auth_test.go
- fixes wrong handling of HTTPS in auth command
Fixes #6267
=> fix(cli): wrong handling of HTTPS in auth command

bridge/client/app/_components/ktb-services-list/ktb-services-list.component.html, bridge/client/app/_components/ktb-services-list/ktb-services-list.component.ts, bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.html, bridge/client/app/_components/ktb-stage-details/ktb-stage-details.component.ts, bridge/client/app/_components/ktb-stage-overview/ktb-stage-overview.component.html, bridge/client/app/_components/ktb-stage-overview/ktb-stage-overview.component.ts, bridge/client/app/_models/project.ts, bridge/client/app/_models/stage.ts, bridge/client/app/_services/data.service.ts, bridge/client/app/_views/ktb-environment-view/ktb-environment-view.component.html, bridge/client/app/_views/ktb-environment-view/ktb-environment-view.component.ts, bridge/cypress/fixtures/get.project.json, bridge/shared/models/project.ts
=> fix(bridge): Fixed environment screen update issues (#6271)

bridge/client/app/_interceptors/http-error-interceptor.ts
- makes sure that for OAUTH the Toast is only displayed and no error message.
=> fix(bridge): fix showing error message for OAUTH

bridge/client/app/_components/ktb-copy-to-clipboard/ktb-copy-to-clipboard.component.scss, bridge/client/app/_components/ktb-create-secret-form/ktb-create-secret-form.component.html, bridge/client/app/_components/ktb-deployment-stage-timeline/ktb-deployment-stage-timeline.component.scss, bridge/client/app/_components/ktb-secrets-list/ktb-secrets-list.component.html, bridge/client/app/_components/ktb-sequence-state-list/ktb-sequence-state-list.component.scss, bridge/client/app/_components/ktb-sequence-state-list/ktb-sequence-state-list.component.ts, bridge/client/app/_components/ktb-subscription-item/ktb-subscription-item.component.scss, bridge/client/app/app-header/app-header.component.scss, bridge/client/app/project-board/project-board.component.scss, bridge/client/styles.scss
Adds hint to secret list and create secret form that secrets are shared among all projects.
Closes #5832
=> feat(bridge): Add hint that secrets are shared among all projects (#5832)

bridge/server/test/bridge-info.spec.ts
=> fix(bridge): Fixed bridge server test

bridge/client/app/_components/ktb-deployment-stage-timeline/ktb-deployment-stage-timeline.component.html, bridge/client/app/_components/ktb-deployment-stage-timeline/ktb-deployment-stage-timeline.component.ts
=> fix(bridge): Fixed incorrect deployment link title (#6304)

mongodb-datastore/db/mongodb_connection.go, mongodb-datastore/db/mongodb_event_repo.go, mongodb-datastore/db/mongodb_event_repo_test.go
=> fix(mongodb-datastore): Ensure MongoDB Client is not nil before retrieving database (#6251) 

statistics-service/db/migrator.go, statistics-service/db/migrator_test.go
backport of: https://github.com/keptn/keptn/pull/6324
=> fix(statistics-service): migration of keptn service execution data (#6250)

configuration-service/common/git.go, configuration-service/common/git_test.go, configuration-service/handlers/project.go, configuration-service/restapi/configure_configuration_service.go, installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/values.yaml
Backport of #6317
CLoses #6315
=> fix(configuration-service): Fix permission issues for configuration service (#6315)

configuration-service/Dockerfile, configuration-service/models/project.go, configuration-service/models/resource.go, configuration-service/models/resources.go, configuration-service/models/stage.go, configuration-service/restapi/embedded_spec.go, configuration-service/restapi/operations/project_resource/post_project_project_name_resource.go, configuration-service/restapi/operations/project_resource/put_project_project_name_resource.go, configuration-service/restapi/operations/service_default_resource/post_project_project_name_service_service_name_resource.go, configuration-service/restapi/operations/service_default_resource/put_project_project_name_service_service_name_resource.go, configuration-service/restapi/operations/service_resource/post_project_project_name_stage_stage_name_service_service_name_resource.go, configuration-service/restapi/operations/service_resource/put_project_project_name_stage_stage_name_service_service_name_resource.go, configuration-service/restapi/operations/stage_resource/post_project_project_name_stage_stage_name_resource.go, configuration-service/restapi/operations/stage_resource/put_project_project_name_stage_stage_name_resource.go, configuration-service/restapi/server.go, configuration-service/swagger.yaml
- improves the documentation of the configuration-service APIs
I used swagger v0.28.0 to generate it, hence there are also some code changes. The real changes are in the [swagger.yaml](https://github.com/keptn/keptn/pull/6008/files#diff-05ae4d3860a9c5f933fea62920fb51890c6b9dc8d129374e993df7ecc97761b2) file
=> docs(configuration-service): Update API documentation

configuration-service/handlers/service_resource.go
=> fix(configuration-service): Create tmpdir for unarchiving in /data/config

configuration-service/common/error_messages.go, configuration-service/common/git.go, configuration-service/common/git_test.go, shipyard-controller/common/keptn_helpers.go, shipyard-controller/common/keptn_helpers_test.go, shipyard-controller/common/secretstore.go, shipyard-controller/handler/error.go, shipyard-controller/handler/projectmanager.go, shipyard-controller/main.go, shipyard-controller/models/project.go
- update error messages to generic ones
=> fix: Update error messages

shipyard-controller/db/mongodb_project_mv_repo.go, shipyard-controller/db/mongodb_project_mv_repo_test.go, shipyard-controller/main.go, test/go-tests/qualitygate_test.go
=> feat(shipyard-controller): Add .triggered events to `lastEventTypes` property of materialized view (#6220)

cli/cmd/helpers.go, cli/cmd/root_test.go, cli/cmd/trigger_delivery.go, cli/cmd/trigger_delivery_test.go, cli/go.sum, cli/internal/cespec/data.go
- fixed triggered delivery when using non-existing service
Fixes #6288
=> fix(cli): Print error message if service does not exist with `trigger delivery`

shipyard-controller/db/mongodb_state_repo_test.go
- adds error check in shipyard-controller test
=> fix: Unit test in shipyard-controller

distributor/cmd/main.go, distributor/pkg/lib/events/uniformwatch.go, shipyard-controller/handler/shipyardcontroller.go
- updates go utils
- exits if integrationID is empty
Fixes #6309
=> fix(distributor): Forcing restart if integration is malformed (#6309)

bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.html, bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.spec.ts, bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.ts, bridge/client/app/_utils/form.utils.ts
=> feat(bridge): Add validation for payload if it contains specific characters (#5950)

test/go-tests/backuprestore_test.go, test/go-tests/continuous_delivery_test.go, test/go-tests/graceful_shutdown_test.go
- fixes flaky errors of backup-restore integration test
Fixes #6342 #6393
=> fix: Stabilize BackupRestore integration test

lighthouse-service/README.md
=> chore: Correct example lighthouse criteria (#6160)

jmeter-service/Dockerfile
Just for testing. Ideally we need 5.4.3 which is yet to be released
Signed-off-by: Oleg Nenashev <o.v.nenashev@gmail.com>
Fixes #1234523
=> fix: Update the JMeter Service to JMeter 5.4.2

installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/values.yaml, test/go-tests/go.sum
- adds a helm value for configuration service version selection
Fixes #6336
=> feat: Add helm value for configuration-service version selection

cli/cmd/upgrade.go
- adds missing upstream warning during keptn upgrade
Fixes #6308
=> feat(cli): Add missing upstream warning during 'keptn upgrade'

CONTRIBUTORS.md, MAINTAINERS
=> chore: Update contributor lists

test/go-tests/graceful_shutdown_test.go
=> fix: Graceful shutdown failing test (#6462)

configuration-service/go.mod, configuration-service/go.sum, configuration-service/handlers/project.go
This PR removes an unneeded dependency to `github.com/google/martian`
=> build(deps): Removed unneeded dependency

jmeter-service/Dockerfile
=> chore: Bump JMeter to latest version

.github/renovate.json
=> ci: Use correct Renovate Preset for auto-merging

jmeter-service/jmeterUtils.go
=> feat(jmeter-service): Improve error reporting for JMeter-service

test/go-tests/test_graceful_shutdown.go
- adds logging and delay
- Integration test passed https://github.com/keptn/keptn/runs/4700660720?check_suite_focus=true#step:53:46 
Fixes #6485
=> fix: Added delay and logging to graceful shutdown (#6485)

cli/cmd/helpers.go, cli/cmd/send_event_newArtifact_test.go, cli/cmd/trigger_delivery.go, cli/cmd/trigger_delivery_test.go
=> feat: Improve error reporting for CLI trigger cmd

MAINTAINERS
Signed-off-by: Juergen Etzlstorfer <jetzlstorfer@microsoft.com>
- updates the affiliation of my user jetzlstorfer
=> chore: update affiliation

VERSIONING.MD
=> docs: Add Keptn versioning and version compatibility document

configuration-service/deploy/service.yaml, test/go-tests/test_graceful_shutdown.go, test/go-tests/test_resourceservice.go
=> fix: minor fix in integration tests + added configuration-service securityContext

docs/integration_tests.md
- Updates outdated Integration Tests Developer documentation
Fixes #3509
=> docs: Update Integration Tests Developer documentation

shipyard-controller/db/mongodb_connection.go
Integration test run: https://github.com/keptn/keptn/actions/runs/1602590373
With new integration test pipeline: https://github.com/keptn/keptn/actions/runs/1686835486
=> perf(shipyard-controller): Remove DB connection locking

installer/manifests/keptn/charts/control-plane/templates/core.yaml
=> fix: Increase Bridge memory limits to avoid OOM

MAINTAINERS
FTR https://github.com/keptn/community/issues/91
Signed-off-by: Oleg Nenashev <o.v.nenashev@gmail.com>
Fixes #1234523
=> chore: Promote @oleg-nenashev to maintainers

cli/pkg/helm/helm_helper.go
Closes #6437
Note: Adding unit tests for this fix requires a larger refactoring of the helm helper.
How to test:
Install Keptn with continuous delivery use case with a faulty configuration of the helm service (e.g. with woring readinessProbe configured) - the URL to the modified chart can be provided with the `--chart-repo` option:
```
keptn install --use-case=continuous-delivery --chart-repo=http://my-faulty-chart
```
Without the fix, the installation will still go through, regardless of the helm-service being able to to be deployed correctly or not:
```
Installing Keptn ...
Helm Chart used for Keptn installation: http://0.0.0.0:8000/keptn-0.11.2-dev-0-11-x.tgz
Start upgrading Helm Chart keptn in namespace keptn2
Finished upgrading Helm Chart keptn in namespace keptn2
Keptn control plane …
```
=> fix(cli): Fix error handling during helm installation (#6437)

bridge/client/_barista.scss, bridge/client/_variables.scss, bridge/client/app/_components/ktb-deployment-stage-timeline/ktb-deployment-stage-timeline.component.scss, bridge/client/app/_components/ktb-keptn-services-list/ktb-keptn-services-list.component.scss, bridge/client/app/_components/ktb-notification-bar/ktb-notification-bar.component.scss, bridge/client/app/_components/ktb-project-tile/ktb-project-tile.component.scss, bridge/client/app/_components/ktb-service-details/ktb-service-details.component.scss, bridge/client/app/_components/ktb-tree-list-select/ktb-tree-list-select.component.scss, bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.scss, bridge/client/app/_services/app.init.ts, bridge/client/app/app-header/app-header.component.scss, bridge/client/app/dashboard/dashboard.component.scss, bridge/client/assets/default-branding/app-config.json, bridge/client/assets/default-branding/keptn-theme.css, bridge/client/styles.scss
- introduces a keptn color scheme for Buttons, Icons, etc.
Fixes #5081
=> feat(bridge): Introduce keptn color scheme #5081

installer/manifests/keptn/charts/control-plane/templates/ingress.yaml
Fixes #4407 
Integration Tests: https://github.com/keptn/keptn/actions/runs/1707575219
=> fix: Support Openshift 3.11

api/go.mod, api/go.sum, api/handlers/event.go, api/models/keptn_context_extended_c_e.go, api/restapi/embedded_spec.go, api/restapi/operations/event/post_event.go, api/restapi/operations/event/post_event_parameters.go, api/utils/event.go, distributor/go.mod, distributor/go.sum, mongodb-datastore/go.mod, mongodb-datastore/go.sum, mongodb-datastore/models/keptn_context_extended_c_e.go, mongodb-datastore/restapi/embedded_spec.go, shipyard-controller/common/configurationstore.go, shipyard-controller/common/fake/configurationstore_mock.go, shipyard-controller/go.mod, shipyard-controller/go.sum, shipyard-controller/handler/fake/shipyardretriever_mock.go, shipyard-controller/handler/shipyardcontroller.go, shipyard-controller/handler/shipyardcontroller_component_test.go, shipyard-controller/handler/shipyardretriever.go, shipyard-controller/handler/shipyardretriever_test.go, shipyard-controller/models/event.go, shipyard-controller/models/eventscope.go, test/go-tests/go.mod, test/go-tests/go.sum, test/go-tests/test_sequencestate.go
=> feat(shipyard-controller): Propagate git commit ID passed in sequence.triggered events (#6348)

cli/cmd/create.go
- re-adds the changes done in #5292 by @Dynatrace-Adam-Gardner since the old PR got stale and outdated
=> fix(cli): Added missing command description for `keptn create secret`

helm-service/chart/values.schema.json, jmeter-service/chart/values.schema.json
- fixes the JSON schema used for the helm values in jmeter-service and helm-service
=> fix(installer): Fixed helm/jmeter service helm values schema

.github/workflows/CI.yml
- changes the conditional to push docker images so that (hopefully) master images are pushed again
=> ci: Fix master builds not pushing docker images

installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml, installer/manifests/keptn/charts/control-plane/templates/continuous-operations.yaml, installer/manifests/keptn/charts/control-plane/templates/core.yaml, installer/manifests/keptn/charts/control-plane/templates/mongodb-datastore.yaml, installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml, installer/manifests/keptn/charts/control-plane/templates/rbac.yaml
Integration test run: https://github.com/keptn/keptn/actions/runs/1738995423
=> feat: Update pod config to be more strict w.r.t. security

helm-service/chart/templates/deployment.yaml, installer/manifests/keptn/charts/control-plane/templates/_helpers.tpl, jmeter-service/chart/templates/deployment.yaml, test/go-tests/test_uniform.go
=> fix(installer): Set distributor version in helm chart (#6652)

bridge/client/app/_components/ktb-project-settings-git/ktb-project-settings-git.component.html, bridge/client/app/_components/ktb-project-tile/ktb-project-tile.component.html, bridge/cypress/integration/git-credentials-edit.spec.ts
=> style(bridge): Change message for project without repo that it is not  supported in future (#6307)

bridge/client/app/_components/ktb-create-secret-form/ktb-create-secret-form.component.ts, bridge/client/app/_interceptors/http-error-interceptor.spec.ts, bridge/client/app/_interceptors/http-error-interceptor.ts
=> feat(bridge): Show specific error message if secret already exists (#6297)

cli/cmd/get_event_approvalTriggered.go, cli/cmd/send_event_approvalFinished.go, cli/go.mod, cli/go.sum
Just adjusted the code of CLI to the recent changes made in go-utils with [this](https://github.com/keptn/go-utils/pull/379) PR
=> chore: adjustments to recent changes in go-utils

installer/airgapped/pull_and_retag_images.sh, installer/manifests/keptn/charts/control-plane/Chart.yaml, installer/manifests/keptn/charts/control-plane/templates/mongodb-credentials.yaml, installer/manifests/keptn/charts/control-plane/values.yaml
* build(deps): update helm release mongodb to v10.31.3
Signed-off-by: Renovate Bot <bot@renovateapp.com>
* update mongo image in airgapped script, update custom mongo values
* also support new value in mongo credentials secret
Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: Moritz Wiesinger <moritz.wiesinger@dynatrace.com>
Fixes #1234523
=> build(deps): update helm release mongodb to v10.31.3 (#6539)

installer/airgapped/pull_and_retag_images.sh, installer/manifests/keptn/charts/control-plane/Chart.yaml, installer/manifests/keptn/charts/control-plane/templates/mongodb-credentials.yaml, installer/manifests/keptn/charts/control-plane/values.yaml
revert of https://github.com/keptn/keptn/commit/240828ca78e0851e2cd64f3b69d9bed9a8dfaecb
=> revert: Revert MongoDB version upgrade

bridge/package.json, bridge/yarn.lock
=> chore(bridge): Remove unused dependency puppeteer

bridge/cypress/integration/project-delete.spec.ts
https://github.com/keptn/keptn/runs/5048484837?check_suite_focus=true
=> test: Fix currently failing UI test

api/handlers/metadata.go, api/handlers/metadata_test.go
=> perf: Directly return Bridge version

jmeter-service/testrunner.go
- jmeter-service should finish processes and return from functions when '.finished' event is sent
Fixes #6778 
Integration tests: https://github.com/keptn/keptn/actions/runs/1806186583
=> fix(jmeter-service): Finish processes when '.finished' event is sent

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.ts, bridge/cypress/integration/sequences.spec.ts
=> fix(bridge): Fixed incorrectly shown loading indicator in sequence list (#6579)

test/go-tests/init_test.go
disables OOM check
fixes #6810
=> ci: Disabled OOM check

shipyard-controller/handler/eventdispatcher.go, shipyard-controller/handler/sequencehooks/fake/sequenceaborted.go, shipyard-controller/handler/sequencehooks/hooks.go, shipyard-controller/handler/sequencehooks/sequencestate.go, shipyard-controller/handler/shipyardcontroller.go, shipyard-controller/handler/shipyardcontroller_component_test.go, shipyard-controller/handler/shipyardcontroller_hooks.go, shipyard-controller/handler/shipyardcontroller_utils.go, shipyard-controller/handler/shipyardcontroller_utils_test.go
=> fix(shipyard-controller): Reflect cancellation in sequence state even when no triggered event is there anymore

cli/pkg/credentialmanager/handler.go, cli/pkg/version/version_checker.go
- fixes wrong CLI new version checker message
Fixes #6858
=> fix(cli): CLI new version checker message

installer/manifests/keptn/charts/control-plane/templates/mongodb-credentials.yaml
=> fix(installer): External connection string not used while helm upgrade

bridge/server/user/oauth-routes.ts
=> chore(bridge): Added log for used OAuth scope

bridge/cypress/integration/git-credentials-edit.spec.ts
=> test(bridge): Fix UI test

bridge/client/app/_models/sequence.spec.ts, bridge/client/app/_models/sequence.ts, bridge/shared/models/sequence.ts
=> fix(bridge): Fix failed sequence shown as succeeded

configuration-service/common/git.go, configuration-service/common/git_test.go
Closes #6881 
Forward port of #6876
=> fix(configuration-service): Adapt to different response from git CLI when upstream branch is not there yet 

cli/go.mod, cli/go.sum, configuration-service/go.mod, configuration-service/go.sum, helm-service/go.mod, helm-service/go.sum, test/go-tests/go.mod, test/go-tests/go.sum
=> build(deps): Auto-update kubernetes-utils to 0.13.0

installer/manifests/keptn/charts/control-plane/templates/_helpers.tpl, installer/manifests/keptn/charts/control-plane/templates/rbac.yaml
- makes use of the common labels helpers function and removes duplicate code by just using it
=> chore(installer): Cleaned up common labels

cli/cmd/root_test.go
- adds missing env variables to tests
=> fix(cli): Added missing env variables to tests

.github/workflows/pre-release.yml, .github/workflows/release.yml
=> ci: Fix release pipeline not uploading helm charts correctly

cli/cmd/auth.go, cli/cmd/authenticator.go, cli/cmd/authenticator_test.go, cli/cmd/status.go, cli/internal/auth/mocks.go, cli/internal/auth/store.go, distributor/pkg/lib/events/poller.go
=> fix: Hardening of OAuth in distributor and CLI

MAINTAINERS
- Adds @pchila as member of the keptn project
Fixes https://github.com/keptn/community/issues/102
=> chore: Add @pchila as member to maintainers.md

distributor/README.md, distributor/pkg/config/const.go, distributor/pkg/config/envconfig.go, distributor/pkg/config/envconfig_test.go, distributor/pkg/lib/client/client.go
=> fix(distributor): Increase timeout of http client to 30s

distributor/go.mod, distributor/go.sum
Updates to the latest go-utils version which includes several fixes for interacting with the Keptn API
=> fix(distributor): Update go-utils dependencies

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/cypress/fixtures/get.sockshop.service.carts.deployment.mock.json, bridge/cypress/fixtures/get.sockshop.service.carts.evaluations.mock.json, bridge/cypress/fixtures/get.sockshop.service.states.mock.json, bridge/cypress/integration/evaluations.spec.ts
- is rounding the evaluation score correctly
Fixes #6890
=> fix(bridge): Rounding evaluation score correctly

bridge/README.md, bridge/cypress/integration/notification.spec.ts, bridge/server/app.ts, bridge/server/user/oauth.ts
=> fix(bridge): Fix incorrect content security policy

distributor/pkg/lib/events/poller.go, distributor/pkg/lib/events/poller_test.go
This PR fixes a flaky unit test in the distributor code.
I've executed the unit test x100 and it was failing every ~ 1/50 or so:
**Before fix:** :-1: 
**After fix:** :+1:
=> chore(distributor): hardening of unit test stability

cli/internal/api.go, cli/internal/api_test.go, cli/internal/auth/mocks.go, cli/internal/auth/oauth.go, cli/internal/auth/oauth_test.go
=> feat(cli): trigger authorization code flow when refresh token is expired

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_pipes/truncate-number.pipe.spec.ts, bridge/client/app/_pipes/truncate-number.ts, bridge/client/app/app.module.ts, bridge/cypress/fixtures/get.sockshop.service.carts.evaluations.mock.json, bridge/cypress/integration/evaluations.spec.ts
- is truncating the evaluation score correctly
Fixes #6890
=> fix(bridge): Truncate evaluation score

shipyard-controller/db/mock/uniformrepo_mock.go, shipyard-controller/db/mongodb_uniform_repo.go, shipyard-controller/db/mongodb_uniform_repo_test.go, shipyard-controller/db/repos.go, shipyard-controller/handler/uniformintegrationhandler.go, shipyard-controller/handler/uniformintegrationhandler_test.go, test/go-tests/test_uniform.go
Closes #7047
Forward port of #7046
=> fix(shipyard-controller): Do not reset subscriptions when updating distributor/integration version 

shipyard-controller/handler/stagehandler.go
=> chore: Move Stage API endpoint into the correct subsection

shipyard-controller/db/mock/uniformrepo_mock.go, shipyard-controller/db/mongodb_uniform_repo.go, shipyard-controller/db/mongodb_uniform_repo_test.go, shipyard-controller/db/repos.go, shipyard-controller/handler/uniformintegrationhandler.go, shipyard-controller/handler/uniformintegrationhandler_test.go, test/go-tests/test_uniform.go
=> fix(shipyard-controller): Do not reset subscriptions when updating distributor/integration version

secret-service/pkg/handler/common.go, secret-service/pkg/handler/scopehandler.go, secret-service/pkg/handler/secrethandler.go, shipyard-controller/db/mongodb_event_repo.go, shipyard-controller/db/mongodb_eventqueue_repo.go, shipyard-controller/deploy/service.yaml, shipyard-controller/handler/common.go, shipyard-controller/handler/common_test.go, shipyard-controller/handler/error.go, shipyard-controller/handler/evaluationhandler.go, shipyard-controller/handler/evaluationhandler_test.go, shipyard-controller/handler/eventhandler.go, shipyard-controller/handler/loghandler.go, shipyard-controller/handler/projecthandler.go, shipyard-controller/handler/sequencedispatcher.go, shipyard-controller/handler/sequencehooks/sequencestate.go, shipyard-controller/handler/sequencewatcher.go, shipyard-controller/handler/servicehandler.go, shipyard-controller/handler/shipyardcontroller.go, shipyard-controller/handler/stagehandler.go, shipyard-controller/handler/statehandler.go, shipyard-controller/handler/uniformintegrationhandler.go
- normalizes error messages
Fixes #7026 
https://github.com/keptn/keptn/actions/runs/1951503358
=> fix: Normalize error messages

bridge/client/app/_services/data.service.ts, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts
Fixes #7045
Currently it's a workaround, the right fix for this will be done in #5101
=> fix(bridge): Fix duplicated sequence and incorrect show older sequences

helm-service/controller/deployment_handler.go, helm-service/controller/deployment_handler_test.go, helm-service/controller/mock_handler.go
- adds error handling when helm charts cannot be loaded
Fixes #7061
=> fix(helm-service): Handling of helm-charts loading problems

distributor/pkg/forwarder/forwarder.go, distributor/pkg/forwarder/forwarder_test.go, distributor/pkg/receiver/receiver_test.go
=> fix(distributor): Fixed reconnection issue of (re)used ce clients

configuration-service/handlers/project.go, shipyard-controller/common/configurationstore.go, shipyard-controller/common/configurationstore_test.go
- modifies err response code
https://github.com/keptn/keptn/actions/runs/1979505177
=> fix(configuration-service): Return 404 when token is invalid

.github/workflows/integration_tests.yml, shipyard-controller/db/mock/tasksequencerepo_mock.go, shipyard-controller/db/mongodb_task_sequence_repo.go, shipyard-controller/db/mongodb_task_sequence_repo_test.go, shipyard-controller/db/repos.go, shipyard-controller/handler/shipyardcontroller.go, shipyard-controller/handler/shipyardcontroller_component_test.go, test/go-tests/test_sequencecontrol.go, test/go-tests/testsuite_gke_test.go, test/go-tests/testsuite_k3s_test.go, test/go-tests/testsuite_openshift_test.go
Forward-port of #7114
Closes #7116
=> fix(shipyard-controller): Make sure sequence queue is free again after aborting a sequence

webhook-service/main.go
Enhances the unallowed URL list of webhook-service
=> feat: Improve unallowed URLs of webhook-service

MAINTAINERS
Signed-off-by: Raphael Ludwig <raphael.ludwig@dynatrace.com>
- adds @raffy23 to the maintainers file as member
Fixes keptn/community/issues/126
=> chore: Add @raffy23 as member

webhook-service/lib/curl_executor.go, webhook-service/lib/curl_executor_test.go, webhook-service/main.go
0.13.x backport of https://github.com/keptn/keptn/pull/7191
=> fix(webhook-service): enhance blacklisting of disallowed urls

bridge/README.md
=> docs(bridge): Add documentation for environment variables

.github/workflows/pre-release.yml, .github/workflows/release.yml
=> ci: Fix release pipeline issues

cli/cmd/trigger_sequence.go, cli/cmd/trigger_sequence_test.go
Signed-off-by: afzal442 <afzal442@gmail.com>
This adds keptn trigger `sequence` cmd
```cmd
keptn trigger sequence --sequence=my-sequence-1 --project=myworld --service=demo --stage=dev                                                    
Triggering sequence my-sequence-1 in project myworld in stage dev service demo
```
Fixes #6060 
Closes #7032
=> feat(cli): Added keptn trigger `sequence` cmd

bridge/client/assets/default-branding/app-config.json, bridge/client/index.html, bridge/cypress/integration/app.spec.ts, bridge/cypress/support/pageobjects/BasePage.ts
=> chore: Use correct Keptn branding logo and spelling

.github/workflows/integration_tests.yml
- fixes a syntax error in the clean up step of the integration test pipeline
=> ci: Fix syntax errors in integration test pipeline

distributor/README.md, distributor/cmd/main.go, distributor/pkg/config/envconfig.go, distributor/pkg/poller/poller.go, distributor/pkg/uniform/log/uniformlog.go, distributor/pkg/uniform/watch/uniformwatch.go, distributor/pkg/uniform/watch/uniformwatch_test.go, distributor/pkg/utils/utils.go
=> fix(distributor): shut down distributor when not able to send heartbeat to control plane

webhook-service/lib/curl_executor.go, webhook-service/lib/curl_executor_test.go, webhook-service/main.go
This PR contains a fix that enhances the blacklisting of urls:
==>
=> fix(webhook-service): enhance denylist of disallowed urls

MAINTAINERS
- adds @j-poecher as member in MAINTAINERS
=> chore: Add @j-poecher as member

.github/workflows/CI.yml, distributor/Dockerfile, distributor/cmd/main.go
closes #7027 
Distributor is printing the following during startup:
=> feat(distributor): Added preamble to distributor logs

cli/cmd/trigger_delivery.go, cli/cmd/trigger_delivery_test.go
=> fix(cli): Fixed parsing of image option in trigger delivery

CONTRIBUTING.md
- Fixes references made to docs folder in contributing guidelines file. 
Fixes #7326
=> docs: Fix hyperlink to references to docs folder

bridge/client/app/_components/ktb-trigger-sequence/ktb-trigger-sequence.component.spec.ts, bridge/client/app/_components/ktb-trigger-sequence/ktb-trigger-sequence.component.ts, bridge/client/app/_models/trigger-sequence.ts, bridge/client/app/_services/api.service.mock.ts, bridge/client/app/_services/api.service.ts, bridge/client/app/_services/data.service.spec.ts, bridge/client/app/_services/data.service.ts
Backport from #7268 to 0.14.x
Details in PR: #7287
=> fix(bridge): Do not send a start date for evaluation if none is given by the user

test/assets/squid/squid.yaml, test/go-tests/test_proxyauth.go, test/go-tests/test_utils.go
- fixes proxy auth integration test
https://github.com/keptn/keptn/actions/runs/2075952953
=> test: Fix proxyAuth integration test to use ClusterIP service

secret-service/pkg/backend/secretbackend_k8s.go, secret-service/pkg/backend/secretbackend_k8s_test.go, secret-service/pkg/handler/secrethandler.go, secret-service/pkg/handler/secrethandler_test.go
- When the scope is not found, the APIs return an HTTP 400 status code
Integration test run: https://github.com/keptn/keptn/actions/runs/2073164360
=> feat(secret-service): provide HTTP 400 when scope is not found

cli/cmd/upgrade.go, cli/pkg/helm/helm_helper.go
=> fix(cli): Provide values needed for upgrading the nats dependency

shipyard-controller/handler/projectmanager.go, shipyard-controller/handler/projectmanager_test.go, test/go-tests/test_proxyauth.go, test/go-tests/test_sshpublickeyauth.go
- adds GET /controlPlane/v1/project* endpoints to integration tests
https://github.com/keptn/keptn/actions/runs/2090701865
=> test: Add GET /controlPlane/v1/project* endpoints to integration tests

cli/cmd/upgrade.go
Before:
After the proposed changes:
=> chore(cli): Polish upgrade message when no upstream is present

mongodb-datastore/db/mongodb_event_repo.go, mongodb-datastore/db/mongodb_event_repo_test.go, mongodb-datastore/restapi/embedded_spec.go, mongodb-datastore/restapi/operations/event/get_events_by_type_parameters.go, mongodb-datastore/restapi/operations/event/get_events_by_type_urlbuilder.go, mongodb-datastore/swagger.yaml
=> chore: Make filter a mandatory field in mongo datastore get event by type

jmeter-service/jmeterUtils.go, jmeter-service/jmeterUtils_test.go
=> fix:  Added correct error and test to jmeter exec

shipyard-controller/handler/uniformintegrationhandler.go, shipyard-controller/handler/uniformintegrationhandler_test.go
- adds validation to integration and subscriptions
Fixes #7358
rerun integration tests:
https://github.com/keptn/keptn/actions/runs/2101710895
=> fix: Added validation of uniform subscriptions

bridge/client/app/_models/project.ts, bridge/client/app/_models/service.ts, bridge/client/app/_services/data.service.ts, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts
Fixes #7393
UI test is done in #7369 
=> fix(bridge): Fixed incorrect selected stage in sequence timeline

bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.html, bridge/client/app/_models/sequence.spec.ts, bridge/client/app/_models/sequence.ts, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.html, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts, bridge/cypress/fixtures/sequences.sockshop.json, bridge/cypress/integration/sequences.spec.ts, bridge/cypress/support/commands.ts, bridge/cypress/support/pageobjects/SequencesPage.ts, bridge/shared/models/sequence.ts
Fixes #4625 (the stage state is already implemented, so we agreed on tackling the waiting state here)
This also introduces the waiting status for the filter.
=> feat(bridge): Consider real waiting state for sequences

mongodb-datastore/db/mongodb_connection.go, shipyard-controller/db/mongodb_connection.go, shipyard-controller/handler/shipyardcontroller_component_test.go, statistics-service/db/mongodb_connection.go
- disconnect mongoDB client before reconnecting
https://github.com/keptn/keptn/actions/runs/2152967134
=> fix: Disconnect MongoDB client before reconnecting

bridge/client/app/_components/ktb-modify-uniform-subscription/ktb-modify-uniform-subscription.component.spec.ts, bridge/client/app/_components/ktb-modify-uniform-subscription/ktb-modify-uniform-subscription.component.ts, bridge/client/app/_services/_mockData/projects.mock.ts
=> fix(bridge): Subscription filter now correctly updates on delete/create service

bridge/client/app/_components/ktb-notification/ktb-notification.component.html, bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.ts, bridge/client/app/_pipes/sanitize-html.pipe.spec.ts, bridge/client/app/_pipes/sanitize-html.pipe.ts, bridge/client/app/app.module.ts
- makes sure that notifications with html content are displayed correctly
Fixes #7520
=> fix(bridge): Render html in notifications

bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.spec.ts, bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.ts, bridge/client/app/_services/api.service.ts, bridge/client/app/_services/data.service.ts
=> fix(bridge): Fix update of git upstream without a user

.github/workflows/CI.yml, .github/workflows/auto-update-go-utils.yml, .github/workflows/auto-update-k8s-utils.yml, .github/workflows/build-cli.yml, .github/workflows/build-helm-charts.yml, .github/workflows/dependencies-and-licenses.yml, .github/workflows/integration_tests.yml, .github/workflows/reviewdog.yml, cli/main.go
- fixes the used go version for our pipeline setup
=> ci: Fix used go version

.github/workflows/CI.yml, .github/workflows/auto-update-go-utils.yml, .github/workflows/auto-update-k8s-utils.yml, .github/workflows/build-cli.yml, .github/workflows/build-helm-charts.yml, .github/workflows/dependencies-and-licenses.yml, .github/workflows/integration_tests.yml, .github/workflows/reviewdog.yml
- fixes the used go version for our pipeline setup
=> ci: Fix go version in pipelines

api/middleware/ratelimiter.go, api/middleware/ratelimiter_test.go, api/restapi/configure_keptn.go, api/restapi/configure_keptn_test.go, installer/manifests/keptn/charts/control-plane/templates/api-service.yaml, installer/manifests/keptn/charts/control-plane/values.yaml
Backport of https://github.com/keptn/keptn/pull/7534
=> fix(api): Allow to enable/disable rate limit 

installer/manifests/keptn/charts/control-plane/templates/api-service.yaml
=> fix(installer): Added missing quote

gh-actions-scripts/build-helm-charts.sh, installer/manifests/common/.helmignore, installer/manifests/common/Chart.yaml, installer/manifests/common/templates/_labels.tpl, installer/manifests/common/templates/_names.tpl, installer/manifests/common/templates/_tplvalues.tpl
- adds a new common chart that stores logic that is needed by all 3 keptn charts
Part of #6042
=> feat(installer): Create separate helm chart for commonly used functionality

bridge/client/app/_components/ktb-copy-to-clipboard/ktb-copy-to-clipboard.component.scss, bridge/package.json
- Fixes the rendering of the success button after copying the API token or auth command to the clipboard
Problem:
https://user-images.githubusercontent.com/36239763/165148350-5442989b-0eb3-4fc0-a3d4-afc6574b5c81.mp4
After changes:
https://user-images.githubusercontent.com/36239763/165148398-dbc858f2-185c-44f6-bfbc-9b7503f33162.mp4
Fixes #6590
=> fix(bridge): Copy to clipboard button rendering

docs/developer/core.md
=> docs: Add conventions for logging and env var naming

bridge/client/app/_components/ktb-project-tile/ktb-project-tile.component.html, bridge/client/app/_components/ktb-project-tile/ktb-project-tile.component.scss
- Adds the functionality to open a Keptn project in a new tab by right clicking the project name.
Fixes #5524 
Demonstration:
https://user-images.githubusercontent.com/36239763/166426250-8838a108-9dc3-4f37-b8b7-53d86f9a35dc.mp4
=> feat(bridge): Open project in new tab

bridge/server/app.ts, bridge/server/services/data-service.ts, bridge/server/utils/print-utils.spec.ts, bridge/server/utils/print-utils.ts
Removes unnecessary data from the error log.
=> fix(bridge): Pretty-print request errors

.github/ISSUE_TEMPLATE/config.yml
Signed-off-by: Oleg Nenashev <o.v.nenashev@gmail.com>
Subj. Downstream of https://github.com/keptn/integrations/pull/2
=> chore: Add New Integration and Keptn Slack to the new issue screen

.github/workflows/integration_tests.yml, .github/workflows/zero-downtime-tests.yml, cli/main.go
=> ci: Bump integration tests cluster version to 1.22

CONTRIBUTORS.md, helm-service/README.md, jmeter-service/README.md
- Updates the README files to don't hardcode the service version to install
=> docs: Update version for installation of Helm and JMeter services

bridge/server/fixtures/sequence-response.mock.ts, bridge/server/services/data-service.ts, bridge/server/test/project.spec.ts
=> perf(bridge): Use adapted sequence endpoint for project endpoint of bridge server

cp-connector/pkg/controlplane/eventmatcher.go, cp-connector/pkg/controlplane/eventsource.go, cp-connector/pkg/controlplane/logforwarder.go, cp-connector/pkg/controlplane/subscriptionsource.go, cp-connector/pkg/controlplane/subscriptionsource_test.go, cp-connector/pkg/nats/nats.go
=> fix(cp-connector): Added missing Register() method to FixedSubscriptionSource

installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml, lighthouse-service/deploy/service.yaml, lighthouse-service/event_handler/cp_eventsender.go, lighthouse-service/event_handler/handler.go, lighthouse-service/event_handler/handler_test.go, lighthouse-service/go.mod, lighthouse-service/go.sum, lighthouse-service/main.go, test/go-tests/test_selfhealing.go, test/go-tests/test_uniform.go, test/go-tests/test_utils.go
- runs lighthouse-service without distributor using cp-connector library
- adapts changes in cp-connector library
Fixes #7435 
https://github.com/keptn/keptn/actions/runs/2313253710
=> feat(lighthouse-service): Run lighthouse-service without distributor sidecar

lighthouse-service/event_handler/common.go, lighthouse-service/event_handler/start_evaluation_handler.go, lighthouse-service/go.mod, lighthouse-service/go.sum, lighthouse-service/main.go
Part of #7613
Integration test run: https://github.com/keptn/keptn/actions/runs/2330206245
=> feat(lighthouse-service): Adapt readiness probe of lighthouse service to consider nats subscription

bridge/client/app/_components/ktb-project-settings-git/ktb-project-settings-git.component.html
=> fix(bridge): Fixed triggering of validation on token reset

installer/manifests/keptn/templates/api-gateway-nginx.yaml, installer/manifests/keptn/templates/api-service.yaml, installer/manifests/keptn/templates/approval-service.yaml, installer/manifests/keptn/templates/configuration-service.yaml, installer/manifests/keptn/templates/core.yaml, installer/manifests/keptn/templates/lighthouse-service.yaml, installer/manifests/keptn/templates/mongodb-datastore.yaml, installer/manifests/keptn/templates/remediation-service.yaml, installer/manifests/keptn/templates/secret-service.yaml, installer/manifests/keptn/templates/shipyard-controller.yaml, installer/manifests/keptn/templates/statistics-service.yaml, installer/manifests/keptn/templates/webhook-service.yaml, installer/manifests/keptn/values.yaml
- adds this new feature for #6982
- custom sidecar containers
- additional volumes
=> feat(installer): Introduce helm values to enable custom sidecar configurations

bridge/client/app/_components/ktb-project-settings-git-extended/ktb-project-settings-git-extended.component.ts, bridge/cypress/integration/project-settings.spec.ts, bridge/cypress/support/intercept.ts, bridge/cypress/support/pageobjects/NewProjectCreatePage.ts
=> fix(bridge): Add missing update project notification

bridge/angular.json, bridge/cypress.json, bridge/package.json, bridge/yarn.lock
Removed dev dependency `start-server-and-test`.
=> test(bridge): Removed dev dependency and use cypress/schematics instead

remediation-service/go.mod, remediation-service/go.sum, webhook-service/go.mod, webhook-service/go.sum
=> chore: updated refs to go-sdk

distributor/go.mod, distributor/go.sum
Update go-utils dependency to v0.15.1
Closes #7684
=> build(deps): Update go-utils dependency to v0.15.1

shipyard-controller/db/migration/sequence_execution_migration_test.go, shipyard-controller/db/models/sequence_execution/v1/sequence_execution.go, shipyard-controller/db/models/sequence_execution/v1/transformer.go, shipyard-controller/db/mongodb_sequence_execution_repo.go, shipyard-controller/db/mongodb_sequence_execution_repo_test.go, shipyard-controller/handler/sequencedispatcher.go, shipyard-controller/handler/sequencedispatcher_test.go, shipyard-controller/handler/shipyardcontroller.go, shipyard-controller/models/sequence_execution.go
- backport of https://github.com/keptn/keptn/commit/b8bad7162821aba8c7d09794a4a1337756adee5e
=> fix(shipyard-controller): Dispatch new sequence directly only if no older sequence is waiting

bridge/client/app/_components/ktb-heatmap/ktb-heatmap-utils.spec.ts, bridge/client/app/_components/ktb-heatmap/ktb-heatmap-utils.ts, bridge/client/app/_components/ktb-heatmap/ktb-heatmap.component.spec.ts, bridge/client/app/_components/ktb-heatmap/ktb-heatmap.component.ts, bridge/client/app/_components/ktb-heatmap/testing/ktb-test-heatmap.component.ts
=> fix(bridge): Fixed D3 heatmap issues

.gitignore, CONTRIBUTORS.md, bridge/client/app/_components/ktb-trigger-sequence/ktb-trigger-sequence.component.html, bridge/client/app/_components/ktb-trigger-sequence/ktb-trigger-sequence.component.spec.ts, bridge/client/app/_components/ktb-trigger-sequence/ktb-trigger-sequence.component.ts, bridge/client/app/_utils/form.utils.spec.ts, bridge/client/app/_utils/form.utils.ts, bridge/cypress/integration/trigger-sequence.spec.ts, bridge/cypress/support/pageobjects/TriggerSequenceSubPage.ts
- Removes input tag
- Change validation
- Adapt unit test
- Adapt integration test
- Add form util function and unit test for it
Resolves #7704 
Ensure that the environment variable `KEPTN_INSTALLATION_TYPE` contains `CONTINUOUS_DELIVERY`
Steps:
1. Trigger sequence
2. Choose delivery
3. Image fields is now full size and tag is removed
=> feat(bridge): Remove tag input field for creating a sequence

MAINTAINERS
- Add @heinzburgstaller as member
keptn/community#145
=> chore: Add @heinzburgstaller as member

resource-service/README.md
=> docs: Improve documentation for resource-service

installer/airgapped/install_keptn.sh
- adds the resource service image to the airgapped installer script
=> fix(installer): Add resource service to airgapped installer script

lighthouse-service/event_handler/common.go, lighthouse-service/event_handler/common_test.go
=> fix(lighthouse-service): Ensure sloFileContent property is always a base64 encoded string

docs/developer/zero_downtime_tests.md
=> docs: Added zero downtime tests documentation

.github/workflows/zero-downtime-tests.yml
- now test runs even with UI test disabled
https://github.com/keptn/keptn/runs/6654566739?check_suite_focus=true
=> fix: Fixed zd test to run without UI tests

mongodb-datastore/handlers/events.go
https://github.com/keptn/keptn/runs/6669629188?check_suite_focus=true
=> fix(mongodb-datastore): Return [] instead of nil from get methods

installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml, installer/manifests/keptn/charts/control-plane/templates/api-service.yaml, installer/manifests/keptn/charts/control-plane/templates/approval-service.yaml, installer/manifests/keptn/charts/control-plane/templates/configuration-service.yaml, installer/manifests/keptn/charts/control-plane/templates/continuous-operations.yaml, installer/manifests/keptn/charts/control-plane/templates/mongodb-datastore.yaml, installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml, installer/manifests/keptn/charts/control-plane/templates/secret-service.yaml, installer/manifests/keptn/charts/control-plane/templates/shipyard-controller.yaml, installer/manifests/keptn/charts/control-plane/templates/statistics-service.yaml, installer/manifests/keptn/charts/control-plane/templates/webhook-service.yaml
- configure default values to values set in values.yaml
=> fix(installer): Configure default preStopHook and grafefulPeriods timeouts

installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml, installer/manifests/keptn/charts/control-plane/templates/statistics-service.yaml, installer/manifests/keptn/charts/control-plane/templates/webhook-service.yaml, installer/manifests/keptn/charts/control-plane/values.yaml
=> fix(installer): Adapt preStop hook times for lighthouse, statistics and webhook

.github/workflows/zero-downtime-tests.yml
#7662
https://github.com/keptn/keptn/runs/6687217363?check_suite_focus=true
When we have a working ZD on master  we could add a report/automated issue generation to this
use default image or 0.16.0-dev both should work
=> ci: Added a cron job for Zero downtime tests pipeline

mongodb-datastore/db/mongodb_event_repo.go, shipyard-controller/db/common.go, shipyard-controller/db/mongodb.go, shipyard-controller/db/mongodb_event_repo.go, shipyard-controller/db/mongodb_eventqueue_repo.go, shipyard-controller/db/mongodb_log_repo.go, shipyard-controller/db/mongodb_state_repo.go, shipyard-controller/db/mongodb_task_sequence_repo.go, shipyard-controller/db/mongodb_uniform_repo.go, statistics-service/db/migrator.go, statistics-service/db/statistics_mongodb_repo.go
=> fix: Ensure all MongoDB cursors are being closed

cp-connector/pkg/controlplane/controlplane.go, cp-connector/pkg/controlplane/subscriptionsource.go, cp-connector/pkg/controlplane/subscriptionsource_test.go, go-sdk/pkg/sdk/keptn.go, shipyard-controller/handler/shipyardcontroller.go, test/go-tests/kubectl.go, webhook-service/handler/handler.go
=> fix(cp-connector): Subscribe to integrations before creating a job

cp-connector/pkg/controlplane/subscriptionsource.go
=> chore(cp-connector): Remove unnecesarry logs

api/go.mod, api/go.sum, approval-service/go.mod, approval-service/go.sum, go-sdk/go.mod, go-sdk/go.sum, lighthouse-service/go.mod, lighthouse-service/go.sum, mongodb-datastore/go.mod, mongodb-datastore/go.sum, remediation-service/go.mod, remediation-service/go.sum, webhook-service/go.mod, webhook-service/go.sum
=> build(deps): Update cp-common and cp-connector to latest version

cp-connector/pkg/controlplane/subscriptionsource_test.go
=> fix(cp-connector): Flaky unit test

test/go-tests/go.mod, test/go-tests/go.sum
=> build(deps): Update go-tests webhook-service deps

gh-actions-scripts/build-helm-charts.sh
Adds helm install --dry-run --debug to our helm checks
Fixes #7925
messup something visible at runtime and push :)  e.g.  in shipyard.yaml refer to value .Values.shipyardController.notexist
=> ci: Ensure CI pipeline fails if helm fails

bridge/client/app/_components/ktb-modify-uniform-subscription/ktb-modify-uniform-subscription.component.spec.ts, bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.spec.ts, bridge/client/app/_components/ktb-project-settings/ktb-project-settings.component.ts, bridge/client/app/_components/ktb-root-events-list/ktb-root-events-list.component.spec.ts, bridge/client/app/_components/ktb-sequence-controls/ktb-sequence-controls.component.spec.ts, bridge/client/app/_components/ktb-sequence-state-info/ktb-sequence-state-info.component.spec.ts, bridge/client/app/_components/ktb-subscription-item/ktb-subscription-item.component.spec.ts, bridge/client/app/_services/data.service.ts, bridge/client/app/app.component.spec.ts, bridge/client/app/app.component.ts, bridge/client/app/app.routing.ts, bridge/client/app/dashboard/dashboard.component.html, bridge/client/app/dashboard/dashboard.component.spec.ts, bridge/client/app/dashboard/dashboard.component.ts, bridge/client/app/project-board/project-board.component.ts, bridge/cypress/integration/dashboard.spec.ts, bridge/cypress/integration/project-create.spec.ts, bridge/cypress/integration/sequences.spec.ts, bridge/cypress/support/intercept.ts, bridge/cypress/support/pageobjects/DashboardPage.ts
Fixes #7942
Also removes one additional projects call while creating a project
=> fix(bridge): Update projects if dashboard is visited

bridge/client/app/_services/data.service.spec.ts, bridge/client/app/_services/data.service.ts
=> fix(bridge): Fix approval being sent twice

bridge/client/app/_components/ktb-sequence-tasks-list/ktb-sequence-tasks-list.component.ts, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts, bridge/cypress/integration/sequences.spec.ts, bridge/cypress/support/pageobjects/SequencesPage.ts
- Fix component
- Add UI test
Fixes #7978
=> fix(bridge): Remove previous filter from URL

gh-actions-scripts/build-helm-charts.sh
=> ci: Fix helm install with --generate-name

bridge/server/services/api-service.ts, bridge/server/test/project.spec.ts
=> fix(bridge): Fix missing evaluation score of sequence

shipyard-controller/db/mongodb_uniform_repo.go, shipyard-controller/db/mongodb_uniform_repo_test.go, shipyard-controller/handler/uniformintegrationhandler.go, shipyard-controller/handler/uniformintegrationhandler_test.go
Fixes #7364
https://github.com/keptn/keptn/actions/runs/2466369899
=> chore(shipyard-controller): Remove references to deprecated subscription

test/go-tests/test_proxyauth.go, test/go-tests/testsuite_openshift_test.go
=> fix: Added proxy to integration test

bridge/client/app/_components/_dialogs/ktb-confirmation-dialog/ktb-confirmation-dialog.component.spec.ts, bridge/client/app/_components/_dialogs/ktb-confirmation-dialog/ktb-confirmation-dialog.module.ts, bridge/client/app/app.module.ts
- Add ktb-confirmation-dialog module
Refers to #7932
=> feat(bridge): Add ktb-confirmation-dialog module

bridge/client/app/_components/_dialogs/ktb-deletion-dialog/ktb-deletion-dialog.component.spec.ts, bridge/client/app/_components/_dialogs/ktb-deletion-dialog/ktb-deletion-dialog.module.ts, bridge/client/app/app.module.ts
- Add module
- Refactor unit test
Resolves #7932 
=> feat(bridge): Add deletion dialog module

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.spec.ts, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.module.ts, bridge/client/app/app.module.ts
- Create ktb-evaluation-details module
- Refactor unit tests
Adds to #7932
=> feat(bridge): ktb-evaluation-details module

.github/workflows/zero-downtime-tests.yml
Added "" to failing ZD pipeline condition
=> ci: Added quotes to zd pipeline if condition

bridge/client/app/_components/ktb-approval-item/ktb-approval-item.component.spec.ts, bridge/client/app/_components/ktb-approval-item/ktb-approval-item.module.ts, bridge/client/app/app.module.ts
- Add module
- Refactor unit test
Adds to #7932 
=> feat(bridge): Add approval-item-module

CONTRIBUTORS.md, cli/cmd/install.go, cli/cmd/root.go, cli/cmd/send_event_approvalFinished.go
Signed-off-by: Simon Schrottner <simon.schrottner@dynatrace.com>
Within https://github.com/keptn/keptn.github.io/pull/1242 we found
some improvements for the CLI documentation. This is our back-port
of those changes.
https://github.com/keptn/keptn.github.io/pull/1242
=> docs(cli): Improve CLI Documentation

MAINTAINERS
Signed-off-by: Sarah Huber <sarah.huber@dynatrace.com>
=> chore: Add @sarahhuber001 as member

bridge/client/app/_components/ktb-copy-to-clipboard/ktb-copy-to-clipboard.component.spec.ts, bridge/client/app/_components/ktb-copy-to-clipboard/ktb-copy-to-clipboard.module.ts, bridge/client/app/app.module.ts
- Add module
- Refactor unit test
Adds to #7932 
=> feat(bridge): Add ktb-copy-to-clipboard module

bridge/client/app/_components/ktb-create-service/ktb-create-service.component.spec.ts, bridge/client/app/_components/ktb-create-service/ktb-create-service.module.ts, bridge/client/app/app.module.ts
- Add module
- Refactor unit test
Adds to #7932 
=> feat(bridge): Add ktb-create-service-module

test/go-tests/test_provisioningURL.go
=> fix: Added longer retry in provisioning URL test

bridge/server/services/api-service.ts, bridge/server/services/data-service.ts, bridge/server/test/intersect-events.spec.ts, bridge/server/test/project.spec.ts, bridge/shared/models/service.ts
=> fix(bridge): Show all evaluations in the environment screen

test/go-tests/testsuite_openshift_test.go
- disables LogForwarding test for Minishift due to flakyness of this test on this platform
Fixes #8100
=> test: Disable LogForwarding test for Minishift

shipyard-controller/common/event.go, shipyard-controller/db/mongodb_event_repo.go, shipyard-controller/db/mongodb_event_repo_test.go, shipyard-controller/handler/eventhandler.go
- adds a time filter property for GetEvents()
#8124
=> fix(shipyard-controller): Add time property to EventFilter

resource-service/handler/project_manager.go, resource-service/handler/project_manager_test.go
=> fix(resource-service): Always delete local project directory when project creation fails

api/README.md, api/restapi/configure_keptn.go, configuration-service/restapi/configure_configuration_service.go, mongodb-datastore/restapi/configure_mongodb_datastore.go
Signed-off-by: STRRL <im@strrl.dev>
- swagger.json -> swagger.yaml
N/A
N/A
N/A
No changes on codes, no need to test.
=> docs: Typo: we are using swagger.yaml not swagger.json

bridge/client/environments/environment.test.ts, bridge/cypress/integration/deep-links.spec.ts, bridge/cypress/integration/oauth-pages.spec.ts, bridge/cypress/integration/uniform-integrations.spec.ts, bridge/cypress/plugins/index.ts, bridge/cypress/support/index.ts, bridge/cypress/support/intercept.ts, bridge/cypress/support/pageobjects/DashboardPage.ts, bridge/cypress/support/pageobjects/UniformPage.ts
=> test(bridge): Run UI tests in production mode and log failed requests

bridge/client/app/_components/ktb-modify-uniform-subscription/ktb-modify-uniform-subscription.module.ts, bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.module.ts
=> chore(bridge): Added missing modules

bridge/client/app/_components/ktb-project-settings/ktb-project-settings-shipyard/ktb-project-settings-shipyard.component.html
Signed-off-by: mehabhalodiya <mehabhalodiya@gmail.com>
- correct message reads when creating a new project
Fixes #8106
=> fix(bridge): Corrected misleading message in creating project

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.module.ts
=> chore(bridge): Added missing modules for evaluation-details

resource-service/common/credentials_test.go, resource-service/common_models/git.go, resource-service/common_models/git_test.go
=> fix(resource-service): Remove token enforcement (#8040)

shipyard-controller/handler/projectmanager_test.go
=> fix(shipyard-controller): Fix project deletion unit test

bridge/README.md, bridge/server/.jest/setupServer.ts, bridge/server/.jest/test.utils.ts, bridge/server/interfaces/configuration.ts, bridge/server/server.ts, bridge/server/test/bridge-info.spec.ts, bridge/server/test/oauth.spec.ts, bridge/server/user/oauth.ts, bridge/server/user/secrets.spec.ts, bridge/server/user/secrets.ts, bridge/server/user/session.ts, bridge/server/utils/configuration.spec.ts, bridge/server/utils/configuration.ts, installer/manifests/keptn/templates/core.yaml
Fixes #8241 
But most of the PR is refactoring.
=> fix(bridge): Save client secret in k8s secret

bridge/client/app/_pipes/keptn-url.pipe.spec.ts, bridge/client/app/_pipes/keptn-url.pipe.ts
=> fix(bridge): Handle invalid bridge versions

bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.scss, bridge/cypress/fixtures/sequence.filter-many.mock.json, bridge/cypress/integration/sequences.spec.ts, bridge/cypress/support/commands.ts, bridge/cypress/support/pageobjects/SequencesPage.ts
=> fix(bridge): Fix 'view more' of quick filter

installer/manifests/keptn/charts/control-plane/templates/_helpers.tpl, test/go-tests/test_uniform.go
Fixes https://github.com/keptn/keptn/issues/8295
Integration test run: https://github.com/keptn/keptn/actions/runs/2620850403
=> fix: Use distributor values namespace and hostname in svc env vars

installer/manifests/keptn/templates/api-gateway-nginx.yaml, installer/manifests/keptn/templates/approval-service.yaml, installer/manifests/keptn/templates/lighthouse-service.yaml, installer/manifests/keptn/templates/mongodb-datastore.yaml, installer/manifests/keptn/templates/rbac.yaml, installer/manifests/keptn/templates/remediation-service.yaml, installer/manifests/keptn/templates/statistics-service.yaml, installer/manifests/keptn/values.yaml
=> feat(installer): Introduce flags to enable / disable Keptn services

bridge/cypress/integration/sequences.spec.ts
- Adds missing wait to view more services ui test
=> fix(bridge): Added missing wait to view more services ui test

bridge/server/interfaces/sequence-stage.ts, bridge/server/models/sequence.ts, bridge/server/services/data-service.ts, bridge/shared/fixtures/traces-response.mock.ts
=> fix(bridge): Fix error on viewing service deployment

installer/airgapped/install_keptn.sh, installer/airgapped/pull_and_retag_images.sh
=> fix(installer): Remove configuration service from airgapped installer scripts

bridge/client/app/_components/ktb-event-item/ktb-event-item.component.html, bridge/client/app/_models/json-serializable.ts, bridge/client/app/_services/clipboard.service.spec.ts, bridge/client/app/_services/clipboard.service.ts, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-tasks-list/ktb-task-item.component.scss, bridge/client/styles.scss
Closes #8277
Note: Some parts were already done before.
=> chore(bridge): Fix Sonar issues

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_components/ktb-selectable-tile/ktb-selectable-tile.component.ts, bridge/cypress/support/intercept.ts, bridge/server/api/index.ts, bridge/server/interfaces/shipyard.ts, bridge/server/services/data-service.ts
Missing code smells from #8277 
=> chore(bridge): Fix Sonar issues part 2

bridge/server/interfaces/configuration.ts, bridge/server/utils/configuration.spec.ts, bridge/server/utils/configuration.ts
=> fix(bridge): Fix incorrect API URL for auth command

bridge/client/app/_views/ktb-environment-view/ktb-stage-details/ktb-stage-details.component.ts, bridge/cypress/fixtures/project.mock.json, bridge/cypress/integration/environment.spec.ts, bridge/cypress/support/intercept.ts, bridge/cypress/support/pageobjects/EnvironmentPage.ts
- Fixes navigating to service from `stage-details` problem
Fixes #8394
=> fix(bridge): Navigating to service from stage-details

.github/workflows/zero-downtime-tests.yml, test/go-tests/test_utils.go, test/go-tests/test_webhook.go, test/zero-downtime/assets/test-values.yml, test/zero-downtime/webhook_test.go
Fix ZD test of webhook back to work
=> fix: Zero Downtime test for the webhook-service

.github/workflows/zero-downtime-tests.yml, test/zero-downtime/testsuite_zerodowntime_test.go
- [adds this new feature](https://github.com/keptn/keptn/actions/runs/2670959787)
=> chore: Fix ZeroDowntime registry

bridge/deploy/service.yaml, bridge/server/feature-flags.ts, bridge/server/test/bridge-info.spec.ts
Set the FF true by default since resource-service is the new default.
The removal of it will be done in #8433
=> chore(bridge): Enable resource-service by default

shipyard-controller/handler/projecthandler.go
This should facilitate the debugging of problems and see if it is on Keptn side or in the automatic provisioner implementation.
=> chore(shipyard-controller): Add extra debug logging to the Git Automatic Provisioner call

bridge/client/app/_components/ktb-date-input/ktb-datetime-picker.component.html, bridge/client/app/_components/ktb-date-input/ktb-datetime-picker.component.ts, bridge/client/app/_views/ktb-environment-view/ktb-stage-overview/ktb-trigger-sequence/ktb-trigger-sequence.component.html, bridge/cypress/integration/trigger-sequence.spec.ts, bridge/cypress/support/pageobjects/TriggerSequenceSubPage.ts
- adds functionality for preserving the datetime picker value
Resolves #7088
https://user-images.githubusercontent.com/36239763/179502365-8b8ebd87-cad9-45da-8fe3-66e3d3f2a705.mp4
=> feat(bridge): Preselect date for datetime picker

.github/.kubescape/controls-inputs.json, .github/.kubescape/exceptions.json, .github/workflows/security-scans.yml
- improves the security scan pipeline by providing more config options to kubescape that result in less false positives
=> ci: Improve kubescape scans

.snyk
- adds a basic snyk config file to ignore some test files
=> ci: Add Snyk config file

installer/manifests/keptn/values.yaml
Integration tests: https://github.com/keptn/keptn/actions/runs/2702743114
=> feat(installer): Enable clustered NATS

installer/manifests/keptn/values.yaml
- fixes the NATS settings for clustering to use the correct helm value
=> fix(installer): Fix NATS clustering settings

bridge/client/app/_components/ktb-app-header/ktb-app-header.component.spec.ts, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_services/_mockData/api-responses/bridgeInfo-response.mock.ts, bridge/client/app/_services/feature-flags.service.spec.ts, bridge/client/app/_utils/test.utils.ts, bridge/cypress/fixtures/bridgeInfo.mock.json, bridge/cypress/fixtures/bridgeInfoAuthMsg.mock.json, bridge/cypress/fixtures/bridgeInfoEnableD3Heatmap.mock.json, bridge/cypress/fixtures/bridgeInfoEnableResourceService.mock.json, bridge/cypress/integration/project-create.spec.ts, bridge/server/feature-flags.ts, bridge/server/test/bridge-info.spec.ts, bridge/shared/interfaces/feature-flags.ts, installer/manifests/keptn/templates/core.yaml, installer/manifests/keptn/values.yaml
- Rename variable from 'D3_HEATMAP_ENABLED' to 'D3_ENABLED'
- Adopt usages
Relates to #6163 
=> refactor(bridge): Rename D3 feature flag

bridge/client/app/_views/ktb-project-view/ktb-project-view-common.module.ts, bridge/client/app/_views/ktb-settings-view/ktb-project-settings/ktb-project-settings.component.html, bridge/client/app/_views/ktb-settings-view/ktb-project-settings/ktb-project-settings.component.spec.ts, bridge/client/app/_views/ktb-settings-view/ktb-project-settings/ktb-project-settings.component.ts
- rx-ify project settings
- Adopt unit tests
Fixes #8414
=> refactor(bridge): Refactor project settings

bridge/client/app/_views/ktb-settings-view/ktb-project-settings/ktb-project-settings-git-extended/ktb-project-settings-git-extended.component.spec.ts, bridge/client/app/_views/ktb-settings-view/ktb-project-settings/ktb-project-settings-git-extended/ktb-project-settings-git-extended.component.ts, bridge/cypress/integration/project-settings.spec.ts, bridge/cypress/support/pageobjects/ProjectSettingsPage.ts
Signed-off-by: ermin.muratovic <ermin.muratovic@dynatrace.com>
- fixes the detection of pending changes when automatic provisioning is active
- shows the configured data correctly in the settings page
Fixes #8493
=> fix(bridge): Fix detection of pending changes when automatic provisioning active

bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.html, bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.spec.ts, bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.ts
=> fix(bridge): Fix invalid header property for webhook

.github/workflows/validate-semantic-pr.yml, api/importer/execute/keptn_endpoints.go, gh-actions-scripts/cleanup_docker_images.sh, gh-actions-scripts/detect_stale_images.sh, installer/manifests/keptn/templates/api-gateway-nginx.yaml, installer/manifests/keptn/templates/rbac.yaml, installer/manifests/keptn/templates/resource-service.yaml, installer/manifests/keptn/values.yaml, shipyard-controller/common/configurationstore_test.go, test/go-tests/test_resourceservice.go
- cleanup tasks
Fixes #8082
https://github.com/keptn/keptn/actions/runs/2751528172
https://github.com/keptn/keptn/actions/runs/2752717080
Most of the pipelines are tested with Integration tests run, ZeroDowntime test run and CI run. The non-tested are: release and pre-release pipelines, which should not be affected.
=> chore: Remove configuration-service k8s service

bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.html, bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.spec.ts, bridge/client/app/_components/ktb-webhook-settings/ktb-webhook-settings.component.ts
=> fix(bridge): Fix invalid header property for webhook (#8543)

bridge/client/app/_components/ktb-chart/ktb-chart.component.html, bridge/client/app/_components/ktb-chart/ktb-chart.component.ts, bridge/client/app/_components/ktb-chart/testing/ktb-chart-test-data.ts, bridge/client/app/_components/ktb-chart/testing/ktb-test-chart.component.ts, bridge/client/app/_interfaces/chart.ts
- Clean API model
- Fix right tick values
- Adopt unit test
- Adopt implementations
Adds to #6166 
=> feat(bridge): Improve ktb-chart

shipyard-controller/internal/handler/uniformintegrationhandler.go, shipyard-controller/internal/handler/uniformintegrationhandler_test.go
=> fix: Merge integration subscriptions into one, apply newly supplied subscriptions if existing ones are empty

shipyard-controller/db/mongodb_uniform_repo.go, shipyard-controller/db/mongodb_uniform_repo_test.go
=> fix(shipyard-controller): Update Integration when Subscriptions field is null

bridge/.eslintrc.json, bridge/package.json, bridge/yarn.lock
Fix: https://github.com/keptn/keptn/issues/8526
=> ci: add rule to deny .only

shipyard-controller/internal/handler/projecthandler_test.go
=> test(shipyard-controller): Validator should be ignored when Provisioner is used

bridge/README.md, bridge/angular.json, bridge/package.json, bridge/proxy.config.json, bridge/server/nodemon.json
=> chore(bridge): Separate run of client and server (dev)

test/go-tests/test_importer_test.go
- corrects the error message for the import package integration tests
Fixes #8642
=> test(api): Fix failing import package integration tests

.github/workflows/integration_tests.yml, gh-actions-scripts/generate-k8s-resource-stats.sh
- updates the tablemark-cli from version 2.0.0 to 3.0.0
Fixes #7604 
[Integration Test execution](https://github.com/keptn/keptn/actions/runs/2866563813)
=> chore: Update tablemark-cli to version 3.0.0

test/go-tests/test_secrets.go
Fixes #8668
https://github.com/keptn/keptn/actions/runs/2873194084
=> test: Added retry to the secret test

.github/workflows/mongodb-version-check.yml
- creates a new workflow that monitors the Helm Chart Version of bitnami/mongodb
- if the chart version used by Keptn differs from the latest version of bitnami, an issue gets created
Fixes #8148
Example [Issue](https://github.com/keptn/keptn/issues/8671) that gets created by this workflow
=> ci: Create a new workflow to monitor the Helm Chart version of MongoDB

.github/workflows/mongodb-version-check.yml
- adds a manual workflow trigger for mongodb-version-check.yml
Fixes #8148
- Follow-up of #8666
=> ci: Add manual workflow trigger for mongodb-version-check.yml

resource-service/common/git.go, resource-service/common/gitsuite_test.go
=> fix(resource-service): Use values provided by GIT_KEPTN_USER and GIT_KEPTN_EMAIL for commits to the upstream

resource-service/common/git.go, resource-service/go.mod, resource-service/go.sum
=> fix(resource-service): GetDefaultBranch looks for HEAD before fallback to master

MAINTAINERS
- adds @philipp-hinteregger to members
[#160](https://github.com/keptn/community/issues/160)
=> chore: Add @philipp-hinteregger to members

.github/workflows/validate-helm-docs.yml, api/Dockerfile, gh-actions-scripts/generate-helm-docs.sh, installer/manifests/keptn/README.md
- fixes the helm values docs pipeline by checking with diff against the file before calling the generator instead of checking against master
=> ci: Fix Helm Docs validation pipeline

test/go-tests/test_secrets.go
Closes #8689
Closes https://github.com/keptn/keptn/issues/8703
Closes https://github.com/keptn/keptn/issues/8654
Closes https://github.com/keptn/keptn/issues/8710
The reason the `Test_ManageSecrets_CreateUpdateAndDeleteSecret` was failing is that in the recently introduced `Test_ImportCorrectManifest` a secret under the same scope as the ones created during the `Test_ManageSecrets_CreateUpdateAndDeleteSecret` is created. Therefore, the check that verifies that the associated role `keptn-secrets-default-read` is not there anymore after deleting those secrets is failing.
This PR changes the check to verify that either the role is not there anymore (if no other secret under the same scope is not available anymore), or - if it is still there - the deleted secrets are not referenced anymore …
=> test: Fix check in secret api integration test

shipyard-controller/internal/common/error.go, shipyard-controller/internal/controller/eventdispatcher.go, shipyard-controller/internal/controller/sequencedispatcher.go, shipyard-controller/internal/controller/sequencedispatcher_test.go, shipyard-controller/internal/controller/sequencestate.go, shipyard-controller/internal/controller/shipyardcontroller.go, shipyard-controller/internal/controller/shipyardcontroller_utils.go, shipyard-controller/internal/controller/shipyardcontroller_utils_test.go, shipyard-controller/internal/db/mongodb_event_repo.go
closes #5442 
regular sequence execution
sequence execution with blocking/overlapping sequences:
integration test run: https://github.com/keptn/keptn/actions/runs/2882116832
=> chore: Improve shipyard-controller logging for better troubleshooting support

resource-service/common/git.go, resource-service/go.mod, resource-service/go.sum
Closes #8690
Backport of #8627
=> fix(resource-service): Determine default branch using HEAD after initial clone

shipyard-controller/handler/eventdispatcher.go, shipyard-controller/handler/eventdispatcher_test.go, shipyard-controller/handler/sequencedispatcher.go, shipyard-controller/handler/shipyardcontroller_component_test.go
based on #8663 
Fixes https://github.com/keptn/keptn/issues/8655
=> fix(shipyard-controller): Added service to shipyard filter in Event Dispatcher

shipyard-controller/handler/eventdispatcher.go, shipyard-controller/handler/eventdispatcher_test.go, shipyard-controller/handler/sequencedispatcher.go, shipyard-controller/handler/shipyardcontroller_component_test.go
based on https://github.com/keptn/keptn/pull/8663
Fixes https://github.com/keptn/keptn/issues/8655
=> fix(shipyard-controller): Added shipyard service filter in event dispatcher

shipyard-controller/internal/controller/eventdispatcher.go, shipyard-controller/internal/controller/eventdispatcher_test.go, shipyard-controller/internal/controller/sequencedispatcher.go, shipyard-controller/internal/controller/shipyardcontroller_component_test.go
based on https://github.com/keptn/keptn/pull/8663
Fixes https://github.com/keptn/keptn/issues/8655
=> fix(shipyard-controller): Added service in filter of event dispatcher

.github/workflows/zero-downtime-tests.yml
- adds automated issue generation to ZD test
Fixes #8212 
eg. https://github.com/keptn/keptn/runs/7976459016?check_suite_focus=true
=> ci: Add issue generation to ZD Test pipeline

shipyard-controller/internal/controller/sequencestate.go, shipyard-controller/internal/controller/sequencestate_test.go, shipyard-controller/main_test.go, shipyard-controller/models/sequence_execution.go, shipyard-controller/models/sequence_execution_test.go
- sequence should fail when receiving unknown status or result
Fixes #7367 
https://github.com/keptn/keptn/actions/runs/2911236457
=> fix(shipyard-controller): Fail sequence when receiving invalid status

.github/workflows/zero-downtime-tests.yml
before: https://github.com/keptn/keptn/actions/runs/2924523882
after: https://github.com/keptn/keptn/runs/8013750251?check_suite_focus=true
=> ci: Fix Zero Downtime scheduled pipeline

shipyard-controller/debugdocs/docs.go, shipyard-controller/debugdocs/swagger.json, shipyard-controller/debugdocs/swagger.yaml, shipyard-controller/internal/handler/debughandler.go
=> fix(shipyard-controller): Remove DB dump enpoints documentation from API docs

.github/workflows/zero-downtime-tests.yml
make sure to override empty default value
as explained here https://dev.to/mrmike/github-action-handling-input-default-value-5f2g
Fixes #8753
=> ci: Fix helm chart to a default

MAINTAINERS
Signed-off-by: mehabhalodiya <mehabhalodiya@gmail.com>
- Add Meha Bhalodiya as Member as per https://github.com/keptn/community/issues/164
=> chore: add @mehabhalodiya as member

.github/workflows/zero-downtime-tests.yml
Fixes #8776 
https://github.com/keptn/keptn/runs/8087866734?check_suite_focus=true
=> ci: Add env variable to setup the default Upgrade Chart

.github/workflows/zero-downtime-tests.yml
Add option to test downgrade in ZD pipeline
=> ci: Add option to check for Zero Downtime Downgrade

.github/workflows/zero-downtime-tests.yml
Only take biggest release for ZD pipeline default
https://github.com/keptn/keptn/runs/8131605963?check_suite_focus=true
=> ci: Changing regex of ZD

cli/cmd/configure_monitoring.go
Remove the outdated `keptn configure monitoring` example text.
Fixes #8595
=> docs(cli): Remove outdated example

test/zero-downtime/sequences_test.go
Closes #8804 #8800
https://github.com/keptn/keptn/actions/runs/2991339925
=> ci: Changing sequence test for ZD

test/go-tests/test_utils.go
Functions mentioned in the ticket are unused, removing them
Fixes #8076
https://github.com/keptn/keptn/actions/runs/2991503167
=> chore: Remove unused functions

installer/manifests/keptn/README.md, installer/manifests/keptn/values.yaml
- enhance helm docs
Fixes #8686
=> docs(installer): Enhance helm values documentation

cli/cmd/trigger_delivery_test.go, cli/pkg/docker/docker_utils.go, cli/pkg/docker/docker_utils_test.go
=> fix(cli): Use docker v2 API for fetching images

installer/manifests/keptn/README.md, installer/manifests/keptn/templates/api-service.yaml, installer/manifests/keptn/values.yaml
- Disable by default the Event validation
=> chore(api): Remote event validation is disabled by default

cli/cmd/add_resource.go, cli/cmd/add_resource_test.go, cli/cmd/trigger_delivery_test.go
=> feat(cli): Support adding resources to all stages without defining a service + refactoring

installer/manifests/keptn/values.yaml
- adapts resource limits
Fixes #8833 
https://github.com/keptn/keptn/actions/runs/3034978880
=> chore(installer): Adapt resource limits

resource-service/common/git.go, resource-service/common/gitsuite_test.go, resource-service/common_models/git.go, resource-service/errors/errors.go, resource-service/handler/common.go, resource-service/handler/common_test.go, resource-service/handler/project_manager.go, resource-service/handler/project_manager_test.go, resource-service/handler/resource_manager.go, resource-service/handler/service_manager.go, resource-service/handler/service_manager_test.go, resource-service/handler/stage_manager.go, resource-service/handler/stage_manager_test.go
- Compute git auth method once per API request
Fixes #7034 
https://github.com/keptn/keptn/actions/runs/3007829806
https://github.com/keptn/keptn/actions/runs/3034862862
=> feat(resource-service): Compute git auth method once per API request

resource-service/common/git.go, resource-service/common/gitsuite_test.go, resource-service/handler/common.go, resource-service/handler/project_resource_handler_test.go, resource-service/handler/service_resource_handler_test.go, resource-service/handler/stage_resource_handler_test.go
Closes #8842
Integration test run: https://github.com/keptn/keptn/actions/runs/3043063481/jobs/4901919208
=> fix(resource-service): Map go-git specific error types to Keptn error types understood by the resource service error handler

webhook-service/handler/handler.go, webhook-service/handler/handler_test.go
- If a webhook config is malformed log a warning
local integration test passed, online run here: 
https://github.com/keptn/keptn/actions/runs/3035853558
=> fix(webhook-service): RAdd warning for malformed configuration

installer/manifests/keptn/README.md, installer/manifests/keptn/values.yaml, resource-service/common/git.go, resource-service/common/gitsuite_test.go, resource-service/common_models/git.go, resource-service/config/config.go, resource-service/config/config_test.go, test/go-tests/test_custom_git_branch_name.go, test/go-tests/test_utils.go, test/go-tests/testsuite_gke_test.go, test/go-tests/testsuite_k3s_test.go, test/go-tests/testsuite_openshift_test.go
- determines default branch from helm value when repository is not initialized
Fixes #8816 
https://github.com/keptn/keptn/actions/runs/3037958482
https://github.com/keptn/keptn/actions/runs/3044820772
=> fix(resource-service): Determine default branch from helm value when repository is not initialized

installer/manifests/keptn/values.yaml
As part of #8833, this PR improves the resource allocation
=> chore(installer): Improve resource limits/requests

resource-service/errors/errors.go, resource-service/handler/common.go, resource-service/handler/common_test.go, resource-service/handler/project_manager.go, resource-service/handler/project_manager_test.go
=> fix(resource-service): Return specific error in when creating a project with an initialized repository

.github/workflows/CI.yml, .github/workflows/build-docker-images.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, .github/workflows/test-and-build-docker-images.yml
- extracts Unit Test and Docker build and push steps into a separate workflow
- reuses the new workflow in the CI / pre-release / release pipelines
Fixes #6091
=> ci: Extract and reuse existing workflow steps

.github/workflows/test-and-build-docker-images.yml
- removes a duplicated docker login step in GitHub Action workflow
=> ci: Remove duplicated docker login step in workflow

.github/workflows/test-and-build-docker-images.yml, shipyard-controller/go.sum
- introduces caching for yarn and go
Fixes #8657
- Run a build with changes in the dependencies of a service
- Re-run the build and compare the test execution time
=> ci: Introduce yarn and go caching

.github/workflows/test-and-build-docker-images.yml, bridge/Dockerfile
- caches Cypress files
Workflow run: https://github.com/keptn/keptn/actions/runs/3173232917
=> ci: Cache Cypress files

shipyard-controller/internal/handler/projecthandler.go, shipyard-controller/internal/handler/projecthandler_test.go, shipyard-controller/internal/handler/projectmanager.go, shipyard-controller/internal/handler/projectmanager_test.go
=> fix(shipyard-controller): Do not validate gitCredentials when not set during project update

resource-service/common/credentials.go, resource-service/common/credentials_test.go, resource-service/common/fake/git_mock.go, resource-service/common/git.go, resource-service/common/gitsuite_test.go, resource-service/handler/project_manager.go, resource-service/handler/project_manager_test.go, resource-service/handler/resource_manager_test.go, resource-service/handler/service_manager_test.go, resource-service/models/project.go, shipyard-controller/internal/handler/projectmanager.go, shipyard-controller/internal/handler/projectmanager_test.go
=> feat(resource-service): Move history of previous upstream to new upstream

resource-service/common/git.go, resource-service/common/gitsuite_test.go, resource-service/common_models/git.go, resource-service/errors/errors.go, resource-service/handler/common.go, resource-service/handler/common_test.go, resource-service/handler/project_manager.go, resource-service/handler/project_manager_test.go, resource-service/handler/resource_manager.go, resource-service/handler/service_manager.go, resource-service/handler/service_manager_test.go, resource-service/handler/stage_manager.go, resource-service/handler/stage_manager_test.go
=> feat(resource-service): Compute git auth method once per API request 

installer/manifests/keptn/templates/shipyard-controller.yaml
=> fix(installer): Remove duplicate volumes and volumeMounts configuration

shipyard-controller/internal/handler/projectmanager.go, shipyard-controller/internal/handler/projectmanager_test.go
=> fix(shipyard-controller): prevent storing empty ssh private key after update

shipyard-controller/internal/db/models/projects_mv/projects_mv.go, shipyard-controller/internal/db/models/projects_mv/projects_mv_test.go, shipyard-controller/internal/db/mongodb_project_repo.go, shipyard-controller/internal/db/mongodb_project_repo_test.go
=> fix(shipyard-controller): Adapt MongoDB query to be compatible with DocumentDB

bridge/client/app/_views/ktb-settings-view/ktb-project-settings/ktb-project-settings.component.ts
=> fix(bridge): Fix missing update in project settings on project change

release-please-config.json
- adds release-please config file
- [8979](https://github.com/keptn/keptn/pull/8979)
=> ci: Add release-please config file

release-please-config.json
- sets the release-type of release-please to Go
=> ci: Set the release type of release-please to Go

bridge/client/app/_views/ktb-sequence-view/ktb-sequence-tasks-list/ktb-task-item.component.html, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-timeline/ktb-sequence-timeline.component.html, bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.module.ts, bridge/cypress/integration/sequences.spec.ts, bridge/cypress/support/pageobjects/SequencesPage.ts
- Show full date on hover on sequence view
Resolves #7719
=> feat(bridge): Show full date on hover on sequence view

gh-actions-scripts/prepare_changed_artifacts.sh
- fixes more set-output occurrences to adhere to the new formatting standard by GH
=> ci: Fix more set-output occurrences

release-please-config.json
- adds the parameter `pull-request-title-pattern` to the release-please config file
- changes the release PR title to `build(release): ${version}`
=> ci: Change release-please PR title pattern

.github/workflows/CI.yml, .github/workflows/release.yml, .github/workflows/test-and-build-docker-images.yml, lighthouse-service/Dockerfile
- simplifies some steps in the pipelines
- removes a bug where on re-ran CI builds, some images were not built and pushed anymore
=> ci: Fix pipeline trigger issues

resource-service/models/resource.go, shipyard-controller/models/stage.go
Signed-off-by: chavacava <salvadorcavadini+github@gmail.com>
Fixes #8974
=> fix: #8974 malformed struct tags

shipyard-controller/internal/provisioner/repository_provisioner.go
=> fix(shipyard-controller): Handle HTTP error response range when provisioning GIT repository

cli/internal/textutils.go
=> fix(cli): Fix non deterministic processing of `trigger sequence --data` flag

.github/workflows/security-scans.yml
- uses .release-please-manifest.json file to fetch the version for the security scan 
Fixes #9071
=> ci: Fix security scans

shipyard-controller/internal/controller/sequencedispatcher.go
=> fix(shipyard-controller): Fixed NilPointerExeption due to typo in SequenceDispatcher

CONTRIBUTORS.md, distributor/pkg/receiver/receiver.go
Fixes #8972 
by passing range variable as gorutine argument.
=> fix(distributor): Datarace range variable is captured in goroutine

MAINTAINERS
Add @DavidPHirsch  as maintainer as per issue: keptn/community#180
Signed-off-by: David Hirsch david.hirsch@dynatrace.com
=> chore: Add @DavidPHirsch as maintainer

.github/kics-config.yml, installer/manifests/keptn/templates/_helpers.tpl, installer/manifests/keptn/templates/lighthouse-service.yaml, installer/manifests/keptn/templates/remediation-service.yaml, installer/manifests/keptn/templates/shipyard-controller.yaml
- resolves issues from the last security scan workflow
- adds securityContext to initContainers
- adds resource limits and requests to initContainers
- reorders initContainers
Fixes #9092
=> fix: Resolve security scan issues

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts, bridge/cypress/fixtures/get.sockshop.service.carts.info-evaluations.mock.json, bridge/cypress/integration/sli-breakdown.spec.ts, bridge/cypress/support/pageobjects/ServicesPage.ts, bridge/shared/models/result-types.ts
- Fixes problem with weight calculation on the evaluation page.
Fixes #9083
Additional information on the tooltip:
Signed-off-by: gilbert.tanner <gilbert.tanner@dynatrace.com>
=> fix(bridge): Fix relative weight calculation

shipyard-controller/internal/handler/common.go, shipyard-controller/internal/handler/projecthandler.go, shipyard-controller/internal/handler/projecthandler_test.go
=> fix(shipyard-controller): Decode input payload strictly when creating or updating project

resource-service/common/git.go, resource-service/common/gitsuite_test.go
=> fix(resource-service): Force checkout event if unstaged changes are present

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts, bridge/cypress/fixtures/get.sockshop.service.carts.info-evaluations.mock.json, bridge/cypress/integration/sli-breakdown.spec.ts, bridge/cypress/support/intercept.ts, bridge/cypress/support/pageobjects/ServicesPage.ts, bridge/shared/models/result-types.ts
=> fix(bridge): Fix relative weight calculation (#9099)

installer/manifests/keptn/templates/_helpers.tpl
=> fix: Typo in script

test/go-tests/test_utils.go
=> test: Fix integration test failk3d

installer/manifests/keptn/values.yaml
=> chore(installer): Add missing labels in MongoDB and NATs charts

README.md
As discussed with @thschue - wanted to put Keptn Lifecycle Toolkit into the spotlight on the readme!
=> chore: Suggestion on making lifecycle toolkit more prominent

bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.html, bridge/client/app/_components/ktb-sli-breakdown/ktb-sli-breakdown.component.ts, bridge/client/app/_interfaces/sli-result.ts, bridge/cypress/integration/sli-breakdown.spec.ts, bridge/cypress/support/pageobjects/ServicesPage.ts
Fixes #9133 
Expanded:
Collapsed:
=> fix(bridge): Fix incorrect relative change

test/go-tests/test_utils.go
https://github.com/keptn/keptn/actions/runs/3459840709
closes #9138 #9128 #9119
=> test: Add retry logic for integration test

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-chart/ktb-evaluation-chart.component.ts, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.spec.ts, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts, bridge/cypress/integration/evaluations.spec.ts, bridge/cypress/support/pageobjects/EvaluationBoardPage.ts, bridge/cypress/support/pageobjects/HeatmapComponentPage.ts
=> fix(bridge): Fix invalidate evaluation

lighthouse-service/event_handler/common.go, lighthouse-service/event_handler/common_test.go
=> fix(lighthouse-service): Return error if slo.yaml cannot be fetched from resource service

MAINTAINERS
Signed-off-by: Simon Schrottner simon.schrottner@dynatrace.com
Add @aepfli as member based on https://github.com/keptn/community/issues/207
Fixes: https://github.com/keptn/community/issues/207
=> chore: Add @aepfli as member (keptn/community#207)

lighthouse-service/event_handler/common.go, lighthouse-service/event_handler/common_test.go
=> fix(lighthouse-service): don't fail sequence if SLO file is missing

.github/workflows/mongodb-version-check.yml
- fixes the mongodb-version-check.yml link
Fixes #9154
=> ci: Fix link to mongodb-version-check.yml

.github/workflows/integration_tests.yml
=> test: Disable K3s 1.24 integration tests due to port-forwarding issues

CONTRIBUTING.md, CONTRIBUTORS.md
Signed-off-by: nitin mewar <nitinmewar28@gmail.com>
Fixes #8914
=> docs: Add info about auto-signoff

bridge/server/app.ts, bridge/server/package.json, bridge/server/yarn.lock
Fixes #9164 
```
[Keptn] 2022-11-17T07:44:56.153Z info    [Express] GET /api/controlPlane/v1/project?disableUpstreamSync=true&pageSize=50 200 
[Keptn] 2022-11-17T07:44:56.248Z info    [Express] GET /api/controlPlane/v1/sequence/test?pageSize=5 200
[Keptn] 2022-11-17T07:45:03.554Z info    [API] get http://api-gateway-nginx/api/controlPlane/v1/project/test 200
```
=> feat(bridge): Unify logging

lighthouse-service/event_handler/configure_monitoring_handler.go, lighthouse-service/event_handler/handler.go, lighthouse-service/event_handler/start_evaluation_handler.go
=> chore(lighthouse-service): Clean up logs

mongodb-datastore/db/mongodb_connection.go, mongodb-datastore/db/mongodb_event_repo.go, mongodb-datastore/handlers/events.go
=> chore(mongodb-datastore): Clean up logs

resource-service/common/files.go, resource-service/common/git.go, resource-service/handler/project_manager.go, resource-service/main.go
=> chore(resource-service): Clean up logs

shipyard-controller/internal/controller/eventdispatcher.go, shipyard-controller/internal/controller/sequencedispatcher.go, shipyard-controller/internal/controller/shipyardcontroller.go
=> chore(shipyard-controller): Clean up logs/errors

api/handlers/event.go, api/handlers/metadata.go, api/middleware/tokenauth.go
=> chore(api): Clean up logs/errors

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.spec.ts, bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts, bridge/client/app/_services/_mockData/evaluations.mock.ts
=> fix(bridge): Fix invalid evaluation score status

.github/workflows/security-scans.yml
- adds govulncheck to the existing security scans
Fixes #8937 
Example [run](https://github.com/philipp-hinteregger/keptn/actions/runs/3573919230) of this workflow.
=> ci: add govulncheck to the existing security scans

shipyard-controller/internal/handler/projecthandler.go, shipyard-controller/internal/provisioner/repository_provisioner.go, shipyard-controller/internal/provisioner/repository_provisioner_test.go
=> fix(shipyard-controller): provide Git provisioning error information

lighthouse-service/event_handler/evaluate_sli_handler.go, lighthouse-service/event_handler/evaluate_sli_handler_test.go, lighthouse-service/main_test.go
Fixes #9198 
Integration test run: https://github.com/keptn/keptn/actions/runs/3575902410
=> fix(lighthouse-service): handling no SLO objectives

lighthouse-service/event_handler/evaluate_sli_handler.go, lighthouse-service/event_handler/evaluate_sli_handler_test.go, lighthouse-service/main_test.go
Integration test run: https://github.com/keptn/keptn/actions/runs/3587342150
Fixes #9207
=> fix(lighthouse-service): fail with descriptive error message when SLO criteria and target cannot be parsed

bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html, bridge/cypress/integration/evaluations.spec.ts, bridge/cypress/support/pageobjects/EvaluationBoardPage.ts
=> fix(bridge): Fix incorrect score-bar representation in evaluation

bridge/server/api/index.ts, bridge/server/app.ts, bridge/server/server.ts, bridge/server/services/api-service.ts, bridge/server/user/oauth-routes.ts, bridge/server/user/session.ts, bridge/server/utils/print-utils.spec.ts, bridge/server/utils/print-utils.ts
=> chore(bridge): Improve Bridge logging levels and messages

shipyard-controller/internal/provisioner/repository_provisioner.go
=> fix(shipyard-controller): Set headers only if request was successfully created

api/go.mod, api/go.sum, installer/manifests/keptn/templates/_helpers.tpl
Fixed wrong indentation issue: Error was showing "expected 18 but found 17  (indentation)"
Fixes #1234523
=> fix: Indentation issue in Installer Modue

api/swagger.yaml
This PR provides documentation for possible OAuth scopes for the `/import` API endpoint
=> docs: Document `/import` OAuth scopes

gh-actions-scripts/go-mod-tidy.sh
Adds an utility script to run `go mod tidy` for all services
=> ci: Add utility for running `go mod tidy` in all services

.github/workflows/integration_tests.yml
https://github.com/keptn/keptn/actions/runs/3749374979
=> build(deps): rebuild helm charts

cli/pkg/version/version_checker.go, cli/pkg/version/version_checker_test.go
=> fix(cli): display incompatible upgrade possibilities even if no minor upgrade is available

bridge/server/services/data-service.ts
- adds a default sorting by name on the uniform screen.
fixes https://github.com/keptn/keptn/issues/7442
Signed-off-by: Shardul Srivastava <shardul.srivastava007@gmail.com>
=> feat(bridge): Sort registration items by name

resource-service/common/git.go, resource-service/handler/resource_manager.go, resource-service/handler/resource_manager_test.go
This PR aims to reduce the load on a project's upstream repository by not automatically doing a fetch each time the resource service checks out a branch
=> feat(resource-service): reduce git fetch operations

.github/.kubescape/controls-inputs.json, .github/.kubescape/exceptions.json, installer/manifests/keptn/templates/_helpers.tpl, installer/manifests/keptn/templates/api-gateway-nginx.yaml, installer/manifests/keptn/templates/api-service.yaml, installer/manifests/keptn/templates/approval-service.yaml, installer/manifests/keptn/templates/bridge.yaml, installer/manifests/keptn/templates/lighthouse-service.yaml, installer/manifests/keptn/templates/mongodb-datastore.yaml, installer/manifests/keptn/templates/remediation-service.yaml, installer/manifests/keptn/templates/resource-service.yaml, installer/manifests/keptn/templates/secret-service.yaml, installer/manifests/keptn/templates/shipyard-controller.yaml, installer/manifests/keptn/templates/statistics-service.yaml, installer/manifests/keptn/templates/webhook-service.yaml
https://github.com/keptn/keptn/actions/runs/3881855545
=> chore: fixed false positive security errors

.github/workflows/release.yml
- fixes some syntax errors in the release pipeline
=> ci: Fix concurrency settings in release pipeline

cli/go.mod, cli/go.sum
=> build(deps): update k8s apimachinery to v0.25.6

test/go-tests/testsuite_gke_test.go, test/go-tests/testsuite_k3s_test.go, test/go-tests/testsuite_openshift_test.go
https://github.com/keptn/keptn/actions/runs/4012883472
=> test: remove unexisting tests from testsuites

installer/manifests/keptn/templates/api-gateway-nginx.yaml
=> fix(installer): Fix Nginx not handling 429 correctly

resource-service/Dockerfile
Bumps the gitlib2 version
Integration test run: https://github.com/keptn/keptn/actions/runs/4282123996
=> build(deps): update libgit2 to 1.5.2-rc0

test/go-tests/test_uniform.go
https://github.com/keptn/keptn/actions/runs/4343273228
Fixes: #9500 #9529 #9542 #9543 #9544 #9545
=> test: increase deadline for uniform multiple registrations pods

resource-service/common/git.go
Integration test run: https://github.com/keptn/keptn/actions/runs/4373044910
=> fix(resource-service): continue with stage creation if a refNotFound error is encountered

bridge/Dockerfile
- bump nodejs version to use the latest LTS
=> ci(bridge): bump nodejs version

.github/kics-config.yml
=> chore: Fix security checks - allow resource-service to read secrets

.github/workflows/security-scans.yml
- bump kics-github-action version to the latest bugfix
- adapt kubescape download url to the new organisation name
- export kubescape binary
Fixes #9595 #9596 
https://github.com/keptn/keptn/actions/runs/4529659600
=> fix: security pipeline

MAINTAINERS
* Changes affiliation of @thschue in MAINTAINERS
=> chore: change @thschue affiliation

.gitignore
- needed due to failing integration tests https://github.com/keptn/keptn/actions/runs/4781545096 -> this is caused due to recent changes in the dependencies, as the PRs were made by bot and these commits are ignored by the integration tests suite -> therefore they are ran in a inconsistent state
=> build: rebuild master

release-please-config.json
=> feat: Changelog reports dependencies bumps

.github/workflows/release.yml, installer/manifests/keptn/README.md, installer/manifests/keptn/values.yaml
- removes scarf redirect for image registry, this was causing sporadic image pull backoff
=> fix(installer): remove scarf redirect

cli/cmd/get_event_evaluationFinished.go
=> fix(cli): remove obsolete and misleading deprecation message

SECURITY.md
We can delete this file as it is covered by the .github repo
Signed-off-by: David Hirsch <david.hirsch@dynatrace.com>
=> chore: delete duplicated security policy file

.github/kics-config.yml
closes #9728 
closes #9729 
closes #9730 
https://github.com/keptn/keptn/actions/runs/5878391112/job/15940382426
=> ci: remove nats volume from kics scan

bridge/Dockerfile
- pins the node version to the patch so builds are reproducible
=> ci(bridge): pin node image

cli/pkg/config/cli_config.go, cli/pkg/config/cli_config_test.go
=> fix(cli): consider customized config directory when managing credentials
